### ISSUE TITLE
Compile flags: OPENSSL_API_1_0/OPENSSL_API_1_1 unnecessary?

### ISSUE THREAD

**Issue by D-r-P-3-p-p-3-r** [civetweb/civetweb#1001]
I ran into this problem with an embedded device: The underlying Linux got updated and now used OpenSSL 1.1.x instead of 1.0.y.
Now an application was not able to start civetweb. The log stated:

>  initialize_ssl: error loading library libcrypto.so

After defining OPENSSL_API_1_1 everything was fine.

Question:
Why is it necessary to define this? Why is this not auto-detected by the information contained in openssl/opensslv.h?

**Comment by bel2125** [comment]
Depends on how you build civetweb. The default is dynamic linking - in this case it is not even required to have any OpenSSL library or header neither on your build system nor on your target machine. If you set the NO_SSL_DL flag (compiler define), it will use the header you have on your system - and the resulting binary will only run on a machine with the same OpenSSL API version, even if you only use HTTP and do not require OpenSSL otherwise.

**Comment by bel2125** [comment]
The available API versions of OpenSSL are OPENSSL_API_1_0 (for 0.9.x and 1.0.x), OPENSSL_API_1_1 (for 1.1.x) and OPENSSL_API_3_0 (for 3.x). There is no major version 2, but 1.0 and 1.1 are different major version from the API point of view, while 0.9 and 1.0 are the same major version. Sounds strange, but that's the way it is.

The headers of your build system are only included, if NO_SSL_DL is defined (this is not by default):
https://github.com/civetweb/civetweb/blob/8c7c1dc51bfa8a68ab55f0fca92a8029fc355343/src/civetweb.c#L1737-L1741

And if they are defined, the API version will be determined from the headers:
https://github.com/civetweb/civetweb/blob/8c7c1dc51bfa8a68ab55f0fca92a8029fc355343/src/civetweb.c#L1772-L1789

For more details see the documentation on [Building](https://github.com/civetweb/civetweb/blob/master/docs/Building.md) - and if you do not main.c but only civetweb.c, the documentation on [Embedding](https://github.com/civetweb/civetweb/blob/master/docs/Embedding.md).

As briefly explained in the post above, the design choice was to not have NO_SSL_DL as a default.
This will create a server that does not require any OpenSSL version if you do not use a HTTPS port.
Then the server itself will not contain or require any cryptography (the binary is smaller, requires less resources and you will not run into any issues with cryptography regulations like export restrictions). When required, the cryptography can be downloaded separately.

**Comment by D-r-P-3-p-p-3-r** [comment]
We changed the way civetweb is embedded now. The problem does not occur anymore in this situation.
Thx for all the information.
