### ISSUE TITLE
Linking with -lcrypto

### ISSUE THREAD

**Issue by kjeldflarup** [civetweb/civetweb#1002]
I'm using CivetWeb embedded.

I'm apparently required to make CivetWeb with `CRYPTO_LIB=libcrypto.so.1.0.0`  
But I would like to do it the normal way, and specify `-lcrypto` and don't border about when libcrypto is changed in the SDK.

How do I do this?

**Comment by bel2125** [comment]
OpenSSL made an incompatible interface change between 1.0.x and 1.1.x - the build system needs to know what you have, at least when you use dynamic linking of OpenSSL at runtime.
You can build NO_SSL_DL defined - depending if you use the Makefile, cmake or use the civetweb.c file directly in your project, this is done in a different way. As a result, your OpenSSL is no longer optional, and the target machine must have the same OpenSSL (either 1.0.x or 1.1.x or 3.x), even if you are only using HTTP and not HTTPS.

**Comment by kjeldflarup** [comment]
Thanks, the NO_SSL_DL helped. But I had to do some C code changes. Please see linked PR.

**Comment by kjeldflarup** [comment]
Thank You for merging.
