### ISSUE TITLE
mg_set_request_handler root path doenst get recognized

### ISSUE THREAD

**Issue by hendrik-weiler** [civetweb/civetweb#1003]
Hello,
im using Version 1.14 of civetweb.

Im trying to set a handler for the root path and folder index paths like "/" or "/test" but it doenst get recognized. It will show:
"Error 403: Forbidden
Error: Directory listing denied"

This is how i set the config and the handlers
```
const char *options[] = {
            "document_root",
            "./www",
            "listening_ports",
            "8000",
            "enable_directory_listing",
            "no"
    };

/* Start the server */
ctx = mg_start(&callbacks, 0, options);

/* Add some handler */
mg_set_request_handler(ctx, "/**.xsl", xslHandler, 0);

mg_set_request_handler(ctx, "**", allHandler, 0);
```

allHandler gets called on every request but not the folder indexes like "/" or "/test" if the folder exists.

I looked for configuration and possible pattern in 
[https://github.com/civetweb/civetweb/blob/d674d31e52bee3c07ab8a7c1b4f8cf42fbf1ecb3/docs/UserManual.md#pattern-matching-in-configuration-options](UserManual) 
but i couldnt find anything.

Is there a configuration let a handler get called even on folder indexes?

**Comment by bel2125** [comment]
Your link above does not work - this is the latest version https://github.com/civetweb/civetweb/blob/master/docs/UserManual.md#pattern-matching-in-configuration-options?

Do you really want a handler for "everything" and not have any files at all? Then you could consider building with the NO_FILES define: https://github.com/civetweb/civetweb/blob/master/docs/Building.md#setting-compile-flags

There is an old "handle everything" callback (`begin_request`), that does not do any pattern matching.

But also pattern matching will work, although the pattern definition is sometimes not very intuitive (https://github.com/civetweb/civetweb/issues/499), but we kept it compatible for existing applications. Handler URI matching will first check for an exact match, second for a partial match and third for a pattern match. So if there is a handler for "/" this exact match would be preferred to all patterns.

For more details I would need a list of all handlers you register and the exact URL you are trying.

**Comment by hendrik-weiler** [comment]
I found the problem.
This was my code on the allHandler. The handler captures everything but if the path is for example "./www" it will try to serve the folder and that results in a
"Error 403: Forbidden
Error: Directory listing denied"

Snippet from the allHandler function:
```
    const struct mg_request_info *ri = mg_get_request_info(conn);

    string path = Tools::ResolvePath("www" + string{ri->request_uri});
    std::ifstream t(path);
    if(t.good()) { // you have to check if path is good and not a folder to avoid serving folders
        mg_send_file(conn, path.c_str());

        return 200;
    } else {
```

**Comment by bel2125** [comment]
> I found the problem.
> This was my code on the allHandler. 

Ok. Thank you for the report.
Can we close this issue or is there still anything open?

**Comment by hendrik-weiler** [comment]
You can close it. Thank you for your help.
