### ISSUE TITLE
How to send  jpeg content in base64 format to client ?

### ISSUE THREAD

**Issue by rahul3349** [civetweb/civetweb#1005]
Can you pls show example to send jpeg content to client ? 
client do http get request and server sends jpeg content in the response.

**Comment by bel2125** [comment]
If you put a *.jpeg or *.jpg file somewhere in the document_root folder or a subdirectory, civetweb will serve this file to the client (browser) automatically, however they will not use base64 encoding but just binary encoding of this file.

Do you have the JPEG as a file or somewhere in memory? Is it already base64 encoded or do you need to do this on the fly?
Do you need to send only the base64 encoded file, or do you need the base64 data to be part of some larger response, e.g. of some JSON object?
If you send the data from memory and need on the fly encoding, you have to use a handler function in C.

Or do you want to embed this in HMTL (like [here](https://stackoverflow.com/questions/8499633/how-to-display-base64-images-in-html)):
```
  <img src="data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4///w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==" alt="Red dot" />
```

Depending on what you want to do exactly, there are different solutions.
