### ISSUE TITLE
Sending a "bigger" JSON-file to the server

### ISSUE THREAD

**Issue by chs-1980** [civetweb/civetweb#1011]
Hi,

I'm a bit confused here. I'm currently trying to send a "bigger" (with bigger i am talking about a filesize of about 1-10 MB) JSON-file to my webserver and whatever i do i only get portions of it. I tried to send it as Blob in a multipart-form, i just used a regular PUT-request...

For the regular PUT-request my handling code looks like this:

void Object::putConfig(mg_connection * conn)
{
	std::string body;
	char buf[524288];
	size_t byteCount = 0;
	int r = ::mg_read(conn, buf, sizeof(buf));
	while (r > 0) {
		byteCount += r;
		body.append(buf);
		r = ::mg_read(conn, buf, sizeof(buf));
	}

	if (!body.empty()) {
		body.resize(byteCount);
		configuration = body;
		
		::mg_send_http_ok(conn, "text/html", 0);
		return;
	}
	

	::mg_send_http_error(conn, 500, "Setting the configuration failed...");
}

and the client-side JS-code looks like this:

fetch('http://localhost:8183${this.selectedURL}/config', {
             method: 'PUT', // *GET, POST, PUT, DELETE, etc.
             mode: 'cors', // no-cors, *cors, same-origin
             cache: 'no-cache', // *default, no-cache, reload, force-cache, only-if-cached
             credentials: 'same-origin', // include, *same-origin, omit
             headers: {
                 'Content-Type': 'application/json'
                 // 'Content-Type': 'application/x-www-form-urlencoded',
             },
             redirect: 'follow', // manual, *follow, error
             referrerPolicy: 'no-referrer', // no-referrer, *client
             body: JSON.stringify(this.configuration) // body data type must match "Content-Type" header
         })

In my opinion it should work this way but as i said i only get a portion of the original file on web-server-side. Does anybody have an idea what i am missing?!?

Thanks,

Christoph

**Comment by bel2125** [comment]
Your `mg_read` loop looks like the code in the example, except for handling string termination. 

Have a look at this example (I am referring to the C example here, since it all steps are obvious and there are no implicit constructors/destructors/overloaded operators/polymorphism/... like in C++):
https://github.com/civetweb/civetweb/blob/ab742dd29d4576fd47b99ef99594694d5b2b8fda/examples/embedded_c/embedded_c.c#L602-L611

`r = mg_read(conn, buf, sizeof(buf));` <-- this reads 'r' bytes into the buffer
`s = mg_send_chunk(conn, buf, r); ` <-- this example code only uses 'r' bytes
`body.append(buf);` <-- your code uses all bytes until a 0 termination ... that may be there or not - mg_read will not set it, and you don't set it

**Comment by grunk** [comment]
To send file to civetweb i use multipart form with [mg_form_data_handler](https://github.com/civetweb/civetweb/blob/master/docs/api/mg_form_data_handler.md) which works perfectly to upload file around 200Mb.

**Comment by chs-1980** [comment]
Thanks for the tips i was able to fix this issue myself. The problem was that after appending the stuff i read from the request to my std::string-object there was some "garbage" at the end of the string. I assume that's because after getting over the resize-threshhold the reserved size was a bit bigger than the actual size of the string which was simply uninitialized. So i simply made sure to resize the string to the correct size and suddenly everything worked like a charm.

```cpp
        std::string body = "";
	char buf[524288];
	size_t byteCount = 0;
	int r = ::mg_read(conn, buf, sizeof(buf));
	while (r > 0) {
		byteCount += r;
		body.append(buf);
		body.resize(byteCount);
		r = ::mg_read(conn, buf, sizeof(buf));
	}
```
