### ISSUE TITLE
Configurable URI within mg_set_request_handler

### ISSUE THREAD

**Issue by bonetor** [civetweb/civetweb#1016]
I am using civetweb to implement a REST API and I am using swagger for REST API definition and to create a *.yaml file. 

One REST API path defined in the *.yaml file is _[ BASE URL : /api/features/{featureID}/list ]_ where {featureID} could be between 1 and 10.

The REST client will call e.g.  _[ BASE URI : /api/features/1/list ]_ or _[ BASE URI : /api/features/5/list ]_.

So the featureID is kind of configurable and depends on the entered path.

To register the handlers in the application I am using **mg_set_request_handler**. Currently I call **mg_set_request_handler** for the different paths 10 times with the same handler to be registered. 

_mg_set_request_handler(ctx, BASE URI : /api/features/1/list , sameHandler, 0);
mg_set_request_handler(ctx, BASE URI : /api/features/2/list , sameHandler, 0);
mg_set_request_handler(ctx, BASE URI : /api/features/3/list , sameHandler, 0);
...
mg_set_request_handler(ctx, BASE URI : /api/features/10/list , sameHandler, 0);_

Is there a way to call **mg_set_request_handler** only once for all the path? So having a configurable URI with a kind of wildcards within the URI of the **mg_set_request_handler** call? 

So it would be kind of having a similar URI as defined in the *.yaml file

_mg_set_request_handler(ctx, BASE URI : /api/features/{featureID}/list , sameHandler, 0);_

**Comment by bel2125** [comment]
Currently you can register "/api/features/" to get all requests, not only "api/features/#/list"

A similar idea is https://github.com/civetweb/civetweb/issues/629, but it has not been fully implemented up to now.

There is some pattern matching for request handlers, but something like "/api/features/**/list" has it restrictions that cannot be solved without breaking compatibility: https://github.com/civetweb/civetweb/issues/499


> So it would be kind of having a similar URI as defined in the *.yaml file

What yaml file do you mean?

**Comment by bonetor** [comment]
> What yaml file do you mean?
The yaml file I created for REST API definition. I did not upload it.

I will go the way with "/api/features/" to get all requests and implement some logic in the handler to get the specific path.

Is there any time schedule when #629 will be available?
