### ISSUE TITLE
Has anyone attempted to compile on Apple Silicon? 

### ISSUE THREAD

**Issue by hexmarkrecords** [civetweb/civetweb#1019]
Has anyone attempted to compile and run on Apple Silicon M1? I would love to know the answer but don't have access to an M1 chipset

**Comment by gjasny** [comment]
The stack compiles and runs fine on the M1.

**Comment by hexmarkrecords** [comment]
Thank you @gjasny.

**Comment by dacrome** [comment]
Did you create a nativ build which targets arm64 e.g. with `CFLAGS="-arch arm64"` or did run Civetweb in rosetta mode?
