### ISSUE TITLE
CMake: Windows build fails in FindWinSock.cmake

### ISSUE THREAD

**Issue by D-r-P-3-p-p-3-r** [civetweb/civetweb#1020]
For me the build under Windows fails with the following error:
```
CMake Error at cmake/FindWinSock.cmake:77 (if):
  if given arguments:

    "STREQUAL" "AMD64" "AND" "4" "EQUAL" "4"

  Unknown arguments specified
Call Stack (most recent call first):
  src/CMakeLists.txt:33 (find_package)
```

Apparently, the variable CMAKE_HOST_SYSTEM_PROCESSOR is empty or does not exist.

If I change
```
if (${CMAKE_HOST_SYSTEM_PROCESSOR} STREQUAL "AMD64" AND "${CMAKE_SIZEOF_VOID_P}" EQUAL 4)
```
to
```
if ("${CMAKE_HOST_SYSTEM_PROCESSOR}" STREQUAL "AMD64" AND "${CMAKE_SIZEOF_VOID_P}" EQUAL 4)
```
in FindWinSock.cmake it works.

**Comment by bel2125** [comment]
I am not an expert on CMake - the CMake build files have been created by a contributor, and my test for Windows is mainly that it has to work with the AppVeyor unit test. I don't know if adding quotes will break anything, I will have to have a look if this breaks the build in a merge request.

According to 
https://cmake.org/cmake/help/v3.21/variable/CMAKE_HOST_SYSTEM_PROCESSOR.html
it should be available for Windows, Linux and macOS - and it was already there for CMake 3.0:
https://cmake.org/cmake/help/v3.0/variable/CMAKE_HOST_SYSTEM_PROCESSOR.html

Maybe it does not exist in CMake 2.x?
According to the CMakeList.txt, 2.8.12 is the required minimum, but it has not been tested with V2.x for a long time:
https://github.com/civetweb/civetweb/blob/efe735d13be827995b8f3355e7ff9fa9910ab7cb/CMakeLists.txt#L2

What version are you using?

**Comment by D-r-P-3-p-p-3-r** [comment]
> I am not an expert on CMake - the CMake build files have been created by a contributor, and my test for Windows is mainly that it has to work with the AppVeyor unit test. I don't know if adding quotes will break anything, I will have to have a look if this breaks the build in a merge request.

The quotes should not break anything I believe.

> What version are you using?

I'm using
```
-- CMake version: 3.19.4
```
