### ISSUE TITLE
Does Civetweb provide a health check / monitoring endpoint?

### ISSUE THREAD

**Issue by dacrome** [civetweb/civetweb#1027]
We want to know if the Civetweb is already up. Is there any way to find out? We can call an HTTP endpoint also possible via C or C++ API.

**Comment by bel2125** [comment]
If you set the `USE_SERVER_STATS` define when building, you can read a lot of information using `mg_get_context_info` or `mg_get_connection_info`. If you just want to know if it is already started, you can use the `init_context` or the `init_thread` callback.

**Comment by bel2125** [comment]
If you build the server with Lua support, you can add a script like https://github.com/civetweb/civetweb/blob/master/test/page_status.lua to your docroot - this will provide a HTTP status endpoint. The information is the same as you get with the `mg_get_*_info` functions in C.

The C++ API is far from complete and does not offer anything you cannot do in C - the C API is complete and usually new features are only added to the C API.

If you tell me exactly what you want to find out, I can tell you where to look for it.

**Comment by dacrome** [comment]
Thanks for your feedback @bel2125 !

We found a way to make sure that the server is started.
