### ISSUE TITLE
declaration of buf shadows a previous local

### ISSUE THREAD

**Issue by admaunaloa** [civetweb/civetweb#1029]
In embedded_c.c line 608 the declaration 
char buf[1024];
shadows line 601 declaration
char buf[2048];

**Comment by bel2125** [comment]
These lines do not seem to match the current version: https://github.com/civetweb/civetweb/blob/0d4f788b13fac7ba55d75695b4d43c73b369ce91/examples/embedded_c/embedded_c.c#L601

https://github.com/civetweb/civetweb/blob/0d4f788b13fac7ba55d75695b4d43c73b369ce91/examples/embedded_c/embedded_c.c#L608
However, "Shadows declaration" is usually not a problem.

**Comment by bel2125** [comment]
warning fixed / October 1
