### ISSUE TITLE
How to embed SSL certificate into the program?

### ISSUE THREAD

**Issue by mfide** [civetweb/civetweb#1030]
Hi,

We use Civetweb on our embedded Linux Platform as a TLS websocket server which works perfect. 

But we don't want to distribute the certificate as a separate file. Is there a way to embed the certificate into our program which uses Civetweb? Let's say we have an array which holds certificate information as a byte stream in the memory. Is it possible to tell Civetweb that use this array as a certificate instead of external file?

Thank you.

**Comment by bel2125** [comment]
You can do the setup of all SSL in your own init callback, and then return "1":

https://github.com/civetweb/civetweb/blob/1a6de4ccb2d4c8be6ea6c4c767e98f6fab55d393/include/civetweb.h#L246-L254

I somewhere had an example of how to do that, including setting up parameters for ecliptic curves, all in a C source file. But this is non-public code - I can try to give you some general hints about what OpenSSL functions you need to call there.
