### ISSUE TITLE
Expose base64 decoder

### ISSUE THREAD

**Issue by gjasny** [civetweb/civetweb#1038]
Hello,

as a civetweb library consumer I have to ship my own base64 implementation to support HTTP Basic Authentication within a custom `AuthHandler`: https://github.com/jupp0r/prometheus-cpp/blob/v0.13.0/pull/src/basic_auth.cc#L43

Maybe you could expose the base64 decoder or provide a convenience function to ease Basic Authentication.

Thanks,
Gregor

**Comment by bel2125** [comment]
These two functions:
```C
void base64_encode(const unsigned char *src, int src_len, char *dst);
int base64_decode(const unsigned char *src, int src_len, char *dst, size_t *dst_len);
```
We could export them to the interface, but probably after making the interface more symmetric. Currently the length of the destination string is handled differently. The CivetWeb internal functions know exactly how they have to use these functions.

**Comment by bel2125** [comment]
Pubic API has been extended in https://github.com/civetweb/civetweb/commit/65a80ce100cb14fb0537ae40294f60b2b7fab94a

**Comment by gjasny** [comment]
Thank you for the addition!
