### ISSUE TITLE
luck of authorisation api for a client

### ISSUE THREAD

**Issue by 6username9** [civetweb/civetweb#1045]
Hi,

thank you for your great work on developing the civetweb library. 
I wrote a client which can submit secure request and it works pretty nice.

The problem is when I want to provide the authorization header, while connection.
I want to connect to and get data from https://api.urlmeta.org/.

if I use that: 
`auto pointer = mg_connect_client("https://api.urlmeta.org/", 443,1, bufferror, bufferrolen) -> the pointer is null, bufferror is empty.`
if i use that: 
`auto pointer = mg_download("https://api.urlmeta.org/", 443,1, bufferror, bufferrolen, "%s", 
"GET / HTTP/1.0\r\n"
"host: api.urlmeta.org\r\n"
"Authorization: XXX \r\n\r\n"
 );
I got SSL Connection Error.
`

I tested my implementation against other https websides and worked pretty well.

Do you know how to make it works?

**Comment by bel2125** [comment]
https://api.urlmeta.org/ seems to return a `401 Unauthorized` response, but without mandatory information how to authenticate - the "WWW-Authenticate" header is missing: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401.

It should not happen that the error buffer remains empty if you use the `mg_connect_client` or `mg_connect_client2` interfaces. Did you provide a the buffer long enough (e.g. 256 characters)?

Maybe this particular website requires to use a TLS client certificate?

**Comment by bel2125** [comment]
You should not provide `"https://api.urlmeta.org/` but only `api.urlmeta.org`. 
However, this particular server seems to need something in addition - other servers don't need this.

I tried using `mg_connect_client_secure` ([this code](https://github.com/civetweb/civetweb/blob/master/examples/client/client.c)) - it would also accept an SSL client certificate, if you have one.

The test code works for `www.google.com`, `www.github.com` and also `urlmeta.org`, but not `api.urlmeta.org` or `www.urlmeta.org`.  As already mentioned, the web page does give any information on what exactly is missing (only `Cannot connect client: SSL connection error`).

**Comment by 6username9** [comment]
Thank you for answers.
So, yes the buffer is big enough 1024:

```
char *error = new char[1024];
 _clientConnection = mg_connect_client(  "api.urlmeta.org", 443, 1, error, strlen(error));
  
  if (_clientConnection == nullptr) {
    std::cout << "Error: " << error;
    return false;
  }
```
and that gives me _clinetConnection = nullptr, and error pointer is empty

**Comment by nemethz5** [comment]
Try to use 
_clientConnection = mg_connect_client(  "api.urlmeta.org", 443, 1, error, **1024**);

**Comment by 6username9** [comment]
ok, that solved the problem with the empty buffer :)

**Comment by bel2125** [comment]
I think I found the problem with the connection to your server:
It seems this server needs the server name to be set for TLS SNI, while others don't care.

The server name can be set using the `mg_connect_client_secure` function, like shown here:
https://github.com/civetweb/civetweb/blob/master/examples/client/client.c

If you use exactly this example for `./client api.urlmeta.org` you will get a response like:

```
cli: 0x7fe86d840010
Status: 401 Access Denied
HTTP Version: 1.1
Content-Length: 20
Headers:
  Date: Wed, 15 Dec 2021 19:18:24 GMT
  Content-Type: text/plain;charset=UTF-8
  Content-Length: 20
  Connection: close
  Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
  Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=YhRnJ2R81fCkKlF1FSmhpah2%2BgQphx7sfZKT6LP5Us%2FhKy94PnbeQUsNPEtbUD15OXh90T0O%2Bg19vh5%2BNuiif5zZ1XQ6J0IwjnZpv59l%2F5ea9nUwutGIIjT6GAgipR0lcpc%3D"}],"group":"cf-nel","max_age":604800}
  NEL: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
  Server: cloudflare
  CF-RAY: 6be20480f952702b-FRA
  alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400, h3-28=":443"; ma=86400, h3-27=":443"; ma=86400
Content:
Error: Auth Required
```

**Comment by bel2125** [comment]
The aforementioned authentication problem remains: The server sends a 401 response but no WWW-Authenticate header.

According to the RFC (https://datatracker.ietf.org/doc/html/rfc7235#section-3.1):
"The server generating a 401 response MUST send a WWW-Authenticate header field containing at least one challenge applicable to the target resource."

The server does not fulfill this requirement, and does not give any information why.
--> This is a server issue you have to clarify with the server admin.

Maybe it needs a client certificate, a cookie or some api key header, or something completely different. Client certificates must be set using `mg_connect_client_secure` (`client_cert` [here](https://github.com/civetweb/civetweb/blob/master/examples/client/client.c#L42)). Cookies or api keys must be sent as additional header line using `mg_printf` ([here](https://github.com/civetweb/civetweb/blob/a06ed2a76910f45bc3701ee6c2c391cfaf286f9d/examples/client/client.c#L57)).

**Comment by 6username9** [comment]
that was great! 
You have saved my development! many thanks.
I have to tell you, that it is not the first time I contacted a team who developed a framework I wanted to use. Your fast reaction, and dedication to provide a solution to the issue is amazing. Great team! Kudos for you!

It worked like a charm. So I had to use the mg_connect_client_secure with the struct like:

```
opt.host          = "api.urlmeta.org"; //_remoteAddress->GetString().c_str(); /* Host name from command line */
opt.port          =  443; /* Default HTTPS port */
opt.client_cert   = NULL;                      /* Client certificate, if required */
opt.server_cert   = NULL;                      /* Server certificate to verify */
opt.host_name     = opt.host;                  /* Host name for SNI */
_client = mg_connect_client_secure(&opt, errbuf, sizeof(errbuf));
```
So I could connect and then add the authorization header in the request.

btw. Why doesn't it work with mg_connect_client?

**Comment by bel2125** [comment]
> btw. Why doesn't it work with mg_connect_client?

Because `mg_connect_client( "api.urlmeta.org", 443, 1, ...);` is basically `mg_connect_client_secure` without host_name for SNI:
```
opt.host          = "api.urlmeta.org"; //_remoteAddress->GetString().c_str(); /* Host name from command line */
opt.port          =  443; /* Default HTTPS port */
opt.client_cert   = NULL;                      /* Client certificate, if required */
opt.server_cert   = NULL;                      /* Server certificate to verify */
opt.host_name     = NULL;    /* !!!!!!!!!!!!!!!!! Host name for SNI !!!!!!!!!!!!!!!!! */
mg_connect_client(&opt, ...);
```

This worked for every server I used up to now - including civetweb as a server, but also gwt (google.com), apache, etc. It does not work for api.urlmeta.org (I think that's a cloudflare server). Maybe it's a matter of server configuration. SNI is required for HTTP/2, but not for HTTP/1.x.

Probably we should change `mg_connect_client` to copy the first argument not only into opt.host (used for resolving the IP address), but also into opt.host name (used in the TLS handshake for SNI).

**Comment by 6username9** [comment]
thank you! Great explanation!

**Comment by minhanghuang** [comment]
@bel2125 hi, excuse me, how to set the client uri? 
example: `http://127.0.0.1:8080/hello-world/`

**Comment by bel2125** [comment]
Hello,

> @bel2125 <https://github.com/bel2125> hi, excuse me, how to set the
client uri?
> example: http://127.0.0.1:8080/hello-world/
I have an issue with linking this question to GitHub. On the one hand the
system says it is from March 3, on the other hand it says this is from 2021.
A client URL is passed to the mg_connect method:
127.0.0.1 is the IP, 8080 the port and /hello-world/ the local URL part.
