### ISSUE TITLE
compile warning on 64-bit linux

### ISSUE THREAD

**Issue by t-j-h** [civetweb/civetweb#1049]
gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04) 

Building ec_server
ec_example.c: In function ‘request_handler’:
ec_example.c:278:26: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 3 has type ‘long unsigned int’ [-Wformat=]
  278 |  sprintf(new_cookie, "c=%u", cookie_number + 1);
      |                         ~^   ~~~~~~~~~~~~~~~~~
      |                          |                 |
      |                          unsigned int      long unsigned int
      |                         %lu
ec_example.c:287:43: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 4 has type ‘long unsigned int’ [-Wformat=]
  287 |           "Hello at %s\nYou have visited %u sites here before!",
      |                                          ~^
      |                                           |
      |                                           unsigned int
      |                                          %lu
  288 |           ri->local_uri,
  289 |           cookie_number);
      |           ~~~~~~~~~~~~~                    
      |           |
      |           long unsigned int

**Comment by bel2125** [comment]
Thank you for reporting.

Fixed in https://github.com/civetweb/civetweb/commit/3ab696bb5ed595bb845a3f17cd5e827f77e242e0
