### ISSUE TITLE
Unable to send large packets with websocket

### ISSUE THREAD

**Issue by jespo655** [civetweb/civetweb#1075]
Application crashes when I try to send large packets (about 3kb) using mg_websocket_write().

mg_websocket_write_exec() always sets the FIN-bit in the packet header, so I'm unable to use continuation frames to split up the packet.

**Comment by bel2125** [comment]
I already used this to send frames much larger than 3 kB.
Could you post some steps (code snippet) to reproduce this problem?

**Comment by jespo655** [comment]
I found the issue, and it was related to memory allocation and not civetweb.

**Comment by AlbertShown** [comment]
@jespo655 I know it has been a while, but I have the same issue. Can you tell me how you solved this?

**Comment by jespo655** [comment]
@AlbertShown When using malloc() to allocate memory to put the packet in, that failed because my small mcu was out of memory. So the crash was a segfault while trying to write to null.

To fix it, I freed up memory usage elsewhere, and made sure that there would always be enough memory to alloc buffers of the size i needed for the packet.

**Comment by AlbertShown** [comment]
Thank you for your quick answer. I see that your issue was after Civetweb received the packet. My issue is with Civetweb itself. It needs more size.

ChatGPT gives me this:

```
const char *options[] = {
        "listening_ports", "8080",
        "websocket_buffer_size", "65536",
        NULL
};
```

But I can't find `websocket_buffer_size` in the Civetweb documentation.

My question is, how do I increase Civetweb's internal WebSocket buffer?

**Comment by jespo655** [comment]
Aight. Can't help you with that, sorry.
I can only suggest not trusting ChatGPT with this :) It can easily lead you on the wrong track.

**Comment by AlbertShown** [comment]
> I can only suggest not trusting ChatGPT

Yes, because AI's last trained data is September 2021. So many things changed after this date :)
Thank you 👍

**Comment by bel2125** [comment]
@AlbertShown : Is it the same topic as https://github.com/civetweb/civetweb/issues/1166 ?
Could you describe the problem there? Not what ChatGPT answered you, but what you asked it and what you want to reach? There is no such thing as "the one and only WebSocket buffer".

**Comment by AlbertShown** [comment]
I'm just wondering what the maximum size of the packets sent using `mg_websocket_write()` is.

**Comment by bel2125** [comment]
In theory 4 GB on a 32 bit system and 256 TB on a 64 bit or 128 bit (or any larger) system.
In practice a little less than 2 GB on a 32 bit system, whatever you have available RAM on a 64 bit system and 128 bit systems are not accessible to me.

**Comment by AlbertShown** [comment]
I got it 😆👍
Thank you
