### ISSUE TITLE
<!DOCTYPE html> missing in directory listing

### ISSUE THREAD

**Issue by jrki1975** [civetweb/civetweb#1086]
Civetweb's (v1.15) function _handle_directory_request()_ does not generate the 
**\<!DOCTYPE html>**
tag at the beginning of a directory listing.

HTML5 standard requires this, see chapter 8.1.1 of 
https://www.w3.org/TR/2011/WD-html5-20110405/syntax.html#the-doctype

Should that be added to Civetweb?

Best regards
Jrki

**Comment by bel2125** [comment]
This part of the code is older than HTML5 - from the "you can specify but you don't have to and the browser will need to guess it" area.
Yes, now it could and should be added.
