### ISSUE TITLE
WebSocket connection failed in chromium based browser after subprotocols were used

### ISSUE THREAD

**Issue by r-j-s** [civetweb/civetweb#1091]
Hello,

me and my colleague maybe discover a problem when using a "chromium based" browser (e.g. Google Chrome), calling two different html/js websites where one of them uses websockets with subprotocols and was served by a civetweb webserver at latest version 1.15.

This is our environment:
Server:
Small linux machine which is running a C++ application which embeds civetweb. We initialize civetweb with the following options:
```
   const char *options[] =
   {
      "document_root", WEBSRV_DOCUMENT_ROOT,
      "listening_ports", PORT,
      "num_threads", "8",
      "request_timeout_ms", "5000",
      "error_log_file", "error.log",
      "websocket_timeout_ms", "1000",
      "enable_websocket_ping_pong", "yes",
      "enable_auth_domain_check", "no",
      "enable_directory_listing", "no",
      "authentication_domain", WEBSRV_REALM,
      0
   };
```
   
index.html:
```
<!DOCTYPE html>
<html>
<head>
    <body onload="Init();">
        Hello world.
        <script>
            function Init() {
                var urlArray = document.URL.split('/');
                var urlStr = "ws://" + urlArray[2];
                var websocket = new WebSocket(urlStr);
                websocket.onopen = function (evt) { alert("Websocket connected!"); }
                websocket.onerror = function (evt) { alert("!!! FAILED to connect !!!"); }
            }
        </script>
    </body>
</html>
```

subprotocol.html:
```
<!DOCTYPE html>
<html>
<head>
    <body onload="Init();">
        Hello world with subprotocol.
        <script>
            function Init() {
                var urlArray = document.URL.split('/');
                var urlStr = "ws://" + urlArray[2];
                new WebSocket(urlStr, 'dumb-increment-protocol');
            }
        </script>
    </body>
</html>
```

To reproduce this you have to call the subprotocol.html at least eight times with a browser of your choice (eight because we set "8" to the "num_threads" parameter of the options above, I will explain this later).
At this point you have to open a "chromium based" browser lets say Google Chrome or Microsoft Edge and call a website which uses websockets WITHOUT subprotocols (for example the index.html above).
Now you can't connect to a websocket (without subprotocols) anymore. Curiously Mozilla Firefox doesn't have any problems with this.

After a lot of debugging and investigating TCP frames with wireshark we found out that when calling the index.html after the server was corrupt the server gave back very strange strings as subprotocols which were part of the header from a previous session. But we didn't used subprotocols with the index.html.
It turns out the the variable "const char * acceptedWebSocketSubprotocol" from the "struct mg_request_info" is not set back correctly when a new client is connected. And then when you make a new connection and the previous session used subprotocols you get this old uninitialized pointer which points to an undefined memory.
Luckily this undefined memory were printable letters so we could go deeper.
Calling the subprotocol.html eight times makes sure that every thread/connection has an uninitialized pointer.

Solution:
To prevent the described behaviour we set the pointer to NULL when a new connection is established in the function "static void init_connection(struct mg_connection *conn)":

```
--- civetweb.c	2022-08-05 14:18:33.161276092 +0200
+++ civetweb_.c	2022-08-05 14:20:45.370002816 +0200
@@ -19281,6 +19281,7 @@
 	conn->data_len = 0;
 	conn->handled_requests = 0;
 	conn->connection_type = CONNECTION_TYPE_INVALID;
+        conn->request_info.acceptedWebSocketSubprotocol = NULL;
 	mg_set_user_connection_data(conn, NULL);
 
 #if defined(USE_SERVER_STATS)
```

I think this is not a big thing because most of the people dont uses this subprotocol. Unfortunatly we don't really use this subprotocol too. It turns out that another colleague used the code from an internet tutorial.

Hope this helps.

**Comment by bel2125** [comment]
Sorry for the delay, I was on extended summer vacation.

Thank you for your detailed error description - and thank you for the fix.
I will integrate it.
