### ISSUE TITLE
is mg_close_connection() thread safe?

### ISSUE THREAD

**Issue by mfide** [civetweb/civetweb#1097]
I want to keep active client connection count at 5 max. Whoever comes the last will kick the first client connection once the total client count reaches to the max which is 5 in my case.

I have a thread safe client list for that. But can I use mg_close_connection() in the ws_connect_handler callback function for another client?

For example, when there is a new client connection, in the ws_connect_handler callback function, can I use mg_close_connection() to close another client's connection?

**Comment by mfide** [comment]
One more question, could you also briefly explain the differences between:
1. `mg_websocket_write(conn, MG_WEBSOCKET_OPCODE_CONNECTION_CLOSE, nullptr, 0);`
2. `mg_close_connection(conn);`

When I execute them on the server side, First one disconnects the client immediately. Second one disconnects after some time. Which method is the proper one to force the client (conn) to disconnect on the server side?

**Comment by bel2125** [comment]
Unfortunately my long answer got lost before I could send it. 
So here again in multiple small paragraphs:

You should not use two functions on the same `conn` in two different threads. If you need to, use `mg_lock_connection` to protect it.

`mg_websocket_write(MG_WEBSOCKET_OPCODE_CONNECTION_CLOSE)' is a higher level function that you should use for well behaved clients. It's a friendly way to say "good bye" and then waiting for the client to leave - the client should initialize the TCP connection closing sequence.

`mg_close_connection` is a lower level "unfriendly" way to terminate a connection from the server side. It is like throwing someone out the door without saying goodbye. It could be that a browser calls a JavaScript error handler in this case (did not test this). You use it for clients that do not behave properly - clients that violate the protocol or block a connection for too long by not sending any data but still keeping it open.

**Comment by mfide** [comment]
Thank you for the reply @bel2125.

If this is the case, I don't wanna rely on the client to initiate the closing sequence when I use `mg_websocket_write(MG_WEBSOCKET_OPCODE_CONNECTION_CLOSE)`

Because of that I want to use second option which is `mg_close_connection(conn)` But one thing is still not clear to me that why `mg_close_connection(conn)` doesn't terminate the connection immediately but after some time (like 5secs in my case)

I want to terminate the client connection without asking the client and immediately on the server side. How can I manage that, any advice?

Thank you.

**Comment by bel2125** [comment]
To answer this, I need more details what you are actually doing:

Are you using `mg_close_connection` on a websocket, but from a different thread than the one calling the websocket handlers?
If yes, then `mg_close_connection` only sets a flag for the websocket handler thread telling it to end the handling loop. You can shorten this time using shorter websocket timeouts.

If you are doing something else, then you need to explain in more detail.

**Comment by bel2125** [comment]
Or one step back:

The information above is actually for developers embedding CivetWeb into their C/C++ program, basically building their own version of a product with CivetWeb.

If you are only downloading the executable of CivetWeb and using it, this information will not help you.

Could you explain a little what you want to do?

**Comment by mfide** [comment]
> To answer this, I need more details what you are actually doing:
> 
> Are you using `mg_close_connection` on a websocket, but from a different thread than the one calling the websocket handlers? If yes, then `mg_close_connection` only sets a flag for the websocket handler thread telling it to end the handling loop. You can shorten this time using shorter websocket timeouts.
> 
> If you are doing something else, then you need to explain in more detail.


Yes I'm developing a websocket server application on an embedded platform runs Linux Kernel v5.4.
The users who have valid certificates can make up to 5 simultaneous connections to the server (kind of licensing option). Lets call first client connection as conn1, second as conn2.. fifth one as conn5. Each are managed on their threads based on how Civetweb designed.

When the user attempt to make a new client connection after the first five, let's call it as conn6, I need to kick conn1. Let's say another client connection came, lets call conn7, then I need to kick conn2 etc..

```
// Handler for new websocket connections.
static int ws_connect_handler(const struct mg_connection* conn, void* user_data)
{
	...
	...
	size_t cc = client_count(um);
	if (cc >= um->max_client_count_allowed)
	{
	    lock_guard<mutex> mtx(um->client_list_mutex);
	    auto kick_conn = (struct mg_connection*)um->client_list.front(); // takes the first client connected in the list
    
	    mg_lock_connection(kick_conn);
	    mg_close_connection(kick_conn);
	    mg_unlock_connection(kick_conn);
	}

	add_new_client(um, conn);	
	
	// 0: civetweb proceeds with websocket handshake.
	// 1: connection is closed immediately.
	return 0;
}

/* Handler indicating the connection to the client is closing. */
static void ws_close_handler(const struct mg_connection* conn, void* user_data)
{
	...
	...	
	remove_client(um, conn);
}
```

As I understand from your previous reply, `mg_lock_connection` and `mg_unlock_connection` were necessary around  `mg_close_connection`. Therefore I have added them.

That approach works fine but when a new client comes, the oldest client connection is closed on the server side after 5 secs and it varies among my trial. Isn't there a way to disconnect the client immediately instead of waiting a kind of timeout?

**Comment by bel2125** [comment]
A client cant disconnect itself immediately, but disconnecting another one always means sending it a flag and waiting until the other thread handles this connection closing.
Forcefully aborting another connection may mean this has some unfinished operations, maybe opening a file that will never get closed then. Therefore it is not designed like this.

You could establish a communication between your clients (worker callbacks on the server side) on your own to know when it is save to abort a connection - but most likely you will end up with the same solution of one thread setting a "you should stop" flag for the other.

If it is really only licensing, I would ignore the 5 seconds closing time on the 6th connection, but maybe not allow a 7th connection until the user is back to only 5 connections.

**Comment by mfide** [comment]
I was relying on ws_close_handler() function which was fired after the timeout to remove the client kicked from my list. 
I have changed the logic slightly and removed the client kicked using `mg_close_connection()` immediately from my list. 
After timeout, ws_close_handler() tries to remove the same client from the list again which is not available but it can manage this condition.

Thanks for your helps.
