### ISSUE TITLE
get_random() is not thread safe

### ISSUE THREAD

**Issue by mfide** [civetweb/civetweb#1098]
`get_random()` used in `mg_websocket_client_write ` and also couple of other places which can be ran from different threads.
get_random has internal global variables lfsr, lcg which are not protected.

If this is not intentional to add more uncertainty and make the output really random, I think it is a bug.

**Comment by bel2125** [comment]
It is true, there is no lock around get_random() and it does use static variables.
In contrast to a (typical) pseudo-random number generator, get_random() also adds a timestamp (nanoseconds from the system clock). Therefore it will not return the same sequence when called twice. 
It will not hurt the "randomness" of get_random() if it is called from two threads, therefore I did not use a mg_lock_context() (or anything like that) in this function. 
In general, I agree, any function that uses static (or global) variables in a multi-threaded environment should have a lock to generate "reproducible" results, and probably good static source code analysis tools will also raise a warning here.
In this specific use case of a random number generator nothing will happen if one thread overwrites lfsr or lcg while the other thread is reading it.
Adding a lock will add only a small overhead, but - from my current understanding - it will not fix any bug.
