### ISSUE TITLE
civetweb1.15 not support http basic auth

### ISSUE THREAD

**Issue by amn028** [civetweb/civetweb#1103]
The latest version 1.15 does not support basic auth. The master branch version 1.16 already supports basic auth. When will version 1.16 be released?

**Comment by bel2125** [comment]
Plan was end of August ... then end of October. 
Currently everything is somewhat volatile, but it has to be available on November 2.

**Comment by amn028** [comment]
ok,thanks.
I look forward to the release of the next version.
