### ISSUE TITLE
On signal read loop for websocket exit

### ISSUE THREAD

**Issue by Kal42** [civetweb/civetweb#1104]
Hi,

I am facing an issue with the websocket read loop that exit on signal.

In "pull_inner" function , if mg_poll (aka poll) receive signal, it's return -2

Is there something to configure to avoid this ? or should I do a PR ?

Best regards,

**Comment by bel2125** [comment]
Sorry for the late reply, I had to take a sick leave.

You are using Linux? Debian/Ubuntu/???
What signal?
Would your pull request use ppoll and a sigmask? 
Didn't I set the sigmask already somewhere?

**Comment by Kal42** [comment]
Yes, It's on linux.

My issue, is in 
```
static int pull_inner(FILE *fp,  struct mg_connection *conn,  char *buf, int len, double timeout)
```

On signal, mg_poll (poll) return -1, and so pull_inner return -2. And -2 is error, so the websocket loop exit.

What I have done, it simply add a check for errno == EINTR, and return -1 inside the if that check the return of mg_poll.


```
		pollres = mg_poll(pfd,
		                  1,
		                  (int)(timeout * 1000.0),
		                  &(conn->phys_ctx->stop_flag));
		if (!STOP_FLAG_IS_ZERO(&conn->phys_ctx->stop_flag)) {
			return -2;
		}
		if (pollres > 0) {
			nread = (int)recv(conn->client.sock, buf, (len_t)len, 0);
			err = (nread < 0) ? ERRNO : 0;
			if (nread <= 0) {
				/* shutdown of the socket at client side */
				return -2;
			}
		} else if (pollres < 0) {
                        /* signal is not an error, just loop again like on timeout */
			if (errno == EINTR)
			{
				return -1;
			}
			/* error callint poll */
			return -2;
		} else {
			/* pollres = 0 means timeout */
			nread = 0;
		}
```
