### ISSUE TITLE
The function exited without calling the mg_global_unlock 

### ISSUE THREAD

**Issue by pavel-pimenov** [civetweb/civetweb#1110]
V1020 [CWE-772] The function exited without calling the 'mg_global_unlock' function. Check lines: 22371, 22303. civetweb.c 22371

https://github.com/civetweb/civetweb/blob/master/src/civetweb.c#L22366

**Comment by bel2125** [comment]
Did this problem occur in reality or is this the result of some static source code analysis tool.
This is a code path that should never be reached: malloc for a small amount of memory returning NULL at the beginning of the a program.

Adding `mg_global_unlock();` here is simple, just want to know if this it did occur.
