### ISSUE TITLE
clang error: assigning to 'char *' from incompatible type 'void *'

### ISSUE THREAD

**Issue by pavel-pimenov** [civetweb/civetweb#1124]
clang: 
civetweb/civetweb.c:22360:17: error: assigning to 'char *' from incompatible type 'void *'
                all_methods = mg_malloc(len);
                              ^~~~~~~~~~~~~~

**Comment by bel2125** [comment]
Since this is C code it should be a warning, not an error like it would be in C++.

Nevertheless this is easy to fix --> done.

**Comment by bel2125** [comment]
Thanks for the report. Fixed :-)
