### ISSUE TITLE
 conversion from 'int' to 'uint8_t', possible loss of data

### ISSUE THREAD

**Issue by pavel-pimenov** [civetweb/civetweb#1127]
civetweb\src\match.inl(38): warning C4244: 'initializing': conversion from 'int' to 'uint8_t', possible loss of data
https://github.com/civetweb/civetweb/blob/master/src/match.inl#L38

<pre>
struct mg_match_context {
	int case_sensitive; /* Input: 1 (case sensitive) or 0 (insensitive) */
	size_t num_matches; /* Output: Number of wildcard matches returned. */
	struct mg_match_element match[MG_MATCH_CONTEXT_MAX_MATCHES]; /* Output */
};
<pre>

**Comment by bel2125** [comment]
This is a boolean value (0 or 1), stored in 1 or 4 bytes, so conversion does not loose anything or cause any error. But, since it is easy to avoid this warning, I modified the code accordingly.
