### ISSUE TITLE
Infinite loop after patch 84cb134e

### ISSUE THREAD

**Issue by franckarts** [civetweb/civetweb#1132]
Hi ! 

I use civetweb as an ambedded server in a home made soft for the Raspberry Pi (Raspbian, 64 bits).
For some reasons, the server does not answer anymore to a simple POST request and seems to be blocked.
My investigation leads me to this commit:
https://github.com/civetweb/civetweb/commit/84cb134e

Commenting out this line:
`if (!ERROR_TRY_AGAIN(err)) {` 
fixes the problem.

I don't know the source code if civetweb, can someone helps on this please?

**Comment by franck-talbart** [comment]
FYI, in my case `err== EAGAIN`.

**Comment by JonasBorchelt** [comment]
Same for me. Good catch! If I revert the changes (84cb134e), it works for me again. I was currently searching for the error why I only get 1 answer and after that it was stuck. 

macOS 13.2.1

**Comment by bel2125** [comment]
Thank you very much for this information.
I don't have a Mac to test this, and I could not reproduce it on Linux (not tested on a RaspPi).
Could you tell me the value of "result" in this case?
At a first look, the code should have checked for (result == 1) as well.

```C
		result = poll(pfd, n, ms_now);
		if (result != 0) {
			int err = ERRNO;
			if ((result == 1) || (!ERROR_TRY_AGAIN(err))) {    // <-----------------------
				/* Poll returned either success (1) or error (-1).
				 * Forward both to the caller. */
```

Forward success or any other error than "EAGAIN". Is it possible that the result is "ok" (result == 1) but the errno was kept as "EAGAIN" from a previous function. Then changing the line above would be the fix.

**Comment by franckarts** [comment]
Thank you for your help.
I can confirm that result == 1 and your patch fixes the problem!

**Comment by nemethz5** [comment]
Hi bel2125!

I think the (!ERROR_TRY_AGAIN(err=ERRNO)) is always true, so function will forward the poll returned success or error all the  time - how it must.

I had modify the code of mg_poll() for my application earlier as below and this code is working in Window and Linux Ubuntu both. 
(I had problem with measuring of the timeout in client functions also, I think it fixed also. I have Raspberry PI and I will build later my app for Raspbian also, but I did not this yet.)

I would appreciate it if you could take the time to review my code and write your opinion.
Thanks!


        #if !defined(_POSIX_VERSION)
        static int
        mg_poll(struct mg_pollfd *pfd,
                unsigned int n,
                int milliseconds,
                stop_flag_t *stop_flag)
        {
	        /* Call poll, but only for a maximum time of a few seconds.       */
  	        /* This will allow to stop the server after some seconds, instead */
	        /* of having to wait for a long socket timeout.                   */
	        int ms_now = SOCKET_TIMEOUT_QUANTUM;       /* Sleep quantum in ms */
        
	        do	{
		        int result;
        
        		if (!STOP_FLAG_IS_ZERO(&*stop_flag)) {
        			/* Shut down signal */
        			return -2;
        		}
        
        		if ((milliseconds >= 0) && (milliseconds < ms_now)) {
        	    	ms_now = milliseconds;
        	    }
        		result = poll(pfd, n, ms_now);
        		if (result != 0) {
        			/* Poll returned either success (1) or error (-1). */
        			/* Forward both to the caller.                     */
        			return result;
        		}
        
	        	/* Poll returned timeout (0). */
        		if (milliseconds > 0) {
        			milliseconds -= ms_now;
        		}
        
        	} while (milliseconds > 0);
        
        	/* timeout: return 0 */
        	return 0;
        }
        #else // _POSIX_VERSION
        static int
        mg_poll(struct mg_pollfd *pfd,
                unsigned int n,
                int milliseconds,
                stop_flag_t *stop_flag)
        {
        	/* Call poll, but only for a maximum time of a few seconds.       */
        	/* This will allow to stop the server after some seconds, instead */
        	/* of having to wait for a long socket timeout.                   */
        	int timeout = milliseconds < 50 ? 1 : milliseconds/50+(milliseconds%50 ? 1 : 0);
        	int n50ms = 0, result;
        
        	do  {
        		if(!STOP_FLAG_IS_ZERO(&*stop_flag))
        			{
        			/* Shut down signal */
        			return -2;
        			}
        
        		result = poll(pfd, n, 50);
        		if(result == 0 || (result < 0 && (errno == EINTR))) {
        			n50ms++;
        			result = 0;
        		}
        
        		if(result != 0)
        			{
        			/* Poll returned either success (1) or error (-1). */
        			/* Forward both to the caller.                     */
        			return result;
        			}
        		}
        		while(n50ms <= timeout);

        	/* timeout: return 0 */
        	return 0;
        }
        #endif // _POSIX_VERSION

**Comment by JonasBorchelt** [comment]
> ```c
> if ((result == 1) || (!ERROR_TRY_AGAIN(err))) {
> ```

Fix is working for me, too. Thank you.

**Comment by franckarts** [comment]
Thanks for the commit. It works.
