### ISSUE TITLE
any plan for a new release?

### ISSUE THREAD

**Issue by mfide** [civetweb/civetweb#1138]
As I see, the last release was on September, 2021 (v1.15). Any plan to have a new release soon?

**Comment by ozenozkaya** [comment]
Especially around OpenSSL 3x release, it may be a kind of good move.

**Comment by bel2125** [comment]
Due to several events that are completely out of my control, the release planned for summer 2022 shifted multiple times. Current plan is mid April:

https://github.com/civetweb/civetweb/issues/1079#issuecomment-1469427018

**Comment by bel2125** [comment]
The release candidate is there, all automatic tests are passed, some long time tests are running right now. Some manual will be done on Monday/Tuesday.

**Comment by bel2125** [comment]
Here you are:
https://github.com/civetweb/civetweb/releases/tag/v1.16
