### ISSUE TITLE
loading libcrypto in an unsafe way Abort trap: 6 (MacOS specific)

### ISSUE THREAD

**Issue by mb12** [civetweb/civetweb#1147]
Please note that this issue is specific to MacOS. (https/ssl works fine when I test it on ubuntu linux.)
I have also included below the stack trace from a debug build.
Its an Intel macbook running Big Sur (11.5.2).

<pre>

* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
  * frame #0: 0x00007fff202e492e libsystem_kernel.dylib`__pthread_kill + 10
    frame #1: 0x00007fff203135bd libsystem_pthread.dylib`pthread_kill + 263
    frame #2: 0x00007fff20268406 libsystem_c.dylib`abort + 125
    frame #3: 0x00007fff77cf6a4a libcrypto.dylib`__report_load.cold.1 + 36
    frame #4: 0x00007fff77cf6763 libcrypto.dylib`__report_load + 427
    frame #5: 0x0000000100041b47 dyld`ImageLoaderMachO::doModInitFunctions(ImageLoader::LinkContext const&) + 535
    frame #6: 0x0000000100041f52 dyld`ImageLoaderMachO::doInitialization(ImageLoader::LinkContext const&) + 40
    frame #7: 0x000000010003cae6 dyld`ImageLoader::recursiveInitialization(ImageLoader::LinkContext const&, unsigned int, char const*, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) + 492
    frame #8: 0x000000010003a89f dyld`ImageLoader::processInitializers(ImageLoader::LinkContext const&, unsigned int, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) + 191
    frame #9: 0x000000010003a940 dyld`ImageLoader::runInitializers(ImageLoader::LinkContext const&, ImageLoader::InitializerTimingList&) + 82
    frame #10: 0x000000010002aa12 dyld`dyld::runInitializers(ImageLoader*) + 82
    frame #11: 0x000000010003611a dyld`dlopen_internal + 616
    frame #12: 0x00007fff20330c94 libdyld.dylib`dlopen_internal(char const*, int, void*) + 185
    frame #13: 0x00007fff2031f07e libdyld.dylib`dlopen + 28
    frame #14: 0x00000001014c2b82 libblcgl.dylib`load_tls_dll(ebuf="", ebuf_len=128, dll_name="libcrypto.dylib", sw=0x00000001016d7cc0, feature_missing=0x00000001016da030) at civetweb.c:16724:20
    frame #15: 0x00000001014ad253 libblcgl.dylib`initialize_openssl(ebuf="", ebuf_len=128) at civetweb.c:16829:26
    frame #16: 0x00000001014ab069 libblcgl.dylib`init_ssl_ctx(phys_ctx=0x00000001086ec000, dom_ctx=0x00000001086f63d8) at civetweb.c:17578:7
    frame #17: 0x00000001014aa194 libblcgl.dylib`mg_start2(init=0x00007ffeefbfe690, error=0x00007ffeefbfe670) at civetweb.c:20896:7
    frame #18: 0x00000001014c4aaa libblcgl.dylib`CivetServer::CivetServer(this=0x000000010873a1d0, options=size=10, _callbacks=0x0000000000000000, UserContextIn=0x0000000000000000) at CivetServer.cpp:463:12
    frame #19: 0x00000001014c4ebb libblcgl.dylib`CivetServer::CivetServer(this=0x000000010873a1d0, options=size=10, _callbacks=0x0000000000000000, UserContextIn=0x0000000000000000) at CivetServer.cpp:434:1
    frame #20: 0x00000001006a58ee libblcgl.dylib`std::__1::__unique_if<CivetServer>::__unique_single std::__1::make_unique<CivetServer, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >&>(__args=size=10) at memory:2755:32

</pre>

**Comment by mb12** [comment]
MacOS seems to require libcrypto.dylib to be a symbolic link to libcrypto.1.1.dylib. Otherwise it fails.
Will close it in the next couple of days.

**Comment by bel2125** [comment]
I do not have a MacOS device available for testing. Is this something that changed recently for Big Sur (11.5.2)?
Does your latest comment mean "you fixed the issue yourself"?
Or is there something that needs to be changed in the code (e.g., default define for library name)?
