### ISSUE TITLE
win32 - _InterlockedIncrement

### ISSUE THREAD

**Issue by pavel-pimenov** [civetweb/civetweb#1151]
Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	E0304	no instance of overloaded function "_InterlockedIncrement" matches the argument list	PtokaX	F:\vc15-eng\ptokax-stable\prometheus-cpp\3rdparty\civetweb\src\civetweb.c	1128	

https://learn.microsoft.com/en-us/windows/win32/api/winnt/nf-winnt-interlockedincrement

![изображение](https://user-images.githubusercontent.com/920705/232200765-b6294d97-e9b0-4c56-8010-9cd82220d6b7.png)

**Comment by bel2125** [comment]
What is this tool you are using here? What build configuration?
I cannot reproduce this error, therefore I don't know how to fix it.

On a WIN32 system, "LONG", "int32_t" and "ptrdiff_t" are the same.
It _WIN64 is not defined but _WIN32 is, it is supposed to be a WIN32 system.
Or is this something else that has those defines set?

**Comment by pavel-pimenov** [comment]
git clone https://github.com/pavel-pimenov/flylinkdc-hub

build PtokaX.sln

Microsoft Visual Studio Community 2022 (64-bit) - Preview
Version 17.6.0 Preview 3.0

**Comment by bel2125** [comment]
Thanks. cloning the repository now.
I don't have that Visual Studio version yet, so I might try it with an older one first.

However, if it is a 64-bit build, I wonder why it does not run in the `#ifdef _WIN64` clause before:
![image](https://user-images.githubusercontent.com/5619191/232233558-7bc3f963-22ee-455b-ad12-a3e9a8dc199d.png)
What is `sizeof(ptrdiff_t)` in your case?
8 ... then you should not be in this `#ifdef` branch
4 ... then sizeof(LONG) should be the same and there should be no type conflict
Maybe there is some inconsistency between the headers and pre-processor definitions.

**Comment by bel2125** [comment]
I have an older Visual Studio and SDK version and compiled for Windows 8.1 as target. 
This repository only contains a 32 bit build.
If I add a 64 bit version myself, everything works fine.

So, this is a 32-bit Windows build, and there might be some difference in the SDK definition.
```C
static ptrdiff_t
mg_atomic_dec(volatile ptrdiff_t *addr)
{
	ptrdiff_t ret;

#if defined(_WIN64) && !defined(NO_ATOMICS)
	ret = InterlockedDecrement64(addr);
#elif defined(_WIN32) && !defined(NO_ATOMICS)
	static_assert(sizeof(ptrdiff_t) == sizeof(LONG), "Size mismatch");
	static_assert(sizeof(ptrdiff_t) == sizeof(int32_t), "Size mismatch");
	ret = (LONG)InterlockedDecrement((LONG*)addr);
#elif defined(__GNUC__)                                                        \
    && ((__GNUC__ > 4) || ((__GNUC__ == 4) && (__GNUC_MINOR__ > 0)))           \
    && !defined(NO_ATOMICS)
	ret = __sync_sub_and_fetch(addr, 1);
#else
...
```

This cast will avoid the problem, and the `static_assert` is there to make sure it is safe.
I still don't understand what compiler or SDK version will require this change and what versions will work without. Checking this in will probably break other (older) builds and therefore requires more tests and probably SDK version #ifdef clauses.

**Comment by bel2125** [comment]
This seems to be a C vs C++ issue.
You compiled civetweb.c as C++, not as C.
This seems to be one of the rare cases of incompatibilities.

Please try this:
```C++
static ptrdiff_t
mg_atomic_inc(volatile ptrdiff_t *addr)
{
	ptrdiff_t ret;

#if defined(_WIN64) && !defined(NO_ATOMICS)
	ret = InterlockedIncrement64(addr);
#elif defined(_WIN32) && !defined(NO_ATOMICS)
#ifdef __cplusplus
	static_assert(sizeof(ptrdiff_t) == sizeof(LONG), "Size mismatch");
	static_assert(sizeof(ptrdiff_t) == sizeof(int32_t), "Size mismatch");
	ret = InterlockedIncrement((LONG*)addr);
#else
	ret = InterlockedIncrement(addr);
#endif
#elif defined(__GNUC__)                                                        \
    && ((__GNUC__ > 4) || ((__GNUC__ == 4) && (__GNUC_MINOR__ > 0)))           \
    && !defined(NO_ATOMICS)
	ret = __sync_add_and_fetch(addr, 1);
#else
```

**Comment by grandchild** [comment]
NB: I had to change 2 other locations when packaging this for Archlinux cross-compilation for Windows with MinGW-w64 for the i686/32-bit build:

https://aur.archlinux.org/cgit/aur.git/tree/0001-Add-cast-for-interlockedincrement-for-32bit.patch?h=mingw-w64-civetweb

(Build steps/commands are visible here: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=mingw-w64-civetweb#n34)
