### ISSUE TITLE
Newbie question:  Is there a way to specify multiple document_root values, for prioritized file lookup?

### ISSUE THREAD

**Issue by jfriesne** [civetweb/civetweb#1159]
I just started with CivetWeb today, so I apologize if the answer to this question is obvious.

I'm looking into embedding CivetWeb into my C++ app; it would replace an older (proprietary) web server and replicate its functionality (except with TLS and HTTP/2 support, yay!).

One feature the old web server has is the ability to specify a 'path' of multiple directories for its "document_root".  For example, on startup you could (conceptually) specify:

     document_root=/var/www/custom:/var/www/default

... and if a client requests the file `index.html`, the web server first looks for `/var/www/custom/index.html`, and if that file exists, the server returns it; if not, the web server then looks for `/var/www/default/index.html`, and if the file exists, the server returns it; and finally if the file doesn't exist in any of the specified folders, the server returns a `404` error.

My question is, what is the best way to obtain this same behavior using CivetWeb?  As a last resort I could start hacking the code in `civetweb.c` to add that behavior, but I'm hoping there is a better/easier way.

**Comment by jfriesne** [comment]
I created pull request #1162 to address this issue.

**Comment by bel2125** [comment]
Previously I solved a similar problem by using a Lua script as 404 handler.
But I like the idea in your pull request and will merge this after having a closer look.
