### ISSUE TITLE
how do I increase Civetweb's internal WebSocket buffer?

### ISSUE THREAD

**Issue by AlbertShown** [civetweb/civetweb#1166]
How do I increase Civetweb's internal WebSocket buffer?
ChatGPT gives me this:

```
const char *options[] = {
        "listening_ports", "8080",
        "websocket_buffer_size", "65536",
        NULL
};
```

But I can't find `websocket_buffer_size` in the Civetweb documentation.

**Comment by bel2125** [comment]
I don't know this option either.
Maybe you ask ChatGPT why it thinks this option exists ... but ChatGPT is usually unable to tell you why it "thinks" something is like this.

I do not even know what exactly a "Websocket buffer size" is supposed to be.
There is one configuration option "max_request_size" that is used for the maximum size of all kinds of request *header data*. It does not affect the *body data* or Websocket message payload.

**Comment by AlbertShown** [comment]
Answered https://github.com/civetweb/civetweb/issues/1075#issuecomment-1550152407
