### ISSUE TITLE
Support `Access-Control-Allow-Credentials: true` header for the file requests

### ISSUE THREAD

**Issue by linev** [civetweb/civetweb#1173]
**Is your feature request related to a problem? Please describe.**
Loading files from civetweb server using XMLHttpRequest with [withCredentials](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/withCredentials) field true.
If `htdigest` authentication is configured, web browser refuses to use stored credentials and reject response provided by `civetweb`. 

**Describe the solution you'd like**
At the same places where `Access-Control-Allow-Origin` header is provided, optionally add credentials header.

**Describe alternatives you've considered**
Handle file requests myself, but this means re-implementing code again.

**Describe how the feature would benefit other users**
Allows to read files from `civetweb`, configured with password, without need to (re)enter password every time new browser tab is started.

Here is example how changes can be implemented:

https://github.com/root-project/root/commit/8157b9334547672d39a29f77a5178b5456c09ad2

**Comment by bel2125** [comment]
Yes, good improvement we should merge into the master branch.
Could you provide a pull request? 
Or is it possible to merge it as a patch from your project (I haven't tried).

**Comment by linev** [comment]
Here is PR: https://github.com/civetweb/civetweb/pull/1174

**Comment by bel2125** [comment]
Thank you. Merged.
