### ISSUE TITLE
Response code handling after file upload via form

### ISSUE THREAD

**Issue by jrki1975** [civetweb/civetweb#1180]
Hi,

I use Civetweb V1.16 on embedded device using C and try to implement a file upload and adapted the "form upload" example from "embedded_c.c". 
Uploading works principally, but I would like to verify the MD5 checksum after the complete file has been uploaded and send one single response to the web browser (either "200 OK" or "500 internal server error" or something similar if the checksum is wrong).

The example in embedded_c.c seems to send the positive response before(!) evaluating the form (see [1] in my code, below).
I would like to evaluate first and send the response afterwards (see lines marked with [2], below. line [1] deactived in that case), but this seems not work. The web browser (VS Code Thunder Client Plugin) says "Parse error - HTTP expected" and in Wireshark I see that Civetweb sends TCP packet instead of an HTTP packet.

Additionally, the client receives the content of one of the form fields ("destinationFolder" and "MD5") and I cannot find any code in civetweb that does this.

Do you have any ideas how I can achieve the "upload first, evaluate file, then send response" task?
Thank you very much for your help!

my REST Post:
  `POST:	http://<ip_address>/api/v1/file `
  The form has fields: destFolder, md5, filename(the file)

```
mg_set_request_handler(ctx, CIVETCTRL_REST_FILE_URI_V1, REST_uploadHandler, (void*)0);
...
int REST_uploadHandler(struct mg_connection *conn, void *cbdata)
{
  ...
  mg_printf(conn, "HTTP/1.1 200 OK\r\nContent-Type: text/plain\r\nConnection: close\r\n\r\n");  // [1]
  
   /* Call the form handler */
   numFieldsFound = mg_handle_form_request(conn, &fdh);
   if(numFieldsFound != 3) {
      mg_send_http_error(conn, 400, "Bad Request");	// [2]
      return 400;
   } else {
      if(REST_chkMd5(gExpectedMd5, gFilePath) == FALSE) {
         mg_send_http_error(conn, 500, "Checksum error");	// [2]
         return 500;
      }
      else {
        mg_printf(conn, "HTTP/1.1 200 OK\r\nContent-Type: text/plain\r\nConnection: close\r\n\r\n"); // [2]
      }
   }
   return 200;
}
```

**Comment by bel2125** [comment]
You used this example as a base?

https://github.com/civetweb/civetweb/blob/8fa86ff9c1e78cfd143c2f56b5521cef4986b89e/examples/embedded_c/embedded_c.c#L419

The handlers "field_found, field_get, field_stored" so not need to send anything, but you could store everything you need to know from them in a user defined structure, passed as "fdh.user_data". Then you move the lines sending 200 OK 

https://github.com/civetweb/civetweb/blob/8fa86ff9c1e78cfd143c2f56b5521cef4986b89e/examples/embedded_c/embedded_c.c#L430

from before the `mg_handle_form_request` call

https://github.com/civetweb/civetweb/blob/8fa86ff9c1e78cfd143c2f56b5521cef4986b89e/examples/embedded_c/embedded_c.c#L437

to after it and send whatever you want to send there.

**Comment by jrki1975** [comment]
Yes, I used the examples that you inserted.

As mentioned above, I already tried moving the "200 OK" line to AFTER mg_handle_form_request(), but the problem is, that Civetweb seems not to reply with a complete/correct HTTP frame.

My code looks like this:   numFieldsFound = mg_handle_form_request(conn, &fdh);
```
   /* Call the form handler */
   numFieldsFound = mg_handle_form_request(conn, &fdh);

   if(numFieldsFound != 3) {
      mg_send_http_error(conn, 400, "Bad Request");
      return 0;
   } else {
      if(REST_chkMd5(gExpectedMd5, gFilePath) == FALSE) {
         mg_send_http_error(conn, 500, "Checksum error");
         return 0;
      }
      else {
         mg_printf(conn, "HTTP/1.1 200 OK\r\nContent-Type: text/plain\r\nConnection: close\r\n\r\n");  // Zeile [2]
      }
   }
```
1) If I send an upload file with wrong MD5 checksum, I get the following in Wireshark:
![image](https://github.com/civetweb/civetweb/assets/50908484/964a0aed-0476-4aa8-8f39-f88ddfeb260c)
The message no.31 ("continuation") shows, that civetweb replys part of the form fields ("destination folder": mnt/flashdrive... and the "MD5") before the "500 internal server error" text.

[FileUploadChecksumErr.zip](https://github.com/civetweb/civetweb/files/12109611/FileUploadChecksumErr.zip)

2) If I send an upload file with CORRECT checksum, the Wireshark log likes very distored:
No HTTP packet at all. In message 32 for example, you see the "mirrored" form content ("mnt/flashdrive0/data") 
[FileUpload_CorrectChecksum.zip](https://github.com/civetweb/civetweb/files/12110136/FileUpload_CorrectChecksum.zip)

Any ideas?
Thanks a lot for your help!

**Comment by bel2125** [comment]
For me, the first file "CorrectCheckSum" looks like you have a broken network communication. Lots of TCP retransmissions and the overall message does not seem to be complete.
When using WireShark, use "follow TCP stream" to see the entire TCP (HTTP) payload assembled into one data stream as the server will see it. This seems to be incomplete in the "CorrectCheckSum" case.

The "CheckSumError" looks better to me, but some part of the server seems to write a path (/mnt/flashdrive0/...0ffe) to the connection before the server starts to send the response.

![image](https://github.com/civetweb/civetweb/assets/5619191/1bf035dc-1d4d-4ebc-a4f3-d4c69bf5c9d0)
![image](https://github.com/civetweb/civetweb/assets/5619191/4a773a49-77fc-49c5-93e8-32616693666a)

This way, the entire response message gets unreadable for the client. The first message written by the server must be the first line of the respone header. You can write it manually or (better) use `mg_response_header_start()` as first call. See https://github.com/civetweb/civetweb/blob/master/docs/api/mg_response_header_X.md

**Comment by jrki1975** [comment]
I found my error. During the debugging process I added a mg_write() statement into field_get() which was responsible for this double and incorrect response. After removing it, everything works fine, now.
Thanks for your help!
