### ISSUE TITLE
It would be useful to be able to specify that a listen-port number is optional and shouldn't abort startup if it can't be bound

### ISSUE THREAD

**Issue by jfriesne** [civetweb/civetweb#1185]
Currently when specifying the set of ports that a CivetWeb should listen on, you can optionally append a suffix-letter to the port number, e.g. 's' to indicate that the port should use SSL/TLS, 'r' to indicate that the port should redirect, etc.  That's all working well.

My app launches a CivetWeb web browser as a background process, with a `listening_ports` argument telling it which ports to listen on.  This argument typically includes a hard-coded TLS port, a hard-coded TCP port, and optionally a user-specified TLS port as well.

That mostly works fine, but sometimes the user chooses his port poorly, and specifies a port that another process is already bound to.  When that happens, the civetweb process detects the error in `bind()` and responds by bailing out and exiting, leaving the user wondering why none of the HTTP-provided functionality of the app is working.

It would be a better user experience if there was a way to specify that certain ports specified in the `listening_ports` argument are "optional", in the sense that a failure to bind to those ports should not be fatal, and the CivetWeb process should just continue running without them.  Then the user would still get the basic CivetWeb functionality, just not on his custom-specified port (and it would be obvious to the user *why not* the next time he tries to connect to that port and finds a different application's web page living there instead).  

This could be implemented by appending an 'o' suffix to the port number (possibly in addition to any other existing suffix-letter), e.g. `listening_ports`,`8000,8080s,8088s` would give a traditional behavior, while `listening_ports`,`8000,8080so,8088s` would be the same except that if CivetWeb failed to bind to port `8080` it would carry on regardless instead of exiting.

**Comment by bel2125** [comment]
Agreed.
This is an easy solution that can be added.
