### ISSUE TITLE
Use of __VA_ARGS__ in macro/function

### ISSUE THREAD

**Issue by hansipie** [civetweb/civetweb#1188]
Hello,

During the compilation of `civetweb` in debug mode (i.e. WITH_DEBUG=1), we encountered an issue related to the use of the `DEBUG_TRACE_FUNC` function. The current definition of this function is:

```c
static void DEBUG_TRACE_FUNC(const char *func,
                             unsigned line,
                             PRINTF_FORMAT_STRING(const char *fmt),
                             ...) PRINTF_ARGS(3, 4);
```

However, following this definition, we are attempting to invoke this function using `__VA_ARGS__`, treating it as if it were a macro:

```c
#define DEBUG_TRACE(fmt, ...)                                                  \
	DEBUG_TRACE_FUNC(__func__, __LINE__, fmt, __VA_ARGS__)
```

This approach results in a compilation error indicating "expected expression before ‘)’ token" on line 234 of `civetweb.c`.

Upon further examination, it became clear that the core issue lies in the fact that `DEBUG_TRACE_FUNC` is a function and not a macro. Hence, the direct usage of `__VA_ARGS__` is not suitable.

To address this, we considered using the wrapping macro with the GCC extension "##__VA_ARGS__". By defining:

```c
#define DEBUG_TRACE(fmt, ...)                                                  \
	DEBUG_TRACE_FUNC(__func__, __LINE__, fmt, ##__VA_ARGS__)
```

I wanted to inform you of this and discuss any implications or further adjustments needed following this change.

Best regards

**Comment by hansipie** [comment]
PR submited taking in account "##__VA_ARGS__" is only available in GCC: #1189

**Comment by bel2125** [comment]
Thank you.
I just had a look at the pull request and found it is GCC specific.

The standard way seems to be `__VA_OPT__`: https://en.cppreference.com/w/cpp/preprocessor/replace

What compiler/system are you using to encounter this problem?

**Comment by hansipie** [comment]
Hello

I'm using gcc verison 11.4.0 under Ubuntu 22.04.3 LTS.

Indeed with
```c
#define DEBUG_TRACE(fmt, ...)                                                  \
	DEBUG_TRACE_FUNC(__func__, __LINE__, fmt __VA_OPT__(, ) __VA_ARGS__)
``` 
no more compilation issue on my side.

**Comment by hansipie** [comment]
Here's a conditional compilation solution that should work across various scenarios:

```c
#if defined(__cplusplus) && (__cplusplus >= 202002L)
    #define DEBUG_TRACE(fmt, ...)                                               \
        DEBUG_TRACE_FUNC(__func__, __LINE__, fmt __VA_OPT__(, ) __VA_ARGS__)
#elif defined(__GNUC__) && defined(__STDC_VERSION__) && (__STDC_VERSION__ >= 201112L)
    #define DEBUG_TRACE(fmt, ...)                                               \
        DEBUG_TRACE_FUNC(__func__, __LINE__, fmt, ##__VA_ARGS__)
#else
    #define DEBUG_TRACE(fmt, ...)                                               \
        DEBUG_TRACE_FUNC(__func__, __LINE__, fmt, __VA_ARGS__)
#endif
``` 

Please review and let me know your thoughts.

**Comment by bel2125** [comment]
My problem here, and the reason why I did not merge it yet:
I did not reproduce the original problem in the first place. And I did not understand why GCC needs this differently than any other compiler. Also, I am on vacation and did not have the time to investigate this in detail.

**Comment by bel2125** [comment]
I mean, the problem in principle is explained here:
https://stackoverflow.com/questions/52891546/what-does-va-args-mean
But the PR only handles GCC (and compilers with a GCC define), while the default branch remains unmodified.

In many cases we used
DEBUG("%s", "the text")
instead of
DEBUG("the text")
before.

**Comment by hansipie** [comment]
Fair enough ... When you will be able to reproduce, you will have the solution here ;)

**Comment by hansipie** [comment]
About DEBUG("%s", "the text") or DEBUG("the text")
In http2.inl i've found the form DEBUG("the text") what causes the build error. Adding "%s" fixes the build error. 
If you prefere this fix i can create a PR.

**Comment by bel2125** [comment]
Yes, please.
This fix works for all compilers, versions, C, C++, ... and does not need compiler version specific macro definitions.

**Comment by hansipie** [comment]
Done. :)
