### ISSUE TITLE
Trying for entire day to get https to work.   Seg fault when trying to access the page.

### ISSUE THREAD

**Issue by BensonBear** [civetweb/civetweb#1200]
I have used the certificate I am already using succesfully that I normally use in stunnel with no problem to forward https from outside my local network to a local machine running a plain http server.

This certificate did not have "RSA" in the label on the private key, but I added it.  Still does not work.  Get nothing but a segmentation fault (which of course should not happen under any circumstances)

EDIT: I got it to work, by removing all but one of the BEGIN CERTIFICATE sections in the certificate given to me by the "lets encrypt" certificate authority.   I was going by the line in the civetweb documentation at said there would be "at least one section BEGIN CERTIFICATE / END CERTIFICATE" in a PEM certificate file from an authority.   But on a hunch that this might not be right, I tried each of the certificates one by one and one of them worked if it was the only one included with the private key in the PEM file offered to civetweb.

I guess to get around this trial and error methodology, I have to learn why there are multiple certificates in the file and why I must include only one of them...

Will close this issue since it does work now.

**Comment by bel2125** [comment]
Certificate handling is not exactly easy, but this is not CivetWeb specific.
CivetWeb just uses the either OpenSSL or mbedTLS, they have to read the certificate files.

Some demo certificates for testing are in the repository, and the script with all the steps to generate it:
https://github.com/civetweb/civetweb/blob/master/resources/cert/make_certs.sh

You solved it already, but maybe having a look at the steps in this script is still helpful or might help others who find this issue later.
