### ISSUE TITLE
Errors in Lua scripts and Lua Server Pages not handled well

### ISSUE THREAD

**Issue by The-EG** [civetweb/civetweb#1213]
Currently errors that occur when loading or running lua scripts or lua server pages are not handled in a helpful way.

By lua scripts, I'm referring to a *.lua file that is requested by URI, ran and the output (via. `mg.write`) is sent as the response body. Lua server pages are *.lp files that have embedded lua tags that are evaluated.

For lua scripts, https://github.com/civetweb/civetweb/blob/master/src/mod_lua.inl#L3070C3-L3074C4:
```c++
               if (luaL_loadfile(L, path) != 0) {
			lua_error_handler(L);
		} else {
			lua_pcall(L, 0, 0, -2);
		}
```
If the script fails to load (a syntax error or similar), `lua_error_handler` is called. This outputs the error message straight to the HTTP client without a valid HTTP response or headers. This confuses the client application, and the best scenario is that it shows an 'invalid response' to the user. In other cases, such as when using curl, you'll get a more misleading message like `curl: (1) Received HTTP/0.9 when not allowed`.

If the script loads successfully, but a runtime error occurs (which is at the `lua_pcall` line above), it appears that `lua_error_handler` is again run and outputs to the response stream. This has the exact same result as above.

If an appropriate HTTP response is output before the error message the client will be able to see the response, with the helpful error message. ie:
```c++
                int load_status = luaL_loadfile(L, path);
		if (load_status != 0) {
			mg_send_http_error(conn, 500, "Lua error:\r\n");
			lua_error_handler(L);
		} else {
			int call_status = lua_pcall(L, 0, 0, 0);
			if (call_status != 0) {
				mg_send_http_error(conn, 500, "Lua error:\r\n");
				lua_error_handler(L);
			}
		}
```

It might be more appropriate to just add the response output to the top of `lua_error_handler`, but I'm not sure where all it's used at.

With lua server pages using kepler syntax (where civetweb automatically sends the HTTP response), the 200 OK response is already sent before the lua on the page is being processed.

https://github.com/civetweb/civetweb/blob/master/src/mod_lua.inl#L661-L669:
```c++
	if (lua_ok) {
		/* Syntax error or OOM.
		 * Error message is pushed on stack. */
		lua_pcall(L, 1, 0, 0);
		lua_cry(conn, lua_ok, L, "LSP", "execute"); /* XXX TODO: everywhere ! */

	} else {
		/* Success loading chunk. Call it. */
		lua_pcall(L, 0, 0, 1);
	}
```

Syntax errors in this case is a little better because the error is at least printed to the log/messages, however the client receives an empty 200 OK response. But, the error listed in the log isn't particularly helpful because it lacks the filename or line number, ie. `LSP: execute failed: syntax error: attempt to call a userdata value`

Runtime errors don't appear to be shown at all. The response is just cut off at the last thing output before the lua section with an error.

Similar to above, it's possible to use `lua_error_handler` here to output a useful error message in the response, which is why including the response header in it may not be appropriate (a 200 has already been sent in this case). But in any case, just having the full error text from lua in the `lua_cry` message would be more helpful that what happens currently

**Comment by bel2125** [comment]
Your suggested code changes have been merged.
To have a complete solution for all cases will require a deeper review and modification.
Usually I test the pages before deploying it outside the web server with the standard Lua standalone interpreter on Linux and a mock-up "mg" Lua library.

**Comment by The-EG** [comment]
Thanks! 
I understand that in some situations, especially embedded applications with static content, this is probably less of a concern, but I think at least giving the proper HTTP response is a good minimum. Having to break out WireShark just to figure out what is happening isn't good!
