### ISSUE TITLE
Can't get index.lua file working on Linux.

### ISSUE THREAD

**Issue by egorkonovalov** [civetweb/civetweb#1236]
The path of the index file is `/var/www/docs/index.lua`, the `document_root` points to  `/var/www`. When I navigate to `localhost/docs/` I expect the lua script to process the request and send a response managed by `mg.write()`, but I get file listing instead.
![image](https://github.com/civetweb/civetweb/assets/73017521/73b406ed-eb11-49cd-9b54-d2f76264f63e)
The same set up works on Windows as expected. Are there some quirks with setting up Civetweb on Linux that I'm not aware of?

Civetweb v1.16
Ubuntu 22.04.3 LTS

**Comment by Dialga** [comment]
Have you tried setting `enable_directory_listing` to no? Have you modified the `index_files` option?
What is the exact commandline you are using and the config file options?

**Comment by bel2125** [comment]
Also, if you build the server, make sure to build with LUA support.
`make WITH_LUA=1`

**Comment by egorkonovalov** [comment]
> Also, if you build the server, make sure to build with LUA support. `make WITH_LUA=1`

that was the issue, thanks
