### ISSUE TITLE
Does not follow RFC 2046 standard for multipart POST data

### ISSUE THREAD

**Issue by timtjtim** [civetweb/civetweb#1276]
The specification for multipart form data can be found in RFC 2046 https://datatracker.ietf.org/doc/html/rfc2046.

Section 5.1.1 contains the formal BNF:

```
boundary := 0*69<bchars> bcharsnospace

     bchars := bcharsnospace / " "

     bcharsnospace := DIGIT / ALPHA / "'" / "(" / ")" /
                      "+" / "_" / "," / "-" / "." /
                      "/" / ":" / "=" / "?"

   Overall, the body of a "multipart" entity may be specified as
   follows:

     dash-boundary := "--" boundary
                      ; boundary taken from the value of
                      ; boundary parameter of the
                      ; Content-Type field.

     multipart-body := [preamble CRLF]
                       dash-boundary transport-padding CRLF
                       body-part *encapsulation
                       close-delimiter transport-padding
                       [CRLF epilogue]

     transport-padding := *LWSP-char
                          ; Composers MUST NOT generate
                          ; non-zero length transport
                          ; padding, but receivers MUST
                          ; be able to handle padding
                          ; added by message transports.

     encapsulation := delimiter transport-padding
                      CRLF body-part

     delimiter := CRLF dash-boundary

     close-delimiter := delimiter "--"

     preamble := discard-text

     epilogue := discard-text

     discard-text := *(*text CRLF) *text
                     ; May be ignored or discarded.

     body-part := MIME-part-headers [CRLF *OCTET]
                  ; Lines in a body-part must not start
                  ; with the specified dash-boundary and
                  ; the delimiter must not appear anywhere
                  ; in the body part.  Note that the
                  ; semantics of a body-part differ from
                  ; the semantics of a message, as
                  ; described in the text.

     OCTET := <any 0-255 octet value>
```

this issue is regarding the end of the multipart-body:

```
                       close-delimiter transport-padding
                       [CRLF epilogue]
```

The current code
1. Does not support handling any transport padding
2. Requires the trailing CRLF
3. Does not handle an epilogue? (TBC)

From my testing, this has been fine when using Google Chrome, as it finishes the multipart data with a CRLF (and an empty epilogue).

however, the JS library node-fetch does not include this optional CLRF, meaning the server fails to parse the request.

The problematic code is

https://github.com/civetweb/civetweb/blob/master/src/handle_form.inl#L730

where it's checking the final boundary is not just ending with the extra `--` of the close delimiter, but also requiring a CRLF.

**Comment by timtjtim** [comment]
From a glance at the code I think there may be further issues with its handling of multipart data vs the RFC, but I've not done any testing yet.

**Comment by timtjtim** [comment]
I've got some test cases going there. Nor sure which are failing and which are fine yet given they're all part of one test function.

**Comment by timtjtim** [comment]
Hopefully will get an initial fix for the final boundary CRLF today

**Comment by timtjtim** [comment]
Possibly the preamble also can't contain a single dash?

**Comment by bel2125** [comment]
The source code has been tested with every major browser at the time of writing. Certainly there are some libraries and maybe some exotic browsers that have not been tested. I am not aware of any RFC-compliance test suite, anything that could be used to check if all special cases possible in theory are handled exactly according to in the RFC. I cannot test this BNF directly.

I don't know if it was done here, but in some cases parts that would be allowed by an RFC, but not done from any "well behaved" client are not implemented - because the only possible reason a client could do that would be to consume a lot of resources at the server without any effect (sending gigabytes of prologue to be ignored).

If there is a legit use case, in particular if a widely used library does not work, of course it needs to be fixed.
If you have a pull request fixing it, I can definitely merge it.
If you don't have a complete fix but a test program to reproduce it, I can have a look.

**Comment by timtjtim** [comment]
Yeah I’ve got a few test cases and I’m working on a PR now :)

**Comment by timtjtim** [comment]
> I don't know if it was done here, but in some cases parts that would be allowed by an RFC, but not done from any "well behaved" client are not implemented - because the only possible reason a client could do that would be to consume a lot of resources at the server without any effect (sending gigabytes of prologue to be ignored).

Agreed - not looking to change that, this was just a particular edge case. In fact, the comments suggested a correct interpretation of the RFC, and the code just didn't quite align :)

I've raised the PR!

**Comment by timtjtim** [comment]
@bel2125 thanks for the help + quick responses :)

Will you tag this as a new release?
