### ISSUE TITLE
How do you build the binary to use the API / where is the source code for the API?

### ISSUE THREAD

**Issue by Hallilogod** [civetweb/civetweb#1290]
Hi, im trying to make a small webserver and need to parse HTTP requests, i found this project but cant find any source file for the API or library to link to, just the header file, please help! thanks

**Comment by haovxuan** [comment]
Maybe you can refer to this link. https://github.com/civetweb/civetweb/blob/master/docs/Embedding.md

**Comment by Hallilogod** [comment]
Ill take a look at it, thank you

**Comment by Hallilogod** [comment]
I got everything working with a custom parser now. Thanks for the help anyways
