### ISSUE TITLE
Question: is there built-in session support?

### ISSUE THREAD

**Issue by shawnye** [civetweb/civetweb#140]
I mean something like `Apache Module mod_session` or `Java HttpSession`.
if none , is there some suggestion to implement it ? 

thank you.

**Comment by bel2125** [comment]
Sessions are usually built on client side cookies and a server side database - this is of course possible with civetweb. It takes just a few lines of code to build your custom session handling - there is no extra module for this.

The way sessions need to be implemented depends on how you use civetweb.
- Are you using it with Lua? Then you add session handling in a few lines of Lua code and put this in the Lua preload file.
An example how to handle cookies in Lua is here:
https://github.com/bel2125/civetweb/blob/master/test/page4.lua
You could create a random cookie and store all additional data fiends in the sqlite data base:
https://github.com/bel2125/civetweb/blob/master/test/page.lua

- Are you using it with CGI? Then it depends on the CGI language.

- Are you using it embedded and handling the requests in a callback? Then you need to handle it there.


There are also other ways than cookies to implement sessions:
http://en.wikipedia.org/wiki/HTTP_cookie#Alternatives_to_cookies

**Comment by shawnye** [comment]
Thank you for detail explanation !
I am using Lua, and try your example .

BTW,  I would rather server side implemented session than client side one for sake of better security.

**Comment by bel2125** [comment]
> ... I would rather server side implemented session than client side one for sake of better security.

Of course. But you might still need a session cookie that identifies the client.
I used a GUID for this, stored in a client side cookie, while all the variables relevant for the session remain in the server side data base. The GUID in the cookie is the key for the data base. So the only client side component is a GUID, and the client can not fudge any sensitive data.

I just saw the Lua library for creating a GUID is currently not in the standard.
It's a simple call to uuid_generate (libuuid) in Linux and CoCreateGuid in Windows - it does not seem to be available for android (http://stackoverflow.com/questions/11888055/include-uuid-h-into-android-ndk-project) - did not check for all other platforms. So I cannot simply add it to the mainline. Are you building the server on your own? Windows or Linux?

**Comment by shawnye** [comment]
Thank you! 
`GUID ` just like `jsessionid` in Java.

BTW, there is a `semi-official` lua uuid C lib provided 
http://webserver2.tecgraf.puc-rio.br/~lhf/ftp/lua/#luuid
A library for generating universally unique identifiers based on libuuid, which is part of e2fsprogs.

**Comment by bel2125** [comment]
> GUID just like jsessionid in Java.

From a brief look at the jsessionid docs: Probably yes - I don't know Java in detail here.
It is also in principle possible to add this ID either as a cookie, or as a part of the URL (also this might be problematic: https://randomcoder.org/articles/jsessionid-considered-harmful).


Also here is quite a number of libraries for Lua:
http://luarocks.org:8080/m/root

The ones that are implemented in pure Lua can be added to CivetWeb by anyone who wants them - there is no use to add them to the Civetweb source tree and maintain them here.

The ones that need some C parts are more critical: I consider file system access (LuaFileSystem) and data base access (lsqlite) as very crucial for a web server, and they have implementations for (more or less) all platforms, so they are added here. Other libraries with C components might be interesting as well, but I can not add all of them here.

**Comment by bel2125** [comment]
It's been a while since the last comment on this topic, so I will close this issue now.
If there are more questions, please open a new thread in the discussion group (https://groups.google.com/d/forum/civetweb).
