### ISSUE TITLE
Civetweb performance is poor on embedded NAS device

### ISSUE THREAD

**Issue by helloray** [civetweb/civetweb#143]
civetweb running as a file sharing server on pogoplug (http://archlinuxarm.org/platforms/armv5/pogoplug-series-4)
The test environments were:
PC: win7 + chrome + core i3 CPU
Pogoplug connected with PC by gigabit ethernet switch

Tried to download/upload a 700M file from/to pogoplug. Please check below test results.
Server/Download Speed/Upload Speed
nginx                40M~42M                 16~20M
pure-ftpd          40M~42M                 18~20M
samba              39M~42M                  18~20M
civetweb           18M~20M                   6M~9M

Any suggestions of performance tuning?

**Comment by bel2125** [comment]
Which version are you running? Did you use the default settings for your test?

**Comment by bel2125** [comment]
I also do not really understand how you did your measurements.
I don't have a pogoplug, so I checked it by downloading a 100 MB file from an Ubuntu server to a Windows client, connected with a 100MBit network, using `curl` (not a browser, that might use a proxy, but a command line tool that shows statistics as well):

    D:\civetweb>curl -o NUL http://192.168.0.3:8080/largefile.bin
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    100  100M  100  100M    0     0  6749k      0  0:00:15  0:00:15 --:--:-- 7006k

15sec for 100 MB

I don't want to set up nginx and samba on my Linux PC, and pure-ftpd does not seem to work for anonymous FTP (or I did not find out what password to use). So I could only test with proftpd:

    D:\civetweb>curl -o NUL ftp://192.168.0.3/largefile.bin -u user:pw
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    100  100M  100  100M    0     0  11.0M      0  0:00:09  0:00:09 --:--:-- 11.1M

9sec for 100 MB

How did you get your numbers above?

**Comment by bel2125** [comment]
Same test localhost - completely different result:

CivetWeb:

    user@host:~$ curl http://localhost:8080/hugefile.bin -o /dev/null
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    100 5000M  100 5000M    0     0  1008M      0  0:00:04  0:00:04 --:--:-- 1013M

FTP:

    user@host:~$ curl ftp://localhost/hugefile.bin -o /dev/null -u user:pw
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    100 5000M  100 5000M    0     0   106M      0  0:00:46  0:00:46 --:--:-- 99.6M

**Comment by helloray** [comment]
Hi bel2125,

Thanks for your reply. I using git lastest version for the tests. Please find more details below.
1. Did you use the default settings for your test?
Yes. 
For download, I did the test using civetweb -document_root $HOMEDIR
For upload, I did the test using examples/upload 

2. I also do not really understand how you did your measurements.
For download, using chrome to download the file and check the speed in chrome's download manager page(chrome://downloads/)
For upload, I counted the time used for upload and get the average speed. 

I think you may hard to duplicate this issue because you using a 100M network and more powerful desktop CPU. I dig into this issue yesterday and found some points for improvement.

1.  In function push,  extra effort is used for time calculate
clock_gettime(CLOCK_MONOTONIC, &start);
clock_gettime(CLOCK_MONOTONIC, &now);
mg_difftimespec(&now, &start) <= timeout)

2. In function mg_upload, too much effort is used for boundary checking.

**Comment by helloray** [comment]
I dig into this issue yesterday and found some points for improvement.

1.  In function push,  extra effort is used for time calculate
clock_gettime(CLOCK_MONOTONIC, &start);
clock_gettime(CLOCK_MONOTONIC, &now);
mg_difftimespec(&now, &start) <= timeout)

2. In function mg_upload, too much effort is used for boundary checking.

**Comment by bel2125** [comment]
I did my measurements with a command line utility called `curl` (http://en.wikipedia.org/wiki/CURL). It is available for Linux and Windows, and can be used to up- and download files from the command line, without having to use a browser. It can be used to automate tests with web servers. Beside HTTP it also supports FTP, and a couple of other protocols. It displays timing statistics - so it is the perfect tool for a quick performance measurement.
In contrast, a browser may do some more stuff, like automatically using a proxy although a direct connection would be possible - this needs to be checked if you want to conclude anything from a performance measurement done by a browser. 
So in this case, a WireShark protocol is required to analyze performance issues.

It can be checked easily if the `clock_gettime` calls have any influence on the performance. You just need to set the timeout value to 0 (e.g., start with `-request_timeout_ms 0` from the command line), then these calls are not made. I can not imagine that these calls make a lot of difference, but of course one can make this simple test to be sure.

The `mg_upload` function can certainly be optimized. I think it should be completely rewritten, so you can not only handle forms that only upload files, but also other input types. The new function will have an incompatible interface. So this is something I won't start before the next release.

I don't know your particular hardware. Is this a single core, 800MHz ARM CPU running Linux? Is it possible to run wireshark there?

**Comment by bel2125** [comment]
It is actually also possible to upload a file without using mg_upload, e.g. by a client side like this
http://stackoverflow.com/questions/8659808/how-does-http-file-upload-work/28193031#28193031
and a server side with a few lines of Lua to store the entire POST body into a file.
This is much more like FTP works - the entire boundary checking logic is not required there.

**Comment by bel2125** [comment]
Another relevant function for file download should be `send_file_data`. Probably one can test with different sizes for `char buf[MG_BUF_LEN];`, maybe 1400 or 1460 will give better performance - but I have not tested it.

**Comment by bel2125** [comment]
I did some more measurements with CivetWeb vs FTP (vsftpd), and found that in my case, the code is mainly limited by the speed of the client hard disk, not the server. If I do not store the result but drop it directly to /dev/null, 1000 MB will load in 6 (FTP) to 7 seconds (HTTP). If I drop it into a filter like `wc` (word count), it takes 1:27 for both:

```bash
user@host:~$ curl -N http://localhost:8080/hugefile.b | wc
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 5000M  100 5000M    0     0  57.1M      0  0:01:27  0:01:27 --:--:-- 57.2M
      0       1 5242880000
user@host:~$ curl -N http://localhost:8080/hugefile.b | wc
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 5000M  100 5000M    0     0  56.9M      0  0:01:27  0:01:27 --:--:-- 56.8M
      0       1 5242880000
user@host:~$ curl -N http://localhost:8080/hugefile.b | wc
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 5000M  100 5000M    0     0  57.2M      0  0:01:27  0:01:27 --:--:-- 56.9M
      0       1 5242880000

user@host:~$ curl -N ftp://localhost/hugefile.b --user anonymous:guest | wc
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 5000M  100 5000M    0     0  57.7M      0  0:01:26  0:01:26 --:--:-- 57.8M
      0       1 5242880000
user@host:~$ curl -N ftp://localhost/hugefile.b --user anonymous:guest | wc
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 5000M  100 5000M    0     0  58.1M      0  0:01:25  0:01:25 --:--:-- 58.1M
      0       1 5242880000
user@host:~$ curl -N ftp://localhost/hugefile.b --user anonymous:guest | wc
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 5000M  100 5000M    0     0  56.8M      0  0:01:28  0:01:28 --:--:-- 57.6M
      0       1 5242880000
```

Changing the timeout to 0, so `clock_gettime` is not called does not change anything.
So probably I am measuring the hard disk speed of the server PC here.

I do have a small embedded system with a weak CPU that I could use for a test, but this has a small disk as well, less than 100 MB, and I will probably again measure the speed of the flash card or disk IO controller, not the speed of the server. I don't have a system with a small CPU but a large hard disk/SSD with a fast connection, like your NAS device.

**Comment by helloray** [comment]
Hi bel2125,

I tried to use sendfile to replace send_file_data and found it can improve the download speed tremendously.You can refer http://man7.org/linux/man-pages/man2/sendfile.2.html for more details. AFAIK, sendfile can be supported on many UNIX like systems. Maybe you can consider adding it to civetweb.

**Comment by bel2125** [comment]
Yes, I will definitely consider this. The problem is, even http://man7.org/linux/man-pages/man2/sendfile.2.html states it should not be used for cross platform code, so I need to check where I can use it and where it has to be avoided. Maybe it should only be used for Linux in the first place.

According to http://www.techrepublic.com/article/use-sendfile-to-optimize-data-transfer/, http://www.techrepublic.com/article/tcp-ip-options-for-high-performance-data-transmission/, TCP_NODELAY and TCP_CORK could also be used as an additional performance optimization.

**Comment by bel2125** [comment]
`sendfile` seems to work well for files smaller than 2 GB
It currently does not work for larger ones, but I'm working on it

    user@lxpc:~$ curl -N http://localhost:8080/hugefile.bin | wc
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
     40 5000M   40 2030M    0     0  58.1M      0  0:01:25  0:00:34  0:00:51 58.3Mcurl: (18) transfer closed with 3095400448 bytes remaining to read
           0       1 2147479552

As discussed above, my test hardware is quite different from yours.
Could you repeat the test and post here what the benefit from using `sendfile` is in your case?

**Comment by bel2125** [comment]
Now it works for 5GB files as well, but it should still be tested.

**Comment by bel2125** [comment]
The timing measurements for `sendfile` gave me some curious results:

HTTPS works without `sendfile`, and uses additional time for encryption:

    D:\civetweb>curl -k -o NUL https://192.168.0.3:443/largefile.bin
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    100  100M  100  100M    0     0  10.4M      0  0:00:09  0:00:09 --:--:-- 10.8M

HTTP works with `sendfile`:

    D:\civetweb>curl -o NUL http://192.168.0.3:8080/largefile.bin
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    100  100M  100  100M    0     0  4467k      0  0:00:22  0:00:22 --:--:-- 4484k

The tests have been done with commit 31a9758c7d46f740d61bbb5a4ac59c095373337e

**Comment by bel2125** [comment]
On the other hand ... the same without `sendfile` (same PC, same code but with the #ifdef LINUX section removed):

    D:\civetweb>curl -k -o NUL https://192.168.0.3:443/largefile.bin
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    100  100M  100  100M    0     0  10.4M      0  0:00:09  0:00:09 --:--:-- 10.7M
    
    D:\civetweb>curl -o NUL http://192.168.0.3:8080/largefile.bin
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    100  100M  100  100M    0     0  3072k      0  0:00:33  0:00:33 --:--:-- 2981k

So, HTTP does benefit from `sendfile`, but HTTPS is still faster than HTTP.

Did you do your tests with HTTP or HTTPS? Could you test both?

**Comment by bel2125** [comment]
Also the 100 images test page (100images.htm) loads faster with HTTPS than with HTTP.
I discovered a similar external test: https://www.httpvshttps.com/

**Comment by bel2125** [comment]
I do not have the equipment to reproduce these measurements - I do not run into these limits with my equipment. Without a way to make some tests, I can probably not do anything more here.

**Comment by bel2125** [comment]
Some performance optimizations have been done in the meantime, and performance depends on the configurations - see also https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/civetweb/35HBR9seFjU/eerWthpMCAAJ - there setting tcp_nodelay to 1 and enabling keep_alive lead to a performance improvement.

Performance optimizations are done on a irregular basis, but I do not have a test system equivalent to the one the issue has been reported, so I cannot analyze it directly.
I'm also not sure if it makes sense to keep this issue open for much longer - I don't know if it still exists, or if there already is an optimization and a parameter set for appropriate performance.

**Comment by bel2125** [comment]
Since this issue has been opened, several performance optimizations have been made.
Performance also depends a lot on the configuration, e.g, sendfile and keep-alive enabled and tcp_nodelay set to 1 gave the best performance in this case: https://groups.google.com/forum/#!topic/civetweb/35HBR9seFjU

I think this issue should be closed now, since there won't be any new insights directly related to the old issue, and general optimization tips should not be tracked with this issue.
