### ISSUE TITLE
Adjust MSVC-_snprintf to POSIX-snprintf

### ISSUE THREAD

**Issue by xtne6f** [civetweb/civetweb#175]
_snprintf/_vsnprintf don't always set a null-terminator. So, for example, lua-script: `s='' for i=1,8192 do s=s..'a' end mg.cry(s)` overruns on Windows. I think the functions should be wrapped as follows:
(a bit fixed at 2015-07-17Z)

    #define snprintf snprintf_msvc
    #define vsnprintf vsnprintf_msvc
    static int vsnprintf_msvc(char *buf, size_t buflen, const char *fmt, va_list ap)
    {
    	int n;
    	va_list ap_copy;
    	if (buflen == 0) {
    #if defined(_MSC_VER) && (_MSC_VER < 1300)
    		n = _vsnprintf(NULL, 0, fmt, ap);
    #else
    		n = _vscprintf(fmt, ap);
    #endif
    	} else {
    		va_copy(ap_copy, ap);
    		n = _vsnprintf(buf, buflen, fmt, ap);
    		if (n < 0 || (size_t)n >= buflen) {
    			buf[buflen - 1] = '\0';
    			n = vsnprintf_msvc(NULL, 0, fmt, ap_copy);
    		}
    		va_end(ap_copy);
    	}
    	return n;
    }
    static int snprintf_msvc(char *buf, size_t buflen, const char *fmt, ...)
    {
    	int n;
    	va_list ap;
    	va_start(ap, fmt);
    	n = vsnprintf(buf, buflen, fmt, ap);
    	va_end(ap);
    	return n;
    }

**Comment by bel2125** [comment]
Microsofts _snprintf behaves differently than POSIX snprintf regarding the terminating zero (http://stackoverflow.com/questions/7706936/is-snprintf-always-null-terminating, https://msdn.microsoft.com/en-us/library/2ts7cx93.aspx).

I think I have to check all `(v)snprintf`, `mg_snprintf`, `alloc_vprintf`, ... uses in the code.
In cases the return value is not needed, this should be enough:

```C
static void vsnprintf_msvc(char *buf, size_t buflen, const char *fmt, va_list ap)
{
    if (buflen>0) {
        vsnprintf(buf, buflen, fmt, ap)
        bug[buflen-1]=0;
    }
}
```

In other cases, a "string truncated" message is added to the server error log (https://github.com/bel2125/civetweb/blob/master/src/civetweb.c#L1377), so I need to take a deeper look here.

**Comment by bel2125** [comment]
All snprintf functions have been replaced by mg_snprintf some time ago.
This function guarantees a null terminator (if the string is at least 1 byte).

**Comment by xtne6f** [comment]
Thank you, the related codes became so clear.
I think the following 3 risks still remain:
1.mg_cry(n > 200 ? 200 : n) in the mg_vsnprintf() does not care the case n < 0. 
2.mg_cry() still overruns.
3.alloc_vprintf2() would also overrun when the output size is exactly MG_BUF_LEN * 4.

**Comment by bel2125** [comment]
Thank you for your comment. I fixed the remaining three risks as well.
These three functions were already in the code before I took over CivetWeb, and the static code analysis tool did not detect it.
