### ISSUE TITLE
Drop or completely rewrite mg_upload

### ISSUE THREAD

**Issue by bel2125** [civetweb/civetweb#180]
mg_upload is a very limited function in terms of available features. It only supports forms consisting exclusively of file input elements - other form elements are not supported. The 'test/handle_form.lua' example can do more than this in much less lines of code. Also the API is very poor here.
The current statical source code analyses report (https://scan8.coverity.com/reports.htm#v27617/p11493) shows 10 errors in the entire civetweb code (built WITH_WEBSOCKET, WITH_IPV6 and WITH_LUA_SHARED) - 6 of the 10 errors are in the one function 'mg_upload'.

The 'mg_upload' function should be either dropped from the C core code or completely rewritten from scratch.

**Comment by Sonderstorch** [comment]
There's https://github.com/iafonov/multipart-parser-c... Would that be a feasible alternative?

**Comment by bel2125** [comment]
I missed to answer the [comment](https://github.com/civetweb/civetweb/issues/180#issuecomment-165481347) from @Sonderstorch above:

Unfortunately the cited parser requires to read the entire body in advance:
`size_t multipart_parser_execute(multipart_parser* p, const char *buf, size_t len);`

CivetWeb is able to upload files of several GB size - larger than the RAM size.
So it must save the content on the fly, while reading the request.

I wrote an alternative to mg_upload, and I will test it thoroughly during the next days.

**Comment by bel2125** [comment]
A new function `mg_handle_form_request` has been added.
This new function provides the same features as `mg_upload` and many more.
The original `mg_upload` has been removed.

A compatible `mg_upload` function can be created using `mg_handle_form_request`.
