### ISSUE TITLE
Create a civetweb group and project

### ISSUE THREAD

**Issue by mattyclarkson** [civetweb/civetweb#183]
Having the project under `bel2125` and being forked from `sunsetbrew` can be confusing to new users and makes the user think that it isn't the official project.

This is a suggestion to create a `civetweb` organisation on github and creating the `civetweb` project group under that and pushing the current code fresh to that project. That will mean that `github.com/civetweb/civetweb` will be the official home of the project.

The benefit of creating an organisation is that you can add multiple users to the organisation with different permissions and track github activity from those users. If the civetweb only ever has `bel2125` user as a member, that is fine but it will make organisation around the project more transparent and clearer.

I would also suggest setting up a free [Gitter](https://gitter.im/) chatroom for both the organisation _and_ the project. These links can be added to the `civetweb/civetweb` `README.md` as a link next to the CI badges. See for example [nodegit](https://github.com/nodegit/nodegit)

This will allow project maintainers to be added to the `civetweb` organisation chat to discuss large features to be added to the project. The `civetweb/civetweb` project chatroom can provide user feedback/support. Much like the mailing list but in a more responsive fashion.

**Comment by bel2125** [comment]
I currently have no idea what the consequences of creating a github organization would be, neither in terms of costs nor in terms of workflow, existing links, existing issues tracking, existing stars and watches, file history, github statistics/graphs, ...

At the repository of @sunsetbrew there is a clear statement at the landing page, so everybody can see the official repository is now here.

A chain of redirections [sunsetbrew](https://github.com/sunsetbrew/civetweb/) --> [bel2125](https://github.com/bel2125/civetweb/), than bel2125 to `civetweb/civetweb` will not make it less confusing in the first place. So the link must also be changed there.

**Comment by bel2125** [comment]
An organization with only open source repositories is free.
I don't know if it is possible to move a repository and keep all the current data.

**Comment by kainjow** [comment]
It's doable:
https://help.github.com/articles/transferring-a-repository/

**Comment by bel2125** [comment]
Thanks.
Seems they are doing everything I asked for when transferring the repository.

Is there any possible problem / disadvantage I have not yet thought of?

**Comment by mattyclarkson** [comment]
Not that I can think off. Most of the github repos that I contribute to have a organisation that backs the project. See [`jquery/jquery`](https://github.com/jquery/jquery), [`polymer/polymer`](https://github.com/polymer/polymer), etc.

Transferring the repository to the organisation will keep the 'forked from sunsetbrew' text. You can ask [GitHub support](http://stackoverflow.com/a/16052845/192993) to remove the link. It would make more sense for sunsetbrew to be part of the civetweb organisation and re-fork his repo from the canonical `civetweb/civetweb`.

**Comment by bel2125** [comment]
So having `civetweb/civetweb` seems to make sense.
I will first try to contact @sunsetbrew

If there is a `civetweb` organization, there could also be more than one repository.
So we could reduce `civetweb/civetweb` to a minimum, and create a new repository for the application examples.

**Comment by mattyclarkson** [comment]
:+1: on having `civetweb/examples`. You could show in that how to use civetweb as an ExternalProject in CMake.

**Comment by bel2125** [comment]
I have no idea how to use anything as an ExternalProject in CMake.
Anyway this is something for a second or third step.

**Comment by bel2125** [comment]
I created a civetweb organization.
Next, I am going to write an announcement at the [google group](https://groups.google.com/forum/#!forum/civetweb), so it is known that civetweb/civetweb will be the new home.
I transfer the repository from bel2125/civetweb to civetweb/civetweb.
I fork the repository to civetweb/examples, remove the examples from civetweb/civetweb and the civetweb sources from civetweb/examples (this should retain the file history).
Then support should convert both to full repositories.
Finally the sunsetbrew repository will be synced again and everything should point to civetweb/civetweb

**Comment by mattyclarkson** [comment]
:+1:

**Comment by bel2125** [comment]
The repository is moved.
It seems, the badges for "Travis Build Status", "Appveyor Build Status" and "Coverage Status" do not recognize the move automatically - or maybe it just takes some hours or days. I will check it again later.

**Comment by bel2125** [comment]
Travis now works somehow (magic?).
For Appveyor I wrote a support request (http://help.appveyor.com/discussions/problems/2762-github-open-source-project-moved-from-user-account-to-open-source-organisation-account)

... I am still busy with some settings that need to be made for the new organization ...

**Comment by bel2125** [comment]
AppVeyor is up again, and the links in the documentation folder are changed.
Next is coveralls and coverity.

**Comment by bel2125** [comment]
bel2125/civetweb has been moved to civetweb/civetweb a week ago.
Now, with the help of GitHub support, we changed the entire fork network, to make civetweb/civetweb the new root of this network. All forks should now show "forked from civetweb/civetweb", including the previous root repository "sunsetbrew/civetweb".

I think this structure is much more clear than before.

**Comment by mattyclarkson** [comment]
Top work! :smile:

**Comment by bel2125** [comment]
I did not find any way to teach coveralls the repository has moved.
I created this issue: https://github.com/lemurheavy/coveralls-public/issues/603
The last build (build 240 with 49% coverage) is still at the old repository site -> https://coveralls.io/github/bel2125/civetweb

**Comment by bel2125** [comment]
Travis and AppVeyor got fixed with the help of their support teams - both answered the same day.
Coverity seems to be not connected to the repository name, but uses some other ID, so there is no problem here.

Only coveralls is still open. They do not seem to have a support mail, but only an issue tracker - see the issue above. I did not get any response from them yet. It seems, the test coverage state will remain unknown for a while.

**Comment by bel2125** [comment]
Status update: I have still no idea how to get "coveralls" to accept `civetweb/civetweb` as a new project source (instead of `bel2125/civetweb`).

I opened an issue (https://github.com/lemurheavy/coveralls-public/issues/603), but did not get any answer in the last months.

So moving to civetweb/civetweb has been done as far as I was able to do on my own. Only coveralls is missing - since months.

I think I will close this issue (here #183) soon, keep the coverall issue on the TODO list and wait for an answer on https://github.com/lemurheavy/coveralls-public/issues/603.

**Comment by bel2125** [comment]
Everything works, except Coveralls.
I did not get response to the issue I created (https://github.com/lemurheavy/coveralls-public/issues/603), so I don`t know how to solve it.

If anyone knows what to do, please let me know.

**Comment by bel2125** [comment]
I finally managed to get the coveralls batch running.
I did not get any response to my [issue report](https://github.com/lemurheavy/coveralls-public/issues/603), so I had to try around and finally got it working.

I think that's all: The group is created and the last piece is transferred from the bel2125/civetweb repository to the civetweb/civetweb repository.
So let's close the issue.
