### ISSUE TITLE
Environment space is too small

### ISSUE THREAD

**Issue by sunsetbrew** [civetweb/civetweb#187]
The HTTP header space is 16K, but the environment space is only 4K, despite copying those headers into it.

This has caused some seriously hard to find CGI problems, because the failures depend entirely on how you access the URL (since headers change) and the server paths.  It took about a man week to track this one down.

I propose that the environment be allocated to match the header size, or at least allow uses to change it with a make define.  What do you think?

**Comment by bel2125** [comment]
You are addressing [this part](https://github.com/civetweb/civetweb/blob/master/src/civetweb.c#L483)?

```C
...
#define CGI_ENVIRONMENT_SIZE (4096)
#define MAX_CGI_ENVIR_VARS (64)
#define MG_BUF_LEN (8192)

#ifndef MAX_REQUEST_SIZE
#define MAX_REQUEST_SIZE (16384)
#endif
...
```

Or [this one](https://github.com/civetweb/civetweb/blob/master/src/civetweb.c#L6237) (16384 should be a define anyway):
```C
static void handle_cgi_request(struct mg_connection *conn, const char *prog)
{
    ...
    buflen = 16384;
    ...
    buf = (char *)mg_malloc(buflen);
    ...
```

I do not see a reason why
```
struct cgi_env_block {
	struct mg_connection *conn;
	char buf[CGI_ENVIRONMENT_SIZE]; /* Environment buffer */
	size_t len;                     /* Space taken */
	char *vars[MAX_CGI_ENVIR_VARS]; /* char **envp */
	unsigned int nvars;             /* Number of variables */
};
```
needs to be a priori fixed buffers at all and does not just use a dynamic list of vars - any number and any length.

**Comment by sunsetbrew** [comment]
I have not taken the time to get the heart of it as we have been closing up a release.  But I can verify with 100% certainty that the environment is not static.  I am not exaggerating when I say it was debug nightmare.  The code gave no indication of the lack of environment space either.  What we did was increase the environment size and all was better after that.  But I want to do it in a way that we can upgrade civetweb releases without changing the civetweb code.

So my goal is to ensure configurability without code changes and provide some indication when this happens.  On that note, the excessive header size occurs under multiple scenarios from process not launched, to no output, to bad formatting.  That needs improvement as well.  It happens more than any other error when developing CGI programs.

**Comment by bel2125** [comment]
The relevant part of the code here still heritage of mongoose.
I can not think of any advantage having an environment limited to a small, fixed size.
I am going to change this to a dynamically allocated environment, allocated to whatever size is required. This is certainly better than any (user changeable) define.

**Comment by bel2125** [comment]
The CGI environment will now grow dynamically, if required, to fit a request of any size.
Currently the number of CGI variables is still fixed to 256 (instead of 64 before). I think this will be enough - one could make this number dynamic as well, if there is any need.

**Comment by bel2125** [comment]
I don't think there is any problem remaining.
So I will close this issue.
