### ISSUE TITLE
civetweb.c: worker threads that do not start cause segmentation fault when closing

### ISSUE THREAD

**Issue by codehero** [civetweb/civetweb#188]
On my ARM system, the default request is for 50 threads...however only 22 of them start.
The issue however is a Segmentation Fault that comes calling mg_close().
In particular, mg_join_thread crashes on NULL inputs.
I put in a check for NULL and everything is fine now, but the thread counting semantics need some cleanup.
(seems that ctx->workerthreadcount is really the size of the workthreadids array, and ctx->num_threads is the actual active count?)

**Comment by bel2125** [comment]
Yes. ctx->workerthreadcount is the size of the workthreadids array, and ctx->num_threads the number of threads successfully started. For any thread you can not start, you should get an error message like
`Cannot start worker thread <index>: error <errno>`

**Comment by bel2125** [comment]
The NULL check for worker thread IDs has been added. Also the member variables of mg_context have been renamed to make it more clear - one of them is the configured number of worker threads, the other one the number of worker threads actually running.

**Comment by bel2125** [comment]
I think this problem has been fixed - at least I am not aware of any remaining problem in this area.
So I am going to close this issue.
If you disagree, feel free to open the issue again.
