### ISSUE TITLE
404 on gzipped static files

### ISSUE THREAD

**Issue by codehero** [civetweb/civetweb#189]
I have a file named jquery.js.gz in my document root; there is no corresponding jquery.js in the same directory.
So what happens is I get a 404 trying to access it.

Resolution seems to be setting *is_found = 1 in interpret_uri when setting filep->gzipped = 1.

**Comment by bel2125** [comment]
Thanks.

I changed the code as you suggested, and added a unit test for zipped files, so from now every commit should test if gz files are still working.

**Comment by codehero** [comment]
Looks good to me, thank you for fixing; you can close
