### ISSUE TITLE
send_file_data hangs on /sys/class/net/eth0/address

### ISSUE THREAD

**Issue by codehero** [civetweb/civetweb#190]
send_file_data() goes into an infinite loop when trying to send a sysfs file.
sysfs files may not report their true size on a stat() call and may far exceed their actual readable() content.

I suspect that sendfile() call is returning 0 because it reads 0 bytes and therefore writes 0 bytes.
Note perhaps that a race condition (ie you stat and then the actual file size changes) could also trigger this.

Recommend checking for readable data on the sf_file descriptor before calling send again.

**Comment by bel2125** [comment]
You mean this loop:
```C
	do {
		/* 2147479552 (0x7FFFF000) is a limit found by experiment on 64
		 * bit Linux (2^31 minus one memory page of 4k?). */
		size_t sf_tosend =
		    (size_t)((len < 0x7FFFF000) ? len : 0x7FFFF000);
		sf_sent =
		    sendfile(conn->client.sock, sf_file, &sf_offs, sf_tosend);
		if (sf_sent > 0) {
			conn->num_bytes_sent += sf_sent;
			len -= sf_sent;
			offset += sf_sent;
		}

	} while ((len > 0) && (sf_sent >= 0));
```
According to [this documentation](http://man7.org/linux/man-pages/man2/sendfile.2.html), sendfile returns -1 on error. A number smaller than sf_tosend is valid, and the code should retry.

It works for *real* files, but I have not tested if for pseudo files like /sys and /proc in Linux.

**Comment by codehero** [comment]
That is the loop.
As a test I added a spin count (if nothing sends 10 times in a row) then the loop aborts.
That fixes the hang with the sysfs files but is NOT a good solution.

I would not expect sendfile to return -1 in this case; it is never an error to keep reading at the end of the file; you just return 0 bytes.

**Comment by bel2125** [comment]
It should not be the end of the file, because then `len>0` should no longer be true ... for *real* files.
Did you check what happens if you remove the `#if defined(__linux__)` section in `send_file_data` completely? Maybe `sendfile` does not work at all with pseudofiles.

I can not imagine the size of `/sys/class/net/eth0/address` changes in the few microseconds between calling `stat` and `sendfile`. If `stat` already returns 0, the code would not run into this loop.

**Comment by codehero** [comment]
I've made myself misunderstood. The amount of data you think are sending comes from a stat call. In the case of a sysfs file that size is 4096 on my machine. The race I was referring to is theoretical but still a very real possibility, especially on the ARM systems I use.

**Comment by bel2125** [comment]
> The amount of data you think are sending comes from a stat call. In the case of a sysfs file that size is 4096 on my machine. 

Of every sysfs file? Independent of the actual size?

4096 is the memory page size for X86 and most ARM CPUs too, but I think some ARMs have modes with different sizes (64k, maybe also other sizes). Your system has 4k pages?

> The race I was referring to is theoretical but still a very real possibility, especially on the ARM systems I use.

I think we have to distinguish between static files (the >99.99% case) and pseudo files (/sys/*, /proc/*, ...). For static files, I would not consider it legitimate, if they change during a request - if anyone still does it, of course the server should not go into an infinite loop, but if the content is only a part of the old file ... bad luck. If you update static file, either risk that this may happen with an extremely low probability, or stop the server, change the files and restart the server to be sure.

I did never try to use /sys or /proc directly, only through Lua or CGI.

**Comment by codehero** [comment]
I am fine with only partial content served up if the file is changed or truncated. Eliminating the infinite loop is most important.

There are atomic ways to update a file (make a copy, modify the copy, then rename to the old file) but the way you have you design now civetweb isn't guaranteed to work with even that. I would suggest you you actually open the file, the do an fstat on the descriptor to get the amount of data you want to send.

**Comment by bel2125** [comment]
Reading `/sys/class/net/eth0/address` now works on my X86 Ubuntu Linux system.

**Comment by bel2125** [comment]
I think this problem has been fixed some months ago, so I'm going to close this issue.
If you disagree, feel free to open the issue again.
