### ISSUE TITLE
304 status is never sent to the browser

### ISSUE THREAD

**Issue by DoubtedEd** [civetweb/civetweb#204]
In the function is_file_in_memory the last_modified member of filep is set to 0. This seems to break browser caching as the Last Modified header is always set to Jan 1970. It is then compared to the actual Last Modification Time, which will always be greater than Jan 1970, so the 304 status is never sent.

**Comment by bel2125** [comment]
It seems this issue got forgotten for a while.
Assuming a memory mapped file is *always* changed is the only safe approach, since we can not know it better from the `open_file` callback api.

**Comment by MGralka** [comment]
I pulled from master today and I wasn't able to build the project:

> 1>------ Build started: Project: civetweb_lua, Configuration: Debug CONSOLE Win32 ------
> 1>  civetweb.c
> 1>...\civetweb\src\civetweb.c(2671): error C2065: 'last_modified' : undeclared identifier
> 1>...\civetweb\src\civetweb.c(2671): warning C4244: '=' : conversion from 'time_t' to 'int', possible > loss of data
> ========== Build: 0 succeeded, 1 failed, 2 up-to-date, 0 skipped ==========

Shouldn't it say 
>**filep->**last_modified = time(NULL); 

instead of 

 > last_modified = time(NULL);

?

**Comment by bel2125** [comment]
Indeed it should.
I just wonder why neither I saw this myself, nor did TravisCI raise any error (the Travis signal on [the main page](https://github.com/civetweb/civetweb) is still green).

**Comment by bel2125** [comment]
See also https://github.com/civetweb/civetweb/commit/8fbe05852aa11d9209abe6a4c90d07a28223387d#commitcomment-14756568
