### ISSUE TITLE
Not listening at any port when using the same port for both ipv4 and ipv6

### ISSUE THREAD

**Issue by everte** [civetweb/civetweb#205]
I'm trying to get ipv6 support working when embedding civetweb (mainly for websocket). When compiling the embedded_c example with ipv6 support it works.

But it will have a separate port for ipv4 and ipv6 defined. When setting the same port for both ipv4 and ipv6 it will not bind to any address or port. 

In the embedded_c.c example I use the following option for the listening_ports: 
> #define PORT "8888,[::]:8888"

It will result in  
> root@kdesktop:/home/evert# netstat -anp | grep -i 8888
> root@kdesktop:/home/evert# 

I expected it to listen on both
> tcp        0      0 0.0.0.0:8888            0.0.0.0:*               LISTEN      5937/valgrind.bin
> tcp6       0      0 :::8888                 :::*                    LISTEN      5937/valgrind.bin

Is it wrong to define the listening ports like this? Or is it not possible to listen to the same port on both ipv4 and ipv6 (sounds weird?). I'm unsure if it even might be a small bug somewhere.

Hope you can help me clear this up!

**Comment by bel2125** [comment]
I just tried: it works fine for Windows, but not for Ubuntu.
What system are you using? Could you post the system information reported by CivetWeb (start with `-I` option).

**Comment by everte** [comment]
I'm running it on various linux systems (ubuntu, debian, arch). The one I'm currently working on:
```
CivetWeb V1.8
CivetWeb V1.8 - Linux #15-Ubuntu SMP Thu Apr 16 23:32:37 UTC 2015 (3.19.0-15-generic) - x86_64
Features: Files HTTPS CGI IPv6 WebSockets
Version: 1.8
Build: Sep 27 2015
gcc: 4.9.2
```
I hope this helps narrowing down the search.

**Comment by bel2125** [comment]
It seems Windows and Linux work differently in this respect. For Windows, this works out of the box.

For your system, please try the following:
- Comment the IPV6_V6ONLY socket option in civetweb.c - the #if section currently around [line 9396](https://github.com/civetweb/civetweb/blob/master/src/civetweb.c#L9396).
- Remove the IPv4 config - in the example [here](https://github.com/civetweb/civetweb/blob/master/examples/embedded_c/embedded_c.c#L20). 
So just use `#define PORT "[::]:8888"` instead of `#define PORT "8888,[::]:8888"`

Then it should listen to both - IPv4 and IPv6. At least this changed the behaviour on my Ubuntu system.

Please test, if it works for you as well.

If so, I can think about a syntax for a PORT specification which will bind to IPv4 and IPv6 without, so there should be no need to modify civetweb.c anymore.

**Comment by everte** [comment]
I'm doubting myself, but I cannot reproduce your working settings.

I pulled latest GIT, commented the ipv6 lines (9396 until the end of the #if) in src/civetweb.c, added the IPV6 and websocket options to the makefile and made a new build.

embedded_c.c
```
~  20 #define PORT "[::]:8888"
```

When running it outputs:
```
evert@desktop:~/dev/civetweb/examples/embedded_c$ make
make -C ../.. clean lib WITH_IPV6=1 WITH_WEBSOCKET=1
make[1]: Entering directory '/home/evert/dev/civetweb'
rm -rf out
rm -rf libcivetweb.a
rm -rf libcivetweb.so
rm -rf libcivetweb.so.1
rm -rf libcivetweb.so.1.8.0
rm -rf civetweb
cc -c -Wall -Wextra -Wshadow -Wformat-security -Winit-self -Wmissing-prototypes -O2 -DLINUX -Iinclude  -DUSE_STACK_SIZE=102400 -DNDEBUG -DUSE_IPV6 -DUSE_WEBSOCKET -fPIC src/civetweb.c -o out/src/civetweb.o
src/civetweb.c: In function ‘set_ports_option’:
src/civetweb.c:9312:6: warning: unused variable ‘off’ [-Wunused-variable]
  int off = 0;
      ^
ar cq libcivetweb.a out/src/civetweb.o
make[1]: Leaving directory '/home/evert/dev/civetweb'
cp ../../libcivetweb.a .
cc -o embedded_c -I../../include  -DUSE_WEBSOCKET -DUSE_IPV6  embedded_c.c libcivetweb.a -lpthread -ldl
evert@desktop:~/dev/civetweb/examples/embedded_c$ ./embedded_c 

1 listening ports:

Browse files at http://[::1]:8888/
Run example at http://[::1]:8888/example
Exit at http://[::1]:8888/exit
```

According to netstat it only listens to the ipv6 port now. Sadly I'm not 100% sure it's not a "problem exists between keyboard and chair" issue... I might have missed something important.

**Comment by bel2125** [comment]
I did not check it with netstat.
But an IPv6 socket should also listen to IPv4 connections, if IPV6_V6ONLY is not set.
You should try to connect to http://127.0.0.1:8888 (IPv4 localhost) and http://[::1]:8888/ (IPv6 localhost).

**Comment by everte** [comment]
Oeps, I didn't actually check since netstat was so convincing :).

Yeah, it works now. It will (according to netstat) only listen to the ipv6 address, but I can access it fine with ipv4 too.

It feels like magic, could you point me at some documentation how or where this is happening? How could the ipv6 socket receive stuff going to a ipv4 socket?

**Comment by bel2125** [comment]
http://stackoverflow.com/questions/1618240/how-to-support-both-ipv4-and-ipv6-connections

http://man7.org/linux/man-pages/man7/ipv6.7.html --> IPV6_V6ONLY documentation

**Comment by bel2125** [comment]
If everything works as expected, you do not need to comment anything in civetweb.c, so "9396 until the end of the #if" is correct - unless your system does not understand the IPV6_V6ONLY option, which is not the case for Linux.

**Comment by everte** [comment]
Thanks for linking the documentation, interesting stuff to learn about!

Sorry for the bogus bug report, it indeed works with current master without any changes (only listening to ipv6 port will accept ipv4 connections as well due to the IPV6_V6ONLY option being false). 

Thank you very much your time and helping a newbie as myself!

**Comment by bel2125** [comment]
You are welcome.
I probably should append this info to the user documentation.
