### ISSUE TITLE
WebSocket example hangs if pressing one of four buttons in websock.htm

### ISSUE THREAD

**Issue by RobertoMalatesta** [civetweb/civetweb#206]
Platform Kubuntu 14.04
CivetWeb version: latest git pulled on 2015.09.28
Browsers Tested: Chrome,Firefox,Vivaldi (all latest versions)

websockets works OK until you click any of the four buttons presented by the page.
The generated call to i.e: 
connection.send('msg A');
blocks all the client connections and the server hangs, accepts no more connections and becomes unable of detecting disconnections (browser/pages closed) as well.

R

**Comment by bel2125** [comment]
There are at least three different websocket examples:
(1) https://github.com/civetweb/civetweb/blob/master/examples/websocket/websocket.c
(2) https://github.com/civetweb/civetweb/blob/master/test/websocket.lua
(3) https://github.com/civetweb/civetweb/blob/master/examples/embedded_c/embedded_c.c#L120

I'm currently reorganizing the [examples](https://github.com/civetweb/civetweb/tree/master/examples) directory. Example (1) is integrated into example (3), so I did not check (1) for a while.

... I will have a look.

**Comment by RobertoMalatesta** [comment]
(1) is the code in question

**Comment by RobertoMalatesta** [comment]
Hi Bel,

On last version I get an error on (3) as well:
robi@zerosingularity:~/src/civetweb/2015.10.01/civetweb-master/examples/embedded_c$ make
cc -o embedded_c -I../../include  -DUSE_WEBSOCKET -DUSE_IPV6  embedded_c.c libcivetweb.a -lpthread -ldl
/tmp/ccMAR9sP.o: In function `WebSocketReadyHandler':
embedded_c.c:(.text+0x5f7): undefined reference to `mg_websocket_write'
/tmp/ccMAR9sP.o: In function `InformWebsockets':
embedded_c.c:(.text+0x8d2): undefined reference to `mg_websocket_write'
collect2: error: ld returned 1 exit status
make: *** [embedded_c] Error 1

Thanks for your time.

R

**Comment by bel2125** [comment]
Did you build `libcivetweb.a` with websockets?
`make lib WITH_WEBSOCKET=1`

**Comment by RobertoMalatesta** [comment]
Yes.
make lib and slib as well.
gcc version 4.9.2 (Ubuntu 4.9.2-0ubuntu1~14.04)

**Comment by RobertoMalatesta** [comment]
Ok, a make clean fixed things up.

But mg_get_server_ports returns -1:
robi@pancras:~/src/civetweb/2015.10.02/civetweb/examples/embedded_c$ ./embedded_c 
-1 listening ports:

/*
 port_cnt = mg_get_server_ports(ctx, 32, ports);
        printf("\n%i listening ports:\n\n", port_cnt);
*/

Hth, R

**Comment by bel2125** [comment]
Did you build libcivetweb.a with IP_V6 support?
`make lib WITH_WEBSOCKET=1 WITH_IPV6=1`
Alternatively, did you deactivate IP_V6 in the example?
You can do this by removing USE_IPV6 in the Makefile.

The example and civetweb.c must be compiled with the same feature defines.
Probably I should add some check in the example, that will tell you what is missing.

**Comment by RobertoMalatesta** [comment]
Now it works.
I had to build in the root with:
make WITH_WEBSOCKET=1 WITH_IPV6=1
then
make lib WITH_WEBSOCKET=1 WITH_IPV6=1
make slib WITH_WEBSOCKET=1 WITH_IPV6=1
and then inside embedded_c
make WITH_WEBSOCKET=1 WITH_IPV6=1
if you simply say make you get the -1 error here.
IP_V6 is deactivated in the example, it seems.

It seems to work only with IP_V6 activated (ie no IP_V6 leads to the error)

Just a quick note this one. As soon as I have time I'll do further tests and notify you.

Thanks for your time,

Roberto

**Comment by bel2125** [comment]
I just added a check to the embedded_c example, so the example will tell you what compile options are missing.

It should work to only build
`make lib WITH_WEBSOCKET=1 WITH_IPV6=1`
This will build the static library libcivetweb.a
change into the example/embedded_c directory, copy the libcivetweb.a to there and
'make'.

Alternatively:
Add 'civetweb.c' into the Makefile of the example, then 'make'.
(The Visual Studio project files for the embedded_c sample in Windows uses this approach.)

Alternatively:
Build the shared library:
`make slib WITH_WEBSOCKET=1 WITH_IPV6=1`
This will build 'libcivetweb.so'. You need to copy it into your /usr/lib/ directory (or whatever your Linux distribution defines). Then you can change the Makefile of the example to use the shared library by adding -lcivetweb as build flag.

It's a question of your preferred way to work and how you want to use CivetWeb in your final software package. 

Before changing build options (like using or not using WITH_IPV6=1), you should always use 'make clean'.

**Comment by RobertoMalatesta** [comment]
It seems to work only with IPV6 enabled.
I will do some tests as soon as I have time.

**Comment by bel2125** [comment]
You could also disable IPv6 in the Makefile, if you prefer:
https://github.com/civetweb/civetweb/blob/master/examples/embedded_c/Makefile#L15
Just remove `-DUSE_IPV6`

**Comment by RobertoMalatesta** [comment]
OK.
Commenting out the IPV6 on both Makefiles does work.
Thanks for your time, Bel

R
