### ISSUE TITLE
Discussion: Pulling in 3rd party projects to replace low-level code.

### ISSUE THREAD

**Issue by Parakleta** [civetweb/civetweb#209]
I've been looking at ways to get SSL/TLS in civetweb without relying on OpenSSL due to concerns with the complexity of its API and the weight of its implementation.  As part of this I was also looking at the threading requirements of different SSL implementations because this places a burden on the applications that depend on them (and is currently causing a problem with building on FreeBSD due to the OpenSSL API not properly working with POSIX pthreads in the strictest sense).

I have a few proposals I'd like to suggest to gauge community interest in work in this direction.

### [mbedTLS](https://github.com/ARMmbed/mbedtls)

mbedTLS has just recently be released with the Apache License v2.0.  This project is a fork of XySSL which was originally BSD Licensed but then abandoned and forked into PolarSSL which continued with a Commercial/GPLv2 license.  This has since been bought by ARM and now re-released.  The Apache License v2.0 is not a [CopyFree](http://copyfree.org/standard/rejected) license but is also not a CopyLeft license.  If the files are kept separate it would not affect the license of the civetweb project.

The advantage of using mbedTLS is that it is small and simple enough that we could distribute it with civetweb in the same way as Lua, and it would add the ability to have TLS support without requiring any system libraries.  Additionally the mbed project specifically targets embedded systems so I would expect that the code will be simpler and more efficient than the full OpenSSL (although I haven't checked yet).  They also have no special threading requirements like OpenSSL which makes support much simpler.

### [libev](http://software.schmorp.de/pkg/libev.html)

I'm keen on having the **option** to remove threads entirely from civetweb on compile to make it easier to embed and integrate with project where the addition of threads may consume unnecessary resources or add complexity that the project doesn't need.  The libev library makes this possible by supporting the [Reactor Pattern](https://en.wikipedia.org/wiki/Reactor_pattern) of event handling.  If civetweb was refactored to be compatible with libev then it would also be possible for people to integrate civetweb into existing event loops when embedding into other applications.

It would still be possible with some care to implement threading support on top of libev to allow civetweb to make use of multiple cores/CPUs in systems where this is relevant for performance reasons.

libev is license compatible with civetweb and the code could be cut straight into the main `civetweb.c` file.

-----

Basically the aims of these changes would be two-fold.

The first is that it should make civetweb a lot simpler, leaner and more efficient, and bring in SSL/TLS without external dependencies.  It should also make it easier to embed civetweb in other applications, and should lower the bar for which embedded devices it can target.  It would be nice to be able to work towards supporting FreeRTOS (or similar) for example.

The second aim would be to try and separate the effort from the low level IO/threading/platform support etc. and the higher level Protocol and Scripting issues.  If civetweb can leverage existing IO/threading/platform libraries then effort going forward can be dedicated to protocol and scripting support.

At this point I'm just interested in having a discussion.  If civetweb doesn't want to go in this direction I'm happy to fork (in fact that would be much easier for me since I can strip down and rebuild rather than trying to migrate carefully).

Are there any other low level libraries that would be useful?

**Comment by sunsetbrew** [comment]
Not a fan of doing this.

1. This library is MIT license.  Any code that even mentions GPL is dead on sight,  BSD is close, but not MIT.  Apache, is less close.
2. This code is highly portable, both as an embedded piece of code and stand-alone.
3. This code does not depend on other code.
4. This code may not be the cleanest code on the Internet, but it is one file and does not require use of any tools build.  The makefile is completely optional.

If someone wants to approach alternate library integrations, it should be done in a way that leaves the current code completely in-tact and simply offers an extra optional integration point.

**Comment by Parakleta** [comment]
1. I certainly wouldn't touch anything GPL.  Apache can be contained just fine if the files are kept separate.  BSD 2-clause only adds the requirement that the license/copyright be distributed with binaries.
2. I think the reliance on threads harms portability.  libev is highly portable but changes the license slightly.
3. I thought the code depends on OpenSSL if you want https support.  I'm proposing pulling mbedTLS into the third_party directory so that TLS is available in the same way as Lua or SQLite.
4. Having a single file is nice and there's no reason this option cannot be maintained with a pre-build step ala SQLite.  A handful of integrated files could be produced with different options and different licenses (i.e. the TLS support integrated file would need to be Apache License v2.0).

The BSD 2-clause from libev is a problem.  It would be possible to make a version of civetweb which just provides the event callbacks and remains MIT but this would be less functional than the current version (people would need to supply their own event loop).

It's going to take a fair bit of work to change to these libraries and trying to preserve the existing code I think may be impractical.  Forking would be the better option then, but there is always there the issue of duplication of effort which is why I wanted to have this discussion.

**Comment by sunsetbrew** [comment]
We have sworn to stay MIT.  That is not negotiable.

This does not depend on openssl.  It depends on a something with an openssl compatible API if you need SSL.  There are a number of packages that support that.  For example here is one that would work, but it has an ugly license so we won't include the code for it. https://github.com/civetweb/civetweb/blob/master/docs/yaSSL.md

Might I suggest making a fork if you want to improve it in that way without maintaining the existing code.  There are too many projects, people and companies that depend on it staying the way it is.  When we first took it over, we discussed splitting the code up to make it more maintainable and a number of options.  It was shot down.

If you just need a basic embedded web server without SSL, it does not get much easier than this.

**Comment by sunsetbrew** [comment]
Or, if you feel strongly enough, bring it up in the Google Group to see if there are other opinions.  This bug report does not reach many people.

**Comment by Parakleta** [comment]
I hadn't noticed the Google Group before, I just read through the archives.  There seems to be some interest in changing the threading model there, but otherwise general resistance to change.

One possibility would be for me to fork the project into the BSD 2-clause license to integrate libev.  Since I own my changes I can give patches back to civetweb under MIT if there's interest.  Once I have a clean interface between civetweb and the standard sort of event-loop/callback used by libev/libevent/libuv then someone could cleanroom an independent implementation into civetweb.

**Comment by bel2125** [comment]
CivetWeb is pure MIT code. Retaining the MIT license is the reason CivetWeb has been created.
Lua and the Lua libraries like lfs, lsqlite, ... have MIT licenses, also sqlite and duktape. So all components in the third party directory have MIT licenses.

The MIT license allows to use the server in any open and closed source, commercial and non-commercial code. You may find some projects using civetweb in the internet, but since it is not required to register them you will not find most of them. Some companies also asked or sent patches directly by mail to me, because they did not want to do this publicly on GitHub.
This all only works because of the MIT license.

Regarding TLS/SSL software, there is also another reason why I do not want to have it included here, even if the license is MIT (currently I do not know an MIT licensed TLS library anyway): software export restrictions, that apply to software containing cryptographic algorithms of a certain strength.
If it would be contained directly, I would need to strictly take care of the proportion of value added by each [contributor](https://github.com/civetweb/civetweb/graphs/contributors), and which country they are from. I would have to write more or less official document explaining which percentage of the value of the software has been generated in which country.

**Comment by Parakleta** [comment]
Wow, I didn't realise the crypto export restriction stuff still existed, I assumed they'd given up on that.

Ok, so I'll make these changes on my own fork.

**Comment by bel2125** [comment]
> ... I assumed they'd given up on that.

Just as an info: 

There are not only US export restrictions: https://en.wikipedia.org/wiki/Export_of_cryptography_from_the_United_States#Current_status
... with quite complicated legal documents

There are also import restrictions in different countries: https://en.wikipedia.org/wiki/Restrictions_on_the_import_of_cryptography

And I don't want to care about this if I don't have to.

**Comment by KingDuckZ** [comment]
Sorry for bumping this, I got here searching the internet for civetweb + libev. My project already uses libev with threads, now I want to add a webserver to it but it would be great if it integrated with the event loop I already have. What became of this discussion? Is there an easy way to make civetweb work easily with libev, or is there such a fork? My project's licence is GPL3+ so I'm not particularly interested in everything being MIT (as long as it's compatible with GPL).

**Comment by Parakleta** [comment]
@KingDuckZ This never made it off my todo list.

**Comment by KingDuckZ** [comment]
Unfortunately I don't think I have the skills required to do that myself, so is there any option or should I just move on to a different library?

**Comment by bel2125** [comment]
@KingDuckZ : What is the actual problem? Library A is not using library B (civetweb is not using libev), does not sound like a real problem - there are millions on libraries civetweb is *not* using. Usually *not* having a dependency is considered as an advantage.

What problem precisely do you want to solve? 

CivetWeb allows you to hook thread creation and lot's of other stuff. Using individual threads for individual connections allows to use blocking functions in all callbacks and CGI scripts.

Regarding libev, all license concerns mentioned above are still valid. LibEv is not MIT: https://github.com/enki/libev/blob/93823e6ca699df195a6c7b8bfa6006ec40ee0003/LICENSE#L11-L14

Regarding the other lib originally mentioned here - mbedtls: By now there is a branch with mbedTLS support https://github.com/civetweb/civetweb/tree/mbedtls
