### ISSUE TITLE
PUT handling with file upload

### ISSUE THREAD

**Issue by gbjbaanb** [civetweb/civetweb#215]
I have a requirement to upload a file and then perform some custom processing on it immediately after the upload. The files are uploaded using webdav (ie PUT requests).

I can see the requests being made and the file upload working, but as soon as I add my own PUT handler, the file upload stops. Looking through the code it seems the handler (if any) is called, and if it returns true, the rest of the if-else chain in handle_request is skipped.

I thought of returning false, but then the handler would be called before the file upload :(

So my next though was to call civet to perform the file upload as if the PUT method had been handled directly... but its not accessible as an exported function.

So, before I hack around in the code to make put_file (and the auth checks) accessible to my handler, is there a better way of doing what I want here - am I missing something that would make my life easy?

**Comment by bel2125** [comment]
What handler do you mean? Civetweb has a lot of different handlers.
What system are you using?
What version?

There is are a couple of examples in the source tree. 
E.g., there is an example how to handle files uploaded from a form (actually using "POST" but you could use "PUT" as well) to a Lua handler (where you can process the data without storing it).
https://github.com/civetweb/civetweb/blob/master/test/form.html
https://github.com/civetweb/civetweb/blob/master/test/handle_form.lua

What do you exactly want to do?

**Comment by bel2125** [comment]
Did you use the `mg_set_request_handler` API function to set a callback?
Or did you set the `begin_request` member of `struct mg_callbacks`?

Did you have a look at the ["embedded example"](https://github.com/civetweb/civetweb/blob/master/examples/embedded_c/embedded_c.c). All handler should send a reply and return 1.

**Comment by gbjbaanb** [comment]
I said what I want to do - "perform some custom processing on it immediately after the upload"

I use the CPP flavour - so I'm setting a POST handler which calls mg_set_request_handler. I can upgrade to master or the latest release.

I do not want to use a form upload, this is "unsolicited" PUTs of data via webdav, so I just need to respond to a file upload after its uploaded.I did see that example but they don't have too much documentation. 

Are you saying to use the callbacks structure to set a callback routine to handle POST request, call mg_upload in this handler and also set a callback for upload completion?

**Comment by bel2125** [comment]
What CivetWeb version are you using? I rewrote the handle_request method some months ago.

`mg_set_request_handler` should work - I would recommend, the `begin_request` handler should no longer be used in new code.

I can add a PUT / POST example to the example.

**Comment by bel2125** [comment]
This is an example how to do it in C++:

https://github.com/civetweb/civetweb/blob/master/examples/embedded_cpp/embedded_cpp.cpp#L191

**Comment by gbjbaanb** [comment]
My production system is running 1.6
I already have GET and POST working fine.
I want to write a PUT handler to process file uploads from a webdav client and receive some notification after the upload completes.

I have downloaded 1.8 and used that, as described in my previous comment.

Using the equivalent of a POST handler that calls mg_upload to receive the file does not work.

Rather than attempt to explain myself again, please, add an example how to write a handler that beeps (or something equally trivial) after a webdav file upload completes.

**Comment by bel2125** [comment]
The example above already has a PUT handler.
I tested it with the fiddler web debugging tool on Windows yesterday.

Now I tested it with a cadaver webdav client on Linux.
I removed the `*.foo` from [this line](https://github.com/civetweb/civetweb/blob/master/examples/embedded_cpp/embedded_cpp.cpp#L260) to handle PUT requests with every filename, not only files ending with *.foo
I think using `server.addHandler("", h_foo);` will just be a simple example of a PUT handler for everything - honestly, I do not know how to make a cross-platform code beep (Windows yes, but everything else?). Just put a debugger breakpoint in the PUT-Handler and use a webdav client:
```
username@hostname:~$ cadaver http://192.168.0.123:8081
dav:/> put mac.txt
Uploading mac.txt to `/mac.txt':
Progress: [=============================>] 100,0% of 170 bytes1 succeeded.
```
... and wait to hit the breakpoint.

**Comment by gbjbaanb** [comment]
I get that the PUT handler gets called, tried it and seen the breakpoints - the interesting bit is that you call mg_read and mg_write inside it. I didn't know those existed for that purpose - only having seen examples that use mg_upload or having read the code that uses the put_file function. Hmm. I shall try myself tomorrow. (though that does say there are several different routines to handle file data, why not use mg_read and mg_write in the PUT handle_request code instead of put_file, or expose put_file for me to put in my own handler to handle a PUT request?)

Next niggle: what about the authentication handling. Currently civetweb does manage auth but I think a handler would end up bypassing that (I am away from work so don't know if that's true yet).

**Comment by bel2125** [comment]
You could try a function like this:

``` C

    bool handlePut(CivetServer *server, struct mg_connection *conn)
    {
        const struct mg_request_info *req_info = mg_get_request_info(conn);
        long long rlen, wlen;
        long long nlen = 0;
        long long tlen = req_info->content_length;
        FILE * f;
        char buf[1024];
        int fail = 0;

        _snprintf(buf, sizeof(buf), "D:\\somewhere\\%s\\%s", req_info->remote_user, req_info->local_uri);
        buf[sizeof(buf)-1] = 0; /* TODO: check overflow */
        f = fopen_recursive(buf, "wb");

        if (!f) {
            fail = 1;
        } else {
            while (nlen < tlen) {
                rlen = tlen - nlen;
                if (rlen > sizeof(buf)) {
                    rlen = sizeof(buf);
                }
                rlen = mg_read(conn, buf, (size_t)rlen);
                if (rlen <= 0) {
                    fail = 1;
                    break;
                }
                wlen = fwrite(buf, 1, (size_t)rlen, f);
                if (rlen != rlen) {
                    fail = 1;
                    break;
                }
                nlen += wlen;
            }
            fclose(f);
        }

        if (fail) {
            mg_printf(conn,
                "HTTP/1.1 409 Conflict\r\n"
                "Content-Type: text/plain\r\n"
                "Connection: close\r\n\r\n");
            MessageBeep(MB_ICONERROR);
        } else {
            mg_printf(conn,
                "HTTP/1.1 201 Created\r\n"
                "Content-Type: text/plain\r\n"
                "Connection: close\r\n\r\n");
            MessageBeep(MB_OK);
        }

        return true;
    }
};
```

But this is just a somewhat simplified form of storing the file directly in the handler. Calling `put_file` in the handler would do the same - only `put_file` is currently static.

Using `mg_upload` works the same way: You have a handler that may pre-process, filter, ... the request, then call mg_upload to do the data transfer, and then do some further steps with the file.
Only `mg_upload` uses form encoding (and has ~10 issues, so I need to rewrite it sooner or later).

**Comment by gbjbaanb** [comment]
Ok, so we're finally at the same point - I need to do something along the lines of call `mg_upload` in a PUT handler, only `mg_upload` doesn't work for PUT requests. What would be nice is a function just like that on (only will work for all file upload cases).

If you're going to rewrite mg_upload to handle PUT requests, bear in mind that it doesn't cope with the optional Content-Type header, but that's reasonably trivial.

Also, the upload function needs a helper to work out the file location - for a PUT request this will be the URL, relative to some root directory on the file system (`put_file` already works this out), and it would also need helpers to handle authentication permissions (eg the `is_request_put_or_delete` function). These things are all present in civetweb, just not accessible from user code.

cheers.

**Comment by bel2125** [comment]
`mg_upload` needs to be rewritten - the code there is not really comprehensive and maintainable.
Even the [coverity scan](https://scan.coverity.com/projects/5784) finds more issues in this single function than in the entire rest of the code. 
And anyway, it should not be called `mg_upload` but something like `mg_handle_form_request`, since it should not only handle file upload but also access all other parameter types you have in a html form.
But this will take some time.

What you would need is a `mg_receive_file` API (in analogy to [`mg_send_file`](https://github.com/civetweb/civetweb/blob/master/include/civetweb.h#L531)), which finally calls `mg_put`.

Now, if you would have an API function `mg_receive_file` which is just a wrapper around `mg_put` (or if only the function is renamed and no longer static), what would you still miss?

**Comment by gbjbaanb** [comment]
I've had a look at the auth handling, and they are fine - the latest codebase handles auth before calling any custom handlers so we're good there. 

You'd probably want to pass in the path (interpreted from the URI) to the PUT handler to save having to re-calculate it, or expose `interpret_uri`. I'd pass in the path to avoid repeating the same operation twice.

And you might as well complete the set by including handers for DELETE, MKCOL and PATCH too, which requires exposure of `delete_file` and `mkcol` functions.

**Comment by bel2125** [comment]
`mg_upload` will be replaced by a better function soon.
see issue #180

**Comment by crimola** [comment]
Similar question from a civetweb newbie:

I have a similar problem but I should explain that I am completely new to civitweb. I built and installed civitweb 1.7 yesterday. My environment is Ubuntu 14.04 LTS and I placed everything in /opt/civitweb (my document_root).

My objective is simply to be able to upload file(s) to any directory (e.g., document_root or..). So far I am able to successfully send OPTIONS looking for a response with "Allow" that includes the PUT method and then perform the file upload using PUT with chunked encoding. This is all done from a program that uses an HTTP Client library, not from a browser.

So far OPTIONS using "/" works fine. PUT using "/file.tx" fails with  "not found" (404) but if I create an empty file.txt in the document_root directory (using touch). The response to the PUT is "OK" (200) but nothing gets written.

I can see on Wireshark that the HTTP interaction is correct. My question is what do I need to do on the Civetweb side to write the data sent (body) to the specified file?

From what I understand, I need some kind of handler to receive and write the data. Where are these handlers documented? Is there an existing one I can use and where do I place? Do I need to rebuild  Civetweb?

If anyone can point me in the right direction, I would greatly appreciate it.

**Comment by bel2125** [comment]
General documentation
---

You probably already know the documentation folder:
https://github.com/civetweb/civetweb/tree/master/docs

A good starting point for handlers written in C would be this example:
https://github.com/civetweb/civetweb/blob/master/examples/embedded_c/embedded_c.c

You could also use a handler written in Lua:
https://github.com/civetweb/civetweb/blob/master/test/handle_form.lua (used by a browser together with https://github.com/civetweb/civetweb/blob/master/test/form.html)


Your specific case
---
There are different ways to do this.

The first one requires to set a `put_delete_auth_file` - without a proper auth file, the server will not accept write/delete requests to static files. You can create a auth file by calling civetweb with the `-A` option - in Windows you can also do it with the graphical user interface.

The second one would be to write a script to handle the PUT requests. This could be C, Lua or CGI. For simplicity I would use Lua here. This script can check the file, the path, check cookies, disk quotas, etc. - so this is the most flexible way.

The form handling methods in some of the civetweb examples are preferable for browsers, not if you use another program (like `curl`).

**Comment by crimola** [comment]
Thanks for the prompt answer. Yes I have a proper put_delete_auth_file and it works. OPTIONS method does return the desired methods (and more) in the "Allow:" header.

Looks like I will most likely write the handler in C as I am not versed in Lua though I will take a look at Lua scripting this weekend. Thanks for the examples links also. The examples will come in handy..

**Comment by bel2125** [comment]
One advantage of using Lua would be: you could directly use the pre-built civetweb executables from SourceForge, and just put a Lua script file somewhere. Also buffer/string handling is simpler in Lua as compared to C. I often do a Lua prototype before a C/C++ implementation (if the extra performance of C is required at all). I added an example: https://github.com/civetweb/civetweb/blob/master/test/filehandler.lua

**Comment by crimola** [comment]
Thanks for the example. It looks straightforward and I see the benefit of Lua. I assume it can be placed in document_root. My only question is what triggers its execution by the CivetWeb executable?

**Comment by bel2125** [comment]
Sorry for the late answer - I have been abroad for some days:

The example works by placing filehandler.lua into the document root.
Then, it will handle all requests to http://yourserver:8080/filehandler.lua and all sub-resources (http://yourserver:8080/filehandler.lua/subresource).
Whenever a request to one these URLs is made, the script is executed by the interpreter directly built into civetweb - so no inter-process communication (like for CGI) is required.

In a next step, you could use URL rewriting or change the configuration for Lua extensions, to change the filehandler.lua to something else (the .lua part, the filehandler part can be changed by renaming the script).

**Comment by bel2125** [comment]
I marked this issue as duplicate to #180.

The `mg_upload` function has been replaced completely.
The new function is able to handle PUT, and process data on the fly.

#180 is solved and closed. 
I will close this duplicated issue now. If you encounter any problems, please open a new issue.
