### ISSUE TITLE
header_walk()

### ISSUE THREAD

**Issue by mewalig** [civetweb/civetweb#221]
I've modified my version of civetweb to include a header_walk() function that applies a generic function to all headers. this is useful for having a header_handler() that can operate on many different headers in a single call. Would do you think about adding this in?

__civetweb.h__:
```
/*
  mg_header_walk: apply a function to each header
  the function should return nonzero to continue,
  or zero to abort.
  the 'data' pointer is passed on to the function
*/
CIVETWEB_API int mg_header_walk(const struct mg_connection *,
                                int (*handler)(const char *name, const char *value,
                                             	void *data),
                                void *data);
```

__civetweb.c__:
```
int mg_header_walk(const struct mg_connection *conn,
                   char (*handler)(const char *name, const char *value,
                                void *data),
                   void *data) {
  const struct mg_request_info *ri = &conn->request_info;
  if (ri) {
    for(int i = 0; i < ri->num_headers; i++) {
      if(!(handler)(ri->http_headers[i].name, ri->http_headers[i].value, data)) {
        return 0;
      }
    }
  }
  return 1;
}```

**Comment by bel2125** [comment]
1) What is the use case for this function? Could you give us an example?

2) The `for(int i = 0; i < ri->num_headers; i++)` loop can be done in the application as well, or did I miss something essential? So what is the advantage of having this available in the API?

I usually prefer to have a minimal API, and functions that can be put together by calling some other functions only if they add some essential, or if they are replaced by newer ones and the older functions remain (at least for a while) to retain compatibility. So why is this function especially valuable?

**Comment by mewalig** [comment]
Two advantages. 

First, and directly related to your last point-- ```mg_get_header()``` can be put together by calling the more general function I propose, but the reverse is not true (```mg_header_walk()``` is the more general function of which ```mg_get_header()``` is just a specific use, where the handler passed to ```mg_header_walk()``` is a function that performs the strcmp and returns the value upon a match). So it seems like this approach is actually more consistent with your objective.

Second, and more importantly, it provides functionality the existing API lacks. Let me know if I'm wrong, which I definitely could be-- but as far as I could tell, the API only lets me look at headers **if I know the exact header name**. Several use cases for wanting to relax this requirement. For example, supposing I have three components, A, B, and C, and B is the one using civetweb, and is an intermediary between A and C, where A does analysis and C interacts with the end user-- well, we may want B to forward any headers it receives from A that start with 'FORWARD-ME-xxxx' (custom error codes etc) so that C can handle them instead of B. So if we want to add some additional headers that A and C recognize, we are not forced to also re-code B to recognize them even though B doesn't do anything but forward them.

**Comment by bel2125** [comment]
From the `const struct mg_connection *` object, you could call 
```C
CIVETWEB_API const struct mg_request_info * 
mg_get_request_info(const struct mg_connection *);
```

Then you get the `mg_request_info` structure with the following members:
```C
	int num_headers; /* Number of HTTP headers */
	struct mg_header {
		const char *name;  /* HTTP header name */
		const char *value; /* HTTP header value */
	} http_headers[64];    /* Maximum 64 headers */
```

You can just do the following code with the current API:

```C++
int myhandler(struct mg_connection *conn, void *cbdata)
{
    const struct mg_request_info * ri = mg_get_request_info(conn);
    for (int i = 0; i < ri->num_headers; i++) {
        func(ri->http_headers[i].name, ri->http_headers[i].value, cbdata);
    }

    mg_printf(...some response header...);
    mg_printf(...some response body...);
    return 1;
}
```

You API would allow to change this to 
```C++
int myhandler(struct mg_connection *conn, void *cbdata)
{
    mg_header_walk(conn, func, cbdata);

    mg_printf(...some response header...);
    mg_printf(...some response body...);
    return 1;
}
```
Two lines less, but nothing that lacks in the existing API.

Or did I miss something?

**Comment by mewalig** [comment]
Yea, you're right, I think I was somehow (clearly wrongly) under the impression that for API purposes mg_request_info was intended to be an opaque structure which was why mg_get_header() was provided in the first place
