### ISSUE TITLE
Can't download the version 1.7

### ISSUE THREAD

**Issue by silvioprog** [civetweb/civetweb#223]
Hello,

How to download the Civetweb 1.7 for Windows?

This link is broken:

http://sourceforge.net/projects/civetweb/files/1.7/civetweb-1.7-win32%2Bwin64.zip/download

It redirects to the Civetweb SF home page.

Thank you!

**Comment by bel2125** [comment]
That's probably a SourceForge problem - I don't know why it is not working.

I just uploaded it again: https://sourceforge.net/projects/civetweb/files/v1.7/
I hope this works better now.

**Comment by silvioprog** [comment]
Indeed. SF has weird bugs hehe. Now it is working like a charm, thank you very much! :-)
