### ISSUE TITLE
Lua: mg.url_decode doesn't decode spaces

### ISSUE THREAD

**Issue by danielrempel** [civetweb/civetweb#228]
```
mg.url_decode("rm+-rf+%2F") -> "rm+-rf+/"
```

I'll try to fix it today or tomorrow if you agree that it's a bug and must be fixed.

**Comment by danielrempel** [comment]
@bel2125, you're right. It worked okay. Then there's a bug in the documentation:)

**Comment by bel2125** [comment]
I think the bug is, it is not documented anywhere.
... another point on the TODO list.

**Comment by bel2125** [comment]
Let's close this issue now.
That something needs to be done with the documentation is on my TODO list - it does not make sense to reuse this issue for keeping track of missing documentations.

**Comment by danielrempel** [comment]
No problem!
