### ISSUE TITLE
Question: Can civetweb handle fork per new client  instaed of thread mechanism

### ISSUE THREAD

**Issue by CoderZeus** [civetweb/civetweb#229]
I  need the server to run safely without crashing. I was under the impression that failure by a thread handling one client could affect all the other clients. Can someone clarify?

Thanks...

**Comment by bel2125** [comment]
Is this the same question as diskussed [in the CivetWeb Google group](https://groups.google.com/forum/#!topic/civetweb/0kMTl2bpNDg) ?

You could use CGI to detach creating the response into another process - in exchange for some performance. 

If this is the same topic as on the Google discussion group, let's continue there.

**Comment by bel2125** [comment]
Closing this question ==> discussion will continue [here](https://groups.google.com/forum/#!topic/civetweb/0kMTl2bpNDg)
