### ISSUE TITLE
Possible bug in error handling in server pages

### ISSUE THREAD

**Issue by danielrempel** [civetweb/civetweb#232]
{{{
function lsp (...)
...
if (lua_ok) {
...
mod_lua.inl: lsp(..): 375: lua_pcall(L, 0, 0, 1);
...
}}}
Shouldn't lua_pcall be called with zero as last argument? After changing it zero I got some error messages in logs and debug output.

**Comment by bel2125** [comment]
([According to the manual](http://www.lua.org/manual/5.2/manual.html#lua_pcall)), the third argument is the error handler. It is pushed onto the Lua stack a few lines before (`lua_pushcclosure(L, lsp_error, 1);`).
This handler should call `mg.onerror`, a function you could overwrite. The default is `mg.cry` - this should log the message.

Do you have an example of a bad page, and describe in more detail what you see and what you expect to see?

What version are you using, and what operating system? You could call civetweb with the parameter `-I` - all the data I'm asking for is in the output.

**Comment by bel2125** [comment]
I did not get any response in the last months, so I think the problem does no longer exist or is no longer of any relevance.
