### ISSUE TITLE
chat example produces "close_socket_gracefully: setsockopt(SOL_SOCKET SO_LINGER) failed" messages (on OSX)

### ISSUE THREAD

**Issue by mewalig** [civetweb/civetweb#237]
Hi,

On OSX, if I build the latest civetweb chat example, and I add a logging callback to show all messages, then, out of the box, when the service is first queried, it shows several messages saying:
 "close_socket_gracefully: setsockopt(SOL_SOCKET SO_LINGER) failed: Invalid argument"

Is this normal / OK / expected?

To replicate (at least on OSX), modify chat.c as follows, then build, then run, then go to https://localhost:8082, and the output shows up in the console: 
* create a function
```
static int log_message(const struct mg_connection *conn, const char *message) {
  fprintf(stderr, "%s\n", message);
  return 0;
}
```
* add ```callbacks.log_message = log_message;``` to main()

**Comment by bel2125** [comment]
Unfortunately I have no OSX system available, so I cannot test this on my own.
Does this also occur with the standalone server (main.c)?

**Comment by mewalig** [comment]
Tried it out, looks like it does happen with main.c, and furthermore, it appears in both cases to only happen when using ssl. I am using a self-signed cert, in case that matters (though, on windows with a self-signed cert, these messages do not appear). I'm using the following to invoke:
```./civetweb -ssl_certificate path/to/ssl_cert.pem -listening_ports 8080s```

**Comment by bel2125** [comment]
What civetweb and OS version are you using?

The message comes from this part of the code:
```C
	/* Set linger option to avoid socket hanging out after close. This prevent
	 * ephemeral port exhaust problem under high QPS. */
	linger.l_onoff = 1;
	linger.l_linger = 1;

	if (setsockopt(conn->client.sock,
	               SOL_SOCKET,
	               SO_LINGER,
	               (char *)&linger,
	               sizeof(linger)) != 0) {
		mg_cry(conn,
		       "%s: setsockopt(SOL_SOCKET SO_LINGER) failed: %s",
		       __func__,
		       strerror(ERRNO));
	}
```

It means, the linger option could not be set to 1 second.
But it does not have any other consequences - the rest of the code should be executed without any problem. Do you experience any other problem?

I did not find any hint using SO_LINGER could be a problem on MacOS.
But what I found something curious: While SO_LINGER is set in seconds for Linux (http://linux.die.net/man/7/socket) and for Windows (https://msdn.microsoft.com/en-us/library/windows/desktop/ms739165%28v=vs.85%29.aspx), there is apparently an extra option SO_LINGER_SEC in MacOS (https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man2/getsockopt.2.html). So maybe SO_LINGER for MacOS works differently than for any other system, and they introduced SO_LINGER_SEC to be compatible with the standard.

I will check if I can find more.
Do you build the server on your own?

**Comment by bel2125** [comment]
According to the [Apple socket.h file](http://www.opensource.apple.com/source/xnu/xnu-2050.18.24/bsd/sys/socket.h):
```C
#if !defined(_POSIX_C_SOURCE) || defined(_DARWIN_C_SOURCE)
#define SO_LINGER	0x0080          /* linger on close if data present (in ticks) */
#else
#define SO_LINGER	0x1080          /* linger on close if data present (in seconds) */
#endif	/* (!_POSIX_C_SOURCE || _DARWIN_C_SOURCE) */

#define SO_LINGER_SEC	0x1080 /* linger on close if data present (in seconds) */
```

So how `SO_LINGER` works depends on some compiler defines.
If you build it on your own, could you try SO_LINGER_SEC instead of SO_LINGER in the `setsockopt` call above?

**Comment by mewalig** [comment]
ok, will try and get back. yes, building on my own, using / on:

Apple LLVM version 7.0.0 (clang-700.0.72)
Target: x86_64-apple-darwin14.5.0
Thread model: posix

**Comment by mewalig** [comment]
Same thing after replacing the 2 occurrences of SO_LINGER with SO_LINGER_SEC in civetweb.c. Here is the console output after going to https://localhost:8080

> ./civetweb -ssl_certificate /path/to/ssl_cert.pem -listening_ports 8080s

Loading config file ./civetweb.conf
CivetWeb V1.8 started on port(s) 8080s with web root [/path/to/civetweb]
close_socket_gracefully: setsockopt(SOL_SOCKET SO_LINGER_SEC) failed: Invalid argument
close_socket_gracefully: setsockopt(SOL_SOCKET SO_LINGER_SEC) failed: Invalid argument
close_socket_gracefully: setsockopt(SOL_SOCKET SO_LINGER_SEC) failed: Invalid argument
close_socket_gracefully: setsockopt(SOL_SOCKET SO_LINGER_SEC) failed: Invalid argument

I'm thinking it has to have something to do with the SSL library interaction. It does not occur on Windows, and it does not occur with plain http. Have not tested on linux. I also tried swapping in libressl (using ```brew libressl``` and then forcing the linkage)-- same result.

**Comment by bel2125** [comment]
I don't know if this issue still exists.
I have no OSX system available, and I won't find anything new without a short test.
If the issue still exists, it won't get better by just waiting yet another month.
So I'm adding a "Help wanted" label, maybe some other user with an OSX system is able to help.

**Comment by bel2125** [comment]
I'm not sure if this issue is related to #320. Probably you could try if the proposed fix for #320 helps.
Maybe OSX has an issue if linger is neither 0 nor not set - maybe 1 is a somewhat unusual value (see #288).

**Comment by saumitravikram** [comment]
The issue here is due to slight difference in system socket library for Mac and that of windows and linux.


On OSX, SO_LINGER can return EINVAL(Invalid Input) if the other end of the socket is already closed. Windows and Linux do not return errors in this case.

Ref -[https://github.com/dotnet/corefx/pull/7506](url) 
[https://github.com/dotnet/corefx/issues/7403](url) 
[http://pubs.opengroup.org/onlinepubs/009695399/functions/setsockopt.html](url)
Refer error code EINVAL in last link

To conform on the same I modified the code for function close_socket_gracefully to check if socket was closed before calling setsockopt(SOL_SOCKET SO_LINGER)
```
	linger.l_onoff = 1;
	linger.l_linger = 1;
	socklen_t error_code,error_code_size;
	error_code=0;
	error_code_size = sizeof(error_code);
	getsockopt(conn->client.sock, SOL_SOCKET, SO_ERROR, &error_code, &error_code_size);
	if (error_code==ECONNRESET)
	{
		mg_cry(conn,
				       "%s: getsockopt(SOL_SOCKET SO_ERROR) : ECONNRESET - Connection closed by client",
				       __func__);
	}
	if (setsockopt(conn->client.sock,
	               SOL_SOCKET,
	               SO_LINGER,
	               (char *)&linger,
	               sizeof(linger)) != 0) {
		mg_cry(conn,
		       "%s: setsockopt(SOL_SOCKET SO_LINGER) failed: %s",
		       __func__,
		       strerror(ERRNO));
	}
```

Below is the output of the test code,where we see each time we get Invalid argument is when the connection is closed by client.
```
ac87a336e29f:MacOS saumitv$ ./Civetweb -listening_ports 8080s -ssl_certificate ../../../../../resources/ssl_cert.pem -error_log_file error.log -access_log_file access.log
close_socket_gracefully: getsockopt(SOL_SOCKET SO_ERROR) : ECONNRESET - Connection closed by client
close_socket_gracefully: setsockopt(SOL_SOCKET SO_LINGER) failed: Invalid argument
close_socket_gracefully: getsockopt(SOL_SOCKET SO_ERROR) : ECONNRESET - Connection closed by client
close_socket_gracefully: setsockopt(SOL_SOCKET SO_LINGER) failed: Invalid argument
close_socket_gracefully: getsockopt(SOL_SOCKET SO_ERROR) : ECONNRESET - Connection closed by client
close_socket_gracefully: setsockopt(SOL_SOCKET SO_LINGER) failed: Invalid argument
close_socket_gracefully: getsockopt(SOL_SOCKET SO_ERROR) : ECONNRESET - Connection closed by client
close_socket_gracefully: setsockopt(SOL_SOCKET SO_LINGER) failed: Invalid argument
```

There are two options to fix it -
1) Check on OSX check if client already closed connection, then no need to linger we can go ahead and close the connection.
2) Same as above but  no need for checking OS since it doesn't make sense to linger if socket is all ready closed by client on windows and Linux also.

**Comment by saumitravikram** [comment]
@bel2125 Please let me know which options you feel fine and i can go ahead a pull request with the changes

**Comment by bel2125** [comment]
> 2) Same as above but no need for checking OS since it doesn't make sense to linger if socket is all ready closed by client on windows and Linux also.

This option makes sense to me.

Looking forward to your pull request.

**Comment by saumitravikram** [comment]
#355

**Comment by saumitravikram** [comment]
#355
