### ISSUE TITLE
parse_date_string is wrong Jan and Feb of leap year

### ISSUE THREAD

**Issue by wernerh2** [civetweb/civetweb#250]
The calculation of parse_date_string is wrong by one day in january and February of a leap year.
Instead parse_date_string, I am using timegm on Linux or an own implementation of timegm on Windows (using mktime and calculating the UTC offset).

**Comment by bel2125** [comment]
You mean, replace this code:
```
			leap_days = num_leap_years(year) - num_leap_years(1970);
			year -= 1970;
			days =
			    year * 365 + days_before_month[month] + (day - 1) + leap_days;
			result = (time_t)days * 24 * 3600 + (time_t)hour * 3600
			         + minute * 60 + second;
```
by a code using `mktime` and some localtime/gmtime difference correction.
Do you have an already working code, you would be willing to share?

**Comment by wernerh2** [comment]
The problem is within num_leap_years.
You could add the parameter month and treat a current leap year only if month > 1 (not January or February).

I did the following:
`
#ifdef _WIN32
time_t timegm(struct tm* pTm)
{
	// Compute the offset between local and UTC time.
	time_t utcTime;
	time_t localTime;
	struct tm *tm;
	utcTime = time(NULL);
	tm = gmtime(&utcTime);
	localTime = mktime(tm);
	// Make UTC time from time structure.
	return mktime(pTm) + (utcTime - localTime);
}
#endif

static time_t
parse_date_string(const char *datetime)
{
	static const unsigned short days_before_month[] = {
	    0, 31, 59, 90, 120, 151, 181, 212, 243, 273, 304, 334};
	char month_str[32] = {0};
	// int second, minute, hour, day, month, year, leap_days, days; // Replaced by struct tm.
	struct tm tm;
	time_t result = (time_t)0;

	// if ...
	// Use &(tm.tm_mday), &(tm.tm_year), &(tm.tm_hour), &(tm.tm_min), &(tm.tm_sec)
	// instead &day, &year, &hour, &minute, &second.

		tm.tm_year -= 1900;
		result = timegm(&tm); // Remark: mktime is the opposite of localtime and not of gmtime!
	}
	return result;
}
`

**Comment by wernerh2** [comment]
(The edit function "Insert code" didn't work as expected ...)

**Comment by bel2125** [comment]
This code ([from above](https://github.com/civetweb/civetweb/issues/250#issuecomment-176012918)) the does actually not work, if the UTC offset of the date/time to parse is different from the current UTC offset. E.g., if the date/time was in summer, and you are calculating gmtime now (in winter), and you have a time zone that uses *daylight saving time* (*Summer Time*, ...) - or if you are in a time zone that changed the UTC offset since the date/time to parse for any other reason.

**Comment by bel2125** [comment]
I completely dropped the old self-made code in CivetWeb and switched to using the functions provided by the operating system libraries (`timegm` or `_mkgmtime` for Windows) - it makes so sense to re-implement what already exists there.
I think this should solve all time calculation issues in `parse_date_string`.

**Comment by bel2125** [comment]
The original function has been replaced by calling the system library function.
Thus, there are no leap year related problems anymore in CivetWeb (if there would be leap year related problems, they would be in the system library - I am not aware of any remaining problem).

Thus, I'm going to close this issue.
