### ISSUE TITLE
Expose HEAD request handling to C++

### ISSUE THREAD

**Issue by PhilLab** [civetweb/civetweb#256]
The CivetHandler also needs a ``handleHead()`` method. I have the patch ready but one question remains:
Should the default implementation call ``handleGet()`` since the underlying c methods like ``mg_send_file`` already handle the difference between GET and HEAD or should it not because it would be unintuitive?

    bool
    CivetHandler::handleHead(CivetServer *server, struct mg_connection *conn)
    {
        // Default behavior: use the GET handler
        return handleGet(server, conn);
    }

or

    bool
    CivetHandler::handleHead(CivetServer *server, struct mg_connection *conn)
    {
    	UNUSED_PARAMETER(server);
	    UNUSED_PARAMETER(conn);
	    return false;
    }

**Comment by bel2125** [comment]
In C, we do not have different handlers for the different methods - only the URI is used to choose the handler, not the method. The handler can/should/must check the method on its own. This is the same for CGI and Lua scripts.

However, the current C++ implementation (`CivetServer::requestHandler`) calls different handlers for all methods. So C++ already works differently than all other interfaces.

I think it would be consistent with the present C++ interface, to use a different handler for `HEAD` as well.

So the question is, what to do if the programmer supplied a `handleGet` method, but not a `handleHead` method.
Currently `CivetServer::requestHandler` will return `0` for any `HEAD` request, so returning `0` will be compatible.

Probably a `405 Method Not Allowed` would be the cleanest way to handle missing handlers - but I would just return 0 for the moment.

So, will you create a pull request?

**Comment by bel2125** [comment]
Merged with #257.
