### ISSUE TITLE
Crosscompiling from linux to windows

### ISSUE THREAD

**Issue by pobfdm** [civetweb/civetweb#259]
It is possible crosscompiler civetweb width mxe tool?
When i try to build:

i686-w64-mingw32.static-ld: cannot find -ld collect2: error: ld returned 1 exit status

My makefile:
`all:

```
i686-w64-mingw32.static-gcc -lpthread -ldl  mywebserver.c civetweb.c -o mywebserver.exe
```

clean:
    rm mywebserver  `

**Comment by bel2125** [comment]
I am no expert in build systems, and before your question I never heard of mxe.
I found the web site (http://mxe.cc/), and from a first, brief look, I do not see any reason why it should not work. 

I'm don't know myself - so probably let's add the "help wanted" label - maybe someone who knows will answer the question.

**Comment by jd-boyd** [comment]
@pobfd, your information on your failure is not really sufficient.  You would need to at least include a dozen (maybe more) of the last lines of the build prior to the line:

    i686-w64-mingw32.static-ld: cannot find -ld collect2: error: ld returned 1 exit status

For anyone else to try this recreating your problem, you would need to supply `mywebserver.c`, preferably reduced to the minimal size needed to show the problem while working on linux.

**Comment by pobfdm** [comment]
My makefile:

all:
	
	i686-w64-mingw32.static-gcc -lpthread -ldl  mywebserver.c civetweb.c -o mywebserver.exe

clean:
	rm mywebserver	


Make output:

i686-w64-mingw32.static-gcc -lpthread -ldl  mywebserver.c civetweb.c -o mywebserver.exe
mywebserver.c: In function 'FooHandler':
mywebserver.c:67:41: warning: initialization discards 'const' qualifier from pointer target type
     struct mg_request_info * req_info = mg_get_request_info(conn);
                                         ^
/home/fabio/.local/bin/mxe/usr/bin/i686-w64-mingw32.static-ld: cannot find -ldl
collect2: error: ld returned 1 exit status

**Comment by jd-boyd** [comment]
I have mxe installing currently.  The initial build is pretty slow.  In the mean time, the first suggestion that leaps out at me is to get rid of `-ldl` from your `Makefile`.

**Comment by bel2125** [comment]
Personally, I cannot contribute anything to this topic.
Should we keep it open or close it?

**Comment by kainjow** [comment]
CMake should help with making this easier, so I would suggest people who want to cross compile should use the CMake build and then if there are fixes that need to be made, they can bring those up.

**Comment by bel2125** [comment]
But dealing with cross compile environments is not a CivetWeb specific issue at all.
So, I don't know if this is the right place for this topic.
I have no problem if you think we should keep it open - but I will not be able to contribute anything useful, and probably there is a better place to ask for community support for dealing with build systems.

**Comment by nattgris** [comment]
I have no idea what mxe is but I could successfully cross-compile and run (under wine) the posted code using the gcc-mingw-w64 Ubuntu package and the following command line:

`x86_64-w64-mingw32-gcc mywebserver.c civetweb.c -o mywebserver.exe -static -lpthread -lws2_32`

Using the i686 compiler I got a missing reference to _mkgmtime but that's apparently a misconfiguration in the 32-bit MinGW-w64 toolchain so whatever mxe is it should not have the same problem. Dynamic link worked fine too but I didn't have the necessary DLLs in place to run it.

I can't imagine what CMake could do to make this easier. In my limited experience CMake only make things harder.

So I guess cross-compiling works and this issue can be closed.

**Comment by bel2125** [comment]
After some minor changes (like replacing "Windows.h" by "windows.h" and setting some defines) the current version (2b6392fc580b065edb65076cd71b10d94f162029) can be built the following way:

`x86_64-w64-mingw32-gcc examples/embedded_c/embedded_c.c src/civetweb.c -Iinclude -lws2_32 -DMUST_IMPLEMENT_CLOCK_GETTIME -DNO_SSL -ocivetweb.exe`

It creates a Win64 executable on Linux (Ubuntu 16.04) without any compile or link errors. The resulting exe works on Windows 10.

I don't know how to wrap this for **mxe** but cross compiling in principle works now. I cannot promise every future commit will also allow cross compiling out of the box, since we do not test it in a continuous integration environment - but if it does not, it should only require some minor change like upper/lower case in includes or some ifdef to include or define the proper system API.

**Comment by bel2125** [comment]
Cross compiling works in principle. Some minor fixes might be required from time to time.
I guess, this is all we can do here.
