### ISSUE TITLE
Handler registration compares only front match

### ISSUE THREAD

**Issue by PhilLab** [civetweb/civetweb#260]
If you register a handler for e.g. ``**.js``, it will also be fired for ``file.json``. This does not seem intended to me, is it?

    mg_set_request_handler(c, "**.js", handler1 ... )
    mg_set_request_handler(c, "**.json",  handler2 ...)
    // -> handler1 will be called for the URI file.json

 
    mg_set_request_handler(c, "**.json",  handler2 ...)
    mg_set_request_handler(c, "**.js", handler1 ... )
    // -> handler2 will be called for the URI file.json

**Comment by bel2125** [comment]
I think this is yet another duplicate of #179 (as #255 is).
My idea to fix this would be an incompatible change in the way pattern matching works - this is something that needs to be well prepared and documented.

**Comment by bel2125** [comment]
You could try a "$" at the end:
```
mg_set_request_handler(c, "**.js$", handler1 ... )
mg_set_request_handler(c, "**.json$",  handler2 ...)
```

This is not a general solution to all problems we have with pattern matching, but it should work in your case.

**Comment by PhilLab** [comment]
thanks for the workaround - it works. Closed this issue since it is indeed a duplicate
