### ISSUE TITLE
Crashes when hits by a proxy scanner

### ISSUE THREAD

**Issue by zouzhiquan** [civetweb/civetweb#266]
Hi there,

Seems the CivetWeb has one bug, when a proxy scanner uses TCP connects to the HTTP port directly and sends in a request with full URL, the program crashes.

How to replicate the problem:
1, Telnet to the HTTP port (e.g. "telnet 127.0.0.1 8080")
2, Type in "GET http://testp2.czar.bielawa.pl/testproxy.php HTTP/1.0" (without quotation mark) and then hit the Enter key a few times.

You should see an exception at line 9499, "uri_len = (int)strlen(ri->local_uri);" because ri->local_uri is NULL.
```C++
		/* 1. get the request url */
		/* 1.1. split into url and query string */
		if ((conn->request_info.query_string = strchr(ri->request_uri, '?'))
		    != NULL) {
			*((char *)conn->request_info.query_string++) = '\0';
		}
		uri_len = (int)strlen(ri->local_uri);             //crashes here

		/* 1.2. decode url (if config says so) */
		if (should_decode_url(conn)) {
			mg_url_decode(
			    ri->local_uri, uri_len, (char *)ri->local_uri, uri_len + 1, 0);
		}
```

Remedy:
For my application, I don not need to care about working as a proxy at all, so I return a "404 - Not Found" if ri->local_uri is NULL, add below code to line 9492.
```C++
		if(ri->local_uri == NULL){
			send_http_error(conn, 404, "%s", "Not found");
			return;
		}
```
It might not work for everyone though.

**Comment by bel2125** [comment]
The "handle_request" should not be called for requests to other servers.
I changed this in the code, and added a TODO for the non local requests - it currently sends no error but just closes the connection.
This will avoid this crash.

**Comment by zouzhiquan** [comment]
Yes, your new code works. May I know when it will be released? Because I don't see it in the latest version.

**Comment by bel2125** [comment]
The latest version is always on github.

I need to do some tests before a release is created.
The released version will be available as source on github as well. Additionally, a source package (for Linux) and a Windows EXE will be available on SourceForge.
