### ISSUE TITLE
When use as a embed ssl/tls server use the server.pem in example, a windows 2k3 client can't connect to server.

### ISSUE THREAD

**Issue by ocean69** [civetweb/civetweb#274]
Sorry to bother.
But i don't know tls well.
I can't figure a way my own, to fix this.
I write a HTTPS client use WINHTTP lib of windows.
When i use WinHttpSendRequest send data to a civetweb server WinHttpSendRequest return false with error detail WINHTTP_CALLBACK_STATUS_FLAG_SECURITY_CHANNEL_ERROR
(windows's explain is The application experienced an internal error loading the SSL libraries).
Error occur when The client run in windows 2003, server run on whatever version doesn't matter.
And windows xp client doesn't have this problem.

**Comment by bel2125** [comment]
So WinHttpSendRequest in an application started on Windows XP works, and the same application on Windows Server 2003 does not work?
Did you check it for any other (more recent) Windows version?

**Comment by ocean69** [comment]
I didn't test all, but quit a few. Just windows 2003 has this problem.(and my windows 2003 never update, may be that useful.)

**Comment by ocean69** [comment]
After some debug and search, I start to think it's windows 2003's problem in self signed cert velidate code.

**Comment by bel2125** [comment]
I don't have a Windows 2003 system to reproduce the problem either, and [its no longer support by Microsoft since July 14, 2015](https://www.microsoft.com/en/server-cloud/products/windows-server-2003/).
Since you said, the problem is (most likely) in the Windows 2003 code, there is probably nothing I can do in civetweb, right?

**Comment by ocean69** [comment]
Yes.

**Comment by PBRCW** [comment]
A problem with the Casablanca REST SDK and WIndows 2008 caused the same error message. They found the cause and a solution to the problem, see if that fixes your problem as well:
[winhttp WINHTTP_CALLBACK_STATUS_FLAG_SECURITY_CHANNEL_ERROR](https://www.google.de/url?q=https://stackoverflow.com/questions/47373513/winhttp-winhttp-callback-status-flag-security-channel-error&sa=U&ved=0ahUKEwjVuYzK7ujZAhWEW8AKHYHdAp8QFggfMAI&usg=AOvVaw2y9OwA37m4Le60wtfTiB4f)
Seems the setup had a problem establishing a TLS 1.2 connection on that machine and disabling TLS 1.2 sovlved the issue. As this is just setting some option in WInhttp this should be easily testable.

HTH

Don
