### ISSUE TITLE
Sec-Wesocket-Protocol response header is wrong when there are multiple protocols

### ISSUE THREAD

**Issue by njh-lbo** [civetweb/civetweb#295]
When a client requests multiple Websocket protocols, such as:
`Sec-Websocket-Protocol: foo, bar`
the server is supposed to reply with just one, e.g.:
`Sec-Websocket-Protocol: foo`
but CivetWeb echoes the entire header line. This causes some browsers (IE10, for example) to close the connection with an error.

Possibly the fix might be as simple as truncating the string at the first comma?

**Comment by bel2125** [comment]
Sorry, I have been sick for a while - I'm going to have a look soon.

**Comment by njh-lbo** [comment]
Thanks - I appreciate the "proper" fix is fiddly and probably not worth anyone's time, and am happy doing my quick fix  - but I thought I ought to mention the issue.

(By way of background: I had a JavaScript client, designed work with Websockify, which was requesting ["binary", "base64"] and so triggering the bug; though in fact it really only wanted "binary".)

**Comment by bel2125** [comment]
The quick fix should work, but I don't have IE10 to test it ... FireFox does not seem to care if the server returns multiple protocols. Could you repeat the test.

I added a TODO mark for the more sophisticated fix, but I will not start to implement it *now*.

**Comment by njh-lbo** [comment]
I just tested before and after 9485598, against a JavaScript client which tries to create a WebSocket with sub-protocols `['binary', 'base64']` running in IE 11.0.30 (which is the browser I was in fact using). I can confirm that the change fixes the problem. Thanks!

Did you intend those comment formatting changes?

**Comment by njh-lbo** [comment]
I just tested the fix and it’s working. I have closed the issue on GitHub (not sure if that was the right thing to do as it’s still flagged “waiting for submitter to confirm”).

BTW it turns out I was using IE11.0.30 instead of IE10 as I previously stated (I think it got updated recently when I wasn’t looking).

Thanks,

Nick

**Comment by bel2125** [comment]
> I just tested the fix and it’s working. I have closed the issue on GitHub 
> (not sure if that was the right thing to do as it’s still flagged “waiting for submitter to confirm”).

Of course - you are the submitter, you tested it and confirmed it's working.
I added a TODO mark to implement a subprotocol list, as intended by the RFC, but this is something that will be implemented probably much later and should not be tracked with this issue.
