### ISSUE TITLE
Windows: Verifying interpreted path is a long path name

### ISSUE THREAD

**Issue by xtne6f** [civetweb/civetweb#299]
On Windows, files can be also accessed by SFN (short filename), so, for example, `hide_files_patterns` is almost useless.
This is my candidate fix for the issue. (sorry this is release-v1.7 based patch.)

    --- a/civetweb.c
    +++ b/civetweb.c
    @@ -2379,6 +2379,24 @@ static void to_unicode(const char *path, wchar_t *wbuf, size_t wbuf_len)
     
    +static int is_existing_long_path(const char *path)
    +{
    +	wchar_t wpath[PATH_MAX];
    +	char buf[PATH_MAX], buf2[PATH_MAX];
    +	DWORD len;
    +
    +	to_unicode(path, wpath, ARRAY_SIZE(wpath));
    +	if (WideCharToMultiByte(CP_UTF8, 0, wpath, -1, buf, sizeof(buf), NULL, NULL) != 0) {
    +		len = GetLongPathNameW(wpath, wpath, ARRAY_SIZE(wpath));
    +		if (len != 0 && len < ARRAY_SIZE(wpath) &&
    +		    WideCharToMultiByte(CP_UTF8, 0, wpath, -1, buf2, sizeof(buf2), NULL, NULL) != 0 &&
    +		    mg_strcasecmp(buf, buf2) == 0) {
    +			return 1;
    +		}
    +	}
    +	return 0;
    +}
    +
     #if defined(_WIN32_WCE)
    @@ -3886,7 +3904,11 @@ interpret_uri(struct mg_connection *conn,   /* in: request */
     
     		/* Local file path and name, corresponding to requested URI
     		 * is now stored in "filename" variable. */
    -		if (mg_stat(conn, filename, filep)) {
    +		if (mg_stat(conn, filename, filep)
    +#if defined(_WIN32)
    +		    && (filep->membuf || is_existing_long_path(filename))
    +#endif
    +		    ) {
     			/* File exists. Check if it is a script type. */
     			if (0
     #if !defined(NO_CGI)
    @@ -3928,7 +3950,11 @@ interpret_uri(struct mg_connection *conn,   /* in: request */
     		    NULL) {
     			if (strstr(accept_encoding, "gzip") != NULL) {
     				snprintf(gz_path, sizeof(gz_path), "%s.gz", filename);
    -				if (mg_stat(conn, gz_path, filep)) {
    +				if (mg_stat(conn, gz_path, filep)
    +#if defined(_WIN32)
    +				    && (filep->membuf || is_existing_long_path(gz_path))
    +#endif
    +				    ) {
     					if (filep) {
     						filep->gzipped = 1;
     						*is_found = 1;
    @@ -3958,7 +3984,11 @@ interpret_uri(struct mg_connection *conn,   /* in: request */
     				         filename) > 0
     #endif
     				     ) &&
    -				    mg_stat(conn, filename, filep)) {
    +				    mg_stat(conn, filename, filep)
    +#if defined(_WIN32)
    +				    && (filep->membuf || is_existing_long_path(filename))
    +#endif
    +				    ) {
     					/* Shift PATH_INFO block one character right, e.g.
     					 * "/x.cgi/foo/bar\x00" => "/x.cgi\x00/foo/bar\x00"
     					 * conn->path_info is pointing to the local variable "path"

**Comment by bel2125** [comment]
I must admit I never use the `hide_file_patters` option - but of course, if it is available it is supposed to work.
My approach is to have two (actually three, sometimes four) different sub-directories: 
* One directory `docroot` - the `document_root` points to it. 
* One directory `offroot` (or something like this) - all files not directly accessible are located there. But the `docroot` may contain scripts accessing files in this directory. If there is an sqlite data base, it will also be in this directory.
* The third directory is usually `bin` - the civetweb.exe, additional dlls, etc. are located there.
* If there is a fourth, it's `tmp`, the working directory of `civetweb.exe`. This working directory could be `offroot` as well.

This makes it much easier to not accidentally have anything in the document root, that should not be exposed, by having a bad `hide_file_patters` option or a short name.

This is not a fix for the short name issue, it's a strategy to avoid the need for `hide_file_patters` - it is not a requirement to do it like described above - using `hide_file_patterns` is perfectly valid.

On the other hand, I`m not perfectly happy with the way pattern matching works in the moment anyway. There are some problems in pattern matching discussed in #179, #255 and the civetweb google group.
I would prefer to first deal with the pattern matching problems in general before working on the specific short/long filename problem of the hide_file pattern.

**Comment by xtne6f** [comment]
Thank you for your reply.
Umm.., so you should notify `hide_file_patters` is deplicated on Windows in your document.
Then, this issue is not only `hide_file_patters`.
Currently `.htpasswd` can be readable by every users as `HTPASS~1` on Windows.
For example, if `lua_script_pattern` is "**.jpeg", anyone can read inner image-generator script of `foo.jpeg` as `FOO.JPE`.

**Comment by bel2125** [comment]
> you should notify hide_file_patters is deplicated on Windows in your document.
What document do you mean?

> Currently .htpasswd can be readable ...
This is indeed a severe bug. I will check this immediately.

**Comment by xtne6f** [comment]
> What document do you mean?

`UserManual.md` or so (of course, I cannot force that).

> This is indeed a severe bug. I will check this immediately.

I think whether severe or not depends on operational policy.
If `.htpasswd` describes multiple users, it would be severe.

**Comment by bel2125** [comment]
It seems short file names are a windows system setting, that can be enabled or disabled: https://support.microsoft.com/en-us/kb/121007
It is enabled for my system ... and it's indeed possible.

Having multiple user in .htpasswd is perfectly valid.
Still, most people will use form/cookie based user authentication anyway, so .htpasswd is not used that often, but still its valid. If it is used for put auth, it should be in the offroot dir - it's the put_delete_auth_file option, with just one file that can by anywhere, and I think it's also not used often since you can usually administrate your server by adding/removing/changing your files in another way as HTTP.
And if you are really concerned about security, you use client certificates, not .htpasswd.
Still: Having multiple user in .htpasswd is perfectly valid, so I think it must be fixed immediately.

I think mg_fopen, mg_stat, mg_remove and opendir must not accept short filenames.
For mg_mkdir it probably does not matter if it does - better disallow it as well.

**Comment by bel2125** [comment]
The patch above should eliminate all these problems by completely disabling short file names on Windows. Could you test and review it? It worked for me in a first smoke-test.

**Comment by xtne6f** [comment]
Thank you, I will test it.

> https://support.microsoft.com/en-us/kb/121007

To disable 8.3 file name must be impossible even the latest Windows 10 :-(

I did not think about PUT or DELETE. I thought the checking was enough only at the place of URI translation, but this might be wrong.
Client certificates must be more secure, but a little complex for users of my project.
Thank you for your advice and commit.

**Comment by xtne6f** [comment]
I tested 47e1dc92ac12e02eabb407418c13586243de90ef .
`if ((long_len >= ARRAY_SIZE(wbuf2)) || (wcscmp(wbuf, wbuf2) != 0)) {`
has to be case-insensitive. Because, unexpectedly, if "C:\Path\To\Content.html" exists on the server, the result of `GetLongPathNameW("c:\path\to\content.html")` is "C:\Path\To\content.html".

Then, I think, the case `long_len==0` (`GetLongPathNameW()` failed), the contents of wbuf2 is not guaranteed, so `wbuf[0] = L'\0';` would also need here.
If I modify it further, I will do `path_to_unicode()` to return success or not. It's your pick.

For your reference, I looked over the codes of Nginx (os/win32/ngx_files.c) and Apache (/srclib/apr/file_io/win32/*), both projects also seem to check or convert to LFN.

**Comment by xtne6f** [comment]
Sorry, the result of `path_to_unicode()` is `wbuf`, so the contents of `wbuf2` don't care.

**Comment by bel2125** [comment]
Checking `(wcscmp(wbuf, wbuf2) != 0)` makes the server case sensitive for Windows.
The server is case sensitive anyway, if it runs on Linux.
The problem with case insensitive comparison is how to deal with characters other than A-Z. There are characters like lower case á with upper case Á, lower case ß corresponds to two upper case letters SS, some languages have a third case in addition to upper and lower case. And even if the case is the same, sometimes letters can be represented either as a combination of two consecutive codes or as one combined, with a completely identical written character.
C offers the [towlower](http://www.cplusplus.com/reference/cwctype/towlower/) but this depends on the locale definition, so using it would make the server case insensitive for letters known by the current locale, and case sensitive for letters not known by the server locale.
... not a simple topic.

Still compatibility should also be considered here - I need to think about what the best solution is here.

But beside upper/lower case, I think there is no other issue here.

I think the server should drop all short names - using short names in the server seems completely weird to me.

**Comment by xtne6f** [comment]
> ... not a simple topic.

I think so, too.
Case sensitive restriction would be OK, because current Windows preserves case of filenames.
Though, US-ASCII characters are used for special files of Civetweb such as `index.htm`.
If you change the case rule from now, `Index.htm` is altered to a normal file on Windows. This might create confusion.
So, I think like a `mg_strncasecmp()` is enough.

Nginx sets it's process locale by `setlocale(LC_ALL, "");` and simply calls `_wcsicmp()` for this topic.
Since Civetweb is embeddable, such a solution would be unacceptable.

> But beside upper/lower case, I think there is no other issue here.
> I think the server should drop all short names - using short names in the server seems completely weird to me.

Yes, I also think so.

**Comment by bel2125** [comment]
> Case sensitive restriction would be OK, because current Windows preserves case of filenames.
Though, US-ASCII characters are used for special files of Civetweb such as index.htm.
If you change the case rule from now, Index.htm is altered to a normal file on Windows. This might create confusion.

There are three different levels:

0. My preferred solution would be to have Linux and Windows equally case sensitive.
This is also the intended way
https://www.w3.org/TR/WD-html40-970708/htmlweb.html
Short names are completely disabled.

1. Since this will raise some compatibility problems with `Index.html` and 'index.html', 'xy.cgi' and 'XY.CGI' ..., one could do the name comparison case insensitive - although this will only work reliable for ASCII letters, for others it might or might not, depending on the letter and the system locale.
Short names are still disabled

2. The last option is to not check anything regarding cases and short names, like it was before. This allows to use short names and is thus fully compatible, but might cause the reported problems with patterns. A deprecated option, but the only one to ensure full compatibility.

The only idea to have a configuration value to set the behavior. I tend to recommend the first option, set the second as default and keep the third as deprecated in case someone uses short names in URLs for whatever reason.

**Comment by xtne6f** [comment]
The options sounds good.
(I think the third option is not needed. It's not worth the implementation cost.)

If you compare `char*` strings, almost all comparisons should not depend on the system locale.
(so, it may be better that `static int lowercase(const char *s)` converts only [A-Z] to [a-z].)
Because Civetweb assumes that almost all the `char*`s are UTF-8.

**Comment by bel2125** [comment]
CivetWeb indeed uses UTF-8 wherever possible. However, Windows does not understand UTF-8, but only code page specific `char` or UTF-16 as `wchar_t`. At this point in the code, a `wchar_t` as UTF-16 and `towlower` must be used (Windows specific).

**Comment by bel2125** [comment]
It is possible to add an option "uri_case_sensitive" for both, Windows and Linux. It has to be implemented differently for these two systems, but it would be more consistent to implement it for both.
The default would be: Linux is case sensitive, Windows is not - just like it was before.

However, this is an enhancement and I don't want to track it with this issue.

I think the original issue is already solved in the current version.

**Comment by xtne6f** [comment]
Thank you, I tested the current master. The issue has been solved.
I will close it.
