### ISSUE TITLE
upload example won't work

### ISSUE THREAD

**Issue by Cardinal-DeepSea-Blues** [civetweb/civetweb#302]
I built upload example on win32 platform,then tested it in the browser(ie, chrome),it doesnt save anything to the temp path.I saw deprecated warning at the function declaration,is it because it's no longer use and the example is outdated?

**Comment by Cardinal-DeepSea-Blues** [comment]
My Bad....didnt see the declaration of drop maintained..

**Comment by bel2125** [comment]
The upload example and the `mg_upload` function in general are superseded by a much more powerful form handler. An example how to use this is in the C embedding example:

https://github.com/civetweb/civetweb/blob/master/examples/embedded_c/embedded_c.c#L242

The (old) upload example will remain here for reference until the version 1.8 release (at least).
