### ISSUE TITLE
WebSocket timeout (ping/pong)

### ISSUE THREAD

**Issue by luckycharms** [civetweb/civetweb#320]
I have been using civetweb for our project at work and i have been pleased with everything it offered so far. Unfortunetly, i have recently been challenged with frustrating server side websocket disconnect which triggers ".onclose" event from our websocket client in JavaScript. 

**After some time playing with the examples provided, i discovered that** : 

-->WEBSOCKET_OPCODE_PING = 0x9
-->WEBSOCKET_OPCODE_PONG = 0xa

With the example provided (ws_server) : 
`mg_websocket_write(...,` WEBSOCKET_OPCODE_PING, NULL, 0); ` line 94

`webSocketDataHandler(..., flags, ..., ..., ...)`
{
    -> flags == 0x8A (should it be equal to 0x90?)
    
	In the example we do 
	if (flags & 0x80) -> which is true
	{
		flags &= 0x7f -> which is fine leaving only (0xA)
		switch (flags)
		{
			// This is where it does not work for me.
			// In the example it says something like : 
			case WEBSOCKET_OPCODE_PING: -> (0x9) (OK, but not the same value, so no PONG here!)
			{
				mg_websocket_write(..., WEBSOCKET_OPCODE_PONG, data, datalen); ` line 223
			}
			case WEBSOCKET_OPCODE_PONG: -> (0xA) (PING EQUALS to PONG, ok?, so i should respond?)
			{
				// Here it says : /* received PONG to our PING, no action */ line 226
				**// If no action is taken here, websocket is closed after 10 to 15 seconds top! 
				// But if we do :**  
				mg_websocket_write(..., WEBSOCKET_OPCODE_PONG, data, datalen); `
				// connection lives forever...
			}
		}
	}
}

Is this intented this way, or im a not using this library correctly here? The example provided does indeed have this bug when we "disable updates" in the browser, the websocket closes 10 seconds later. Which leads me to believe it is intended, but i could be wrong. Any answer would be appreciated.

**Comment by bel2125** [comment]
I'm not exactly sure what you do in your example. What is the browser side (javascript) code?

How did you configure `request_timeout_ms` and `websocket_timeout_ms`?

**Comment by luckycharms** [comment]
Despite what i discovered about the WEBSOCKET_OPCODE_PING opcode being a PONG instead of a PING request in "webSocketDataHandler(...)" function handler, i may have found something interesting in the civetweb.c code. 

In function pull(...) line [ 4025 ] a SSL_get_error(...) is requested on SSL connection which sometimes returns the error 2 described as "SSL_read() failed, error 2" in debug mode. I thought at first that this was a legitimate error that should be dealt as such with a "return -1" in pull(...), but i was somewhat wrong... This error seems to occur periodically and when ignored ( force -> err = EAGAIN ) , connection is not getting closed and furter SSL_read(...) in do ... while() can do their thing. Any info on this (other) issue would be appreciate, because i don't know how this effects other aspect of Civetweb.

*** Consecutive SSL_read(...) will also return other ( error = 2 ), but will proceed normaly after some tries... *** 

Can this be related to OpenSSL changes in 1.0.2h regarding SSL_get_error (...) error 2 which says somehow that further tries should be done upon this "error"...?!

https://www.openssl.org/docs/manmaster/ssl/SSL_get_error.html
SSL_ERROR_WANT_READ / SSL_ERROR_WANT_WRITE

Thanks!

**Comment by bel2125** [comment]
I don't think that PING and PONG are exchanged:

From https://tools.ietf.org/html/rfc6455

    The following values are defined.
      *  %x0 denotes a continuation frame
      *  %x1 denotes a text frame
      *  %x2 denotes a binary frame
      *  %x3-7 are reserved for further non-control frames
      *  %x8 denotes a connection close
      *  %x9 denotes a ping
      *  %xA denotes a pong
      *  %xB-F are reserved for further control frames

From https://github.com/civetweb/civetweb/blob/master/include/civetweb.h
```C
/* Opcodes, from http://tools.ietf.org/html/rfc6455 */
enum {
	WEBSOCKET_OPCODE_CONTINUATION = 0x0,
	WEBSOCKET_OPCODE_TEXT = 0x1,
	WEBSOCKET_OPCODE_BINARY = 0x2,
	WEBSOCKET_OPCODE_CONNECTION_CLOSE = 0x8,
	WEBSOCKET_OPCODE_PING = 0x9,
	WEBSOCKET_OPCODE_PONG = 0xa
};
```

**Comment by bel2125** [comment]
According to https://www.openssl.org/docs/manmaster/ssl/SSL_get_error.html, one should indeed retry the call if it fails with this error

> The operation did not complete; the same TLS/SSL I/O function should be called again later.
> ...
> There is no fixed upper limit for the number of iterations that may be necessary until progress becomes visible at application protocol level.

This does not make it easy to find a way to handle this properly. Should there be a `sleep()` call in between two SSL_read/write calls? And when should one stop trying? These topics probably need some experiments. However, I currently cannot reproduce it.

Did you try to use `ws` instead of `wss`? Did you find any issues there?

**Comment by luckycharms** [comment]
Thank you for looking further on the issue! I did not used the "ws" scheme because i wanted to reproduce the setup of our project with the same configuration options ("wss" with self-signed-certificate). Right now, your suggestion might be the solution to the problem... In our case, no sleep() call were added, instead error is ignored and pull(...) loop can proceed without failing (returning -1). If a change is made or is related to self-signed certificate i would like to hear. 

Thanks.

**Comment by mewalig** [comment]
can you send / post the change you made? I would like to see if it might somehow be an issue that is also related to this one: https://github.com/civetweb/civetweb/issues/237

**Comment by bel2125** [comment]
My problem is, I'm not able to reproduce the problem. Maybe you could try to replace the existing functions in `civetweb.c` with following code:

```C
static int
push(struct mg_context *ctx,
     FILE *fp,
     SOCKET sock,
     SSL *ssl,
     const char *buf,
     int len,
     double timeout)
{
	struct timespec start, now;
	int n, err;

#ifdef _WIN32
	typedef int len_t;
#else
	typedef size_t len_t;
#endif

	if (timeout > 0) {
		memset(&start, 0, sizeof(start));
		memset(&now, 0, sizeof(now));
		clock_gettime(CLOCK_MONOTONIC, &start);
	}

	if (ctx == NULL) {
		return -1;
	}

#ifdef NO_SSL
	if (ssl) {
		return -1;
	}
#endif

	do {

#ifndef NO_SSL
		if (ssl != NULL) {
			n = SSL_write(ssl, buf, len);
			if (n <= 0) {
				err = SSL_get_error(ssl, n);
				if ((err == 5 /* SSL_ERROR_SYSCALL */) && (n == -1)) {
					err = ERRNO;
				} else if ((err == 2 /* SSL_ERROR_WANT_READ */)
				           || (err == 3 /* SSL_ERROR_WANT_READ */)) {
					n = 0;
				} else {
					DEBUG_TRACE("SSL_write() failed, error %d", err);
					return -1;
				}
			} else {
				err = 0;
			}
		} else
#endif
		    if (fp != NULL) {
			n = (int)fwrite(buf, 1, (size_t)len, fp);
			if (ferror(fp)) {
				n = -1;
				err = ERRNO;
			} else {
				err = 0;
			}
		} else {
			n = (int)send(sock, buf, (len_t)len, MSG_NOSIGNAL);
			err = (n < 0) ? ERRNO : 0;
			if (n == 0) {
				/* shutdown of the socket at client side */
				return -1;
			}
		}

		if (ctx->stop_flag) {
			return -1;
		}

		if ((n > 0) || (n == 0 && len == 0)) {
			/* some data has been read, or no data was requested */
			return n;
		}
		if (n < 0) {
			/* socket error - check errno */
			DEBUG_TRACE("send() failed, error %d", err);

			/* TODO: error handling depending on the error code.
			 * These codes are different between Windows and Linux.
			 */
			return -1;
		}

		/* This code is not reached in the moment.
		 * ==> Fix the TODOs above first. */

		if (timeout > 0) {
			clock_gettime(CLOCK_MONOTONIC, &now);
		}

	} while ((timeout <= 0) || (mg_difftimespec(&now, &start) <= timeout));

	(void)err; /* Avoid unused warning if NO_SSL is set and DEBUG_TRACE is not
	              used */

	return -1;
}
```

and

```C
static int
pull(FILE *fp, struct mg_connection *conn, char *buf, int len, double timeout)
{
	int nread, err;
	struct timespec start, now;

#ifdef _WIN32
	typedef int len_t;
#else
	typedef size_t len_t;
#endif

	if (timeout > 0) {
		memset(&start, 0, sizeof(start));
		memset(&now, 0, sizeof(now));
		clock_gettime(CLOCK_MONOTONIC, &start);
	}

	do {
		if (fp != NULL) {
#if !defined(_WIN32_WCE)
			/* Use read() instead of fread(), because if we're reading from the
			 * CGI pipe, fread() may block until IO buffer is filled up. We
			 * cannot afford to block and must pass all read bytes immediately
			 * to the client. */
			nread = (int)read(fileno(fp), buf, (size_t)len);
#else
			/* WinCE does not support CGI pipes */
			nread = (int)fread(buf, 1, (size_t)len, fp);
#endif
			err = (nread < 0) ? ERRNO : 0;

#ifndef NO_SSL
		} else if (conn->ssl != NULL) {
			nread = SSL_read(conn->ssl, buf, len);
			if (nread <= 0) {
				err = SSL_get_error(conn->ssl, nread);
				if ((err == 5 /* SSL_ERROR_SYSCALL */) && (nread == -1)) {
					err = ERRNO;
				} else if ((err == 2 /* SSL_ERROR_WANT_READ */)
				           || (err == 3 /* SSL_ERROR_WANT_READ */)) {
					nread = 0;
				} else {
					DEBUG_TRACE("SSL_read() failed, error %d", err);
					return -1;
				}
			} else {
				err = 0;
			}
#endif

		} else {
			nread = (int)recv(conn->client.sock, buf, (len_t)len, 0);
			err = (nread < 0) ? ERRNO : 0;
			if (nread == 0) {
				/* shutdown of the socket at client side */
				return -1;
			}
		}

		if (conn->ctx->stop_flag) {
			return -1;
		}

		if ((nread > 0) || (nread == 0 && len == 0)) {
			/* some data has been read, or no data was requested */
			return nread;
		}

		if (nread < 0) {
/* socket error - check errno */
#ifdef _WIN32
			if (err == WSAEWOULDBLOCK) {
				/* standard case if called from close_socket_gracefully */
				return -1;
			} else if (err == WSAETIMEDOUT) {
				/* timeout is handled by the while loop  */
			} else {
				DEBUG_TRACE("recv() failed, error %d", err);
				return -1;
			}
#else
			/* TODO: POSIX returns either EAGAIN or EWOULDBLOCK in both cases,
			 * if the timeout is reached and if the socket was set to non-
			 * blocking in close_socket_gracefully, so we can not distinguish
			 * here. We have to wait for the timeout in both cases for now.
			 */
			if (err == EAGAIN || err == EWOULDBLOCK || err == EINTR) {
				/* EAGAIN/EWOULDBLOCK:
				 * standard case if called from close_socket_gracefully
				 * => should return -1 */
				/* or timeout occured
				 * => the code must stay in the while loop */

				/* EINTR can be generated on a socket with a timeout set even
				 * when SA_RESTART is effective for all relevant signals
				 * (see signal(7)).
				 * => stay in the while loop */
			} else {
				DEBUG_TRACE("recv() failed, error %d", err);
				return -1;
			}
#endif
		}
		if (timeout > 0) {
			clock_gettime(CLOCK_MONOTONIC, &now);
		}
	} while ((timeout <= 0) || (mg_difftimespec(&now, &start) <= timeout));

	/* Timeout occured, but no data available. */
	return -1;
}
```

**Comment by luckycharms** [comment]
I changed the source code and compiled another lib with the example i was using. So far so good, the connection seems to hold and i will be leaving that browser up all weed end just to see how far it can go. The changes provided seems to be doing what i wanted, i will probably change the lib in our project and provide feedback if all goes down again ;) !

#237 : I don't know about this issue, but the code provided did changed the unwanted behavior i was experiencing, so feel free to try this fix.

**Comment by bel2125** [comment]
Did you have time to test during the last week?
If everything works, probably the issue can be closed.

**Comment by luckycharms** [comment]
Yes i would close this issue, i am satisfied with the current results.Date: Thu, 7 Jul 2016 13:55:30 -0700
