### ISSUE TITLE
function for reading bytes in send buffer, or just a way to access raw sock fd from mg_connection

### ISSUE THREAD

**Issue by mpekar** [civetweb/civetweb#321]
We use civetweb to dish out motion jpegs and have added this small utility function to allow us to detect when to throttle down the framerate on low bitrate connections:

```
int socket_send_buffer_bytes_filled(struct mg_connection *conn);

#include <sys/ioctl.h>
#include <linux/sockios.h>

int socket_send_buffer_bytes_filled(struct mg_connection *conn) {
    int send_buffer_bytes_used = 0;

    int res = ioctl(conn->client.sock, SIOCOUTQ, &send_buffer_bytes_used);

    if(res < 0) {
        return -1;
    }

    return send_buffer_bytes_used;
}

```

This may be too obscure of a thing to add to the codebase.  An alternative would be just a utility method to grab the fd from mg_connection.client.sock.  I figured I'd submit the idea and see if it had any value to other users.

**Comment by bel2125** [comment]
I found this option is Linux specific - Windows does not have it, and probably other OS don't have it either. So probably a function to get the OS handle would be more suitable.

**Comment by bel2125** [comment]
Sorry if I did not respond clearly before. It can not be implemented in an OS independent way (as `socket_send_buffer_bytes_filled`). But adding a function to get the OS handle in `civetweb.h` breaks the abstraction, and if someone is using the socket handle in a wrong way, it might break the web server. What the "wrong way" is will depend on the web server version and may change without explicit notification, and I think is unacceptable for a public API. The SIOCOUTQ ioctl will work with the socket file handle, but others will not. 
I did not find a really good solution for this yet - a better solution than "you apply a patch to your own copy".

**Comment by mpekar** [comment]
We have an internal patch for our use, and I agree it's hard to figure how such a feature would be exposed.  I figured I'd go ahead and close the issue so it wasn't making your list any longer than necessary.

**Comment by bel2125** [comment]
Ok, thank you.
In case you do have any idea how this feature could be added in an operating system independent way, that does not expose internals that might lead to users breaking the code (in a way neither they, nor we, the maintainers, can find errors anymore), I would still be willing to merge this into the code base.
