### ISSUE TITLE
Error build  examples/embedded_cpp on linux

### ISSUE THREAD

**Issue by tranhuanltv** [civetweb/civetweb#323]
_snprintf & MessageBeep function only exists on Windows, so we need port these functions to linux

**Comment by bel2125** [comment]
There is more Windows specific stuff in this example, for example the path `D:\\somewhere\\%s\\%s` will only work on Windows as well. Anyway, the folder "somewhere" probably does not exist - so `fopen_recursive` should create the missing folders first - but that's just a dummy in `embedded_cpp.cpp`. It's meant as an example, so you wont use it 1:1 in production anyway.

I think MessageBeep should be removed - it does not make much sense if a web server beeps if it receives a file. In case you need a Linux equivalent for something: call http://linux.die.net/man/1/beep or use ioctl KIOCSOUND.

```
_snprintf(buf, sizeof(buf), "D:\\somewhere\\%s\\%s", req_info->remote_user, req_info->local_uri);
```
would be
```
snprintf(buf, sizeof(buf), "~/somewhere/%s/%s", req_info->remote_user, req_info->local_uri);
```
and `fopen(..., "wb")` would be `fopen(..., "w")`.

**Comment by bel2125** [comment]
I actually already fixed the example several days ago, but forgot to state it here.
