### ISSUE TITLE
Bug: mg_calloc_ex if MEMORY_DEBUGGING enabled

### ISSUE THREAD

**Issue by hcp24** [civetweb/civetweb#328]
file: mg_calloc_civetweb.c
function:
static void *
mg_calloc_ex(size_t count, size_t size, const char *file, unsigned line)
{
    void *data = mg_malloc_ex(size * count, file, line);
    if (data) {
        memset(data, 0, size);  // error
        // change to
        memset(data, 0, count*size);  
    }
    return data;
}

Is it realy true  MAX_WORKER_THREADS (64*1024) ? it needs 1,5MB memory for timers

**Comment by bel2125** [comment]
I fixed the memset to the proper size.

> Is it realy true MAX_WORKER_THREADS (64*1024) ?

This is a limit to the number of connections the server have at the same time. In a test on a ~5 year old standard office PC in 2014 I could reach about 30000 connections (see this issue: https://github.com/civetweb/civetweb/issues/50).  With issue https://github.com/civetweb/civetweb/issues/50 the definition of MAX_WORKER_THREADS has been set from 1024 to the current value (64*1024). But this is just a default value you might overwrite.

> it needs 1,5MB memory for timers 

I already planned to do some optimization for timers (already more than a year ago), but with a very low priority.
