### ISSUE TITLE
Cross site scripting vulnerability

### ISSUE THREAD

**Issue by ken-reister** [civetweb/civetweb#329]
A scan by a tool called Nessus reported this.  In civetweb.c:11839-11844 (or if your line numbers don't match up - in function process_new_connection in switch (uri_type) default:)
Existing line:  
					mg_snprintf(conn,
					            NULL, /* No truncation check for ebuf */
					            ebuf,
					            sizeof(ebuf),
					            "Invalid URI: [%s]",
					            ri->request_uri);
Change to:
					mg_snprintf(conn,
					            NULL, /* No truncation check for ebuf */
					            ebuf,
					            sizeof(ebuf),
						    "Invalid URI");

The bug was basically that the "request_uri" variable was not being sanitized prior to being returned.  The way to test it was as follows:
telnet ip port
get <script>test</script> HTTP/1.1<carriage return><carriage return>

You could probably have two versions if you wanted to #ifdef _DEBUG or something similar.

**Comment by bel2125** [comment]
The complaint is, a bad URL gets sent back in the body data of an error message?
```
					mg_snprintf(conn,
					            NULL, /* No truncation check for ebuf */
					            ebuf,
					            sizeof(ebuf),
					            "Invalid URI: [%s]",
					            ri->request_uri);
					send_http_error(conn, 400, "%s", ebuf);
```

**Comment by bel2125** [comment]
Thinking about this again, it *would* be a XSS vulnerability if the returned error page would be "Content-type: text/html", but in the [default](https://www.w3.org/Protocols/rfc1341/4_Content-Type.html) of "Content-type: text/plain; charset=us-ascii" (or application/octet-stream) there are no scripts.
So I think it is a false positive.

But in general there are several error messages that should not be sent to the client - they are mostly useless to anyone but the system administrator and probably tell the user more than he has to know about the server. Probably an option "short error responses" / "full error response" (for setup/debug) would be useful - or maybe only a fixed client IP of the admin should get the full messages.

**Comment by ken-reister** [comment]
Yeah, sorry about that...didn't notice that it stripped out the code I added after the "get"
`telnet ip port
get HTTP/1.1 <script>test</script>`

**Comment by ken-reister** [comment]
And I agree with the "false positive" assessment, however I can't say that to the end user.  I've already modified our current version of the code, but want to submit the fix back so we will be able to upgrade without having to apply said fix every time.  I suppose that an alternative would be to strip out any script tags (and leave the contents behind).

**Comment by bel2125** [comment]
> I suppose that an alternative would be to strip out any script tags

The alternative would be probably to change `<` to `&lt;` and `>` to `&gt;`, but this would be the solution only if the reply would be HTML and not just plain text.

Another solution would be to check for characters in URIs that are neither reserved nor unreserved according to [RFC 3986](https://www.ietf.org/rfc/rfc3986.txt) - basically URIs should only contain `:/?#[]@!$&'()*+,;=` , `%`, `A`-`Z`, `a`-`z`, `0`-`9` and `-._~`. If any other character is found, the server could return a `400 Bad Request` with some general message it found a non-URL-encoded character.

I'm going to check this idea next week.

**Comment by xxyyx** [comment]
Hey all, looking over this server for my project and saw this thread.  

Generally the recommendation is to to filter input(exclusively allow alphanumeric characters) and encode the output. As to your URI filtering idea, you should check this out http://www.jsfuck.com. Totally possible to run javsascript with only those chars.


Above you mentioned setting the Content-Type HTTP header to "text/plain" (or something else) in the response, as opposed to "text/html", in order to tell the browser to not render the page as HTML. In theory, XSS should not be possible even if user input gets directly reflected in the response. However, specific browsers (IE 6/7/8, Safari on iOS and maybe other browsers) still try to parse the response regardless of the Content-Type header, and will render it if they identify the body of the response as HTML. As a consequence, you can still get an XSS affecting those vulnerable browsers, if user input gets directly reflected in the response. 


The best fix is to output-encode the data before reflecting it in the page/data. Also, the X-Content-Type-Options: nosniff header can be used to tell browsers to not try to detect the content type, but it only works on IE8+ (leaving IE 6 / 7 users vulnerable).

:)

**Comment by bel2125** [comment]
The content does not start with `<html>` or any other HTML typical field, so I would wonder if a stray `<script>something</script>` in the middle of a text would make the browser think it is a HTML document. As far as I know this content detection is mainly used to detect the HTML version. I could test it with IE8 - I don't know if I can get older versions somewhere. However, if someone is still using IE6, I think all hope is lost.

Regarding my comment above: 
I meant I could change CivetWeb to return an error `400 Bad Request` whenever the URI contains a `<` character (without reflecting the full URI but only "URI contains invalid character" as additional information).

**Comment by xxyyx** [comment]
Agree that old versions of IE are not worth it... just wanted to let you know. 

I really like the 400 bad request solution!

**Comment by ken-reister** [comment]
Do this and add a normal printf to a civetweb log file with the actual unfiltered content for debugging.  

Even better - add a callback function for logging debug output so the implementing program can use it's logging method.
> I meant I could change CivetWeb to return an error 400 Bad Request whenever the URI contains a character (without reflecting the full URI but only "URI contains invalid character" as additional information).

**Comment by bel2125** [comment]
There are already logging functions:
Here, you could use the `http_error` callback (called in `send_http_error`).
For other error messages, use the `log_message` callback (called in `mg_cry`).

**Comment by ken-reister** [comment]
Thanks bel...I'll test it as soon as I can.

**Comment by ken-reister** [comment]
I looked at the code change you made and it looks good.  I really can't spare the time to test this and I don't want to hold up this change on my account.
