### ISSUE TITLE
Please document thread-per-client model used

### ISSUE THREAD

**Issue by rhulha** [civetweb/civetweb#334]
Mongoose documents its thread-per-client model like this:

"Single-threaded, asynchronous, non-blocking core with simple event-based API"

I am missing a similar statement in the Civetweb Readme.md.

Please add a short statement about the thread-per-client model used

**Comment by bel2125** [comment]
I am not exactly sure what  you want to do with a statement of the core itself. It is probably more important what you are allowed to do in which callback function - and "non-blocking" is a somewhat ambiguous term anyway (... "non blocking", "lock free", "wait free", ... and real-time/driver programmers mean something different by this terms as other application programmers ... it will not "block" in a sense of waiting for a network message but it will "block" while waiting on the disk ...).

But anyway:
The Civetweb core itself is multi-threaded. When starting the server (mg_start) the server will create it's own master thread and a set of worker threads (thread farm). You can block in callbacks (on disk IO and also on network IO), but need to respond in a reasonable time (network timeouts - typically ~10 seconds would be recommended - longer is possible but depends on the client).

**Comment by bel2125** [comment]
If you could post some more specific questions what you want to know, I could certainly find a more useful statement to add to the documentation.
(After being on vacation for ~10 days).

**Comment by rhulha** [comment]
Basically I was comparing Mongoose to Civetweb and I got the impression that Mongoose was "modern" single threaded asynchronous like Node.js and Civetweb was "stuck" using the one thread-per-client model. I have later found this statement in the UserManual.md: "Civetweb handles each incoming connection in a separate thread. " confirming my suspicion. It would have been nice to get that important information on the "Frontpage", e.g. the Readme.md.

**Comment by bel2125** [comment]
One thread per request or connection is the most simple and still effective approach. Multi-Threaded or even Multi-Process is still the way to create dynamic websites using Apache (with [more than 50% market share](https://w3techs.com/technologies/details/ws-apache/2/all)). It's not my intention to compete with nginx in the discipline of serving millions of static files a second, and I also want to avoid deeply operating system specific optimizations (Linux [sendfile](http://man7.org/linux/man-pages/man2/sendfile.2.html) is ok, kqueue/IOCP is too specific). Civetweb will run on embedded operating systems that do not support these very specific mechanisms. A simple operating system thread on a modern operating system is also quite cheap - a handle and some kB physical memory (not to be confused with the virtual address space consumption - I mean plain OS threads pthread/CRT-threads used in Civetweb, not Java/C# threads which are much more expensive). So I do not at all consider this as "stuck" in "old" ideas, but as a reasonable design choice. If you still really want to push it to the limits, you can also use 30000 threads to handle 30000 connections (see https://github.com/civetweb/civetweb/issues/50) on a simple office PC from 2010, probably more with a better hardware. 

I also found [this answer](http://stackoverflow.com/questions/8227548/whats-the-advantage-of-one-thread-per-connection-in-an-http-server) from Nov 22 '11 explaining the advantages quite well.
