### ISSUE TITLE
segmentation fault when mg_close with wss

### ISSUE THREAD

**Issue by motomuman** [civetweb/civetweb#336]
When I call mg_close_connection for not closed wss connection in wss client.
This failed with segmentation fault.

I think the reason is below.
mg_close_connection call close_connection and in close_connection.
close_connection call SSL_shutdown and SSL_free.

But If wss connection is not closed yet.
worker thread is waiting at SSL_read.
websocket_client_thread->read_websocket ->pull ->SSL_read
So worker thread crush.

Motomu Utsumi

**Comment by bel2125** [comment]
Maybe you would have to send a websocket close message first.
I'll have a look, but only in two weeks.
