### ISSUE TITLE
Bugfix or better more correctness in civetweb.c get_request_handler

### ISSUE THREAD

**Issue by hcp24** [civetweb/civetweb#337]
As i played with the authentication handlers i got following problem:
(I using c++ so i have to translate to c).

I put two auth handlers to the engine like this

first : **mg_set_auth_handler**( context, _"/secure/"_, authHandler, h1);
second: **mg_set_auth_handler**( context, _"/sercure/more_secure/"_, authHandler, h2);

If I call _"http://server/secure/more_secure/somthing"_ only the first auth handler _"/sercure/"_ was called but I expected the second one _"/secure/more_secure/"_ will be called.
I did not tried any other sequences like 
first: **mg_set_auth_handler**(  context, _"/sercure/more_secure/"_, authHandler, h2);
second: **mg_set_auth_handler**( context, _"/sercure/"_, authHandler, h1);
It works (conn->ctx->handlers is an unsorted single linked list).
The same is happens on all other handlers. With a little changes in the code it will be more robust
against stupid developers like me.
The sequence of handler insertion should never be decided. 
If I decode sequences in my mind I will do it from largest to smallest.

I have two solutions:
1. sort the conn->ctx->handlers on insert and use uri_len from largest to smallest.
   Then it will always match the nerest uri.  I prefer this variant. 
   
   Put this code at the end of mg_set_handler_type it works for me (I tested it a little bit but not extensive). 

```
#if 1 /* enable/disable work around */
  if (ctx->handlers != NULL) {
    lastref = &(ctx->handlers );
    struct mg_handler_info *rh1;
    /* check for insert */
    for (rh1 = ctx->handlers; rh1 != NULL; rh1 = rh1->next) {
      if (rh1->uri_len > tmp_rh->uri_len) {
        lastref = &(rh1->next);
      }
      else {
        /* position found */
        tmp_rh->next = rh1;
        break;
      }
    }
  }
#endif
/* old code */
  *lastref = tmp_rh;
  mg_unlock_context(ctx);

```
1. change get_request_handler loop (it's easier ?? but cost more time)

```
       /* next try for a partial match, we will accept uri/something */
        { /* create a block so c variables can be placed here */ 
          int found_len = 0; /* PF added initialize with 0 */
          for (tmp_rh = conn->ctx->handlers; tmp_rh != NULL; tmp_rh = tmp_rh->next) {
            if (tmp_rh->handler_type == handler_type) {
              /*PF use only if tmp_rh->uri_len > found_len */
              if ( tmp_rh->uri_len < urilen 
                   && tmp_rh->uri_len > found_len /* PF changes */
                   && uri[tmp_rh->uri_len] == '/' && memcmp(tmp_rh->uri, uri, tmp_rh->uri_len) == 0) {
                found_len = tmp_rh->uri_len;  /* PF set new len */
                if (handler_type == WEBSOCKET_HANDLER) {
                  *connect_handler = tmp_rh->connect_handler;
                  *ready_handler = tmp_rh->ready_handler;
                  *data_handler = tmp_rh->data_handler;
                  *close_handler = tmp_rh->close_handler;
                } else if (handler_type == REQUEST_HANDLER) {
                  *handler = tmp_rh->handler;
                } else { /* AUTH_HANDLER */
                  *auth_handler = tmp_rh->auth_handler;
                }
                *cbdata = tmp_rh->cbdata; /* some found */
              }
            }
          }
          if (*cbdata && (found_len > 0)) {
            mg_unlock_context(conn->ctx);
            return 1; /* found */
          }
        } /* end block */

```

Excuse my bad english I'm a stupid German. 
I hope it will be helpful.
best regards

**Comment by bel2125** [comment]
> I put two auth handlers to the engine like this
first : mg_set_auth_handler( context, "/secure/", authHandler, h1);
second: mg_set_auth_handler( context, "/sercure/more_secure/", authHandler, h2);

Please add a `$` sign at the end of the pattern.

Unfortunately this oddity of the pattern syntax often leads to problems - it's already reported several times as issue (https://github.com/civetweb/civetweb/issues/179, https://github.com/civetweb/civetweb/issues/255, https://github.com/civetweb/civetweb/issues/260) and there is a [discussion thread](https://groups.google.com/forum/#!topic/civetweb/0CAukw3LWOs) at the google group.

https://github.com/civetweb/civetweb/issues/179 is the "active" issue, all others are set to duplicate.
I postponed working on this problem until after the V1.8 release - which is now done, so #179 is now open again. The entire problem is somewhat more complicated than just the length of the pattern (as already discussed in the other issues/discussions).

**Comment by bel2125** [comment]
duplicate to #179

**Comment by bel2125** [comment]
The documentation of patterns has been modified to minimize confusion. The rest of this issue is duplicate to #179 (other duplicates #255, #260, #337, #376). I'm closing all duplicates except the original one (#179).
