### ISSUE TITLE
Bugfix timer.inl in timer_add

### ISSUE THREAD

**Issue by hcp24** [civetweb/civetweb#340]
comparisation 	
`if (ctx->timers->timers[u].time < next_time) {`

should be
`if (ctx->timers->timers[u].time > next_time) {`

result is:
if you put 2 or more functions to the timer list, it will only called one.

second one:
next_time should never < current time 
if  is_relative = 0 and next_time = 0 and period = 1 then the timer function will called until next_time >= now without pause (now it was > 29000). 
Show in my Pull request.

**Comment by bel2125** [comment]
You do not have a pull request for this, do you?
If it's only the `<` replaced by `>`, I can do this without a pull request as well.

**Comment by hcp24** [comment]
I will create a pull request

**Comment by bel2125** [comment]
Solved with pull request #344
