### ISSUE TITLE
The use of sendfile() should be made configurable because of broken sendfile implementations

### ISSUE THREAD

**Issue by nfrmtkr** [civetweb/civetweb#346]
With civetweb 1.8 the use of sendfile() has been introduced. This results in reading corrupted files in case the file is changed and read from a network share or from a folder hosted by a VM server. 
We currently solve this issue by removing the whole code block starting at line 6400 marked with #if defined(__linux__)  ... #endif.

Other webservers report issued regarding sendfile too and provide the possibility to switch of using sendfile. For instance Apache: https://httpd.apache.org/docs/2.4/mod/core.html#enablesendfile

What about adding a new configuration parameter (e.g. use_sendfile) that allows to switch on/off the use of sendfile?

**Comment by bel2125** [comment]
I do not really want to have a USE_SENDFILE define, since USE_* is for features only, and using sendfile is not a feature but an implementation detail. From the systematic naming it could be HAVE_SENDFILE and this must be set to 1 as a default for Linux. So it could be a define that needs to be set to avoid to use sendfile in Linux.

But first, please tell me more about the actual problem. 
Is this a bug in Linux? Which Linux Distribution? Which version? Is it a Kernel Bug?
Is this bug reported as a Linux issue and what is the state of the bug?
Is it possible to detect at runtime if sendfile should be used or if it has this bug?

**Comment by nfrmtkr** [comment]
We get problems with sendfile using VirtualBox 4.X - 5.X (5.0.26) accessing files hosted by virtualbox shared folders (vboxfs). OS used: MacOS 10.10 / Ubuntu 14.04 X64. 

I have no exact sendfile error reports, but if you google for "sendfile bug" you get many hits from different products that report issues about it. See the link in my first post and here is another interesting one: http://www.proftpd.org/docs/howto/Sendfile.html. Most of the applications that use sendefile allow to disable it.

I don't care about the name of the configuration parameter. But I would prefer to configure it instead disabling it during compile time. The sendfle function is a good performance improvement and in most cases it works. The use of VM or network share is most probably a development enviornment in those environments the user can switch sendfile off. In production environments the file usually a stored on local disc and in this case sendfile can be used and performance improves.

**Comment by bel2125** [comment]
I indeed found several articles, including [a blog](https://blog.phusion.nl/2015/06/04/the-brokenness-of-the-sendfile-system-call/) from 2015 stating sendfile is still broken. And several HTTP and FTP servers do have config options to disable the use of this call.

So it seems we need an option as well.

**Comment by bel2125** [comment]
I added the `allow_sendfile_call` configuration option.
I still need to test it - please check it as well.

**Comment by nfrmtkr** [comment]
I've checked your enhancement regarding "allow_sendfile_call. This will work. 
You may mention in documentation, that this option is available on Linux, only. 
Thank you very much!

**Comment by bel2125** [comment]
> You may mention in documentation, that this option is available on Linux, only. 

I already did: https://github.com/civetweb/civetweb/blob/master/docs/UserManual.md

> This option can be used to enable or disable the use of the Linux sendfile system call. It is only available for Linux systems and only affecting HTTP (not HTTPS) connections if throttle is not enabled. While using the sendfile call will lead to a performance boost for HTTP connections, this call may be broken for some file systems and some operating system versions.
