### ISSUE TITLE
Using "\r\n" instead of "\n" in POST request causes http 400 bad request

### ISSUE THREAD

**Issue by beefcheese** [civetweb/civetweb#348]
Using the embedded_c example, the following command results in a good request:

`echo -e 'POST /example HTTP/1.1\nHost: 192.168.1.7\nContent Length: 231\nContent-Type: application/json\n\n{"city":"","country_code":"","country_name":"","down":2764,"down_avg":221.954544067383,"ip":"192.168.1.6","latitude":0,"longitude":0,"metro_code":0,"region_code":"","region_name":"","time_zone":"","up":0,"up_avg":0.0,"zip_code":""}' | nc 192.168.1.7 8884`

> HTTP/1.1 200 OK
> Content-Type: text/html
> Connection: close
> 
> etc...

while the following request result in an http 400 bad request response:

`echo -e 'POST /example HTTP/1.1\r\nHost: 192.168.1.7\r\nContent Length: 231\r\nContent-Type: application/json\r\n\r\n{"city":"","country_code":"","country_name":"","down":2764,"down_avg":221.954544067383,"ip":"192.168.1.6","latitude":0,"longitude":0,"metro_code":0,"region_code":"","region_name":"","time_zone":"","up":0,"up_avg":0.0,"zip_code":""}' | nc 192.168.1.7 8884`

> HTTP/1.1 400 Bad Request
> Cache-Control: no-cache, no-store, must-revalidate, private, max-age=0
> Pragma: no-cache
> Expires: 0
> Date: Sun, 21 Aug 2016 02:18:25 GMT
> Connection: close
> 
> Error 400: Bad Request
> Bad Request

The only difference being that the second request uses \r\n instead of \n

**Comment by bel2125** [comment]
This is probably again a "Windows vs Linux" problem. Windows uses \r\n line endings as a default while Linux uses only \n. Furthermore Windows uses some "text mode" where it automatically appends a \r for every \n. Do you use Windows? Then it might be you actually send `POST /example HTTP/1.1\r\r\n`... (an extra \r).

Could you provide your system information (if you call `civetweb -I`, it will print all the information I need).

**Comment by beefcheese** [comment]
`civetweb -I`

> CivetWeb V1.9
> CivetWeb V1.9 - Linux #21-Ubuntu SMP PREEMPT Sun Apr 5 01:56:02 UTC 2015 (3.18.0-20-rpi2) - armv7l
> Features: Files HTTPS CGI
> Version: 1.9
> Build: Aug 21 2016
> gcc: 5.4.0
> Data model: i:2/4/4/8, f:4/8/8, c:1/4, p:4, s:4, t:4

embedded_c was running on a raspberry pi. I first noticed the problem while writing a windows application using windows sockets. Requests to an application I made using civetweb - also running on the raspberry pi - kept resulting in bad requests. I finally found out the problem was the '\r' and wrote up the bash _one liners_ in the op to prove it.

**Comment by bel2125** [comment]
> I finally found out the problem was the '\r' and wrote up the bash one liners in the op to prove it.

So, the problem is already solved?

If not:
Could you use the `echo -e 'POST /example HTTP/1.1\r\n...` command with ` > somefile.bin` instead of ` | nc 192.168.1.7 8884` to write the result in a file, and then try with `hexdump` or some hex editor to check if there is indeed only one `\r`?
Could you then try to send the file to netcat by `cat somefile.bin | nc 192.168.1.7 8884` and `192.168.1.7 8884 < somefile.bin`?

**Comment by beefcheese** [comment]
```
steve@ubuntu ~> echo -en 'POST /example HTTP/1.1\nHost: 192.168.1.7\nContent Length: 4\nContent-Type: application/json\n\ntest' | nc 192.168.1.7 8884
```

> HTTP/1.1 200 OK
> Content-Type: text/html
> Connection: close
> 
> etc...

```
steve@ubuntu ~> echo -en 'POST /example HTTP/1.1\r\nHost: 192.168.1.7\r\nContent Length: 4\r\nContent-Type: application/json\r\n\r\ntest' > test-post
steve@ubuntu ~> xxd test-post
```
```
00000000: 504f 5354 202f 6578 616d 706c 6520 4854  POST /example HT
00000010: 5450 2f31 2e31 0d0a 486f 7374 3a20 3139  TP/1.1..Host: 19
00000020: 322e 3136 382e 312e 370d 0a43 6f6e 7465  2.168.1.7..Conte
00000030: 6e74 204c 656e 6774 683a 2034 0d0a 436f  nt Length: 4..Co
00000040: 6e74 656e 742d 5479 7065 3a20 6170 706c  ntent-Type: appl
00000050: 6963 6174 696f 6e2f 6a73 6f6e 0d0a 0d0a  ication/json....
00000060: 7465 7374                                test
```
`steve@ubuntu ~> cat test-post | nc 192.168.1.7 8884`

> HTTP/1.1 400 Bad Request
> Cache-Control: no-cache, no-store, must-revalidate, private, max-age=0
> Pragma: no-cache
> Expires: 0
> Date: Sun, 21 Aug 2016 22:04:09 GMT
> Connection: close
> 
> Error 400: Bad Request
> Bad Request

**Comment by xtne6f** [comment]
I think `Content Length` is invalid (must be `Content-Length`).

**Comment by beefcheese** [comment]
Ah yes xtne6f, that does fix it. Thanks. I suppose this isn't an issue.

Still strange the difference in behavior with '\r\n' and '\n' in the examples I posted here...

**Comment by bel2125** [comment]
The difference comes from the HTTP headers being parsed differently in these two cases.
For the correct header "Content-Length", the \r\n case has the following headers:
```
Host             = 192.168.1.7
Content-Length   = 4
Content-Type     = application/json
```
the \n case has just one header
```
Host = 192.168.1.7°Content-Length: 4°Content-Type: application/json°°test
```
with the ° being the \n character.  The \n character in the header value is not considered as a separator and not detected as an error, so it's just a part or the value. Also the content is added, since it is not split by a proper separator from the HTTP header. The actual content length of the message is 0 - no content, everything is header. The request is complete enough to be processed when the connection is closed.

For the incorrect header "Content-Length", in the \r\n case
```
Host             = 192.168.1.7
Content Length   <<<======= INVALID HEADER NAME !!!
Content-Type     = application/json
```
and the \n case
```
Host = 192.168.1.7°Content Length: 4°Content-Type: application/json
```
So the space in the value is valid, the space in the header field is not.

Civetweb tries to tolerate small protocol violations, but tolerating \n without \r in the HTTP header might be somewhat too tolerant, since this causes such cryptic errors.

**Comment by bel2125** [comment]
\n without \r in the HTTP header should not be accepted, since this causes errors that are hard to find.

Since you do have a way to work now, I think this modification is not very urgent, right?
Anyway, this change would only show request errors more clearly.

**Comment by ForNeVeR** [comment]
Hello, guys. I just randomly found this page through Google, but I'd have to add here that HTTP spec [recommends](https://www.w3.org/Protocols/rfc2616/rfc2616-sec19.html#sec19.3) treating `\n` as `\r\n` while parsing the headers. But that's not a strict requirement to be standard-compliant.

Probably a good-behaving tolerant web server should parse both samples equally and generate an error for both cases from the top post.

**Comment by bel2125** [comment]
Civetweb currently accepts \n in some places, while it does not in others.
Although it might be acceptable from the spec, this leads to hard to find errors.
We should either accept it everywhere or nowhere.

Probably "everywhere" is not more work as "nowhere" - I will have a look.
Thanks for comment.

**Comment by bel2125** [comment]
I fixed this some weeks ago, but did not give feedback here yet.
It worked in my tests with any combination of \r\n or only \n - if you have the time, please test it as well.

**Comment by bel2125** [comment]
In version 1.9, \n and \r\n are accepted.
