### ISSUE TITLE
Build errors on macOS 10.12 Sierra: clock_gettime

### ISSUE THREAD

**Issue by coffeefog** [civetweb/civetweb#349]
I'm not able to build civetweb on the macOS 10.12 Sierra public beta. Apple has declared & defined clock_gettime starting in 10.12, so this code causes build errors:

[ 98%] Building C object CMakeFiles/src/lib/civetweb/civetweb.c.o
src/lib/civetweb/civetweb.c:135:5: error: conflicting types for 'clock_gettime'
int clock_gettime(int clk_id, struct timespec *t);
    ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/time.h:177:5: note: 
      previous declaration is here
int clock_gettime(clockid_t __clock_id, struct timespec *__tp);
    ^
src/lib/civetweb/civetweb.c:138:1: error: conflicting types for 'clock_gettime'
clock_gettime(int clk_id, struct timespec *t)
^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/time.h:177:5: note: 
      previous declaration is here
int clock_gettime(clockid_t __clock_id, struct timespec *__tp);
    ^
2 errors generated.
make[2]: *** [CMakeFiles/src/lib/civetweb/civetweb.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....

See similar reports in other projects:
• https://github.com/Homebrew/homebrew-x11/issues/219
• https://github.com/jordansissel/xdotool/issues/138

**Comment by bel2125** [comment]
Since I do not have a OSX 10.12 system available, I will not be able to reproduce this issue.
Is there any define to check if `clock_gettime` is available or not - some `#ifdef HAS_CLOCK_RUNTIME` or `#if (SOME_VERSION>10) || ((SOME_VERSION==10) && (SOME_SUBVERSION >= 12))`?

**Comment by kainjow** [comment]
I haven't tested this on 10.12, but I think it should work for compile time testing of 10.12. Maybe @coffeefog can test this? Note that I pulled `MAC_OS_X_VERSION_10_12` from Chromium source (from a Google search), so I'm assuming they got that value right :)

    #ifdef __APPLE__
      #include <AvailabilityMacros.h>
      #ifndef MAC_OS_X_VERSION_10_12
        #define MAC_OS_X_VERSION_10_12 101200
      #endif
    #endif
    
    #define APPLE_HAVE_CLOCK_GETTIME defined(__APPLE__) && MAC_OS_X_VERSION_MIN_REQUIRED >= MAC_OS_X_VERSION_10_12
    
    #if APPLE_HAVE_CLOCK_GETTIME
        clock_gettime(...)
    #endif

**Comment by coffeefog** [comment]
Thanks for the quick solution. I can confirm that this APPLE_HAVE_CLOCK_GETTIME define successfully determines presence of clock_gettime symbols on my 10.12 Beta Mac.

I wrapped civetweb.c's declaration & definition of clock_gettime with "#if !APPLE_HAVE_CLOCK_GETTIME / #endif"; it compiles and runs now.

**Comment by bel2125** [comment]
So this entire code section above should be added, and it will work for 10.12 and versions prior to 10.12 as well?

Or is APPLE_HAVE_CLOCK_GETTIME already defined in the Apple header as well?

**Comment by kainjow** [comment]
No, APPLE_HAVE_CLOCK_GETTIME is a custom define. Maybe you could change it to CIVETWEB_APPLE_HAVE_CLOCK_GETTIME just to limit scope. the MAC_OS_X*** macros are defined by Apple. MAC_OS_X_VERSION_10_12 is only set if you're using the 10.12 SDK, so if you're targeting an older OS X version then you need to define that to match what the SDK sets it to.

**Comment by coffeefog** [comment]
I'm trying to get this code working on 10.11; I'm not sure __APPLE__ is defined... I expect to comment again tomorrow. Cheers.

**Comment by coffeefog** [comment]
I have a few notes, but no certain next steps:
1. I was wrong before: #ifdef __ Apple __ works, and it's defined on OS X. That's fine.
2. But the code doesn't work on 10.11 because MAC_OS_X_VERSION_MIN_REQUIRED isn't defined. I think MAC_OS_X_VERSION_MIN_REQUIRED is defined by compiler via Xcode flags (which I'm not using; I've got my own CMakeLists.txt), or by adding "-D__ENVIRONMENT_MAC_OS_X_VERSION_MIN_REQUIRED__=101200" to your compiler invocation.
AFAICT civetweb's Makefile & CMakeLists wouldn't define this constant either.
3. I haven't determined how to get the current system's MAC_OS_X version in 101100 format, which we'd need to pass-in at compile time. It's obviously insufficient to hardcode 101100 or 101200 for 10.11 or 10.12 respectively.
4. Besides all that, I suspect that the "right solution" isn't at compile-time, but at run-time by weak-linking clock_gettime. This is the strongest solution, and is Apple's intention: Build once, run on 10.11 or 10.12. 

I'll keep looking into both compile-time and run-time options as my time allows. Thanks.

**Comment by kainjow** [comment]
Hm, that is odd. If I compile this code without any flags on 10.11 using just `gcc main.c` in Terminal it outputs "10.11" for me:

```
#include <stdio.h>

#if __APPLE__
#include <AvailabilityMacros.h>
#ifndef MAC_OS_X_VERSION_10_12
#define MAC_OS_X_VERSION_10_12 101200
#endif
#endif

int main(int argc, const char * argv[]) {
#if MAC_OS_X_VERSION_MIN_REQUIRED >= MAC_OS_X_VERSION_10_11
    printf("10.11\n");
#endif
#if MAC_OS_X_VERSION_MIN_REQUIRED >= MAC_OS_X_VERSION_10_12
    printf("10.12\n");
#endif
    return 0;
}
```

**Comment by coffeefog** [comment]
You're right. That code snippet, compiled in 10.12 w/ gcc and clang, produces the expected output ("10.11\n1.12\n") from both compilers.

I don't have my 10.11 box accessible today; I don't understand what was different about my setup yesterday where I didn't see this. I'll try to poke further next week.

**Comment by bel2125** [comment]
Would it be possible for one of you to create a pull request with the required change?

**Comment by coffeefog** [comment]
Sorry, I'm not able to submit a PR.

**Comment by bel2125** [comment]
A patch file would also be fine.
Or a detailed description what code has to be added to what line number.
The problem is, I do not have an OSX system available to test it. I can only build OSX remotely at Travis CI, but probably not for the newest OSX version.

**Comment by kainjow** [comment]
I don't have a 10.12 system setup right now. I'll try to get something soon.

**Comment by catnapgames** [comment]
I'm getting EXC_ARM_BREAKPOINT in the clock_gettime() call when I let it call the newly added "native" one. Still investigating.

**Comment by ehlertjd** [comment]
This issue is a bit more complicated than I originally anticipated.
clock_gettime is defined for OSX version 10.12 (and iOS 10, etc) even if you set the -mmacosx-version-min=10.11 compiler option. 
This means that if you build on OSX 10.12 and try to run on 10.11 you get a dynamic link error at runtime. 
You can avoid this by checking if clock_gettime is NULL. (See the [llvm section on availibility](http://clang.llvm.org/docs/AttributeReference.html#availability)).

I'm opening a revised pull-request that does the NULL check for further discussion.

**Comment by bel2125** [comment]
The second attempt is merged. Thank you.

**Comment by chrisdembia** [comment]
I'm about to make a similar fix for my project. I feel that your fix is a bit fragile because I expect macOS 10.13 and on will also have `clock_gettime()`.

**Comment by chrisdembia** [comment]
I deleted my previous comment, because I made it before reading carefully! This thread has been helpful for me; thank you.
