### ISSUE TITLE
Enhancing Makefile for debug option WITH_DEBUG=1

### ISSUE THREAD

**Issue by saumitravikram** [civetweb/civetweb#351]
In Makefile  optimization flag '-02' is being set code for compile eachtime irrespective of DEBUG option.
```
CFLAGS += -Wall -Wextra -Wshadow -Wformat-security -Winit-self -Wmissing-prototypes -O2 -D$(TARGET_OS) -Iinclude $(COPT) -DUSE_STACK_SIZE=102400  
```

While debugging the code if we try to see values of variable it fails saying optimized out
```
Thread 2 hit Breakpoint 1, handle_request (conn=0x100800600) at src/civetweb.c:10192
(gdb) n
(gdb) n 
(gdb) p ws_close_handler
$1 = <optimized out>
(gdb) p ri
$2 = <optimized out>
```

If we exclude the flag "-O2" in compile when debug option is selected then we can see the values of variables.Snippet of same code without -O2 option.
```
Thread 2 hit Breakpoint 1, handle_request (conn=0x100800600) at src/civetweb.c:10192
(gdb) n
(gdb) n
(gdb) p ri
$1 = (struct mg_request_info *) 0x100800600
(gdb) p ri->http_headers
$2 = {{name = 0x100800bcf "Host", value = 0x100800bd5 "127.0.0.1:8884"}, {name = 0x100800be5 "User-Agent",
    value = 0x100800bf1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:45.0) Gecko/20100101 Firefox/45.0"}, {name = 0x100800c45 "Accept",
    value = 0x100800c4d "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"}, {name = 0x100800c8e "Accept-Language", value = 0x100800c9f "en-US,en;q=0.5"}, {
    name = 0x100800caf "Accept-Encoding", value = 0x100800cc0 "gzip, deflate"}, {name = 0x100800ccf "Connection", value = 0x100800cdb "keep-alive"}, {name = 0x0, 
    value = 0x0} <repeats 58 times>}
 ``` 

Thus it will be better to set -O2 flag when we are checking WITH_DEBUG option in Makefile like below.
```
CFLAGS += -Wall -Wextra -Wshadow -Wformat-security -Winit-self -Wmissing-prototypes -D$(TARGET_OS) -Iinclude $(COPT) -DUSE_STACK_SIZE=102400

ifdef WITH_DEBUG
  CFLAGS += -g -DDEBUG_ENABLED
else
  CFLAGS += -O2 -DNDEBUG
endif
```

If you feel its fine i can go ahead and pull request for this one.

**Comment by bel2125** [comment]
A year ago we intended to remove the Makefile from the repository and create it automatically using CMake. Now it seems the Makefile will stay with us longer, so enhancements there still make sense. If you create a pull request, I will merge it.

Probably a similar change needs to be done in the CMakelist.txt as well.

Why DEBUG_ENABLED instead of just DEBUG? The civetweb.c file uses #ifdef DEBUG, but never DEBUG_ENABLE`D?

**Comment by saumitravikram** [comment]
Why DEBUG_ENABLED instead of just DEBUG?
I just checked the Makefile in source.Its a typo error.I just made the changes in else condition by adding -O2 flag.

I will check in CMakelist.txt where to make changes, and create pull request.

Would fix the typo also.

**Comment by saumitravikram** [comment]
I have to admit,i have not much idea of cmake.

I went through CMakelist.txt and can see we are setting optimization flag only for release build.
```
add_c_compiler_flag(-flto RELEASE)
```
flto flag :  [https://gcc.gnu.org/wiki/LinkTimeOptimization](url)

So i guess there is no need for any change in CMakelist.txt .Still as mentioned above i have not much knowledge about cmake i will let more learned people to decide if there is any need of change in CMakelist.txt
