### ISSUE TITLE
simplify code by using __thread variables instead of sTlsKey?

### ISSUE THREAD

**Issue by mewalig** [civetweb/civetweb#361]
Misc question: wouldn't it be simpler to use __thread instead of sTlsKey? Seems like it could reduce code base and complexity (and therefore increase maintainability) by a meaningful, if not huge, amount

**Comment by bel2125** [comment]
This is compiler specific and not portable in general.

In Win32, the TlsAlloc/TlsFree/TlsGetValue/TlsSetValue functions also work differently than the __thread attribute, if it is used inside a DLL.

**Comment by bel2125** [comment]
Visual Studio uses __declspec(thread), at least Visual Studio 2010 and earlier do not understand __thread.

Some of the DLL limitations I mentioned above are documented here: https://msdn.microsoft.com/en-us/library/6yh4a9k1.aspx
 

> _If a DLL declares any data or object as __declspec( thread ), it can cause a protection fault if dynamically loaded. After the DLL is loaded with LoadLibrary, it causes system failure whenever the code references the __declspec( thread ) data._

**Comment by mewalig** [comment]
I see, was not aware of that DLL issue (and/or other issues). thx
