### ISSUE TITLE
Error on handle_static_file_request, 304 never sent

### ISSUE THREAD

**Issue by albertino80** [civetweb/civetweb#363]
Function **handle_static_file_request** in civetweb.c

the function executes this code:
`if (!mg_fopen(conn, path, "rb", filep)) {`

that internally calls **mg_fopen** that does a 
`memset(filep, 0, sizeof(*filep));`

after that, (in function **handle_static_file_request**) it executes:
`gmt_time_string(lm, sizeof(lm), &filep->last_modified);`

`filep->last_modified` at this point is always = 0

this behaviour causes wrong Last-Modified header value, and at the **304 Not Modified** is never sent to the client.

Bye

**Comment by bel2125** [comment]
This could be another error caused by the bad design of mg_fopen/mg_stat (issue #246).

One could either do another local fix, or try to restructure the code in this area - but restructuring might take a couple of days. I will have a look.

**Comment by bel2125** [comment]
The functions causing this problem have been completely rewritten, eliminating the root cause for this and some related problems. I get a 304 in my tests now - you could repeat your tests if you like.

**Comment by bel2125** [comment]
The relevant functions have been completely rewritten ~10 weeks ago.
