### ISSUE TITLE
OSX build fails @ Travis CI

### ISSUE THREAD

**Issue by bel2125** [civetweb/civetweb#364]
Travis CI changed something in the OSX build environment.
While a build worked without a problem 10 days ago, the identical code does no longer build yesterday (I just restarted the old build). I have no idea what they changed and what needs to be done to fix it at Travis CI.
The error looks like this: https://travis-ci.org/civetweb/civetweb/jobs/165911385

If anyone has any idea what happened and how it must be fixed, please let me know.

**Comment by lammertb** [comment]
These warnings are generated by the compiler in Xopen 7.00 and higher. Adding the compiler flags **-Wno-reserved-id-macro -Wno-keyword-macro** should silence these warnings.

**Comment by bel2125** [comment]
Thank you for the advice. But either I did not do it correctly, or it did not help, since I'm still getting the same warnings and errors: https://travis-ci.org/civetweb/civetweb/jobs/166256029

> You may want to check where the header files are located now on travis.

I don't know how this can be done, but I found this documentation:
https://docs.travis-ci.com/user/osx-ci-environment/
So, probably they use whatever xcode7.3 uses. Maybe they had another xcode version two weeks ago, and I can try to set this image version (e.g. `osx_image: xcode7.2`).

**Comment by bel2125** [comment]
Setting the OSX image did not work out. A different image is used (can be seen here: https://travis-ci.org/civetweb/civetweb/jobs/166284204#L71), but still the same errors.

**Comment by bel2125** [comment]
The OSX builds at Travis CI are still failing for reasons I do not understand.
Since nothing has been changed in the code, it must be due to a change in the build environment.

I cannot investigate this myself, but we can also not have a "build failing" for all CI tests for an undefined time.  Thus I set all OSX builds as "allowed failure" for Travis CI, until someone comes up with an idea how to fix the OSX build at Travis again. This build (https://travis-ci.org/civetweb/civetweb/builds/166539525) now has a Travis CI status "green" although all OSX parts failed.
It's not an ideal solution, but I can not take unlimited time for OSX constantly asking for special treatment.

**Comment by saumitravikram** [comment]
```
In file included from /Users/travis/build/civetweb/civetweb/test/private.c:38:

In file included from /Users/travis/build/civetweb/civetweb/test/../src/civetweb.c:455:

In file included from /usr/include/pthread.h:77:

/System/Library/Frameworks/Kernel.framework/Headers/sys/_types/_mach_port_t.h:49:30: error: typedef redefinition with different types ('__darwin_mach_port_t' (aka 'unsigned int') vs 'ipc_port_t' (aka 'struct ipc_port *'))

typedef __darwin_mach_port_t mach_port_t;

                             ^

/System/Library/Frameworks/Kernel.framework/Headers/mach/port.h:145:22: note: previous definition is here

typedef ipc_port_t              mach_port_t;
```

The issue seems to be originating from same typedef having different definition from pthread and mach port.

Checking on it further.

**Comment by bel2125** [comment]
Thanks for having a look.
Both math_port_t definitions seem to be somewhere in the OSX SDK `/System/Library/Frameworks/Kernel.framework/Headers/` - not within CivetWeb.

Could it be, Travis CI installed a new version of the headers without uninstalling the old one, or something like this? Could this be a general bug of Travis CI, completely independent of CivetWeb? Then one should probably create a new issue in the Travis CI tracker - although I had no luck with creating issues there yet, since the last issue I created there (https://github.com/travis-ci/travis-ci/issues/6497, see #345) is still not commented since about 8 weeks.

**Comment by saumitravikram** [comment]
Its an incompatible update from Apple.The issue is with recent SDK since build is failing on my native OSX also.

**Comment by bel2125** [comment]
Thanks for this information. So it's nothing I have to complain about at Travis CI. Probably the only Travis specific problem is I cannot set the Apple SDK version (setting `osx_image` did not have this effect).

Do you have any idea how to fix it?

**Comment by saumitravikram** [comment]
Hi @bel2125 

I found a fix which is working for MacOSX.

Made the below changes in file cmake/FindLibM.camke

Before
```
find_path(LIBM_INCLUDE_DIRS
  NAMES math.h
  PATHS ${LIBM_ROOT}/include/
)
```
After
```
find_path(LIBM_INCLUDE_DIRS
  NAMES math.h
  PATHS /usr/include /usr/local/include /usr/local/bic/include
  NO_DEFAULT_PATH
)

```

I don't have a Linux machine to check if the change doesn't break  the fix on Linux box.This is very crude fix and i have no clue if it will fix even in travis ci.

**Comment by bel2125** [comment]
This fix works for Linux and OSX at Travis CI. 
Thank's a lot. 

I will test a few more builds to check if the OSX build is now stable (we had some stability with OSX @ Travis: issue #345), and if everything works fine, I will remove OSX from the "allow_failure" list again.

**Comment by saumitravikram** [comment]
@bel2125 could you please add me CREDITS.md file? :P

**Comment by i3roly** [comment]
Hello everyone,

I am just curious if there's an easy work around for this problem when you're writing a kernel drier for Mac?

right now, the only feasible solution i could come up with is adding
#define _MACH_PORT_T before 
#include <pthread.h>

which will successfully compile. however I am a bit uncertain if this is a realistic solution, since it seems to me that pthread's inclusion of the mach_port_t structure (which the header file says is exclusively for userland) implies that it is not to be used in kernel land.

do any of you have any insight as to whether it should be okay?

**Comment by bel2125** [comment]
This issue is closed since more than 3 years, and I cannot remember the details ... but it seems it has nothing to do with kernel drivers, just with include libraries.
Writing Kernel drivers is not easy, and not portable between operating system versions. A web server should not need a kernel driver.

In case you have further questions, or want to discuss this, please create a new issue.
