### ISSUE TITLE
CGI - SCRIPT_NAME incorrect

### ISSUE THREAD

**Issue by v00d00y** [civetweb/civetweb#368]
When accessing a CGI script, which is also an index_file (ie: index.php) without specifying the script in the URL, the SCRIPT_NAME variable is set incorrectly.  I am using CivetWeb 1.8 / PHP 5.6.27, both Windows 64 bit versions.

Accessed URL:  h**p://127.0.0.1/test/
index_files index.php

CGI variable set by CivetWeb: SCRIPT_NAME=/test/
Result: PHP responds with "Access denied." (from the log: "PHP Warning:  Unknown: failed to open stream: Permission denied in Unknown on line 0")

Expected: SCRIPT_NAME=/test/index.php
Result: script loads fine.

As stated at the beginning, specifying the script in the URL (ie: h**p://127.0.0.1/test/index.php) sets the proper SCRIPT_NAME, and works fine.

**Comment by bel2125** [comment]
There is a CGI variable "SCRIPT_NAME" and another one "SCRIPT_FILENAME".
The first one is the URI used to access the script, the second one is the script file to be executed at the server. I think "SCRIPT_FILENAME" is what you need, right?

As to my knowledge
REQUEST_URI =Web path, requested URI
SCRIPT_NAME = Web path, requested file
SCRIPT_FILENAME = Server path, requested file

**Comment by v00d00y** [comment]
If you look at the wiki example, SCRIPT_NAME includes printenv.pl ...  With CivetWeb, it's not including the script filename, just the path (when loading a file from index_files), so PHP for instance is trying to read the folder itself as a script, and generating an error.

As a bare minimum test:

> set SCRIPT_FILENAME=D:\Web/test/index.php
> set SCRIPT_NAME=/test/index.php
> php-cgi.exe
> X-Powered-By: PHP/5.6.27
> Content-type: text/html; charset=UTF-8
> 
> test
> 
> set SCRIPT_FILENAME=D:\Web/test/index.php
> set SCRIPT_NAME=/test/
> php-cgi.exe
> PHP Warning:  Unknown: failed to open stream: Permission denied in Unknown on line 0
> Status: 403 Forbidden
> X-Powered-By: PHP/5.6.27
> Content-type: text/html; charset=UTF-8
> 
> Access denied.

The second one is what CivetWeb is setting when accessing h**p://127.0.0.1/test/ , with index.php in the index_files setting, and CGI properly setup.

**Comment by bel2125** [comment]
> If you look at the wiki example, SCRIPT_NAME includes printenv.pl ... With CivetWeb, it's not including the script filename, just the path (when loading a file from index_files), so PHP for instance is trying to read the folder itself as a script, and generating an error.

Yes. And CivetWeb will also contain /cgi-bin/printenv.pl if the uri is /cgi-bin/printenv.pl/...
But in this case, the URI does not contain printenv.pl but is only /cgi-bin/
The example in Wiki does not cover the implicitly added index.php 

Your "bare minumum test" is something you did at the shell?
In Windows or Linux?
What's the first line of your script file and how did you set the "cgi_interpreter" config?

**Comment by v00d00y** [comment]
Yes, the bare test was in windows at the shell, duplicating the values sent by civetweb (set the CGI interpreter to a batch file containing nothing but "SET", to see what was wrong).

test/index.php:
> <?php
> echo 'test';
> ?>

from the civetweb.config:
> cgi_pattern **.php$
> cgi_interpreter D:\PHP\php-cgi.exe
> index_files index.php

If I load /test/index.php - works.  /test/ - doesn't (at least, not with CGI..  .html's load fine when enabled).  The first line of the PHP file in this case doesn't matter though, because php-cgi.exe isn't even loading the script unless the script filename is in SCRIPT_NAME.

**Comment by v00d00y** [comment]
What I am currently doing for now (unsure how well it would work under other OS):
> addenv(env, "SCRIPT_NAME=%s", (char *)prog + (int)strlen(conn->ctx->config[DOCUMENT_ROOT]));

Since SCRIPT_FILENAME is currently just set to prog (complete path to the script), just push the pointer ahead by the length of the DOCUMENT_ROOT, resulting in (for instance): SCRIPT_NAME=/test/index.php (which works fine for both /test/, and /test/index.php).

**Comment by bel2125** [comment]
I always had the interpreter in the first line of the script, or used executable files as scripts (in particular on Linux) and did not use cgi_interpreter. But of course using the cgi_interpreter configuration is valid as well. The script name is passed as the first command line argument to the interpreter.
Probably php-cgi.exe on Windows ignores the first parameter and uses SCRIPT_NAME instead (and for whatever reason not SCRIPT_FILENAME). I never tested it like that.

As a quick workaround you could try is to set the cgi_interpreter to a something.cmd file with the content
```
set SCRIPT_FILE=%1
php-cgi.exe
```
to store the command line argument in the environment before calling php-cgi.exe (I did not test it now).

Meanwhile I will have to study the CGI spec, if the index.php is supposed to be added to SCRIPT_FILE, or if this is intended to be used in a different way.

**Comment by v00d00y** [comment]
Ok, I just tested php-cgi.exe manually using the command line + variable environment variables.  If SCRIPT_FILE is set to anything, it overrides the command line.  If SCRIPT_FILE is unset, it will read the script from the command line, however the server variable SCRIPT_FILE will also be empty and may break some scripts.

**Comment by bel2125** [comment]
I added the `index.cgi` to the `SCRIPT_NAME` CGI variable.
It should not be done with `addenv(env, "SCRIPT_NAME=%s", (char *)prog + (int)strlen(conn->ctx->config[DOCUMENT_ROOT]));`, because this might break URI rewriting and paths like /path/script.cgi/param/xyz
After some tests, I think this should work: https://github.com/civetweb/civetweb/commit/399a7a02e5e28c8893e4dc2e3fbb2c1693a90f20
Please repeat your tests as well.

**Comment by bel2125** [comment]
Fixed in version 1.9 (December 2016)
