### ISSUE TITLE
how to launch .lp files ? 

### ISSUE THREAD

**Issue by PaulTsai20160627** [civetweb/civetweb#372]
Hi ALL: 

I am new to civetweb . The example of civetweb failed  to be launch when executing the .lp by opening

with firefox web browser. It show some source code file in the .lp and seems does not correctly be accessed.

So how to launch .lp file(Lua server page) ?

**Comment by bel2125** [comment]
Did you build the server with Lua support?
I also need some information on your operating system.
You can check this by calling "civetweb -I" and posting the result.

**Comment by bel2125** [comment]
Did it work? Is there anything else I can do to help?
