### ISSUE TITLE
Two issues found related to read_auth_file(), infinite recursion and minor optimization

### ISSUE THREAD

**Issue by pstrinkle** [civetweb/civetweb#374]
I have a PR prepared to address this.  You can provide an `.htpasswd` file to civetweb that includes another.  This can let a user (or malicious actor) change the `.htpasswd` file to include itself, which then triggers an infinite recursion and crash, or more subtly include file A that includes B which then includes A again.

The other issue I found was an simple optimization s.t. returning after we get a positive result saves from processing more files and lines which won't switch the positive to a negative.

in file: `usr/share/civetweb/htdocs/folder/.htpasswd`
`:include=/usr/share/civetweb/htdocs/folder/.htpasswd`

**Comment by bel2125** [comment]
Thank you for your contribution.
