### ISSUE TITLE
hide_files_patterns does not work.

### ISSUE THREAD

**Issue by malcome** [civetweb/civetweb#376]
UserManual.md says, "...and return 404 Not Found if requested" in about hide_files_patterns. but it does not work.
I checked on v1.8.

**Comment by bel2125** [comment]
So, you see a file that should be hidden?
Could you tell me the exact path and filename and the hide_file_pattern you used?
Please also send me some system information ("civetweb -I" from the command line will print this).

**Comment by malcome** [comment]
Hi bel2125.

" not
show up in directory listing" is working well, but "return 404 Not Found if requested" is not working.

Source code:

		/* 11. File does not exist, or it was configured that it should be
		 * hidden */
		if (!is_found || (must_hide_file(conn, path))) {
			send_http_error(conn, 404, "%s", "Not found");
			return;
		}

I think that "path" does not have "File Name" part. 

I am using libcivetweb.dll compiled with MSYS2+MinGW-w64 32bit, so I do not try "civetweb -I" soon.

**Comment by bel2125** [comment]
The -I option just prints some information on the system (operating system, compiler, ...) that help to reproduce the problem - essentially Win (Version?), 64 Bit, MinGW and the feature compile flags.
Maybe I have to move it from main.c to civetweb,c some time.

What pattern did you use, and what filename and path?

**Comment by bel2125** [comment]
I need some instructions to reproduce this. Without the pattern and filename+path you used, I cannot tell if it is an error in the code, or an error in the way you used it.

For example:
`hide_file_patterns **.ico$` hides /test.ico and /path/test.ico on a Windows XP 32-Bit system (my oldest test machine), Visual Studio Studio Build, ...

I cannot do anything, if I cannot reproduce the issue.

**Comment by malcome** [comment]
Thanks bel2125,
"**.ico$" makes "404 Not Found" well.
But I can not understand that "*.ico$" only makes "no directory listing" from UserManual.
IMHO it is wired design.

**Comment by bel2125** [comment]
Pattern matching is a common source of confusion - see #179 (and the duplicates #255, #337).
It was like this before the project was forked / before I was involved in this project, and unfortunately it cannot be changed without breaking compatibility.

From https://github.com/civetweb/civetweb/blob/master/docs/UserManual.md:
```
 **      Matches everything
 *       Matches everything but slash character, '/'
 $       Matches the end of the string
```

*.ico$ matches test.ico but not /path/to/test.ico, so pattern matching to file_extension must always use **.file_extention$

**Comment by malcome** [comment]
I see.
IMHO, it could turn out a security issue, so had better change description of UserManual.md.

**Comment by bel2125** [comment]
The documentation has been modified. The rest of this issue is duplicate to see #179 (and the duplicates #255, #337). I'm closing all duplicates except the original one (#179).
