### ISSUE TITLE
Possibly Wrong va_arg parameter used when calling alloc_vprintf2

### ISSUE THREAD

**Issue by ewesemann** [civetweb/civetweb#378]
In civetweb.c in the "alloc_vprintf" function there are a few va_copy calls made where the copy is passed into another function. In one case the original is supplied instead of the copy.

line 5108 //commit "0d73d76ea4c24c6389f3b91d91df05f6333bb7cc [0d73d76]"
`len = alloc_vprintf2(out_buf, fmt, ap);` 
     should be  
`len = alloc_vprintf2(out_buf, fmt, ap_copy);`

Evidence to support that this should be changed:
1) va_copy is called before the function call and va_end is called after the function call.
2) ap is again used later in the function.

I am not sure what impact this would have but I noticed the difference when reviewing the code.

**Comment by bel2125** [comment]
You mean this code:
```C
		va_copy(ap_copy, ap);
		len = alloc_vprintf2(out_buf, fmt, ap);
		va_end(ap_copy);
```

I'm quite sure it does not have any consequence to use ap instead of ap_copy, since ap is no longer used after the alloc_vprintf2 call. A va_list is a pointer to the stack, and va_arg calls increment (or decrement, according to the stack direction) this pointer.

But you are right, it was meant to be ap_copy there.

**Comment by ewesemann** [comment]
I appreciate your reply.  As this is such a small change I suspect that it is more work to merge then just change. If you want I am fine with providing a pull request.  Thanks again.

**Comment by bel2125** [comment]
Thank you, I already changed it.

**Comment by bel2125** [comment]
Usually I set the "done - wait for submitter to confirm" flag, so I can be sure I changed what was meant to be changed before closing an issue. I guess this one is rather obvious, but please have a brief look.

**Comment by ewesemann** [comment]
It looks good to me.  Thanks.
