### ISSUE TITLE
'mg_handle_form_request()' doesn't appear to free allocated memory

### ISSUE THREAD

**Issue by nntrab** [civetweb/civetweb#380]
In 'handle_form.inl' released as part of version 1.8, the function 'mg_handle_form_request()' calls 'url_encoded_field_get()' for each field found. There are several locations where it is called, depend on the type of form submitted. In 'url_encoded_field_get()', on line 93, memory is allocated for a URL-decoded version of the field's value. This is the value that is passed to the 'field_get' callback. That memory doesn't appear to be freed. Since 'mg_free()' is a static function, it would appear that it **isn't** the callback's responsibility to free the memory.

A very crude test was performed, using an embedded version of CivetWeb and an HTML page that submitted a form containing a 1kB field value repeatedly. The process showed increased memory usage over time. The test was done on Windows 10 and 'GetProcessMemoryInfo()' was used to get the working memory set for the process. Initially every form processed increased the memory usage (by about 4kB) but slowly the amount got larger but less frequently.

A check of the 'civetweb.h' header file didn't suggest a function that should be called to free resources allocated for a call to 'mg_handle_form_request()', nor did the documentation for the function itself. Have I missed something?

Is the intention that the 'field_get' callback should do its own memory allocation, if required, or alternatively that the value passed to the callback should be usable for the remainder of the processing of the form? I can see arguments for both but if the latter there would appear to be a need for a function to free the allocated resources once all form processing has been completed.

**Comment by bel2125** [comment]
The memory allocated in line 93:
https://github.com/civetweb/civetweb/blob/master/src/handle_form.inl#L93

Is freed in line 115:
https://github.com/civetweb/civetweb/blob/master/src/handle_form.inl#L115

The memory leak was fixed here, but some weeks after the 1.8 release:
https://github.com/civetweb/civetweb/commit/85b9b7e09e2ee6ec30291fb4faa2eb982922124a

**Comment by nntrab** [comment]
My mistake. I assumed a memory leak would have warranted a new release. I should have checked later commits. My apologies.

**Comment by bel2125** [comment]
I plan to create a new release 1.9 soon. 
The moment this leak has been found, several new features for 1.9 were already, added but not fully stabilized.
