### ISSUE TITLE
Could civetweb support static file download?

### ISSUE THREAD

**Issue by FTAndy** [civetweb/civetweb#381]
Recently I use [crow](https://github.com/ipkn/crow) to be the web server, but I find that crow don't support the static file download. Everytime I download from crow, I need to read the whole file content to the memory and my os system just crash.

I am looking for a c++ web framework that support static file download through stream, which means read file content in a stream way and send the file content to rep in a stream way.

Seem that civetweb can do that with the api `mg_send_file`. But I am not family with c++, I am not going to read the source code. Can somebody know that the `mg_send_file` api support send file in a stream way? I just need this function to complete some task. Thanks.

**Comment by bel2125** [comment]
I do not know how crow works. I just saw it's written in Python, while CivetWeb is written in C.
CivetWeb uses the "[sendfile](https://linux.die.net/man/2/sendfile)" C system call on Linux, which allows to send a file without reading anything from the content. In Windows, CivetWeb reads and sends the file chunk by chunk, so you can download a gigabyte file without having a gigabyte RAM. Furthermore, it is also possible to download only a range for a long file (e.g., to resume download), if the client (browser) supports this.

If you just want to have a certain directory to download, you do not need to use `mg_send_file` yourself. You can just set the `document_root` configuration to this folder, and the server will take care.

You can test if the server meets your requirement: If you use Windows, download the pre-compiled version from [SourceForge](https://sourceforge.net/projects/civetweb/), and just run it (it does not need installation). Set the document_root to some folder, or use the default (current directory) and copy some files there. For Linux you need to create it from the sources (just type `make`). Then open localhost:8080 in your browser.

**Comment by bel2125** [comment]
Or, in short: 

> Can somebody know that the mg_send_file api support send file in a stream way?

Yes, it does ;-)

**Comment by FTAndy** [comment]
@bel2125 Thanks for the answers. I am going to use it on Linux. Screw crow.

By the way, happy new year 2017.
