### ISSUE TITLE
ceph radosgw unable to use port 65535, rgw_frontends = "civetweb port=65535"

### ISSUE THREAD

**Issue by mailzhou** [civetweb/civetweb#386]
fail to start radosgw
// vi /etc/ceph/ceph.conf
[client.radosgw.test]
rgw_frontends = "civetweb port=65535"
host = xxx.xxx.xxx.xxx
radosgw -c /etc/ceph/ceph.conf -n client.radosgw.test

why is_valid_port only allow port < 65535 not <=65535?
// vi src/civetweb.c +6802
is_valid_port(unsigned long port)
{
    return port < 0xffff;
}

**Comment by bel2125** [comment]
> why is_valid_port only allow port < 65535 not <=65535?

Looking at the history, it was already the case when civetweb was created, and it seems up to now no one really tried 65535. 
I just checked, this is an [private port](https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers#Dynamic.2C_private_or_ephemeral_ports), but it is still valid.

So I currently do not see a reason why we should not replace the `<` by `<=`.

**Comment by bel2125** [comment]
Fixed two months ago.
