### ISSUE TITLE
tiny fix for embeddability

### ISSUE THREAD

**Issue by PavelVozenilek** [civetweb/civetweb#387]
In `civetweb.c` change:

`# include "civetweb.h"
`
to:

```
#ifndef CIVETWEB_HEADER_INCLUDED
#  include "civetweb.h"
#endif
```

This helps when code is embedded like:

```
#include "3pp/civetweb 1.10/include/civetweb.h"
#include "3pp/civetweb 1.10/src/civetweb.c"
```

I cannot make pull request because the file is so big that my browser freezes when I try to open it in the internal editor.

**Comment by bel2125** [comment]
Done.

I'm don't know about the browser problem - it works for me with FireFox.

**Comment by PavelVozenilek** [comment]
@bel2125: it's problem for people not having infinite bandwith (I have quite limited ADSL) and infinite memory.
