### ISSUE TITLE
suggestion: add tiniest possible example that works

### ISSUE THREAD

**Issue by PavelVozenilek** [civetweb/civetweb#395]
I am trying to add internal webserver for an application, to help trobleshooting. For this purpose I am trying to use the smallest possible set of features, but someting somewhere fails.

Could there be some very simple example how to make embedded "Hello World" (and nothing else, just one page with one line of text)? The `embedded_c.c` has > 900 LOC, tries to do everything and is not exactly easy to grok.

I imagine snippet of code like:

```
#include "civetweb.h"
#include "civetweb.c"

init();
start();
add_the single_page_handler();
getch();
stop();
```

which I can copy/paste to any place, w/o worry about makefiles, libraries, main(), just to make sure the thing works for me.

**Comment by bel2125** [comment]
The embedded_c example shows most of the features in one example.
Simpler examples might be found in the unit tests (https://github.com/civetweb/civetweb/blob/master/test/public_server.c) - this file contains several different tests for different aspects.

Suitable examples might be `test_mg_start_stop_http_server` - but you should drop the mg_get_ports/mg_get_server_ports section and the client.
Or `test_large_file` - this example has an #ifdef NO_SSL to use either HTTP or HTTPS, and a client as well.

This is the essential part:
```C
test_large_file(...)
{
	/* Server var */
	struct mg_context *ctx;
	struct mg_callbacks callbacks;
	const char *OPTIONS[32];
	int opt_cnt = 0;

	OPTIONS[opt_cnt++] = "listening_ports";
	OPTIONS[opt_cnt++] = "8080";
	OPTIONS[opt_cnt] = NULL;


	memset(&callbacks, 0, sizeof(callbacks));
	callbacks.begin_request = test_large_file_begin_request;

	ctx = test_mg_start(&callbacks, 0, OPTIONS);


... run the server

	mg_stop(ctx);
}
```

Although I would not use the `begin_request` callback but `mg_set_request_handler` like in `test_request_handlers` (but test_request_handlers is a lengthy example again).

**Comment by bel2125** [comment]
Or did you mean, we should add this example to the example directory?
Or probably to https://github.com/civetweb/civetweb/blob/master/docs/Embedding.md ?

**Comment by PavelVozenilek** [comment]
Yes, something like that (with detail on what it means "run the server").  An example which one can copy/paste and it does show Hello World would be the best.

I eventually ended up writing my own webserver, the most primitive one, ~30 lines, but it works for me.

**Comment by bel2125** [comment]
The example is now available in the documentation, and there is a continuous integration (CI) test to make sure it will remain working.
