### ISSUE TITLE
VCRUNTIME140.dll is missing from your computer

### ISSUE THREAD

**Issue by klevstul** [civetweb/civetweb#401]
# description
trying to start the latest 64-bit civetweb on win 10 gives the error "VCRUNTIME140.dll is missing from your computer"
![k_000079](https://cloud.githubusercontent.com/assets/216850/22186422/0ef50dde-e0f6-11e6-8ca9-6ccbe1f2b413.jpg)

# extra info
- the 32-bit exe for V1.9.1 works fine
- for the previous version i used, V1.6, the 64-bit exe ran fine

# details
- downloaded file: `CivetWeb_Win32+64_V1.9.1.zip` ([sourceforge](https://sourceforge.net/projects/civetweb/))
- running on 64 bit win 10 pro
![image](https://cloud.githubusercontent.com/assets/216850/22186450/705d4636-e0f6-11e6-90d5-05a8e2d5ebaa.png)

**Comment by bel2125** [comment]
Did you install the Visual Studio 2015 redistributables, as explained in Installing.md in the zip file?
https://www.microsoft.com/en-us/download/details.aspx?id=48145

Earlier versions of CivetWeb 64 bit used earlier versions of Visual Studio and, thus, earlier versions of the redistributables (e.g. 1.8 and 1.9 use Visual Studio 2015, 1.6 and 1.7 used Visual Studio 2013, earlier versions used 2012 - as far as I remember).
The 32 bit version uses Visual Studio 2010 (the latest version supporting WinXP 32-bit without requiring special settings).
But it's always written in Installing.md what version you need, and there is a download link as well.

So you probably have the Visual Studio 2013 redistributables already installed, and missing the 2015 version.

**Comment by klevstul** [comment]
thanks a lot, @bel2125. installing visual studio 2015 did the trick! i had the 2013 version earlier.

in [installing.md on github](https://github.com/civetweb/civetweb/blob/master/docs/Installing.md) it is stated that you should you the 2013 version for the 64bit:
> 1b. 64 Bit: Install the Visual C++ Redistributable for Visual Studio 2013

but, installing.md included in the downloaded file, the correct info is given:
> 1b. 64 Bit: Install the [Visual C++ Redistributable for Visual Studio 2015](http://www.microsoft.com/en-us/download/details.aspx?id=48145)
