### ISSUE TITLE
civetweb cannot be build and test

### ISSUE THREAD

**Issue by loafer-mka** [civetweb/civetweb#402]
I'm using opensuse tumbleweed

$ git branch -v
* master 6ed309a Update link in test scripts

1. attempt to build using make and static lua -- building is OK, but unit-test fails:
$ make WITH_LUA=1 WITH_WEBSOCKET=1 WITH_CPP=1 PREFIX=/opt/civetweb
...
$ sudo make install PREFIX=/opt/civetweb
...
$ make unit_test 
make: *** No rule to make target 'test/unit_test.c', needed by 'civetweb_test'.  Stop.

The test/unit_test.c really is not found

2. attempt to build with shared lua:
$ make WITH_LUA=1 WITH_LUA_SHARED=1 WITH_WEBSOCKET=1 WITH_CPP=1 PREFIX=/opt/civetweb
...
g++ -o civetweb -Wall -Wextra -Wshadow -Wformat-security -Winit-self -Wmissing-prototypes -DLINUX -Iinclude  -DUSE_STACK_SIZE=102400 -O2 -DNDEBUG -DLUA_VERSION_MAKEFILE=502 -Isrc/third_party/lua-5.2.4/src -DLUA_COMPAT_ALL -DUSE_LUA -DLUA_USE_POSIX -DLUA_USE_DLOPEN -Isrc/third_party -DTHREADSAFE=1 -DSQLITE_ENABLE_FTS3 -DSQLITE_ENABLE_FTS3_PARENTHESIS -DUSE_LUA_SQLITE3 -Isrc/third_party -DUSE_LUA_FILE_SYSTEM -Isrc/third_party -DUSE_LUA_LUAXML -DUSE_WEBSOCKET  out/src/civetweb.o out/src/main.o out/src/CivetServer.o out/src/third_party/sqlite3.o out/src/third_party/lsqlite3.o out/src/third_party/lfs.o out/src/third_party/LuaXML_lib.o  -lpthread -lm -lrt -ldl -llua5.2

/usr/lib64/gcc/x86_64-suse-linux/6/../../../../x86_64-suse-linux/bin/ld: cannot find -llua5.2
collect2: error: ld returned 1 exit status
make: *** [Makefile:287: civetweb] Error 1

The setting lua version does not help:
$ make WITH_LUA=1 WITH_LUA_SHARED=1 WITH_LUA_VERSION=503 WITH_WEBSOCKET=1 WITH_CPP=1 PREFIX=/opt/civetweb
...
g++ -o civetweb -Wall -Wextra -Wshadow -Wformat-security -Winit-self -Wmissing-prototypes -DLINUX -Iinclude  -DUSE_STACK_SIZE=102400 -O2 -DNDEBUG -DLUA_COMPAT_5_2 -DLUA_VERSION_MAKEFILE=503 -Isrc/third_party/lua-5.3.3/src -DLUA_COMPAT_ALL -DUSE_LUA -DLUA_USE_POSIX -DLUA_USE_DLOPEN -Isrc/third_party -DTHREADSAFE=1 -DSQLITE_ENABLE_FTS3 -DSQLITE_ENABLE_FTS3_PARENTHESIS -DUSE_LUA_SQLITE3 -Isrc/third_party -DUSE_LUA_FILE_SYSTEM -Isrc/third_party -DUSE_LUA_LUAXML -DUSE_WEBSOCKET  out/src/civetweb.o out/src/main.o out/src/CivetServer.o out/src/third_party/sqlite3.o out/src/third_party/lsqlite3.o out/src/third_party/lfs.o out/src/third_party/LuaXML_lib.o  -lpthread -lm -lrt -ldl -llua5.3
/usr/lib64/gcc/x86_64-suse-linux/6/../../../../x86_64-suse-linux/bin/ld: cannot find -llua5.3
collect2: error: ld returned 1 exit status
make: *** [Makefile:287: civetweb] Error 1

the lua libraries have other pattern: 
$ ls -l /usr/lib*/liblua*
lrwxrwxrwx 1 root root      13 Oct 26 23:09 /usr/lib64/liblua5.1.so.0 -> liblua.so.5.1
-rw-r--r-- 1 root root 1313648 Oct 26 22:59 /usr/lib64/liblua.a
lrwxrwxrwx 1 root root      19 Oct 19 17:14 /usr/lib64/libluabind.so -> libluabind.so.0.9.1
-rwxr-xr-x 1 root root  129240 Oct 19 17:14 /usr/lib64/libluabind.so.0.9.1
lrwxrwxrwx 1 root root      13 Oct 26 22:59 /usr/lib64/liblua.so -> liblua.so.5.3
-rw-r--r-- 1 root root  201336 Oct 26 23:09 /usr/lib64/liblua.so.5.1
-rw-r--r-- 1 root root  208680 Oct 26 23:22 /usr/lib64/liblua.so.5.2
-rw-r--r-- 1 root root  237408 Oct 26 22:59 /usr/lib64/liblua.so.5.3

3. attempt to build using ./build script:
$ ./build
-- The C compiler identification is GNU 6.2.1
-- The CXX compiler identification is GNU 6.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Target architecture - x86_64
-- Max Request Size - 16384
-- Thread Stack Size - 102400
-- Serve no static files - OFF
-- Disable CGI support - OFF
-- Disable caching support - OFF
-- C++ wrappers - OFF
-- IP Version 6 - OFF
-- Websockets support - OFF
-- Memory Debugging - OFF
-- Lua CGI support - OFF
-- Build if there are warnings - OFF
-- Duktape CGI support - OFF
-- SSL support - ON
-- Compile for OpenSSL 1.1 API - OFF
-- Dynamically load SSL libraries - ON
-- SSL Library Name - libssl.so
-- SSL Cryptography Library Name - libcrypto.so
-- Configuring C Compiler
-- Performing Test HAVE_C_FLAG_STD_C11
-- Performing Test HAVE_C_FLAG_STD_C11 - Success
-- Performing Test HAVE_C_FLAG_WALL
...
then it builds OK... but how to enable websockets and lua cgi?

also unit tests partially failed:

Scanning dependencies of target main-c-unit-test
[ 96%] Building C object test/CMakeFiles/main-c-unit-test.dir/main.c.o
[100%] Linking C executable main-c-unit-test
[100%] Built target main-c-unit-test
Running tests...
Test project /home/makarov/NAMI/_try_it/civetweb/output/build
      Start  1: test-private-http-message
 1/33 Test  #1: test-private-http-message ...................   Passed    0.00 sec
      Start  2: test-private-url-parsing
...
20/33 Test #20: test-publicserver-start-stop-http-server ....   Passed   15.02 sec
      Start 21: test-publicserver-start-stop-https-server
21/33 Test #21: test-publicserver-start-stop-https-server ...***Failed    1.02 sec
      Start 22: test-publicserver-tls-server-client
22/33 Test #22: test-publicserver-tls-server-client .........***Failed    1.02 sec
      Start 23: test-publicserver-server-requests
23/33 Test #23: test-publicserver-server-requests ...........***Failed    1.02 sec
      Start 24: test-publicserver-handle-form
24/33 Test #24: test-publicserver-handle-form ...............   Passed   20.23 sec
...
28/33 Test #28: test-publicserver-limit-speed ...............   Passed   20.06 sec
      Start 29: test-publicserver-large-file
29/33 Test #29: test-publicserver-large-file ................***Failed    1.03 sec
      Start 30: test-publicserver-file-in-memory
30/33 Test #30: test-publicserver-file-in-memory ............***Failed    1.02 sec
      Start 31: test-timer-timer-single-shot
31/33 Test #31: test-timer-timer-single-shot ................   Passed    4.40 sec
      Start 32: test-timer-timer-periodic
32/33 Test #32: test-timer-timer-periodic ...................   Passed   12.10 sec
      Start 33: test-timer-timer-mixed
33/33 Test #33: test-timer-timer-mixed ......................   Passed    2.20 sec

85% tests passed, 5 tests failed out of 33

Total Test time (real) = 164.56 sec

The following tests FAILED:
         21 - test-publicserver-start-stop-https-server (Failed)
         22 - test-publicserver-tls-server-client (Failed)
         23 - test-publicserver-server-requests (Failed)
         29 - test-publicserver-large-file (Failed)
         30 - test-publicserver-file-in-memory (Failed)
Errors while running CTest
make: *** [Makefile:150: test] Error 8

The tests with https protocol were failed because wrong path to certificate file
(below are citates from ./output/build/Testing/Temporary/LastTest.log):

21/33 Testing: test-publicserver-start-stop-https-server
21/33 Test: test-publicserver-start-stop-https-server
Command: "/home/makarov/NAMI/_try_it/civetweb/output/build/test/main-c-unit-test" "--test-dir=/home/makarov/NAMI/_try_it/civetweb/test" "--suite=PublicServer" "--test-case=Start Stop HTTPS Server"
Directory: /home/makarov/NAMI/_try_it/civetweb/output/build/test
"test-publicserver-start-stop-https-server" start time: Jan 23 17:23 MSK
Output:
----------------------------------------------------------
Running suite(s): PublicServer
0%: Checks: 1, Failures: 1, Errors: 0
/home/makarov/NAMI/_try_it/civetweb/test/public_server.c:537:F:Start Stop HTTPS Server:test_mg_start_stop_https_server:0: Assertion 'errmsg == ""' failed: errmsg == "ssl_use_pem_file: cannot open certificate file ../../resources/ssl_cert.pem: error:02001002:system library:fopen:No such file or directory", "" == ""
<end of output>
Test time =   1.02 sec
----------------------------------------------------------
Test Failed.
"test-publicserver-start-stop-https-server" end time: Jan 23 17:23 MSK
"test-publicserver-start-stop-https-server" time elapsed: 00:00:01
----------------------------------------------------------

22/33 Testing: test-publicserver-tls-server-client
22/33 Test: test-publicserver-tls-server-client
Command: "/home/makarov/NAMI/_try_it/civetweb/output/build/test/main-c-unit-test" "--test-dir=/home/makarov/NAMI/_try_it/civetweb/test" "--suite=PublicServer" "--test-case=TLS Server Client"
Directory: /home/makarov/NAMI/_try_it/civetweb/output/build/test
"test-publicserver-tls-server-client" start time: Jan 23 17:23 MSK
Output:
----------------------------------------------------------
Running suite(s): PublicServer
0%: Checks: 1, Failures: 1, Errors: 0
/home/makarov/NAMI/_try_it/civetweb/test/public_server.c:670:F:TLS Server Client:test_mg_server_and_client_tls:0: Assertion 'errmsg == ""' failed: errmsg == "ssl_use_pem_file: cannot open certificate file ../..
/resources/cert/server.pem: error:02001002:system library:fopen:No such file or directory", "" == ""
<end of output>
Test time =   1.02 sec
----------------------------------------------------------
Test Failed.
"test-publicserver-tls-server-client" end time: Jan 23 17:23 MSK
"test-publicserver-tls-server-client" time elapsed: 00:00:01
----------------------------------------------------------

23/33 Testing: test-publicserver-server-requests
23/33 Test: test-publicserver-server-requests
Command: "/home/makarov/NAMI/_try_it/civetweb/output/build/test/main-c-unit-test" "--test-dir=/home/makarov/NAMI/_try_it/civetweb/test" "--suite=PublicServer" "--test-case=Server Requests"
Directory: /home/makarov/NAMI/_try_it/civetweb/output/build/test
"test-publicserver-server-requests" start time: Jan 23 17:23 MSK
Output:
----------------------------------------------------------
Running suite(s): PublicServer
0%: Checks: 1, Failures: 1, Errors: 0
/home/makarov/NAMI/_try_it/civetweb/test/public_server.c:1031:F:Server Requests:test_request_handlers:0: Assertion 'ctx != ((void *)0)' failed
<end of output>
Test time =   1.02 sec
----------------------------------------------------------
Test Failed.
"test-publicserver-server-requests" end time: Jan 23 17:23 MSK
"test-publicserver-server-requests" time elapsed: 00:00:01
----------------------------------------------------------

...

29/33 Testing: test-publicserver-large-file
29/33 Test: test-publicserver-large-file
Command: "/home/makarov/NAMI/_try_it/civetweb/output/build/test/main-c-unit-test" "--test-dir=/home/makarov/NAMI/_try_it/civetweb/test" "--suite=PublicServer" "--test-case=Large file"
Directory: /home/makarov/NAMI/_try_it/civetweb/output/build/test
"test-publicserver-large-file" start time: Jan 23 17:25 MSK
Output:
----------------------------------------------------------
Running suite(s): PublicServer
0%: Checks: 1, Failures: 1, Errors: 0
/home/makarov/NAMI/_try_it/civetweb/test/public_server.c:3647:F:Large file:test_large_file:0: Assertion 'ctx != ((void *)0)' failed
<end of output>
Test time =   1.03 sec
----------------------------------------------------------
Test Failed.
"test-publicserver-large-file" end time: Jan 23 17:25 MSK
"test-publicserver-large-file" time elapsed: 00:00:01
----------------------------------------------------------

30/33 Testing: test-publicserver-file-in-memory
30/33 Test: test-publicserver-file-in-memory
Command: "/home/makarov/NAMI/_try_it/civetweb/output/build/test/main-c-unit-test" "--test-dir=/home/makarov/NAMI/_try_it/civetweb/test" "--suite=PublicServer" "--test-case=File in memory"
Directory: /home/makarov/NAMI/_try_it/civetweb/output/build/test
"test-publicserver-file-in-memory" start time: Jan 23 17:25 MSK
Output:
----------------------------------------------------------
Running suite(s): PublicServer
0%: Checks: 1, Failures: 1, Errors: 0
/home/makarov/NAMI/_try_it/civetweb/test/public_server.c:3768:F:File in memory:test_file_in_memory:0: Assertion 'ctx != ((void *)0)' failed
<end of output>
Test time =   1.02 sec
----------------------------------------------------------
Test Failed.
"test-publicserver-file-in-memory" end time: Jan 23 17:25 MSK
"test-publicserver-file-in-memory" time elapsed: 00:00:01
----------------------------------------------------------

The real path must be one directory above: ../../../resources/ssl_cert.pem instead of ../../resources/ssl_cert.pem, so I'm try to add link:

$ cd output
$ ln -s ../resources
$ cd ..
$ ./build
...

97% tests passed, 1 tests failed out of 33

Total Test time (real) = 209.15 sec

The following tests FAILED:
         23 - test-publicserver-server-requests (Failed)
Errors while running CTest
make: *** [Makefile:150: test] Error 8

The only one test remain failed:
...
23/33 Testing: test-publicserver-server-requests
23/33 Test: test-publicserver-server-requests
Command: "/home/makarov/NAMI/_try_it/civetweb/output/build/test/main-c-unit-test" "--test-dir=/home/makarov/NAMI/_try_it/civetweb/test" "--suite=PublicServer" "--test-case=Server Requests"
Directory: /home/makarov/NAMI/_try_it/civetweb/output/build/test
"test-publicserver-server-requests" start time: Jan 23 17:43 MSK
Output:
----------------------------------------------------------
Running suite(s): PublicServer
cp: cannot stat '../../output//cgi_test.cgi': No such file or directory
0%: Checks: 1, Failures: 1, Errors: 0
/home/makarov/NAMI/_try_it/civetweb/test/public_server.c:1303:F:Server Requests:test_request_handlers:0: Assertion 'ri->uri == "200"' failed: ri->uri == "404", "200" == "200"
<end of output>
Test time =   4.05 sec
----------------------------------------------------------
Test Failed.
"test-publicserver-server-requests" end time: Jan 23 17:43 MSK
"test-publicserver-server-requests" time elapsed: 00:00:04
----------------------------------------------------------

The ../../output//cgi_test.cgi really is missing, the path must be ../../../output, but cgi_test.cgi does not exist at all:
$  find . |grep '\.cgi$'
./test/hello.cgi
./test/windows_fail.cgi
./test/linux_fail_silent.cgi
./test/env.cgi
./test/ajax/echo.cgi
./test/windows_fail_silent.cgi
./test/windows.cgi
./test/timeout.cgi
./test/dir with spaces/hello.cgi
./test/linux.cgi
./test/bad2.cgi
./test/bad.cgi
./test/linux_fail.cgi
./output/build/test/test.cgi

**Comment by bel2125** [comment]
>    $ make unit_test
>    make: *** No rule to make target 'test/unit_test.c', needed by 'civetweb_test'. Stop.
>
> The test/unit_test.c really is not found

unit_test.c has been replaced by a new set of CMake based tests using the "check" framework more than a year ago. The original unit_test.c file was no longer maintained an finally removed end of last year.
Probably there are some remainders of this old test still in the "Makefile". The new way to build the tests are using CMake.

> attempt to build with shared lua:
> ...
> /usr/lib64/gcc/x86_64-suse-linux/6/../../../../x86_64-suse-linux/bin/ld: cannot find -llua5.2

So it seems the default names fit for Debian, but not for Suse.
You could use a symlink

"Lua shared" means you don't use the Lua version in the CivetWeb source tree, but you use the Lua version installed in the system. The exact naming convention depends on the system. 

> The tests with https protocol were failed because wrong path to certificate file
> (below are citates from ./output/build/Testing/Temporary/LastTest.log):

That's unfortunately a common problem. Every Linux has its own flavor of paths. The Linux test environment on Travis CI is a different one than on my local Linux test machine - so there are some ugly #ifdef in the code to get the correct path: https://github.com/civetweb/civetweb/blob/master/test/public_server.c#L65
I have to set the `LOCAL_TEST` define if I do not work on Travis CI or AppVeyor, but I cannot set it in the repository because Travis will not work anymore. 


> The only one test remain failed:
> ...
> The ../../output//cgi_test.cgi really is missing, the path must be ../../../output, but cgi_test.cgi does not exist at all:

On Travis CI and AppVeyor, cgi_test.c is created in a preparation step from cgi_test.c:
https://github.com/civetweb/civetweb/blob/master/test/cgi_test.c
This is copied into the directory required for the test here:
https://github.com/civetweb/civetweb/blob/master/test/public_server.c#L1281

**Comment by bel2125** [comment]
- [ ] I will remove the old "make unit_test" from "Makefile". It's a relic from an old version before CMake.
- [ ] You could use WITH_LUA=1 instead of WITH_LUA_SHARED=1 (then the build system does not need to find the system library), but for WITH_LUA_SHARED the LUA_SHARED_LIB_FLAG (https://github.com/civetweb/civetweb/blob/master/resources/Makefile.in-lua#L27) must be set appropriately. I'm not familiar with the liblua.so.5.2 naming (Suse?), Debian used liblua5.2.so.0 (https://packages.debian.org/jessie/i386/liblua5.2-0/filelist), but you can only link to different versions if the version is before .so, right? At least I don't know the compiler flag for libsomething.so.number.
- [ ] Could you try this with LOCAL_TEST set? Or do you have any idea how the "different path" problem can be solved? I could search for the files in the unit test.

**Comment by loafer-mka** [comment]
1. As I understood - make system is obsolete now, yes? The ./build script is the preferred way?

2. The naming scheme for shared libraries is not suse-specific, it is common for many distributions and it is based on libtool naming; for example suse documentation
https://en.opensuse.org/openSUSE:Shared_library_packaging_policy#Using_libtool
same naming scheme is used by buildroot, yocto... for building embedded systems, suse .. etc; libtool is a very common tool.

> At least I don't know the compiler flag for libsomething.so.number.
This is done by libtool's options, ... (yes, I prefer use gcc/ld directly, but ...)

The normally there must be symbolic links; for example
/usr/lib/liblua.so   ->   /usr/lib/liblua.so.5.3.0
/usr/lib/liblua.so.5.3.0
here liblua.so is a symbolic link to versioned shared library /usr/lib/liblua.so.5.3.0

someone symbolic links are used to maintain alternative naming scheme also (for example /usr/lib/liblua5.3.so --> /usr/lib/liblua.so.5.3.0),
for example - opensuse 13.2 (installed packages lua, lua-devel, liblua5_0, liblua5_1, liblua5_2; the liblua5_3 is not found in suse repository):
$ ls -l /usr/lib64/liblua*
/usr/lib64/liblua5.1.so.0 -> liblua.so.5.1
/usr/lib64/liblua.a
/usr/lib64/liblualib.so.5.0
/usr/lib64/liblua.so -> liblua.so.5.2
/usr/lib64/liblua.so.5.0
/usr/lib64/liblua.so.5.1
/usr/lib64/liblua.so.5.2

opensuse tumbleweed (the tumbleweed is linux based on a most recent packages... but updates are going one or few tens per day; so some files/symbolic links may be skipped and will be updated later; installed packages lua, lua-devel; the packages lua5_1, lu5_1-devel, lua5_2, lua5_2-devel were not installed, but 5.1 and 5.2 libraries presented)
$ ls -l /usr/lib64/liblua*
/usr/lib64/liblua5.1.so.0 -> liblua.so.5.1
/usr/lib64/liblua.a
/usr/lib64/liblua.so -> liblua.so.5.3
/usr/lib64/liblua.so.5.1
/usr/lib64/liblua.so.5.2
/usr/lib64/liblua.so.5.3

The common is using symboling link
/usr/lib64/liblua.so -> liblua.so.*latest*

Is it possible try to link with liblua.so (as for statis liblua.a) instead (or before) liblua5.2.so/liblua5.3.so ?
Of course, I can use symbolic link liblua5.3.so -> liblua.so.5.3.0, this is not a problem - for make build.

Anyway, when ./build is a preferable build method - which lua libraries are used? How to configure lua and/or
websocket etc. support by this script? How to define LOCAL_TEST using ./build?
make help is readable while ./build --help is too short ;)



>Вторник, 24 января 2017, 1:32 +03:00 от bel2125 <notifications@github.com>:
>
>*  I will remove the old "make unit_test" from "Makefile". It's a relic from an old version before CMake.
>*  You could use WITH_LUA=1 instead of WITH_LUA_SHARED=1 (then the build system does not need to find the system library), but for WITH_LUA_SHARED the LUA_SHARED_LIB_FLAG ( https://github.com/civetweb/civetweb/blob/master/resources/Makefile.in-lua#L27 ) must be set appropriately. I'm not familiar with the liblua.so.5.2 naming (Suse?), Debian used liblua5.2.so.0 ( https://packages.debian.org/jessi or e/i386 or /liblua5.2-0/filelist ), but you can only link to different versions if the version is before .so, right? At least I don't know the compiler flag for libsomething.so.number.
>*  Could you try this with LOCAL_TEST set? Or do you have any idea how the "different path" problem can be solved? I could search for the files in the unit test.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-----------
Regards,
Andrey

**Comment by loafer-mka** [comment]
The only one test remain failed:
>>...
>>The ../../output//cgi_test.cgi really is missing, the path must be ../../../output, but cgi_test.cgi does not exist at all:
>On Travis CI and AppVeyor, cgi_test.c is created in a preparation step from cgi_test.c:
>https://github.com/civetweb/civetweb/blob/master/test/cgi_test.c
>This is copied into the directory required for the test here:
>https://github.com/civetweb/civetweb/blob/master/test/public_server.c#L1281
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .
I'm try to search the string 'cgi_test' in civetweb folder; It is found in:
1) log file ./output/build/Testing/Temporary/LastTest.log (message about 'cannot copy')
2) executable ./output/build/test/main-c-unit-test
3) it's source tset/public_server.c
4) .travis.yml (command to build cgi_test)

but cgi_tset was not build _without_ travis ci environment... I think some Makefile must contain build commands.


-----------
Regards,
Andrey

**Comment by bel2125** [comment]
> but cgi_tset was not build _without_ travis ci environment... I think some 
> Makefile must contain build commands.

I agree, it would be better to build it with the test/CMakeFile. Currently it's in .travis.yml and appveyor.yml, since it's easier to do there. I will try to integrate it in the test/CMakeFile later.

But everything works for you now, if you build the cgi_test executable manually before starting the test, like done on travis and appveyor?

**Comment by bel2125** [comment]
In this issue, there was just one small topic unsolved: The CGI test executable is not built from the CMakeFiles

Currently building the test executable outside CMake serves as a test for the Travis and AppVeyor test environment as well. Rarely, but still from time to time, it is not possible to build the simple C test executable, for unknown reasons (maybe in a small percentage closing the build machine images goes wrong).

Although this might be somewhat unclean from the pure CMake point of view, it is actually helpful to distinguish between build system related and code/CMakeFile related issues. I added a diagnostic message to the test in case the CGI file is missing, and the user has to build it before starting the test. But at least for the moment, I will not build it in the CMake File.
