### ISSUE TITLE
PHP option engine=On 

### ISSUE THREAD

**Issue by quantuumsnot** [civetweb/civetweb#403]
Do we need it enabled for this server or not? Thanks in advance

**Comment by bel2125** [comment]
I never needed this option. According to the Apache documentation here (http://php.net/manual/en/apache.configuration.php), it is only used if you turn on and off PHP parsing on a per directory level.

If you have the proper file extensions in the cgi_pattern option (https://github.com/civetweb/civetweb/blob/master/docs/UserManual.md#cgi_pattern-cgiplphp), PHP can be used. 
See also cgi_interpreter (https://github.com/civetweb/civetweb/blob/master/docs/UserManual.md#cgi_interpreter).

**Comment by quantuumsnot** [comment]
Yes, options are default ones, only changed number of threads to be equal to number of CPU cores ...

**Comment by bel2125** [comment]
CivetWeb does not have a direct equivalent to the Apache .htaccess file used to enable/disable php parsing on a per directory base by setting the php engine parameter. Similar results can be reached in a different way. Of course the php engine must be "on" for php parsing, but that's the default anyway.

But, what is your real problem? Do you have a directory, where users can put files, and you don't want them to put .php files there? Or do you just want to get PHP running, and have some special php interpreter with "engine off" as a default?

I don't have enough information to understand your problem.

**Comment by quantuumsnot** [comment]
Sorry that wasn't clear enough and posting here as an Issue - just wondering if civetweb needs engine option to be On

**Comment by bel2125** [comment]
Up to now, I never touched the "engine" option, and everything worked with the defaults.

If you need help for a specific system:
Could you post your system information? The civetweb executable will print it with the "-I" command line option.

**Comment by quantuumsnot** [comment]
Windows 7 x64 and php is 7.0.9-TS-VC14-x64
Anyway I disabled the option and it works as usual

**Comment by bel2125** [comment]
So, can this issue be closed?

**Comment by quantuumsnot** [comment]
Yep
