### ISSUE TITLE
embedded.c example to add a C++ handler and get/set parameters/files from server using AngularJs web browser.

### ISSUE THREAD

**Issue by hiharsh** [civetweb/civetweb#404]
I successfully installed and build the civetweb. Ultimately, I would like to run embeded C++ server in my application and get response to the AngularJs client. 
I compiled the embedded_c.c  and executed it as below. 

```
smartcart@smartcart-VirtualBox:/media/sf_winshare/civetweb/civetweb-master/examples/embedded_c$ ls
embedded_c.c  Makefile
smartcart@smartcart-VirtualBox:/media/sf_winshare/civetweb/civetweb-master/examples/embedded_c$ vim Makefile
smartcart@smartcart-VirtualBox:/media/sf_winshare/civetweb/civetweb-master/examples/embedded_c$ make 
make -C ../.. WITH_IPV6=1 WITH_WEBSOCKET=1 COPT='-DNO_SSL_DL=1' clean lib
make[1]: Entering directory '/media/sf_winshare/civetweb/civetweb-master'
rm -rf out
rm -rf libcivetweb.a
rm -rf libcivetweb.so
rm -rf libcivetweb.so.1
rm -rf libcivetweb.so.1.10 .0
rm -rf civetweb
rm -f civetweb_test
cc -c -Wall -Wextra -Wshadow -Wformat-security -Winit-self -Wmissing-prototypes -DLINUX -Iinclude -DNO_SSL_DL=1 -DUSE_STACK_SIZE=102400 -O2 -DNDEBUG -DUSE_IPV6 -DUSE_WEBSOCKET -fPIC src/civetweb.c -o out/src/civetweb.o
ar cq libcivetweb.a out/src/civetweb.o
make[1]: Leaving directory '/media/sf_winshare/civetweb/civetweb-master'
cp ../../libcivetweb.a .
cc -o embedded_c -I../../include  -DUSE_WEBSOCKET -DUSE_IPV6  embedded_c.c libcivetweb.a -lpthread -ldl -lcrypto -lssl -DUSE_SSL_DH=1
smartcart@smartcart-VirtualBox:/media/sf_winshare/civetweb/civetweb-master/examples/embedded_c$ ls
embedded_c  embedded_c.c  libcivetweb.a  Makefile
```
smartcart@smartcart-VirtualBox:/media/sf_winshare/civetweb/civetweb-master/examples/embedded_c$ ./embedded_c
ECDH ciphers initialized

3 listening ports:

Browse files at http://127.0.0.1:8888/
Run example at http://127.0.0.1:8888/example
Exit at http://127.0.0.1:8888/exit

Browse files at http://[::1]:8888/
Run example at http://[::1]:8888/example
Exit at http://[::1]:8888/exit

Browse files at https://127.0.0.1:8843/
Run example at https://127.0.0.1:8843/example
Exit at https://127.0.0.1:8843/exit

Browse files at https://[::1]:8843/
Run example at https://[::1]:8843/example
Exit at https://[::1]:8843/exit

Browse files at http://127.0.0.1:8884/
Run example at http://127.0.0.1:8884/example
Exit at http://127.0.0.1:8884/exit
```
**Now, I would like to test this with Postman chrome extension followed by implementing my own handler on embedded.c to get status and send command to/from  C ++ server application from a  web browser/client (AngularJs).** Are there any example to achieve the same? And/or do you see any issue with the approach or any limitations that I need to be aware of?**

**Comment by bel2125** [comment]
Your build does not look too different from the Makefile in the embedded_c directory at first sight.

What is the actual problem? A browser cannot open http://127.0.0.1:8888/example?
Are you using virtual box? Browser and server in the same virtual machine?
Can you first try to open the page directly from a browser at the same machine, without any special browser extension? Can you access the server with curl or wget?

**Comment by hiharsh** [comment]
Hi @bel2125 , the issue associated with the browser has been resolved.  I am looking for answer for the following. 

Now, I would like to test this with Postman chrome extension followed by implementing my own handler on embedded.c to get status and send command to/from  C ++ server application from a  web browser/client (AngularJs).** Are there any example to achieve the same? And/or do you see any issue with the approach or any limitations that I need to be aware of?**

**Comment by bel2125** [comment]
I'm not an expert to AngularJS, but the Javascript library shouldn't make any difference to the server. Chrome Postman, Firefox HttpRequester or the Fiddler composer should also do more or less the same.

If you use C++, you could use the [embedded_cpp](https://github.com/civetweb/civetweb/blob/master/examples/embedded_cpp/) example. E.g. put a breakpoint [here](https://github.com/civetweb/civetweb/blob/master/examples/embedded_cpp/embedded_cpp.cpp#L204), and send a PUT request to http://localhost:8081/xy.foo

It's possible in C as well. The C++ wrapper just makes different handlers for different verbs (see [CivetServer.cpp](https://github.com/civetweb/civetweb/blob/master/src/CivetServer.cpp#L134)).

**Comment by bel2125** [comment]
Is there anything more I can do to help, or can we close this issue?

**Comment by bel2125** [comment]
No further questions regarding this topic, so I think we can close this issue.
