### ISSUE TITLE
cannot build embedded_cpp example

### ISSUE THREAD

**Issue by jguiban** [civetweb/civetweb#406]
Error reported from Ubuntu 16.04:

g++ -o embedded_cpp -I../../include   embedded_cpp.cpp libcivetweb.a -lpthread -ldl
embedded_cpp.cpp: In member function ‘virtual bool FooHandler::handlePut(CivetServer*, mg_connection*)’:
embedded_cpp.cpp:221:23: error: ‘strlen’ was not declared in this scope
         if (strlen(buf)>1020) {
                       ^
Makefile:27: recipe for target 'embedded_cpp' failed

The following line is missing:
`#include <cstring> `

**Comment by bel2125** [comment]
Thanks. include added.

**Comment by bel2125** [comment]
It works on my Ubuntu test machine, and I have not heard of any problem that still persists.
So I'm closing this issue now.
