### ISSUE TITLE
Build of slib fails

### ISSUE THREAD

**Issue by tbultel** [civetweb/civetweb#407]
Hi, build of slib is broken on master, due to a space in version information got by grep & sed.

**Comment by bel2125** [comment]
Reproduced and fixed on an Ubuntu system.
Could you please try if it's fixed for your system as well.

**Comment by bel2125** [comment]
It works on my Ubuntu test machine, and I have not heard of any problem that still persists.
So I'm closing this issue now.

**Comment by tkantor81** [comment]
I think grep -w is better, instead of white space at the end.

**Comment by bel2125** [comment]
You mean, replace
```
$(eval version=$(shell grep "define CIVETWEB_VERSION " include/civetweb.h | sed 's|.*VERSION "\(.*\)"|\1|g'))
```
by
```
$(eval version=$(shell grep -w "define CIVETWEB_VERSION" include/civetweb.h | sed 's|.*VERSION "\(.*\)"|\1|g'))
```
Thank's, I will try it.
