### ISSUE TITLE
Urldecode corrupts long strings

### ISSUE THREAD

**Issue by Vhati** [civetweb/civetweb#411]
Regarding CivetWeb 1.9.1, SourceForge build 32bit. (1.8 does it too.)

Something I noticed dealing with long form data.
The mg.url_decode() function unexpectedly truncates.

Code below illustrates this problem. It grows a string of uninteresting zeroes and checks if the string can make it through intact.
```
mg.write( "HTTP/1.0 200 OK\r\nContent-Type: text/plain\r\n\r\n" )

for i=1,3000,1 do
	local a = string.rep( "0", i )
	local b = mg.url_decode( a )
	if ( a ~= b ) then
		mg.write( "Decode broke at length: " .. i .. "\r\n" );
		mg.write( "a: " .. a .. "\r\n" );
		mg.write( "\r\n" );
		mg.write( "b: " .. b .. "\r\n" );
		break
	end
end

-- Result: Decode broke at length: 512
```

**System Info**
Server Version: 1.9.1
Windows 6.1
CPU: type 0, cores 4, mask f
Features: EFF
 Files HTTPS CGI IPv6 WebSockets Lua JavaScript Cache
Lua Version: 502 (Lua 5.2.4)
JavaScript: Duktape 1.5.2
Build: Jan  4 2017
MSC: 1600 (160040219)
Data model: int:2/4/4/8, float:4/8/8, char:1/2, ptr:4, size:4, time:8

**Comment by bel2125** [comment]
Currently mg.url_decode (lsp_url_decode in C) internally uses a 512 bytes destination buffer.

It is possible and meaningful to allocate the buffer dynamically, so the limit is the available memory, but in all versions up to now there is this 512 byte limit. I will change this in a the next version.

**Comment by bel2125** [comment]
The commit above removed the limit. All automatic unit tests succeed for the current version.

Do you build the server on your own, or do you need a pre-built executable?
Although all automatic unit tests succeed, I did not plan to build a release right now.

**Comment by Vhati** [comment]
> I did not plan to build a release right now
That's okay. I don't compile this myself, but there's no urgency to get a test build either.

It was easy enough to write my own function as a stand-in. I was just letting you know.

**Comment by bel2125** [comment]
Changed several weeks ago.
Closing this issue.
