### ISSUE TITLE
mg_store_body always returns 0 on success

### ISSUE THREAD

**Issue by sgmesservey** [civetweb/civetweb#421]
The variable `len' in mg_store_body never gets updated with
the byte count during writes.

The Civetweb docs say the return value is the number of bytes written.

I have attached a testcase which demonstrates the error.
A quick and easy test can be performed if you have bash
and curl available (Linux, OS X, MSys, Cygwin):
```sh
echo -e 'Hello, World!\nFoo\nBar\n' | curl -v --header "ContentType:text/plain" -X PUT -d @- host:port/hello.txt
```

I have also attached a patch which fixes the problem.
The files are stored in a zip due to GitHub policy
[mg_store_body.zip](https://github.com/civetweb/civetweb/files/801500/mg_store_body.zip)

**Comment by bel2125** [comment]
Thank you for your patch. I will add your test program to "test/public_server.c" later.

**Comment by bel2125** [comment]
Patch and test program are added to the repository.
Thank you for your contribution.
