### ISSUE TITLE
Blocked my UI when if there is no infinite while loop

### ISSUE THREAD

**Issue by xeoshow** [civetweb/civetweb#423]
Hello,

I am now trying integrate civetweb into my QT Application (with GUI). I have used the c++ wrapper and code as below:
>     <initial part code ...>
>
>     <begin: code to start CivetServer >
>     const char *options[] = {"document_root", DOCUMENT_ROOT, "listening_ports", PORT, 0};
>        std::vector<std::string> cpp_options;
>        for (int i = 0; i < (sizeof(options)/sizeof(options[0])-1); i++) {
>            cpp_options.push_back(options[i]);
>        }
>        CivetServer server(cpp_options); // <-- C++ style start
>        LOG(TRACE) << "CivetServer.started";
>    
>        while (!exitNow) {
>        #ifdef _WIN32
>                Sleep(1000);
>        #else
>                sleep(1);
>        #endif
>            }
>     <end: code to start CivetServer >
>
>      <code to start my GUI ...>

The civetweb can work well but the GUI can not be shown now, which seems was blocked. But if I remove the "while (!exitNow) {" infinite loop code, my GUI can be shown successfully, but looks like civetweb server started and then stopped immediately, since I tried to open the url for the server but failed.

Anything I did wrong and how to resolve? Thanks!

**Comment by bel2125** [comment]
I do not know your application, and I'm not sure if I get the problem correctly.

What you want to do is probably `CivetServer *myServer = new CivetServer(cpp_options);`

Or, you just use the C interface and call `mg_start(...)`

**Comment by xeoshow** [comment]
Thanks for help!
