### ISSUE TITLE
Question: serve html file

### ISSUE THREAD

**Issue by bellekci** [civetweb/civetweb#424]
I am using civetweb embedded into my exe.

I would like to serve an html file that needs other files such as an image file.

How I return the first html file to the requester is as follow:

```
int webUIHandler(struct mg_connection *conn, void *cbdata)
{

	/* Handler may access the request info using mg_get_request_info */
	const struct mg_request_info *req_info = mg_get_request_info(conn);
	int returnCode = REQUEST_OK;
	std::string requestMethod = req_info->request_method;
	std::string requestedCommand = req_info -> local_uri;
	
		if(requestMethod.compare("GET") == 0)
		{
			const char *fileName = (const char *)"index.shtml";
			mg_send_file(conn, fileName);
		}			
		else
		{
			mg_printf(conn, http_notAllowedErrorHeader.c_str());
			returnCode = REQUEST_NOT_SUPPORTED; // NOT SUPPORTED REQUEST
		}

	return returnCode;
}
```

I get the sense that I am doing sth wrong since my images do not show. (or simply any other file such as css, js, etc. is not downloaded by the browser).

The path for the image file is correct. I checked it by simply opening index file locally with Chrome. I have also tried 100images.htm accompanied with imagetest folder but same problem.

I would be happy if you could point me to the right direction.

**Comment by bellekci** [comment]
I have noticed another thing. If I try the addresses which I did not set a request handler for, I get the root file. For ex, if I have the following request handler for the root dir at port 27000:

`		mg_set_request_handler(serverContext, "", webUIHandler, cbdata);
`

And I try the address 127.0.0.1:27000/asdasdads returns me just like 127.0.0.1:27000/.

Why does this happen?

**Comment by bellekci** [comment]
Ok I have solved my problems.

Latter one: as shown in example.c, I had to add $ to the end of local address to match exactly.

For the first one, I have added handlers for generic files such as:

```
mg_set_request_handler(serverContext, "**.js$", fileHandler, cbdata);
mg_set_request_handler(serverContext, "**.png$", fileHandler, cbdata);
mg_set_request_handler(serverContext, "**.css$", fileHandler, cbdata);
```
 and fileHandler simply returns:

```
	const struct mg_request_info *req_info = mg_get_request_info(conn);
	int returnCode = REQUEST_OK;
	std::string requestMethod = req_info -> request_method;
	std::string requestedFile = req_info -> local_uri;
	QString exePath = qApp->applicationDirPath();
	std::string fullFile = exePath.toStdString() + requestedFile;
	if(fileExists(fullFile))
	{
		//std::cerr << "Sending file: "<<fullFile << std::endl;
		mg_send_file(conn, fullFile.c_str());
	}
	else
	{
		mg_printf(conn, http_fileNotFoundErrorHeader.c_str());
		//std::cerr << "Could not find file: "<<fullFile << std::endl;
	}

	return returnCode;
```

**Comment by bel2125** [comment]
If you want to serve static files (images, html, ...), you could also just put them into a directory, set the document_root there, and the server will handle it.
You only need handlers for content you want to create dynamically, depending on some data within your exe.

But this is also shown in the embedded_c example.

Did you already find an answer to all open topics?

**Comment by bellekci** [comment]
OK, I will give it a try with the document_root. I have not set it.

Yes, all of my problems are solved. You can close this issue.
