### ISSUE TITLE
send_http_error as public API

### ISSUE THREAD

**Issue by PhilLab** [civetweb/civetweb#427]
Is there a reason behind ``send_http_error`` not being published in the header files? It seems like a useful API function

**Comment by bel2125** [comment]
Main reason is no one asked for it yet ;-)

I will have a look if there is anything problematic, e.g. regarding possible future compatibility issues.

**Comment by bel2125** [comment]
Actually, there is no reason not to have this as public API.
So I added it there: 5bd621ccf131dcade5cf77ed3df8190792c81c78

**Comment by PhilLab** [comment]
thanks 👍
