### ISSUE TITLE
return value of the log_access callback is not evaluated

### ISSUE THREAD

**Issue by extergnoto** [civetweb/civetweb#435]
The return value of the log_access callback is not evaluated.
civetweb version 1.9.1

static void
log_access(const struct mg_connection *conn)
{
...
	if (conn->ctx->callbacks.log_access) {
		conn->ctx->callbacks.log_access(conn, buf);
	}
...
}

**Comment by extergnoto** [comment]
It would be good if the extensive fomatting of the buffer could be avoided totally when the log_access callback returns non zero.
The reason is: I have limited space in a log message. Therefore I have to use a shorter format which renders the long message useless anywany. Formatting the buffer is waste of time and stack space.
Maybe the formatting could extracted and provided as a public helper for those who can benefit from it.

**Comment by bel2125** [comment]
I'm not sure what you mean. The function is currently like
```C
static void
log_access(const struct mg_connection *conn)
{
    if (no log_file && no log_access callback) {return}

    format buf

    if (conn->ctx->callbacks.log_access) {
        no_return_value = conn->ctx->callbacks.log_access(conn, buf);
    }

    if (logfile) {
       write buf to logfile
    }
}
```

What do you want to avoid by adding a return value? The buffer formatting is done before, since it is passed as an argument to log_access. Adding a return value there will not avoid any formatting before the function was called. The only work that could be avoided it writing buf to logfile, but that is already avoided by not specifying any log file.

**Comment by extergnoto** [comment]
I think with "currently" you mean code not yet published, because I cannot see it in the master branch.

What looked like a bug to me, is not evaluating the return value.

Just to clarify: What I meant in my second comment is a solution like below. But it´s probably better to leave it like it is.

// Not really a good name
public void mg_format_access_buffer(conn, buffer, ...)
{
  format buf...
}

static void
log_access(const struct mg_connection *conn)
{
    if (no log_file && no log_access callback) {return}

   // no format buf here

    if (conn->ctx->callbacks.log_access) {
        no_return_value = conn->ctx->callbacks.log_access(conn);
    }

    if (logfile && !no_return_value) {
       char buffer[big];
        mg_format_access_buffer(conn, buffer, ...);
        write buf to logfile
    }
}

If anyone needed a formatted buffer in the callback, he can use mg_format_access_buffer().
Otherwise, if a formatted buffer is needed in a callback AND in a file, formatting is done twice.
