### ISSUE TITLE
Number of crypto locks can be zero with wolfSSL

### ISSUE THREAD

**Issue by extergnoto** [civetweb/civetweb#436]
civetweb 1.9.1

The number of crypto locks can be zero when using wolfSSL. 
I have marked the changes I have made with WOLFSSL.

static int
initialize_ssl(struct mg_context *ctx)
{
	int i;
	size_t size;

#if !defined(NO_SSL_DL)
	if (!cryptolib_dll_handle) {
		cryptolib_dll_handle = load_dll(ctx, CRYPTO_LIB, crypto_sw);
		if (!cryptolib_dll_handle) {
			return 0;
		}
	}
#endif /* NO_SSL_DL */

	if (mg_atomic_inc(&cryptolib_users) > 1) {
		return 1;
	}

	/* Initialize locking callbacks, needed for thread safety.
	 * http://www.openssl.org/support/faq.html#PROG1
	 */
	i = CRYPTO_num_locks();
	if (i < 0) {
		i = 0;
	}
	size = sizeof(pthread_mutex_t) * ((size_t)(i));
#ifdef WOLFSSL
	/*
	 * CRYPTO_num_locks in WOLFSSL may return zero, which is totally immaculate,
	 * but then we have to bypass some of civetwebs assertions and replace them with our own
	 * modified assumptions
	 */
	if (size == 0) {
		ssl_mutexes = NULL;
	}
	else 
   {
#endif // WOLFSSL
	if ((ssl_mutexes = (pthread_mutex_t *)mg_malloc(size)) == NULL) {
		mg_cry(fc(ctx),
		       "%s: cannot allocate mutexes: %s",
		       __func__,
		       ssl_error());
		return 0;
	}
#ifdef WOLFSSL
	}
#endif // WOLFSSL

	for (i = 0; i < CRYPTO_num_locks(); i++) {
		pthread_mutex_init(&ssl_mutexes[i], &pthread_mutex_attr);
	}

	CRYPTO_set_locking_callback(&ssl_locking_callback);
	CRYPTO_set_id_callback(&mg_current_thread_id);

	return 1;
}

**Comment by bel2125** [comment]
I think the `if (size == 0) {ssl_mutexes = NULL;}` could be done in every case `CRYPTO_num_locks` returns 0, so we don't need the `#ifdef WOLFSSL`.
I did this in d2ebc9d35d62d82e9f6578e96296d03f25e044b1 - could you please test it!

Is the `#ifdef WOLFSSL` some *official* define? Is it set in the header, or do you need to set it manually (in the Makefile)?

**Comment by extergnoto** [comment]
You are right, the size check can always be done. 

The "WOLFSSL" define is just a marker for my code changes. 
It is not an official define from the WOLFSSL stack.

Official defines are:

version.h
#define LIBWOLFSSL_VERSION_STRING "3.10.2"
#define LIBWOLFSSL_VERSION_HEX 0x03010002

ssl.h
#define WOLFSSL_VERSION LIBWOLFSSL_VERSION_STRING

Unfortunately I cannot test at the moment, because the test target is unavailable, but my code from above has been successfully tested. I looked at your change and it looks good.

Thanks.

**Comment by bel2125** [comment]
Then probably `#ifdef WOLFSSL_VERSION` would be the natural check, in cases a SSL implementation dependent code is required. Here it can be done without this check.

Will you do a check some time later, and close the issue, or do you think we can close it immediately with my fix?

**Comment by extergnoto** [comment]
I think we can close it.
Once I get the hardware I´ll test it.
