### ISSUE TITLE
wolfSSL does not support certificate chain files that contain private keys and certificates in one file

### ISSUE THREAD

**Issue by extergnoto** [civetweb/civetweb#437]
wolfSSL does not support certificate chain files that contain
private keys and certificates in its method SSL_CTX_use_certificate_chain_file
The CivetWeb-Server on the other hand requires pem-Files that contain
both information.

What I die: Use of two files. One file that contains key and certificate
that is used by the server and and optional chain file for the ssl stack.
In the current implementation I require the chain file to be in the same location as the
ssl-certificate and to have the same name followed by the extension .chain.pem
If no such file is found the certificate chain will not be verified.

**Comment by bel2125** [comment]
Sorry, I do not really understand the state of this issue?
Does anything in the civetweb.c implementation need to be changed, so it works this way with wolfSSL?
Or is this the default behaviour of wolfSSL, and should be documented?
There is already some documentation: https://github.com/civetweb/civetweb/blob/master/docs/yaSSL.md but it is not maintained and probably quite outdated.

**Comment by extergnoto** [comment]
This is the code we currently use with civetweb 1.9.1:
[ssl_use_pem_file.txt](https://github.com/civetweb/civetweb/files/871935/ssl_use_pem_file.txt)
Without the change the call to SSL_CTX_use_certificate_chain_file() fails for wolfSSL (version 3.10.2).

I don't know, if the approach with .chain.pem ist best for all use cases. Maybe a separate configuration item is better, because our solution is a little intransparent. We did it like that to keep changes to the existing code minimal. 

SSL_CTX_use_certificate_chain_file is mapped to wolfSSL_CTX_use_certificate_chain_file. 
wolfSSL documentation sais: "The server and client can send certificate chains using the 
wolfSSL_CTX_use_certificate_chain_file() function.  The certificate chain file must be in 
PEM format and must be sorted starting with the subject's certificate (the actual client or 
server cert), followed by any intermediate certificates and ending (optionally) at the root 
"top" CA. "

**Comment by bel2125** [comment]
This looks like it could be done without `#ifdef WOLFSSL` (or better `#ifdef WOLFSSL_VERSION`) as well. Your code searches for a file "server.pem.chain.pem" (two "pem", if the ssl file "server.pem" is used as in the examples).
For the server, one could add a new configuration option (like "ssl_certificate_chain", default NULL, taking the value of "ssl_certificate"). But this is not possible for the client (mg_connect_client, struct mg_client_options) - I'm not sure if it is required for the client interface.

**Comment by bel2125** [comment]
With 95603a3a74c9d6ae68cf10448835ff42f8e107a6 I added a server configuration option to split the information into two files. It's not tested with wolfSSL.

**Comment by extergnoto** [comment]
It looks good.
I will test it when I have access to the hardware. Can take some time.
For the time being the ticket can be closed, I think.

**Comment by extergnoto** [comment]
I tested it and it works as expected.

**Comment by bel2125** [comment]
Thanks for your feedback.
