### ISSUE TITLE
Seems bug with `handle_static_file_request` function

### ISSUE THREAD

**Issue by khanhbui** [civetweb/civetweb#440]
I've built for android and got the issue that the content length is zero if `is_file_in_memory` returns `true`.

I checked and found that in case of `is_file_in_memory` returns `true`, the filep->stat.size has not set yet.

```c
if (filep->stat.size > INT 64_MAX) {
    send_http_error(conn,
                               500,
                               "Error: File size is too large to send\n%" INT64_FMT,
                               filep->stat.size);
}
cl = (int64_t)filep->stat.size;
```
This block code should be place after `mg_fopen` and `fclose_on_exec`. Like this

```c
if (!mg_fopen(conn, path, MG_FOPEN_MODE_READ, filep)) {
    send_http_error(conn,
		                500,
		                "Error: Cannot open file\nfopen(%s): %s",
		                path,
		                strerror(ERRNO));
    return;
}

fclose_on_exec(&filep->access, conn);

if (filep->stat.size > INT 64_MAX) {
    send_http_error(conn,
                               500,
                               "Error: File size is too large to send\n%" INT64_FMT,
                               filep->stat.size);
}
cl = (int64_t)filep->stat.size;
```

Please help to check.

**Comment by khanhbui** [comment]
I created a pull request for this https://github.com/civetweb/civetweb/pull/441

**Comment by bel2125** [comment]
If a file is in memory, the size should be set - at least in the current version and the latest release.
What version are you using?
Maybe I missed some code path where it is not set? But if, this should be fixed there.

Are you actually using the "file in memory" feature? There is currently a discussion to remove it, if it is not used (see https://groups.google.com/forum/#!topic/civetweb/h9HT4CmeYqI). I think it's superseded by callbacks since years, but maybe I missed some important use case, and I would like to understand these use cases.

**Comment by khanhbui** [comment]
I'm using v1.9.1

**Comment by khanhbui** [comment]
I'm embedding civetweb to my android app. 
With android, you can not `fopen` the file in the 'assets' directory, instead, you have to use `Resource Manager` to read. So I wrote a JNI code to make this work
```c
buf = conn->ctx->callbacks.open_file(conn, path, &size);
```

**Comment by bel2125** [comment]
May I ask you to try the following alternative:


1. Start the server with `ctx =mg_start(...)` without open_file callback
2. Open the required files from the assets. Are you using [ACCESS_BUFFER](https://developer.android.com/reference/android/content/res/AssetManager.html#ACCESS_BUFFER) to map the buffer into memory, or are you reading the file and storing a copy of the content?
3. Register callbacks for all file names you would handle in your open_file callback: `mg_set_request_handler(ctx, fileName, FileInMemoryHandler, new CBufferAddrAndSize(fileMapAddr, fileSize))` (CBufferAddrAndSize is some data structure storing all relevant data, at least mapping address and mapping size)
4. Send the content directly from the FileInMemoryHandler callback. It could look like this:
```C
int ExampleHandler(struct mg_connection *conn, void *cbdata) {
    CBufferAddrAndSize bs = (CBufferAddrAndSize*)cbdata;
    mg_printf(conn,
              "HTTP/1.1 200 OK\r\n"
              "Content-Type: text/plain\r\n"
              "Content-Length: %lu\r\n"
              "\r\n",
              (long unsigned)bs->size);
    mg_write(conn, bs->address, bs->size);
}
```

It would be very helpful for us to understand if this works, or if there are any aspects we did not consider yet.

**Comment by bel2125** [comment]
Original pull request merged, and no further update since almost 1 year --> closing this issue now.
