### ISSUE TITLE
How to access Post request body

### ISSUE THREAD

**Issue by saggoyal12** [civetweb/civetweb#442]
Hi,

I can see method to access request header i.e mg_get_header(), but could not find any method access request_body (for POST request). Please point me to method or sample code.

Thanks,
Sagar

**Comment by bel2125** [comment]
`PostResponser` mirrors the body back to the client:
https://github.com/civetweb/civetweb/blob/master/examples/embedded_c/embedded_c.c#L466

**Comment by bel2125** [comment]
Do you need any more help, or can we close this issue?

**Comment by bel2125** [comment]
No further questions, so let's close this issue.

**Comment by KlausLionizers** [comment]
Hello,

I want to handle a form that gets filled using lua. I already have an init_lua_callback with a **const** struct mg_connection *conn
So I guess I need an additional request handler callback to be able to use mg_read to get the POST data, right?

Using civetweb 1.13
Thanks in advance

**Comment by bel2125** [comment]
This issue is closed since quite a while.
You may have a look at this example: https://github.com/civetweb/civetweb/blob/master/test/handle_form.lua
But for any additional discussion, we should use a new issue.
