### ISSUE TITLE
Proposed patch: conditionally disable SSL_VERIFY_FAIL_IF_NO_PEER_CERT

### ISSUE THREAD

**Issue by sgmesservey** [civetweb/civetweb#443]
Hello,
  I have here a patch that adds a new config option, 
`SSL_FAIL_IF_NO_PEER_CERT`:
`{"ssl_fail_if_no_peer_cert", CONFIG_TYPE_BOOLEAN, "yes"}`
It retains default Civetweb behavior: if the user doesn't configure it,
the server will reject connections without a client certificate.
If the user configures it with a value of 'no',
Civetweb will still process SSL connections without a certificate, but the
`client_cert` field in `request_info` will be NULL.

This allows end users / embedders to define `mg_authorization_handler`s that can reject
or accept SSL connections to individual URIs based on the presence of a client cert,
instead of all or nothing.

Patch is here: [gist](https://gist.github.com/sgmesservey/1cdf90eaf23520ed734baeb14249164a)

**Comment by bel2125** [comment]
So, the idea is to have an `mg_authorization_handler`, and check the `client_cert` structure in `mg_request_info`. That's essentially a good idea. 
I'm just afraid, the configuration gets somewhat confusing.

`ssl_fail_if_no_peer_cert` will not do anything if `ssl_verify_peer` is not set.
It could be better to change the type of `ssl_verify_peer` from *boolean* (`yes`/`no`) to *multi-state* `yes`/`no`/`optional`, where `optional` means "do not set the `SSL_VERIFY_FAIL_IF_NO_PEER_CERT` flag".

I think this "boolean" to "multi-state" transition of options could be useful for other options as well. I just have to check how to set the option type properly. `CONFIG_TYPE_STRING` would work, but looses all semantics. And the windows configuration GUI should understand it as well, and show some list box.

What do you think?

**Comment by bel2125** [comment]
I tried to implement it as an additional option value for ssl_verify_peer. 
Please have a look. I did not do a test yet.

**Comment by sgmesservey** [comment]
Sorry, I replied by email to your first comment.
This looks perfect, thanks!

**Comment by bel2125** [comment]
Patch added two weeks ago.
Closing this issue.
