### ISSUE TITLE
Memory leak on client side

### ISSUE THREAD

**Issue by thilbern** [civetweb/civetweb#448]
When performing a simple http request on client side, a memory leak is present.

Code to produce the leak:

`char ebuf[1000];`
`struct mg_connection * conn = mg_download("google.com", 80, 0, ebuf, sizeof(ebuf), "%s", "GET / HTTP/1.0\r\nHost: google.com\r\n\r\n" );`
`mg_close_connection(conn);`

The following allocation is never free:

`mg_connect_client_impl(...){`
`   ...`
`   mg_calloc(1, sizeof(*conn) + MAX_REQUEST_SIZE)) == NULL)`
`   ...`
`}`

Code to fix the leak:

`mg_close_connection(struct mg_connection *conn){`
`    ...`
`    if (client_ctx != NULL) {`
`    /* free context */`
`    mg_free(client_ctx->worker_threadids);`
`    mg_free(client_ctx);`
`    (void)pthread_mutex_destroy(&conn->mutex);`
`    mg_free(conn);`
**`    } else if (conn->ctx->context_type == 0) {//Client`
`        mg_free(conn);`
`    }`**
`}`

Valgrind output

`==26288== `
`==26288== HEAP SUMMARY:`
`==26288==     in use at exit: 17,832 bytes in 1 blocks`
`==26288==   total heap usage: 294 allocs, 293 frees, 72,269 bytes allocated`
`==26288== `
`==26288== LEAK SUMMARY:`
`==26288==    definitely lost: 17,832 bytes in 1 blocks`
`==26288==    indirectly lost: 0 bytes in 0 blocks`
`==26288==      possibly lost: 0 bytes in 0 blocks`
`==26288==    still reachable: 0 bytes in 0 blocks`
`==26288==         suppressed: 0 bytes in 0 blocks`
`==26288== Rerun with --leak-check=full to see details of leaked memory`
`==26288== `
`==26288== For counts of detected and suppressed errors, rerun with: -v`
`==26288== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)`

Best regards,

Bernard THILMANT

**Comment by bel2125** [comment]
Fixed by #449
