### ISSUE TITLE
WebSocket Client to test examples

### ISSUE THREAD

**Issue by juvasquezg** [civetweb/civetweb#451]
Hi,

I want to test websocket but  I get

```js
(index):11 WebSocket connection to 'ws://192.168.1.48:8081/ws' failed: Error during WebSocket handshake: Unexpected response code: 404
```

The server say 

```bash
Run websocket example at http://localhost:8081/ws
```

My test script is

```js
         var ws;
	 window.onload=function(){
	   ws=new WebSocket("ws://192.168.1.48:8081/ws");
	   ws.onmessage=function(evt){console.log(evt.data);};
	   ws.onopen=function(evt){
		 ws.send("Hello");
	   }
	 }
	 window.onclose=function(){
	   ws.close();
	 }
```

can I test ?

Thank you!!

**Comment by juvasquezg** [comment]
Hi,

Excuse me  I changed my websocket url **[ws://192.168.1.48:8081/webSocket]**
 
Can I create a client from civetweb C++?

Thank you!!

**Comment by bel2125** [comment]
Currently there is no object oriented C++ interface, but of course you can use the C interface (civetweb.h) also from C++.

There are a few issues in the client interface I would like to change soon (https://github.com/civetweb/civetweb/blob/master/docs/Interface_Changes_1.10.md#client-interface), so there will be some minor changes to the interface soon, or a mg_connect_client2 interface.

**Comment by bel2125** [comment]
You can find an example code here: https://github.com/civetweb/civetweb/blob/master/test/public_server.c#L1648
```C
/* Websocket test */
#ifdef USE_WEBSOCKET
	/* Then connect a first client */
	ws_client1_conn =
mg_connect_websocket_client(...
```

**Comment by juvasquezg** [comment]
Hi, 

Excuse me for the question, I need to send a JSON message via WebSocket using C/C++ The JSON is something like

```js
{
  id: 1,  // video
  stream: video binary data
}
```

```js
{
  id: 2,  // audio
  stream: audio binary data
}
```

With C/C++ Is it easier to first send the type of data and then send the data?

**Comment by bel2125** [comment]
If you want to send JSON data from a websocket server, you probably need something like this:

```C
        char * txt = cJSON_Print(json_object);
        mg_lock_connection(ws_client1_conn);
	mg_websocket_client_write(ws_client1_conn,
	                          WEBSOCKET_OPCODE_TEXT,
	                          txt,
	                          strlen(txt));
        mg_unlock_connection(ws_client1_conn);
        free(txt);

```

Here I was using cJSON (https://github.com/DaveGamble/cJSON), but you might use a different library as well.

**Comment by bel2125** [comment]
Do you need anything else, or can we close this issue?

**Comment by juvasquezg** [comment]
Hi, 

Really, thank you. Closed. Great. You are a master.

**Comment by bel2125** [comment]
Thanks ;-)
