### ISSUE TITLE
mg_websocket_connect_handler can't set user conn data without type-cast

### ISSUE THREAD

**Issue by snej** [civetweb/civetweb#452]
A `mg_websocket_connect_handler` is passed a const pointer to `mg_connection`. I think this is so that it can't write to the connection? But one thing it's likely to want to do is link the connection to its own object or struct. Unfortunately `mg_set_user_connection_data` takes a non-const connection pointer, so the call will fail.

Obviously one can work around this by casting the parameter, i.e.
```c
mg_set_user_connection_data((struct mg_connection*)conn, myObject);
```
but the API shouldn't be designed in such a way that a client has to break const-safety to use it.

My suggested fix would be to change `mg_set_user_connection_data` to take a const pointer. (Internally it'll have to cast, but that kind of workaround does happen in implementations.)

**Comment by bel2125** [comment]
`mg_connection` is an opaque data type, more like a handle - you cannot access any members of this structure from outside civetweb.c (and the *.inl files). Thus, there is no intrinsic meaning of `const` as defined from the programming language.
You are right, the `const` here means, you must not use `mg_write`, but also not `mg_read`. So, what's essentially const, is the data in the send/receive buffers.

On the other hand, setting members of a `const` object using a setter is somewhat weird either.
`mg_set_user_connection_data(const mg_connection * conn, void *data)`

But I just checked my code, I have this cast as well.

**Comment by bel2125** [comment]
Now there is a new callback to initialize the user connection data:
```C
	/* Called when initializing a new connection object.
	 * Can be used to initialize the connection specific user data
	 * (mg_request_info->conn_data, mg_get_user_connection_data).
	 * When the callback is called, it is not yet known if a
	 * valid HTTP(S) request will be made.
	 * Parameters:
	 *   conn: not yet fully initialized connection object
	 *   conn_data: output parameter, set to initialize the
	 *              connection specific user data
	 * Return value:
	 *   must be 0
	 *   Otherwise, the result is undefined
	 */
	int (*init_connection)(const struct mg_connection *conn, void **conn_data);

```
The intended use is to allocate memory for a user defined data structure in this callback.
It can be freed again in `connection_close`.

Every other callback should only use the *get* function
```C
/* Get user data passed to mg_start from context. */
CIVETWEB_API void *mg_get_user_data(const struct mg_context *ctx);
```
to get this user defined data structure. The pointer to this data is not a "const", so it is possible to update the information there without a const cast. The `mg_set_user_data` function is no longer required, but it will remain to keep the interface compatible (at least for a while ... it may be marked as deprecated and fade out after several versions).

**Comment by bel2125** [comment]
The current release has interfaces that can be used to avoid const_casts (see comments above and code in the example directory).
