### ISSUE TITLE
Is it possible to use a certificate file from memory?

### ISSUE THREAD

**Issue by nntrab** [civetweb/civetweb#454]
For a project I am working on I need to store the certificate file in a database of sorts, rather than the host OS file system. Getting it into memory is trivial but passing it to CivetWeb doesn't appear to be possible. Have I missed an option?

At first I thought the 'init_ssl' callback might offer a solution, admittedly with some duplication of some of the code in 'set_ssl_option()',  but there appear to be 2 uses of the 'SSL_CERTIFICATE' config attribute, one which does check 'init_ssl' (in 'set_ssl_option()') and one which doesn't (in 'refresh_trust()'), even though a comment in that function suggests that it should be. This would seem to preclude using the 'init_ssl' callback.

If there isn't currently any method of achieving this, how would you prefer it implemented? Maybe use the HTML embedded image paradigm and prepend 'data:' to the PEM file data? In that way no new option would need to be created and only 'ssl_use_pem_file()' would need to be modified.  Looking at the source for 'SSL_CTX_use_certificate_chain_file()' and its ilk suggests it would be then possible to use a BIO memory file to process the data.

**Comment by bel2125** [comment]
`refresh_trust` is only called, if the `ssl_short_trust` config option is set. Are you using short trust certificates as well?

**Comment by nntrab** [comment]
Nope, not at this time.

**Comment by bel2125** [comment]
Then, overriding `init_ssl` should be sufficient.

On the long term, we probably need some `reinit_ssl` for short trusts, or just call `init_ssl` again.

**Comment by nntrab** [comment]
OK, I'll look into that route further then, Thank you.
