### ISSUE TITLE
Embedded C application - Handle http requests with LUA? 

### ISSUE THREAD

**Issue by eamonnmg** [civetweb/civetweb#455]
Hi,

I have an embedded C application using Civetweb to serve a simple web interface. I currently use handlers written in c. However the web interface now needs much more functionality. I am convinced Lua a is much better suited for processing http requests and performing database operations. It also means we can still access the main device program written in C.

Can I receive a http request and hand it off to a Lua script where it can be parsed and return a response to the browser? 

Are there any docs that illustrate how to do this? 

I do not have much experience in this domain and perhaps i am on the wrong track.

Any guidance would be greatly appreciated.

Thanks

**Comment by bel2125** [comment]
That's exactly what I do all the time ;-)

Did you try to build the standalone server (or download the pre-compiled one from SourceForge), and run the *.lua examples in the test directory (https://github.com/civetweb/civetweb/tree/master/test)?

If you have Linux:
```sh
cd /path/to/civetweb
make WITH_LUA=1 WITH_WEBSOCKET=1
./civetweb -document_root test
```
then start a browser to http://localhost:8080 and open all the *.lua files there.

**Comment by eamonnmg** [comment]
Thanks for the reply!
Ive got the test scripts running. So you just direct your forms or ajax requests to a Lua script similar to php? 

What about setting up a router for friendly URL's? I'm trying to make a json api for an spa. Have you tried any thing like that before?

Also, if i register a C function with the Lua c api i will have have access to it in any Lua script, right?

I have an alternative solution which may be better giver my experience.
I could install an nginx server on the raspberry pi we are developing on. I could then build the web app using languages and tools I am familiar with (php/laravel). When I need to interface with the device code written in C i could use curl from the php app to a civetweb server embedded in the main C program. By this time any input sent to the c application will be validated on the php side.

I am leaning towards this solution now as it should keep me further away from C code!

Thanks for you help.

**Comment by bel2125** [comment]
> So you just direct your forms or ajax requests to a Lua script similar to php?

Essentially yes. I have some Lua libraries in the `lua_preload` configuration, to simplify request handling, but essentially Lua creates the response.

> What about setting up a router for friendly URL's?

User friendly, search engine friendly, ...? https://techterms.com/definition/friendly_url
You can use sub-resources of Lua scripts, like
http://localhost:8080/resource.lua/some/friendly/path
You can also get rid of the .lua in resource.lua by creating a folder resource and using an index.lua there.

> I'm trying to make a json api for an spa. Have you tried any thing like that before?

So it's a home automation project for a wellness spa? I've done some automation, but no spa yet.
You would add a JSON parsing library in the lua_preload (like https://github.com/harningt/luajson/tree/master/lua), to convert between Lua tables and JSON representations.

> Also, if i register a C function with the Lua c api i will have have access to it in any Lua script, right?

You would use the `init_lua` callback to add your functions. Or you build a standard Lua library, then you don't need this callback.

> I have an alternative solution which may be better giver my experience. ...

Technically, you could do that.
For me, it seems somewhat overkill to have two web servers. First of all, if you want to use PHP, you could also do this in Civetweb by using CGI. If you want to use nginx and PHP, you could just read the data you need from a named pipe (mkfifo) to just read/write from/to the C application without using civetweb. Two servers need additional resources, additional interprocess communication, additional development and maintenance effort for a more complex architecture.

But, of course, it's up to you.

> I am leaning towards this solution now as it should keep me further away from C code!

If you just need some read/write interface for variables in C, it's just a few lines of code. I can post an example, if this is what you need.

By the way: If you prefer JavaScript to Lua, you could write your server side scripts in JavaScript as well. See all the *.ssjs ("Server-Side Java-Script") files in the test directory.

**Comment by eamonnmg** [comment]
Sorry for only getting back to you now.

For the time being I have decided to move away from the lua solution. However your information has been very helpful and has given us a better picture of our options. 

Thank you for your help!

**Comment by bel2125** [comment]
You are welcome.
I'm closing this issue now. If you have further questions, feel free to ask.
