### ISSUE TITLE
Adding support for hostnames in option listening_ports 

### ISSUE THREAD

**Issue by nfrmtkr** [civetweb/civetweb#462]
Civet web doesn't support configuring listening ports bound to interfaces by providing a hostname. It leads to error, for instance with hostname "foo" and port 5000:

foo:5000: invalid port spec (entry 1). Expecting list of: [IP_ADDRESS:]PORT[s|r]

It would be convenient to have civetweb resolving the hostname to an IP adress, before opening the socket.

**Comment by bel2125** [comment]
I think hostnames are not really useful here, since one host may have multiple interface cards. One could use interface names like eth0, eth1, ... on Linux, but that's different on Windows and I don't know for OSX, iOS and others.
If you just want to bind to any adapter on the current host, you don't need to specify an IP address at all.

**Comment by bel2125** [comment]
I think hostnames are not really useful here, since one host may have multiple interface cards. One could use interface names like eth0, eth1, ... on Linux, but that's different on Windows and I don't know for OSX, iOS and others.
If you just want to bind to any adapter on the current host, you don't need to specify an IP address at all.

**Comment by nfrmtkr** [comment]
Well, for each interface card a specific hostname can be defined (also in DNS). In case of IPv6 addresses it is more convenient to use a hostname instead the IPv6 address and using the hostname makes the configuration independend of IP changes.

**Comment by bel2125** [comment]
From my understanding, hostname is whatever is set in `/etc/hostname` in Linux, in Windows it's the "Computer name" defined in some system settings dialog. And there is only one for every interface.

Probably you could use `/etc/hosts` and take the names from there. The default seems to be, the hostname is assigned to 127.0.0.1, so you would have to change this default to some static IP address.
Is this, what you are proposing?
This will not work for DHCP (or ZeroConf/Bonjour/Avahi or anything else than static IPs) ... it might work with the .local domain ... I did not test it.

Just that I get the idea correctly ...

**Comment by nfrmtkr** [comment]
There is also hosts file on Windows (C:\Windows\system32\drives\etc\hosts). But most network configuration suse DNS in order to resolve a hostname to IP address.  DHCP configurations may work as well, for servers usally MAC-Address pinning is used in order to provide the allways the same IP for the interface. 
Given a hostname you can use getaddrinfo() function on Unix and Windows in order to get a list of struct addrinfo items.

**Comment by bel2125** [comment]
I know DNS, MAC pinning, ...
I just want to be sure allowing a hostname is the best solution for the problem, as compared to the alternative of using interface names (like eth0).

**Comment by bel2125** [comment]
I added support for host names, but limited to RFC 952 compliant host names, i.e., all host names, starting with a letter, and containing only digits, letters and hyphens. More recent specs allow a hostname starting with a digit, or even consisting only of digits, but this border case might cause conflicts with the rest of the listening_ports configuration syntax. So I currently do not plan to add support for RFC 952 in-compliant host names.

**Comment by bel2125** [comment]
Could you please do a test with your use case, and give me some feedback if it works or not.

**Comment by nfrmtkr** [comment]
Hello @bel2125,

it works for ipv4 addresses but not for ipv6 addresses on Windows. Linux I didn't test. If I add 

::1 foo 

to C:\Windows\system32\drivers\etc\hosts an use foo in listening_ports option I get errro:

"Failed to start CivetWeb V1.10:
foo:8086: invalid port spec (entry 1). Expecting list of: [IP_ADDRESS:]PORT[s|r]"

I've called WSAGetLastError() after the call to gethostbyname() and the error code is 11004 (WSANO_DATA). Reading about gethostbyname I see a "deprecated" note for Windows:

https://msdn.microsoft.com/en-us/library/windows/desktop/ms738524(v=vs.85).aspx

They recommend to use getaddrinfo. Reading gcc documentation about gethostbyname I see mentions about thread safety. They recommend to use gethostbyname_r().

Please think about using getaddrinfo. The use would be similar to gethostbyname. You'll pick up the first address being delivered (like you do now with h_addr which is an alias for h_addr_list[0]) and you get a full struct sockaddr back.

**Comment by bel2125** [comment]
You are right getaddrinfo should be used - it's already wrapped in `mg_inet_pton`.
I changed it to mg_inet_pton and tested it in Linux for IPv4 and IPv6.

Some Windows environments are somewhat iffy with IPv6, and it's also different if the IPv4 address will work implicitly if you specify IPv6, or if you need to specify both separately.

Could you please repeat your test with the recent version?

**Comment by nfrmtkr** [comment]
Hello  @bel2125,

I've testet on Windows 10 using entries in C:\Windows\system32\drivers\etc\hosts in various configurations for IPv4 and IPv6 addresses. I also used a list of host:port in listening_ports option. Fiinally I also tried to resolve using real DNS. This seems to work also. 

THX!
Frank

**Comment by bel2125** [comment]
I also added some documentation (https://github.com/civetweb/civetweb/blob/master/docs/UserManual.md#listening_ports-8080), and a warning: When using a hostname, you need to test in your particular network environment - in some cases, you might need to resort to a fixed IP address.

So I think we can close this issue now.
