### ISSUE TITLE
query_string missing in API doc

### ISSUE THREAD

**Issue by jrosenboom** [civetweb/civetweb#464]
I'm wondering whether the query_string is not also part of the API? It is missing in https://github.com/civetweb/civetweb/blob/master/docs/api/mg_request_info.md, is that just a bug or is it intentional?

**Comment by bel2125** [comment]
It is part of the API [civetweb.h](https://github.com/civetweb/civetweb/blob/master/include/civetweb.h#L90). It seems it was not added to the documentation.

**Comment by bel2125** [comment]
Added to the documentation 8 days ago.
