### ISSUE TITLE
405 Method not allowed

### ISSUE THREAD

**Issue by TaoCHEN92** [civetweb/civetweb#468]
Hi all,

I'm trying to use Ceph RGW to build an object store system. I have web site which send request to civetweb with S3 JS SDK, but I always met 405 Method not allowed. Of course we can avoid CORS issue with replacing civetweb with Nginx or apache, but is it possible to add support like 'access_control_allow_methods' in civetweb, if not, can someone tell me what negative influence will it bring?

Thanks for your attention!

**Comment by bel2125** [comment]
Sorry, but I don't know Ceph + S3 good enough to understand what you want to do - in particular, I don't know what requests will be sent to civetweb. There are some CORS settings ([access_control_allow_origin](https://github.com/civetweb/civetweb/blob/master/docs/UserManual.md#access_control_allow_origin)) and arbitrary headers ([additional_header](https://github.com/civetweb/civetweb/blob/master/docs/UserManual.md#additional_header)) - you want to set a `Access-Control-Allow-Methods:` header along with the existing `Access-Control-Allow-Origin:` header? For what method?

Every standard can be added, if it is useful. In case I should add support for it, I need to understand the problem in more detail. In case you prepare a pull request, I still want to understand it (but probably I get it from reading the code then).

**Comment by bel2125** [comment]
CivetWeb actually allows to use other methods as GET for CORS requests as well, but not for static files but only for dynamic resources (i.e., scripts and callbacks). An example for a PUT request, including a CORS preflight can be found here ([html + javascript at browser side](https://github.com/civetweb/civetweb/blob/master/test/cors.html) and [Lua script at server side](https://github.com/civetweb/civetweb/blob/master/test/cors.reply.lua)).

In case CivetWeb still misses something, could you provide an example to reproduce the problem?

**Comment by TaoCHEN92** [comment]
Thanks for your reply @bel2125.  I made a web UI, like Amazon S3 web ui, which provides an web service interface, it allows to create bucket, upload/download object, the back storage end is Ceph RGW. As I installed this web site in the difference domain with RGW(civeweb), I got 405 method not allowed if I send a request like 'list bucket' with S3 JS SDK ([http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#listBuckets-property](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#listBuckets-property)). I checked the history of sending package, I found that before browser send a 'GET' request, it sent a 'OPTIONS' request as preflighted request to determine whether the actual request is safe to send。 But it seems civetweb doesn't have optional parameter to set, like `Access-Control-Allow-Methods: OPTIONS`, so the 405 error returned.

Here is my configuration for my RGW:
`[client.rgw.vm2]`
`host = vm2`
`keyring = /var/lib/ceph/radosgw/ceph-rgw.vm2/keyring`
`rgw socket path = /tmp/radosgw-vm2.sock`
`log file = /var/log/ceph/ceph-rgw-vm2.log`
`rgw data = /var/lib/ceph/radosgw/ceph-rgw.vm2`
`rgw frontends = civetweb port=172.16.150.102:8080 access_control_allow_origin=*`
`rgw resolve cname = False`


If i try 
`curl -X OPTIONS 172.16.150.102:8080`

the RGW will returns:
`<?xml version="1.0" encoding="UTF-8"?><Error><Code>MethodNotAllowed</Code><RequestId>tx00000000000000000001b-00593df1c7-5e31-default</RequestId><HostId>5e31-default-default</HostId></Error>`

**Comment by bel2125** [comment]
CivetWeb does support OPTION requests, but only for dynamic resources.
By dynamic resource I mean everything that is either generated by a CGI script (PHP, Python, ...), in-server script (Lua, Server-Side-JavaScript) or a C/C++ callback.
For static resources, like files or directory listings, an OPTIONS request returns a generic response with a list of supported methods.

So "curl -X OPTIONS 127.0.0.1:8080 -v" is a request to a directory (unless you have an index script) and will give something like
```
HTTP/1.1 200 OK
Allow: GET, POST, HEAD, CONNECT, PUT, DELETE, OPTIONS, PROPFIND, MKCOL
```

For a request to a CORS-preflight aware script like cors.reply.lua, the Referer is missing, so `curl -X OPTIONS 127.0.0.1:8080/cors.reply.lua` will print "This test page should not be used directly. Open cors.html instead.". The script detects this as an invalid CORS request. A valid CORS request would be `curl -X OPTIONS 127.0.0.1:8080/cors.reply.lua -H "Origin: somewhere" -H "Access-Control-Request-Method: PUT" -v` (the `-v` just prints the header, it's not required for the request):
```
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> OPTIONS /cors.reply.lua HTTP/1.1
> Host: 127.0.0.1:8080
> User-Agent: curl/7.47.0
> Accept: */*
> Origin: somewhere
> Access-Control-Request-Method: PUT
> 
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
< Access-Control-Allow-Methods: PUT
< Access-Control-Allow-Origin: *
< Connection: close
< Content-Type: text/html; charset=utf-8
< 
* Closing connection 0

```

After this preflight, the browser does the actual request. In case a PUT request is used, and there is a script (not a callback) we can only address sub-resources: `curl -X PUT 127.0.0.1:8080/cors.reply.lua/something -H "Origin: somewhere" -v` so cors.reply.lua/something works, while cors.reply.lua will not.
This is different for POST requests. While POST requests send something too the resource (the script), PUT requests are meant to replace the resource (the script). If you use a sub-resource (script.lua/some/path/to/something), all methods are handled by script.lua, including PUT. 

(I hope this is not too confusing).

**Comment by bel2125** [comment]
It would be possible to add a configuration value for the server, to allow CORS for all dynamic resources, without having to implement this directly in the script. Is this what you are looking for?

**Comment by TaoCHEN92** [comment]
Thanks for your reply in detail. In Ceph, civetweb is an embedded web server for RGW. We can add configuration value for RGW in ceph.conf file. The list of available web server for RGW is : nginx, apache, civetweb.  If we want to use civetweb, we just add:
`rgw frontends = civetweb port=172.16.150.102:8080 access_control_allow_origin=*`
in RGW section in ceph.conf. We can start RGW with:
`radosgw -c ./path_to_ceph.conf  -n  RGW_name`
After that the RGW will work with a embedded civetweb listing on 8080. Then we can visit bucket/object by sending a request like 'http://127.0.0.1:8080/bucket_name/object_name' with auth.

I don't know if it is possible to add lua script for an embedded civetweb in Ceph, if so ,could you please show me?  Thank you for your attention!

**Comment by bel2125** [comment]
I don't know exactly how civetweb is embedded in Ceph - the configuration options seem similar but not identical.
What version of civetweb are you using?
Can you build it from the source yourself?

If you add the following code to `handle_request` (as step 2), all CORS requests will be accepted:

```C
 if (!strcmp(ri->request_method, "OPTIONS")) {
        const char *cors_origin = get_header(ri, "Origin");
        const char *cors_acrm = get_header(ri, "Access-Control-Request-Method");
        if ((cors_origin!=NULL) && (cors_acrm!=NULL)) {
            const char *cors_acrh = get_header(ri, "Access-Control-Request-Headers");

            gmt_time_string(date, sizeof(date), &curtime);
            mg_printf(conn,
                      "HTTP/1.1 200 OK\r\n"
                      "Date: %s\r\n"
                      "Access-Control-Allow-Origin: %s\r\n"
                      "Access-Control-Allow-Methods: %s\r\n"
                      "Content-Length: 0\r\n"
                      "Connection: %s\r\n",
                      date,
                      cors_origin,
                      cors_acrm,
                      suggest_connection_header(conn));

            if (cors_acrh!=NULL) {
                mg_printf(conn, "Access-Control-Allow-Headers: %s\r\n", cors_acrh);
            }
            mg_printf(conn, "Access-Control-Max-Age: 60\r\n");

            mg_printf(conn, "\r\n");

            return;
        }
    }
```

Could you test if this solves your problem?

**Comment by TaoCHEN92** [comment]
I use Ceph jewel version, which using civetweb 1.8, so I don't think it support CORS parameters such as "access-control-methods", "access-control-allow-header".  I tried the latest version of civetweb(master) and followed your advice, CORS problem has gone. I hope Ceph community will merge the latest verison of civetweb. 

Thank you so much for your reply and your advice. As problem has been solved, I close this issue.

**Comment by bel2125** [comment]
> I tried the latest version of civetweb(master) and followed your advice

Did you add the code above (https://github.com/civetweb/civetweb/issues/468#issuecomment-308261269), or did it already work without that modification?
In case you need this modification, I will add it to V1.10.

**Comment by TaoCHEN92** [comment]
I build civetweb from source and run it without adding your code above, I tried `curl -X OPTIONS localhost:8080 -v` and it returns:
```
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> OPTIONS /cors.reply.lua HTTP/1.1
> Host: 127.0.0.1:8080
> User-Agent: curl/7.47.0
> Accept: */*
> Origin: somewhere
> Access-Control-Request-Method: PUT
> 
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
< Access-Control-Allow-Methods: PUT
< Access-Control-Allow-Origin: *
< Connection: close
< Content-Type: text/html; charset=utf-8
< 
* Closing connection 0
```

So I don't think the code should be added
