### ISSUE TITLE
Multipart upload parts starting with \r\n

### ISSUE THREAD

**Issue by PhilLab** [civetweb/civetweb#470]
In [line 606 of handle_form.inl](https://github.com/civetweb/civetweb/blob/master/src/handle_form.inl#L606), the parts are said to end with ``\r\n``. However, I now have a client which additionally starts their parts with this, meaning that the [start check](https://github.com/civetweb/civetweb/blob/master/src/handle_form.inl#L597) fails.

Is this a violation / missing support of the standard by the client (which is the [AndroidUploadService](https://github.com/gotev/android-upload-service)) or by civetweb?

It works if I work around this issue like this:

             // ... still civetweb code ...
             r = mg_read(conn,
			            buf + (size_t)buf_fill,
			            sizeof(buf) - 1 - (size_t)buf_fill);

            if (r < 0) {
                /* read error */
                return -1;
            }

            /*
             * Workaround for integration with AndroidUploadService: the buffer contains \r\n
             * before the true message starts. Remove them
             */
            int startOffset = 0;
            while (r > 2 && buf[startOffset] == '\r' && buf[startOffset + 1] == '\n') {
                startOffset += 2;
                r -= 2;
            }
            if (startOffset > 0) {
                for (int i = 0; i < r; i++) {
                    buf[i] = buf[i + startOffset];
                }
            }
            // End of workaround

            buf_fill += r;
            buf[buf_fill] = 0;
            if (buf_fill < 1) {
                        /* No data */
                        return -1;
            }
I would contribute this to civetweb but it looks rather hacky

**Comment by bel2125** [comment]
I was looking for `/* read error */` and `buf_fill += r;` in the code to determine the actual location of your workaround, but both marks appear several times. Since you cite line 606, you added the workaround between line 598 and 590, right? Only there, or again at another location?

I just checked the example in [RFC 2388](https://www.ietf.org/rfc/rfc2388.txt), [RFC 7578](https://tools.ietf.org/html/rfc7578) and many other examples ([here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition), [here](https://www.w3.org/TR/html401/interact/forms.html), [here](https://stackoverflow.com/questions/4238809/example-of-multipart-form-data), [here](https://stackoverflow.com/questions/8659808/how-does-http-file-upload-work), [here](http://code.activestate.com/recipes/578846-composing-a-postable-http-request-with-multipartfo/), [here](https://www.huyng.com/posts/under-the-hood-an-http-request-with-multipartform-data), [here](http://chxo.com/be2/20050724_93bf.html), [here](https://stackoverflow.com/questions/4526273/what-does-enctype-multipart-form-data-mean), [here](https://familysearch.org/developer/docs/api/memories/Upload_Photo_Via_Multipart_Form_Data_usecase), [here](http://swagger.io/docs/specification/file-upload/) and some pages in languages I can't read) - none of them had an extra \r\n.

Could you post a complete request?

**Comment by PhilLab** [comment]
Correct, between lines 589 and 590, The first 1024 bytes of the request right before the workaround is added look like this (notice the first blank line)
```

---------AndroidUploadService1497526512363
Content-Disposition: form-data; name="file"; filename="myAndroidImage.jpg"
Content-Type: image/jpeg

ÿØÿá#åExif
```

**Comment by bel2125** [comment]
These are the first lines after the header?
In my first ["here" above (from developer.mozilla.org)](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition) shows a full request like this:

```
POST /test.html HTTP/1.1
Host: example.org
Content-Type: multipart/form-data;boundary="boundary"

--boundary
Content-Disposition: form-data; name="field1"

value1
--boundary
Content-Disposition: form-data; name="field2"; filename="example.txt"

value2
--boundary--
```

So, AndroidUploadService creates a request like this?
[1]
```
POST /test.html HTTP/1.1
Host: example.org
Content-Type: multipart/form-data;boundary="boundary"


--boundary
Content-Disposition: form-data; name="field1"

value1
--boundary
Content-Disposition: form-data; name="field2"; filename="example.txt"

value2
--boundary--
```

Or like this?
[2]
```
POST /test.html HTTP/1.1
Host: example.org
Content-Type: multipart/form-data;boundary="boundary"

--boundary
Content-Disposition: form-data; name="field1"

value1

--boundary
Content-Disposition: form-data; name="field2"; filename="example.txt"

value2

--boundary--
```

Or like this?
[1]
```
POST /test.html HTTP/1.1
Host: example.org
Content-Type: multipart/form-data;boundary="boundary"


--boundary
Content-Disposition: form-data; name="field1"

value1

--boundary
Content-Disposition: form-data; name="field2"; filename="example.txt"

value2

--boundary--
```

**Comment by bel2125** [comment]
I just found an w3.org article on multipart (https://www.w3.org/Protocols/rfc1341/7_2_Multipart.html) - (there are [more different multipart types](https://msdn.microsoft.com/en-us/library/ms527355(v=exchg.10).aspx) than multipart/form-data). There, they allow a "preamble" and an "epilog" for multipart messages, looking like this (the standard was originally intended for email):

```
     From: Nathaniel Borenstein <nsb@bellcore.com> 
     To:  Ned Freed <ned@innosoft.com> 
     Subject: Sample message 
     MIME-Version: 1.0 
     Content-type: multipart/mixed; boundary="simple 
     boundary" 

     This is the preamble.  It is to be ignored, though it 
     is a handy place for mail composers to include an 
     explanatory note to non-MIME compliant readers. 
     --simple boundary 

     This is implicitly typed plain ASCII text. 
     It does NOT end with a linebreak. 
     --simple boundary 
     Content-type: text/plain; charset=us-ascii 

     This is explicitly typed plain ASCII text. 
     It DOES end with a linebreak. 

     --simple boundary-- 
     This is the epilogue.  It is also to be ignored.
```
But they also state:

> NOTE: These "preamble" and "epilogue" areas are not used because of the lack of proper typing of these parts and the lack of clear semantics for handling these areas at gateways, particularly X.400 gateways. 

And in another w3.org article on forms (https://www.w3.org/TR/html401/interact/forms.html), they don't have a preamble or epilogue and no additional newline:
```
   Content-Type: multipart/form-data; boundary=AaB03x

   --AaB03x
   Content-Disposition: form-data; name="submit-name"

   Larry
   --AaB03x
   Content-Disposition: form-data; name="files"; filename="file1.txt"
   Content-Type: text/plain

   ... contents of file1.txt ...
   --AaB03x--
```

So maybe it is or was allowed to have *something* before the first boundary, including an additional \r\n. But no up to date browser uses it for multipart/form-data now - maybe it is no longer allowed, or it was only allowed for other multipart types. If it is only a preamble (like in [1] above), it would be save to ignore it, but then it should be done with a slightly different patch than the one in the original issue. 

But before spending more time on "is it allowed" / "is it still allowed" ... could you post the full request, including header, to be sure it is like [1] above. I would need to know in detail, how a complete request to upload a tiny file looks like, including all headers.

**Comment by PhilLab** [comment]
Is this sufficient for you?
```
POST /some/api HTTP/1.1
Connection: close
Content-Type: multipart/form-data; boundary=-------AndroidUploadService1499093154573
Content-Length: 17054
Accept-Encoding: gzip
User-Agent: okhttp/3.8.1


---------AndroidUploadService1499093154573
Content-Disposition: form-data; name="parameter"

value
---------AndroidUploadService1499093154573
Content-Disposition: form-data; name="photo"; filename="image.jpg"
Content-Type: image/jpeg

...
```

**Comment by bel2125** [comment]
Yes. Thank you.
So the problem seems to be, the extra space here
```
User-Agent: okhttp/3.8.1


---------AndroidUploadService1499093154573
```
as compared to
```
User-Agent: okhttp/3.8.1

---------AndroidUploadService1499093154573
```

I recently had to completely rewrite request parsing (issue collection: #479), so I have to check if it still behaves the same way. But I think it's not a problem to skip the content until the first boundary.

**Comment by bel2125** [comment]
Now, the current implementation should ignore the leading \r\n in multipart messages.
At least, your request (tested with curl) is accepted now.

Could you repeat the test with the actual client?

**Comment by PhilLab** [comment]
Thanks, this works the used client!
