### ISSUE TITLE
send_ssi_file - len > (int)sizeof(buf)

### ISSUE THREAD

**Issue by pavel-pimenov** [civetweb/civetweb#472]
V781 The value of the 'len' variable is checked after it was used. Perhaps there is a mistake in program logic. Check lines: 9863, 9865. civetweb.c 9863
![default](https://user-images.githubusercontent.com/920705/27250810-0d129c3a-5341-11e7-8ed0-b0bb8a063e44.png)

**Comment by bel2125** [comment]
This check is a remains from removing/replacing all "assert" statements.
Anyway, the logic in this function was quite complicated, so I rewrote it (https://github.com/civetweb/civetweb/commit/50b3d7e3ab3ad8f19c44a1eb2037ff3c4c4d8c45) - but it still isn't really simple now.
