### ISSUE TITLE
Duplicate if (field_storage == FORM_FIELD_STORAGE_STORE)

### ISSUE THREAD

**Issue by pavel-pimenov** [civetweb/civetweb#473]
V581 The conditional expressions of the 'if' statements situated alongside each other are identical. Check lines: 843, 859. handle_form.inl 859

![default](https://user-images.githubusercontent.com/920705/27250850-08f1c652-5342-11e7-9d44-b3e9ee228fdd.png)

**Comment by bel2125** [comment]
That's not really an issue in the code, it just looks somewhat curious.
I'm not even sure if it has any performance implications, if the compiler optimizes it.

I joined the two if statements now.
What program did you use to detect this?

**Comment by pavel-pimenov** [comment]
https://www.viva64.com/en/pvs-studio/
