### ISSUE TITLE
Is there any reason why parse_http_message() accepts HTTP *responses*?

### ISSUE THREAD

**Issue by newsoft** [civetweb/civetweb#476]
It is possible to connect to the Web server and send the following request:
```
HTTP/whatever / 1.0\r\n\r\n
```

This will be considered as valid by parse_http_message(), and rejected later on with an HTTP 405 error "Method not allowed".

If there is any bug in the header processing code, it will be easy to trigger through the above (invalid) HTTP request - possibly evading most traffic analysis devices.

On the other hand, I have no idea why an HTTP server would actually need to receive an HTTP *response* from the client.

**Comment by bel2125** [comment]
This is some legacy code.
Before CivetWeb was forked and before I became involved, a rudimentary HTTP client feature has been implemented. The client uses the same parsing method for HTTP responses as the server for HTTP requests. Unfortunately, server and client also use the same data structure "mg_connection", the same data structure "mg_request_info" and client and server both use "request_info = mg_get_request_info(connection);". One of the effects: client get their response code (like 200 for OK) in the URI field (https://github.com/civetweb/civetweb/blob/master/test/public_server.c#L4290).

This cannot be changed without an incompatible change to the client interface - an incompatible interface changes for a code already in production in various products. Nevertheless, I think the current interface is mischievous and an interface change will be required on the mid term. It's already on the list: https://github.com/civetweb/civetweb/blob/master/docs/Interface_Changes_1.10.md#mg_connect_client-family

**Comment by bel2125** [comment]
Request parsing has been rewritten, and split into a server (request parsing) and a client (response parsing) part.
See #479

In order to keep the API compatible, some functions (like `mg_get_request_info`) still work with http responses, at least for a while until all users could adapt to the new API.

**Comment by bel2125** [comment]
Request parsing has been rewritten, removing legacy code that did not distinguish between requests and responses. In most cases, the current code does (leaving only a small common part).

Thus, closing this issue.

**Comment by newsoft** [comment]
Submitter confirms :) Thank you!
