### ISSUE TITLE
V519 The 'ebuf[0]' variable is assigned values twice successively

### ISSUE THREAD

**Issue by pavel-pimenov** [civetweb/civetweb#481]
V519 The 'ebuf[0]' variable is assigned values twice successively. Perhaps this is a mistake. Check lines: 14699, 14703. civetweb.c 14703

https://github.com/civetweb/civetweb/blob/master/src/civetweb.c#L14703
https://github.com/civetweb/civetweb/blob/master/src/civetweb.c#L14699

**Comment by bel2125** [comment]
Additional assignment removed.
Thanks.
