### ISSUE TITLE
V557 Array overrun is possible. The value of 'len + i - 1' 

### ISSUE THREAD

**Issue by pavel-pimenov** [civetweb/civetweb#483]
V557 Array overrun is possible. The value of 'len + i - 1' index could reach 8221. civetweb.c 3820

![default](https://user-images.githubusercontent.com/920705/27576596-35f20162-5b26-11e7-9d1b-4dcdf50f2826.png)

**Comment by bel2125** [comment]
Are you sure?

The analyser states `len + i - 1` could be 8221
But i<32. For i=31: `len + 31 - 1 == 8221` , then len == 8191


In line 3812: `len = (int)strlen(buf);` and `char buf[MG_BUF_LEN = 8192];`
So the analyser considers this buffer to be completely filled.

But above, we don't fill the buffer completely - there is at least 32 characters space (from `sizeof(buf) - 32`):
```
						mg_snprintf(conn,
						            &truncated,
						            buf,
						            sizeof(buf) - 32,
						            "%serror%03u.",
						            error_handler,
						            status);
```

Could this be a false positive?
