### ISSUE TITLE
CivetServer::closeHandler Assertion failed: request_info != NULL

### ISSUE THREAD

**Issue by pavel-pimenov** [civetweb/civetweb#485]
source = git-master
Browse files at http://localhost:8081/
Run example at http://localhost:8081/example
Exit at http://localhost:8081/exit
Assertion failed: request_info != NULL, file c:\git\civetweb\src\civetserver.cpp, line 325

![default](https://user-images.githubusercontent.com/920705/27578038-8a15230a-5b2b-11e7-88f0-8599a84e48eb.png)

**Comment by bel2125** [comment]
This could be, because I'm right in the middle of a more complex, multi-step refactoring
"Rewrite request parsing (Step x/?)"
and pushed it to the server mainly for CI tests and synchronization.
I'm going to have a look after the refactoring is completed.

**Comment by btsimonh** [comment]
change to 
CivetServer::closeHandler(const struct mg_connection *conn)
{
	CivetServer *me = (CivetServer *)me = (CivetServer *)mg_get_user_data(mg_get_context(conn));
	assert(me != NULL);

as request_info can be returned as NULL on a failed request (e.g. no data).
I see failed request for the first few reads by chrome?

**Comment by bel2125** [comment]
> I see failed request for the first few reads by chrome?

The current master repository is in the middle of a more complex refactoring ("Rewrite request parsing (Step x/?)"), so you should either use the latest release, or a version after refactoring (in a few days).

But you are right, using the new API functions (mg_get_user_data and mg_get_contex) is more robust in this case, so it makes sense to change this anyway.

**Comment by btsimonh** [comment]
so go to 1.9 branch?

**Comment by bel2125** [comment]
If you need a released version today, use 1.9.1 - some manual tests on multiple platforms are done with this version

If you need a working version today, that does not have to be "released", choose the latest clean build with all automatic tests "ok" (3f0fcdf - see https://travis-ci.org/civetweb/civetweb/builds)

If you need a working version tomorrow, or on Monday, ... I think this problem will be fixed.

**Comment by bel2125** [comment]
I do not get an assert in the current version (after refactoring "Rewrite request parsing (Step 26/?)").

Could you repeat your test?

**Comment by bel2125** [comment]
Fixed some weeks ago.
