### ISSUE TITLE
Websockets stop the server from closing - after they have been disconnected

### ISSUE THREAD

**Issue by btsimonh** [civetweb/civetweb#486]
may be related to 
https://github.com/civetweb/civetweb/issues/77

I have websockets enabled.  Windows 64 bit build.
Websockets connect and disconnect fine, and shutdown is quick if the websocket is connected, or never been connected, or more than 30s since disconnect.

BUT.  If I connect to a websocket, and then disconnect (e.g. leave the page in a browser, resulting in a correct close opcode with status code observed as 1001), and then try to delete the server (I'm using the C++ wrapper), then the server is stuck in a websocket worker for many seconds (actually, exactly 30 s from the time the websocket closed?).

It MAY be more serious a problem too.  Sometimes when this occurs, my VS2010 express environment locks up/screws up, the process does not stop, and VS can't end it cleanly, even needing a restart at times.

One more edit: If I Open one, close, open another, the issue is still there.  I'm using 4 worker threads: if I open 4, close one, then open another (i.e. so all threads are active again), it closes quickly.

P.S. whilst working on this issue, I found that on WS close, ws_data_handler is called with the 2 byte status code as data before the close handler; until I realised this, I was interpreting the two bytes as data - maybe the sample code should reflect checking of 'bits' for opcode and printing something appropriate - the functionality is actually OK as long as you know it will happen :).
maybe something like:
```
    // if a close command
    if ((bits & 0xf) == 8){
        if (data_len == 2){
            printf("WS close data %d\n", htons(*(unsigned short*)data));
        } else {
            printf("WS close data not a short?\n");
        }
    } else {
        printf("WS got %lu bytes: ", (long unsigned)data_len);
        fwrite(data, 1, data_len, stdout);
        printf("\n");
    }
```
br,
simon

**Comment by bel2125** [comment]
I added some code to the C example.

My VS2010 Express used to hang sometimes on different projects as well, so it's not specific to CivetWeb. Although I never had to restart Visual Studio but could always stop with Ctrl+F5 (I think .. today I'm working on a Linux machine).

I'm not sure if this is related to #77 - the relevant code changed several times since that time, since earlier "fixes" had undesirable side effects.

You cannot rely on a close message - the client connection can be gone without any message as well.

What version are you using?

**Comment by btsimonh** [comment]
oooo..  hold that thought...  version is 1.9, and date is sept 2016 - I thought I'd updated this project, so will now and report.... (will also get a proper repo going so I can track stuff :)...).

**Comment by btsimonh** [comment]
hmm.. done a lot more on the compiler instability.  I'll start a new issue.

**Comment by bel2125** [comment]
The current master repository is in the middle of a more complex refactoring ("Rewrite request parsing (Step x/?)"), so you should either use the latest release, or a version after refactoring (in a few days).
