### ISSUE TITLE
How to size num_threads

### ISSUE THREAD

**Issue by grunk** [civetweb/civetweb#494]
Hi,

is there some kind of rule to set num_threads to a "proper" value for my use case ?
If i'm not mistaken the default value is 50.
Is there a low value that should not be exceeded ?

Let's say i have an html page with 2 css files and 2 JS files. Will it use 5 threads (1 for the html content , and 1 for each resources) ? or the same thread is used for the all thing ?

Thanks ;)

**Comment by bel2125** [comment]
It does not depend on the number of HTML/CSS/JS/Image/.. Files, but on the number of simultaneous connections. And it also depends on the type of clients (web browsers or machines using a web api).

Browsers tend to open two or more simultaneous connections to the same server - how much depends on the browser and browser version. Having just one thread will work, but cause performance penalties (page load speed in the browser). Having 2 is better than just 1, even if you just have one user (e.g. it's localhost and you are the only user looking on just one page). 5 could be sufficient for a small network.

If you have a server available to multiple users (in a small LAN) and use long running scripts or websockets, you need more threads - up to one additional thread per simultaneous user.

Recently I added some server diagnostics - unfortunately there is no user documentation yet. You could do some realistic test and check in the server diagnostics how much threads were used.
You could just start the server with a lot of threads, then check in the diagnostics how much were actually used, then restart the server with a smaller number of threads.

**Comment by grunk** [comment]
Thanks for this answer. I'm currently running civetweb 1.8 , i'll consider updating to try the diagnostic functionality.
Thanks :)
