### ISSUE TITLE
Run from directory in linux?

### ISSUE THREAD

**Issue by cornergraf** [civetweb/civetweb#502]
One of the great things of mongoose under windows was that you could just drop it into a directory, launch it, and it would host that current directory.

How do I achieve the same with civetweb under linux? It seems to be built to be installed in a fixed location with a fixed config file location which makes it much less flexible...

**Comment by cornergraf** [comment]
Nevermind, it seems you just have to start it with the right command line options. Would have been nice if it worked just as simple as under windows :S

**Comment by bel2125** [comment]
You could also use it like this in Linux: Build it with `make`, copy the `civetweb` to wherever you want, change to this directory (in a shell) and run `./civetweb`.
And you can use the `-document_root` option in Windows and in Linux the same way.

**Comment by cornergraf** [comment]
That is what I did, but on startup civetweb says the (default) document root is somwehere in /var/www. On windows (using mongoose back then) it just always defaulted to the current directory. It's not a big deal though, now I know how to to it right.

**Comment by bel2125** [comment]
> but on startup civetweb says the (default) document root is somwehere in /var/www

Sorry, I can`t reproduce this. In my test with the current version, it defaults to the directory of the executable, and it has been like this as long as I can remember:

```
user@host:/somewhere/civetweb$ make clean
  rm -rf out
  rm -rf libcivetweb.a
  rm -rf libcivetweb.so
  rm -rf libcivetweb.so.1
  rm -rf libcivetweb.so.1.10.0
  rm -rf civetweb
  rm -f civetweb_test
user@host:/somewhere/civetweb$ make
  cc -c -Wall -Wextra -Wshadow -Wformat-security -Winit-self -Wmissing-prototypes -DLINUX -Iinclude  -DUSE_STACK_SIZE=102400 -O2 -DNDEBUG src/civetweb.c -o out/src/civetweb.o
  cc -c -Wall -Wextra -Wshadow -Wformat-security -Winit-self -Wmissing-prototypes -DLINUX -Iinclude  -DUSE_STACK_SIZE=102400 -O2 -DNDEBUG src/main.c -o out/src/main.o
  cc -o civetweb -Wall -Wextra -Wshadow -Wformat-security -Winit-self -Wmissing-prototypes -DLINUX -Iinclude  -DUSE_STACK_SIZE=102400 -O2 -DNDEBUG  out/src/civetweb.o out/src/main.o  -lpthread -lm -lrt -ldl
user@host:/somewhere/civetweb$ ./civetweb 
CivetWeb V1.10 started on port(s) 8080 with web root [/somewhere/civetweb]
...
user@host:/somewhere/civetweb$ cp civetweb /tmp
user@host:/somewhere/civetweb$ cd /tmp
user@host:/tmp$ ./civetweb 
CivetWeb V1.10 started on port(s) 8080 with web root [/tmp]
```
Maybe you do have a "civetweb.conf" file somewhere around.

Or your executable is in /var/www, since the location of the exe is the default, not the current directory, but that's the same in Windows:
```
user@host:/tmp$ cd /proc/
user@host:/proc$ /tmp/civetweb 
CivetWeb V1.10 started on port(s) 8080 with web root [/tmp]
```

If you want to start it from the current directory instead of the exe directory you can do it like this (in Linux):
```
user@host:/proc$ /tmp/civetweb -document_root `pwd`
CivetWeb V1.10 started on port(s) 8080 with web root [/proc]
```

I think it was always like this, at least I'm not aware of a difference.
