### ISSUE TITLE
Disable installing executable

### ISSUE THREAD

**Issue by kuzi117** [civetweb/civetweb#505]
Hi, I was wondering if you'd be willing to accept a pull request that allowed disabling installation of the c-executable target. When civetweb's used as part of a cmake superbuild where we don't want the executable to be built and only need the headers and library, adding civetweb through add_subdirectory automatically adds the c-executable target as an install. If the target's disabled via EXCLUDE_FROM_ALL so that it isn't built, an error is thrown by cmake when it tries to install the subproject, because it tries to install the non-existent binary.

**Comment by bel2125** [comment]
I'm not an expert in CMake. Most of the CMake files were made by contributors - I can maintain the status quo, do some adaptations and minor improvements.

If there is a way to improve this file without breaking existing features or making it so complicated it becomes more or less unmaintainable, every enhancement is fine with me.

**Comment by kuzi117** [comment]
I have a PR ready that should leave installing on by default, but allow it to be turned off by an advanced user. I'll put it up in a bit.

**Comment by kuzi117** [comment]
Thanks!
