### ISSUE TITLE
Potential CSRF Vulnerability

### ISSUE THREAD

**Issue by ddillard** [civetweb/civetweb#513]
A [CSRF vulnerability for Mongoose](http://seclists.org/fulldisclosure/2017/Sep/3) was published to Full Disclosure.  Given civetweb's history, can someone confirm or deny that that this vulnerability is also in civetweb?

**Comment by bel2125** [comment]
I did not have a look at Mongoose in the last years. It seems this attack is based on first saving something using a form request to `/__mg_admin?save`. I don't know what `__mg_admin` is and what it does. A Google search for `mg_admin` basically gives me just pages with the same error: http://www.securityfocus.com/archive/1/541126 (and some totally unrelated pages).

Maybe this is a http remote administration interface?
This interface did not exist when civetweb was forked from mongoose, I never added this kind of interface, and from my point of view it will never be added - someone can create his own interface by adding a script (with or without security checks), but it won't be a standard.

Do you know what `__mg_admin` is and how it works?

**Comment by ddillard** [comment]
I don't know what __mg_admin is and I can't find anything about it either.  However, if it's not a part of civetweb think I think we can safely say this vulnerability isn't an issue so I'm going to close this.

Thanks for looking at it.
