### ISSUE TITLE
Support Log Response header

### ISSUE THREAD

**Issue by diluga** [civetweb/civetweb#516]
is that any way to log Response header in log_access file?

**Comment by bel2125** [comment]
Currently most data in the log is request data - the only response information is the http status code and the number of bytes sent.

Since sending headers is different for static files, CGI scripts, Lua scripts, directory lists, ... it's also not just one point in the code where all headers are sent. Do you want to log only a specific response header field, only for selected requests, or every header line from every response?

**Comment by diluga** [comment]
I used ceph radosgw gateway with civetweb(s3 only),and i want log a specific response header field which name is "x-amz-request-id"  in every response, is that any way to do this?
"x-amz-request-id" introduce -> http://docs.aws.amazon.com/AmazonS3/latest/API/RESTCommonResponseHeaders.html

**Comment by bel2125** [comment]
Ok.
Do you know how the responses are generated in this case? 
From CGI, from Lua, form a C callback, forwarded from another source?

**Comment by diluga** [comment]
in my case it is from a C callback,
https://github.com/ceph/ceph/blob/master/src/rgw/rgw_civetweb_frontend.cc#L92
https://github.com/ceph/ceph/blob/master/src/rgw/rgw_civetweb.cc#L156

**Comment by bel2125** [comment]
It seems ceph/rgw has it's own `access_log` callback anyway:

https://github.com/ceph/ceph/blob/95b3a8a6c348a501a82ceac469c66120a9ed9743/src/rgw/rgw_civetweb_log.cc#L16

Without any detailed knowledge on ceph/rgw, I think, what you want to do must be added there, and in `RGWCivetWeb::send_header` (from your link above). There is no way for civetweb to directly "know" this header.

**Comment by diluga** [comment]
rgw_civetweb_log_access_callback will call access_log https://github.com/ceph/civetweb/blob/de23828cea740032428ce6f288ad061b429ce68e/src/civetweb.c#L10578
i will try another way to slove it! thx very much!

**Comment by bel2125** [comment]
> rgw_civetweb_log_access_callback will call access_log

It's actually the other way round - rgw_civetweb_log_access_callback is a callback called from log_access here:
https://github.com/ceph/civetweb/blob/de23828cea740032428ce6f288ad061b429ce68e/src/civetweb.c#L10640
(Looking at this code, I found the return value of the callback is currently ignored, which should not be the case, but that's a different issue.)

But in civetweb.c itself, there is no way to intercept a certain header right now.

**Comment by diluga** [comment]
yes,you are right.i will use openresty with ngx.resp.get_headers to solve my problem.
https://github.com/openresty/lua-nginx-module#ngxrespget_headers
it that any plan to support a function like "ngx.resp.get_headers" in civetweb ?

**Comment by bel2125** [comment]
> any plan to support a function like "ngx.resp.get_headers" in civetweb ?

This feature needs to be implemented "one layer above" `civetweb.c`, at least when it comes to using scripts (Lua, CGI) and callbacks (C, C++, ...) - for other resources like static files and directory lists it would be possible, but that's probably the rather uninteresting part. The `civetweb.h` API offers functions like `mg_print` or `mg_write` that just send data without knowing it it contains a header or body data, or both, or just single letters, ...

It is easy to add this kind of feature in the layer calling `mg_write`, for example in a Lua library if you use Lua scripts or in a C++ library if you are using callbacks.

**Comment by diluga** [comment]
Thank you for your advice,i have add char *resp_header in struct mg_connection,and add function mg_set_resp_header  in rgw‘s code,it worked well !thx a lot！
