### ISSUE TITLE
Compiling Qt project with GCC in Ubuntu

### ISSUE THREAD

**Issue by QuentinCG** [civetweb/civetweb#518]
Hi,

I just wanted to help other people having issue while compiling the Qt project with GCC 4.4.3 (in ubuntu):
If you have an error during the link: You'll need to add those libs: "LIBS += -lpthread -lm -lrt -ldl".

Cheers

**Comment by bel2125** [comment]
Hello,

We have the following project file in the Qt directory:
https://github.com/civetweb/civetweb/blob/master/Qt/CivetWeb.pro#L28
I think there is everything but -lrt (my Ubuntu seems to work without it).

But if you think we should add some more information, for example as a comment in the CivetWeb.pro file or in the ["building" documentation for Qt](https://github.com/civetweb/civetweb/blob/master/docs/Building.md#using-qt-creator), please write a paragraph or two, and I will be happy to add it to the documentation.

Regards
