### ISSUE TITLE
AuthStartHandler - in embedded_c example needs a patch 

### ISSUE THREAD

**Issue by dlissimore** [civetweb/civetweb#521]
A quick trace through the auth example material; 
Line 572:  - has 
if (mg_check_digest_access_authentication(conn, realm, passfile) > 0) { ... No valid auth ...

Tracing it through -  checkpassword returns 1 if valid   so it should be 

if (mg_check_digest_access_authentication(conn, realm, passfile) <= 0) {
... at least that works for me when running the example..

**Comment by bel2125** [comment]
Thanks. 
Fixed.

**Comment by bel2125** [comment]
Already fixed
