### ISSUE TITLE
possible issue with mg_get_header used as a client

### ISSUE THREAD

**Issue by AndreyArsov** [civetweb/civetweb#530]
I am using civetweb as a client through mg_client_connect.
When I ask for headers the num_headers variable from request_info is used which is 0.
The response_info.http_headers seem to be properly populated.

Is this a bug? When I replace with response_info.num_headers it seems to work.

```
const char *
mg_get_header(const struct mg_connection *conn, const char *name)
{
	if (!conn) {
		return NULL;
	}
	if (conn->connection_type == CONNECTION_TYPE_REQUEST) {
		return get_header(conn->request_info.http_headers,
		                  conn->request_info.num_headers,
		                  name);
	}
	if (conn->connection_type == CONNECTION_TYPE_RESPONSE) {
		**return get_header(conn->response_info.http_headers,
		                  conn->request_info.num_headers,
		                  name);**
	}
	return NULL;
}

```

**Comment by bel2125** [comment]
I probably tested 'mg_get_header' only as "server api function", but the documentation indeed lists it as "common api function" interface ([API Reference](https://github.com/civetweb/civetweb/blob/master/docs/APIReference.md)). .... Seems to be a copy paste error, when adding the distinction between server/request and client/response.
