### ISSUE TITLE
Allow access to mg_connection.SSL

### ISSUE THREAD

**Issue by nfrmtkr** [civetweb/civetweb#531]
In past we added a local patch to civetweb in order to get access to the SSL member in structure mg_connection. We made this by adding following function:

void *mg_get_ssl(struct mg_connection *conn) { return conn->ssl; };

We use the SSL structure in order to get full access to the certificate information. We intend to access the fields of "X509v3 extensions". 

I see mg_client_cert is part of mg_request_info. It includes a few fields from the certificate. What about adding SSL* to the mg_request_info structure or the mg_client_cert structure?

I am not sure if the mg_client_cert structure is much of help in all cases. Data is created and destroyed for each request, wether it is used or not. I guess it would be enough to provide SSL* in mg_request_info and users of the civetweb API are responsible to get the required data from it.

**Comment by bel2125** [comment]
Adding get-functions for internal members like the ssl context handle, the socket handle, internal buffers ... comes at the risk of the users code doing something interfering with the library code. I cannot offer any list of operations that would be allowed with this handle either. I cannot test it, and I cannot guarantee something worked with one version will work in the next one.

One could add this kind of get-function, but only with some special #ifdef, that isn't set in the default.
Still, I would prefer to add a specific API function to get the missing information instead of the low-level handle - unless this is infeasible. But I don't know if there are any better options, without knowing more details.

**Comment by nfrmtkr** [comment]
We extract the complete PEM certificate information using the SSL handle:

...
    X509* _peerCertificate =  = SSL_get_peer_certificate( ssl );
    string ans;
    BIO* bio;
    unsigned char* data;
    int datalen;
    bio = BIO_new( BIO_s_mem() );
    PEM_write_bio_X509( bio, _peerCertificate );
    datalen = BIO_get_mem_data( bio, &data );
    string cert( ( const char* )data, ( size_t )datalen );
    ans.swap( cert );
    BIO_free( bio );
   return ans;


and pass this to a script based interface for single sign on (SSO) implementations. Accessing X509v3 extension fields in this certificate is of interesst. 

Honestly speaking, extracting all potentially required data before the call to process_new_connection(conn) and freeing it after this call would add much overhead - uneccessary.
But, what about adding the X509 pointer fetched in ssl_get_client_cert_info to the mg_client_cert structure and freeing it after the call to process_new_connection(conn) ?
After the call to ssl_get_client_cert_info() the X509 handle is no longer used by civetweb and no damage can influence civietweb. The X509 object is a free copy of information. I can imagine that the X509 pointer would enough and makes the existing client_cert fields obsolete. 

Of course, adding X509 pointer to mg_client_cert struct must be done using a void* in order to keep the civetweb.h free from SSL specific stuff.

**Comment by bel2125** [comment]
So, you don't need `conn->ssl` but `cert` from `X509 *cert = SSL_get_peer_certificate(conn->ssl);` like [done here](https://github.com/civetweb/civetweb/blob/53ab2e364e1d0a4936184373d008691c59442c6e/src/civetweb.c#L13913)?

Currently the API is designed in a way the user code does not need to #include any of the SSL libraries (unless you use the `init_ssl` callback for some special stuff), so I don't want to remove the current fields in `mg_client_cert` as an incompatible interface change and force anyone to deal with OpenSSL directly. 

One could add some `void *` data field, or some callback to "inspect" the certificate.

**Comment by nfrmtkr** [comment]
Regarding API design I aggree with your motivation. For most cases the fields you provide are enough. 
However for special purpose (SSO) more data from the certificate may be required. I intend to add a void* to mg_client_cert struct. This will hold the pointer to the X509 object created in ssl_get_client_cert_info(). The call to X509_free(cert) will move to the clean up code after the call to process_new_connection() (SSL specific code block) inside worker_thread_run.
This can replace my mg_get_ssl() patch mentioned above. However, I'll invest time for that only if you signal to accept a pull request for this feature. If not I'll stay with my private mg_get_ssl() patch.

**Comment by bel2125** [comment]
We can add this `void *` parameter to the `mg_cert_info` structure - I will accept a pull request.
Do you think there is any "expanded" data (= not void*) in the cert, that would be meaningful to add to this structure?

**Comment by nfrmtkr** [comment]
I've created pull request #537. 

I suggest to keep the list of members in mg_client_cert minimal. The members available today provide the most important and specific/exotic stuff can be extracted by using the per_cert, now.

**Comment by bel2125** [comment]
Closed by #537
