### ISSUE TITLE
SourceForge download defaults to 1.9.1 for Windows

### ISSUE THREAD

**Issue by Vhati** [civetweb/civetweb#532]
![sourceforge_button](https://user-images.githubusercontent.com/2262621/31316094-04463c22-abf4-11e7-913f-ba439bb0b183.png)

Clicking "Browse All Files" shows 1.10 is available. It's just not the default release.

**Comment by bel2125** [comment]
I had a couple of problems with SourceForge when I tried to upload the new release:
https://groups.google.com/forum/#!topic/civetweb/BmiIE_QCW7c
... seems it was during a maintenance of outage of SourceForge.

I also have to announce [on google groups](https://groups.google.com/forum/#!topic/civetweb/BmiIE_QCW7c) the binaries are upload to SourceForge.

**Comment by bel2125** [comment]
Tested: SourceForge works correctly with the new version now.
