### ISSUE TITLE
Thread initialization with sotred data ptr

### ISSUE THREAD

**Issue by albertino80** [civetweb/civetweb#534]
I need to do a thread initializations and to store a pointer to my structure for each thread.
I'm using JVM through JNI and before using JVM in a thread I have to call `AttachCurrentThread` and keep (for example) `JNIEnv * jenv;` for subsequent calls.
When stopping the server for each thread, I must call a `DetachCurrentThread`.

It would make me comfortable to have:

two new mg_callbacks
```
void (* init_connection_thread) (struct mg_connection * conn);
void (* free_connection_thread) (const struct mg_connection * conn);
```
two new APIs
```
void * get_connection_thread_data (const struct mg_connection * conn);
void set_connection_thread_data (struct mg_connection * conn, void * user_data);
```
a new property:
```
void * mg_connection::user_data;
```
I've already experienced this solution and it works fine.

What do I ask makes sense for you?
Can I do a pull request for this?

**Comment by bel2125** [comment]
Do you need to initialize this *per thread* or *per connection* or *per request*. One thread will handle multiple connections during lifetime of the server, and a connection may handle several requests. So, when you initialize a thread, you will not have a connection object.

We do have some existing callbacks. For initializing a thread (called from `mg_start`):
```C
	/* Called when a new worker thread is initialized.
	   Parameters:
	     ctx: context handle
	     thread_type:
	       0 indicates the master thread
	       1 indicates a worker thread handling client connections
	       2 indicates an internal helper thread (timer thread)
	       */
	void (*init_thread)(const struct mg_context *ctx, int thread_type);
```
You only have the context here, but no connection yet.

If you need a callback per connection, you could use
```C
	/* Called when civetweb has received new HTTP request.
           ... must return 0 in your use case ...
	   Return value:
	     0: civetweb will process the request itself. In this case,
	        the callback must not send any data to the client.
        */
	int (*begin_request)(struct mg_connection *);
```
Here you have the connection object with the current request information.

Or do you need something else?

**Comment by albertino80** [comment]
Thanks for your time.

I have installed a new handler with `mg_set_request_handler `in which I have to use Java JVM.
Java JVM requires an initialization for each thread that uses it and needs a `JNIEnv* jenv` pointer; from which to invoke the methods.

I have evaluated the `init_thread`, but it seems to me that I have no way of associating my pointer to the thread for successive use (in a request_handler).
It would also miss a callback at `close_thread`.

My requirment is: 
- to have thread initialization (`init_thread` whould be fine)
- to set a user ptr at thread level
- to get back that pointer in request_handlers
- to have a destruction callback per thread, for finalizing Jvm

I can use `begin_request` and `end_request` for this, but initialize a JVM and delete it for each request is too heavy.

What have I done?

**civetweb.c**
```
struct mg_connection {
...
	void* user_data;
};
```
```
static void *
worker_thread_run(struct worker_thread_args *thread_args)
{
...
	conn->user_data = 0;
	if(ctx->callbacks.init_connection_thread)
	{
		ctx->callbacks.init_connection_thread(conn);
	}
...
	while (consume_socket(ctx, &conn->client, conn->thread_index)) {
... 	    Main worker loop
	}
...
	if(ctx->callbacks.free_connection_thread)
	{
		ctx->callbacks.free_connection_thread(conn);
	}
...	
}
```

**main.cpp**
before mg_start
```
...
	callbacks.init_connection_thread = init_connection_thread;
	callbacks.free_connection_thread = free_connection_thread;
	mg_start
...
```

My callbacks
```
void init_connection_thread(struct mg_connection *conn)
{
	void* user_data = get_connection_thread_data(conn);
	if(!user_data)
	{
		user_data = (void*)new MyClass();
		... initialization ...
		set_connection_thread_data (conn, user_data);
	}
}
void free_connection_thread(const struct mg_connection *conn)
{
	void* user_data = get_connection_thread_data(conn);
	if(user_data)
	{
		MyClass *myObj = (MyClass*)user_data;
		... destruction ...
		delete (MyClass*)user_data;
	}
}
```

My handler
```
int MyHandler(struct mg_connection* conn, void* cbdata)
{
	struct mg_context* ctx = mg_get_context(conn);
	MyClass *myObj = (MyClass*)get_connection_thread_data(conn);
	myObj->DoJava(...);
	...
}
```

**Comment by milipili** [comment]
Actually arbitrary custom struct per thread would help a lot to optimize some code. In many cases there is no reason to reallocate some data and can be reused inside the same thread.

**Comment by bel2125** [comment]
> Actually arbitrary custom struct per thread would help a lot to optimize some code. In many cases there is no reason to reallocate some data and can be reused inside the same thread.

What about using pthread_get/setspecific (Linux), respectively TlsGet/SetValue (Windows)?
What could civetweb do better for arbitrary thread specific data than the operating system?

**Comment by milipili** [comment]
Why using TLS (which can be costly depending on the platform, and limited anyway) where we can have a simple variable directly accessible?

**Comment by milipili** [comment]
A TLS is global to the app, and does not suit well in complex apps. Additionally it can be very costly, it depends on the OS implementation and might kill the performances. Additionally, dealing with resource allocation is complicated, where a simple `void*` with just 2 hooks can provide a fully-contained variable, with absolute scope delimitation. TLS are often a bad idea.

**Comment by milipili** [comment]
TLS has a non-negligible cost. And can e limited in many cases (`PTHREAD_KEYS_MAX` for example)
Quick links just for example:
*  https://testbit.eu/2015/thread-local-storage-benchmark
* https://software.intel.com/en-us/blogs/2011/05/02/the-hidden-performance-cost-of-accessing-thread-local-variables

Typical use-cases, more may apply:
* connection to a database, one per thread as rarely thread-safe.
* cache to avoid costly structures allocation. It may reduce the pressure to memory allocator by a lot

In current situation, we have to lock, which sucks as it is not required at all with a different design.

So yes, it is just a matter of storing an arbitrary pointer per thread, with simply 2 hooks to creating/destroying, so the additional cost for current civetweb scenarios should be nearly very low.

**Comment by bel2125** [comment]
> So yes, it is just a matter of storing an arbitrary pointer per thread, with simply 2 hooks to creating/destroying, so the additional cost for current civetweb scenarios should be nearly very low.

There is already a hook for [creating](https://github.com/civetweb/civetweb/blob/5e8d424458e682aac7ae0cdf1cdfac8d6f30ad6f/include/civetweb.h#L351):
```C
	/* Called when a new worker thread is initialized.
	   Parameters:
	     ctx: context handle
	     thread_type:
	       0 indicates the master thread
	       1 indicates a worker thread handling client connections
	       2 indicates an internal helper thread (timer thread)
	       */
	void (*init_thread)(const struct mg_context *ctx, int thread_type);
```
Would it be sufficient to return a `void *` (instead of `void`), store it somewhere so it can be accessed by all server functions with a `mg_connection` handle input?

Then some 
`void (*exit_thread)(const struct mg_context *ctx, int thread_type, void *thread_param);`
would work as destructor.

Is this what you need?

**Comment by milipili** [comment]
Perfect!

**Comment by bel2125** [comment]
Implementation available since February 2019
