### ISSUE TITLE
 Multiple SSL certificates

### ISSUE THREAD

**Issue by zhangsw** [civetweb/civetweb#535]
Does civetweb support multiple SSL certificates? We use civetweb in ceph, and we have two different domains. So we need two different SSL certificates.

**Comment by bel2125** [comment]
I'm not familiar with the details how civetweb is integrated in ceph.

You could start two server instances in one process by calling `mg_start` twice, if you use different ports. You don't have to do anything special for this, but the two domains will run on different ports (like 443 and 8443).

If you have two related sub-domains, like "x.mydomain.com" and "y.mydomain.com" you could probably use one certificate for "mydomain.com" using wildcards, even if you are using the same port (only one `mg_start` call). 

It should also be possible to use subject alternative names - personally I have no experience with this. It's a way to create one certificate valid for two or more domains, but you must always create a new certificate if you change the list of domains.

Currently SNI ([TLS Server Name Identication](https://en.wikipedia.org/wiki/Server_Name_Indication)) is not implemented in civetweb, but I think support for this can be added without big effort.
Some old clients do not support SNI, mostly browsers on WinXP and older embedded devices. According to https://caniuse.com/#search=sni, 98% of the browsers currently in use will work with SNI.
I have no statistics for other clients than browsers (machine to machine communication, curl, wget, ...).
You will reach the 100% only with one of the methods above.

**Comment by bel2125** [comment]
solved several months ago
