### ISSUE TITLE
Version 1.11 incompatibilities

### ISSUE THREAD

**Issue by bel2125** [civetweb/civetweb#544]
CivetWeb used to have a very high API compatibility, with old (obsolete) interfaces being available with a `MG_LEGACY_INTERFACE` define for years. In some cases, strict compatibility hampers the further development. Some of the planned enhancements for V1.11 require minor changes in API and configuration, some code in `MG_LEGACY_INTERFACE` will be finally removed.

This issue here is used to track the required changes, and aid as a guideline for users updating to V1.11. Incompatibilities and required changes will be numbered here (instead of creating a separate issue for every required change). Comments are welcome - please provide the same change number in your comment.

**Comment by kakwa** [comment]
It's a personal opinion (I like the semantic versioning spec: http://semver.org/).

If changes break public APIs, the major version number should be updated.

Next version should be 2.0 (or 2.0.0).

soversion should also move accordingly.

**Comment by bel2125** [comment]
Obsolete issue
