### ISSUE TITLE
mg_stop with secure websocket is crashing civetweb

### ISSUE THREAD

**Issue by grunk** [civetweb/civetweb#552]
Hi,

When i close civetweb (embedded in C++ app) via `mg_stop()` while a secure websocket (wss://) is still open and used by a browser i got a SIGPIPE (Broken pipe) in `close_connection()`

More specifically it's the call to SSL_shutdown() that seems to be the problem : 
```
#ifndef NO_SSL
	if (conn->ssl != NULL) {
		/* Run SSL_shutdown twice to ensure completly close SSL connection
		 */
		SSL_shutdown(conn->ssl); // This causing the crash
		SSL_free(conn->ssl);
/* Avoid CRYPTO_cleanup_all_ex_data(); See discussion:
 * https://wiki.openssl.org/index.php/Talk:Library_Initialization */
```

I'am able to reproduce this problem only on Linux (ubuntu 17.04) but not on Windows. 
CivetWeb 1.10 (downloaded from the tag) with -DNO_SSL_DL
OpenSSL 1.0.2h
Note : if the browser is closed before civetweb , everything works fine.

This is an extract of my websocket which basically just doing a ping/pong : 

```
bool HandlerWSStatus::handleData(CivetServer* /*server*/, mg_connection* conn, int flags, char* data, size_t data_len)
{
	int indexSocket = FindSocketId(conn);

	if (indexSocket == -1)
		return false;

	if (flags & 0x80)
	{
		flags &= 0x7f;
		switch (flags)
		{
		case WEBSOCKET_OPCODE_CONTINUATION:
			TRACE("CONTINUATION STATUS \n");
			break;
		case WEBSOCKET_OPCODE_TEXT:
		{
			//TRACE("WEBSOCKET_OPCODE_TEXT STATUS \n");
			break;
		}
			
		case WEBSOCKET_OPCODE_BINARY:
			TRACE("BINARY STATUS \n");
			break;
		case WEBSOCKET_OPCODE_CONNECTION_CLOSE:
		{
			if (mWsConnections[indexSocket].webSocketState != static_cast<int>(WSState::CLOSING)) {
				mg_lock_connection(conn);
				mg_websocket_write(conn, WEBSOCKET_OPCODE_CONNECTION_CLOSE, data, data_len);
				mg_unlock_connection(conn);
				mWsConnections[indexSocket].webSocketState = static_cast<int>(WSState::CLOSING);
			}
			break;
		}
			
		case WEBSOCKET_OPCODE_PING:
			mg_lock_connection(conn);
			mg_websocket_write(conn, WEBSOCKET_OPCODE_PONG, data, data_len);
			mg_unlock_connection(conn);
			break;
		case WEBSOCKET_OPCODE_PONG:
			TRACE("PING STATUS \n");
			break;
		default:
			TRACE("DEFAULT STATUS : %02x\n", flags);
		}
	}

	return true;
}
```

**Comment by bel2125** [comment]
> CivetWeb 1.10 (downloaded from the tag)

So, you used the 1.10 release (from 2017-09-26), not some intermediate version.

There is a similar issue (similar from the description): #515 
I fixed the crash in #515 on 2017-09-21, just a few days before the 1.10 release.

My quick test (test/websocket.xhtml+lua, Ubuntu 16.04, OpenSSL 1.0.2g, current HEAD version of standalone server) did not cause the same problem. 

SIGPIPE should be ignored by the server.
Current code (
```
	memset(&sa, 0, sizeof(sa));
	sa.sa_handler = SIG_IGN;
	sigaction(SIGPIPE, &sa, NULL);
```
Old code from 1.10
```
	(void)signal(SIGPIPE, SIG_IGN);
```
Change: https://github.com/civetweb/civetweb/commit/b7678afb55f02143476bb1393fcda1c3ac0e1428

Did you change anything regarding signal handling?

**Comment by grunk** [comment]
I'll gonna double check the version used tomorrow and let you know.
Thanks for your answer.

**Comment by bel2125** [comment]
Please also check if there are other uses of "SIGPIPE" somewhere else in your code. Maybe you turn signal handling back to default (abort) somewhere in your application.

**Comment by grunk** [comment]
Just updated to HEAD and everything works fine. So i guess the b7678af commit did the job :)

I defined -DMG_LEGACY_INTERFACE to get my code to compile. Is that ok ? I guess i'll need to update my code in the future ?

Thanks

**Comment by bel2125** [comment]
The `MG_LEGACY_INTERFACE` is for old functions superseded by newer ones. The old functions should still work, but they are no longer tested in a continuous integration test. For most functions there is a guideline how to update to the corresponding new function, with one exception: `open_file` (see [this discussion/decision](https://groups.google.com/forum/#!topic/civetweb/h9HT4CmeYqI) to drop it without direct replacement).
