### ISSUE TITLE
Questions on global lock in mg_init_library

### ISSUE THREAD

**Issue by extergnoto** [civetweb/civetweb#568]
The following code is from trunk, but 1.10 is basically the same.

1) I think an unlock is missing in case of error (see UNLOCK_ON_ERROR)
2) The global mutex is created with default attributes. At least on my system this means non recursive. I get a dead lock, because the mutex is locked again in mg_atomic_inc.

```C
unsigned
mg_init_library(unsigned features)
{
#if !defined(NO_SSL)
	char ebuf[128];
#endif

	unsigned features_to_init = mg_check_feature(features & 0xFFu);
	unsigned features_inited = features_to_init;

	if (mg_init_library_called <= 0) {
		/* Not initialized yet */
		if (0 != pthread_mutex_init(&global_lock_mutex, NULL)) {
			return 0;
		}
	}

	mg_global_lock();

	if (mg_init_library_called <= 0) {
		if (0 != pthread_key_create(&sTlsKey, tls_dtor)) {
			/* Fatal error - abort start. However, this situation should
			 * never occur in practice. */
#ifdef UNLOCK_ON_ERROR
                       mg_global_unlock();
#endif
			return 0;
		}

#if defined(_WIN32) && !defined(__SYMBIAN32__)
		InitializeCriticalSection(&global_log_file_lock);
#endif /* _WIN32 && !__SYMBIAN32__ */
#if !defined(_WIN32)
		pthread_mutexattr_init(&pthread_mutex_attr);
		pthread_mutexattr_settype(&pthread_mutex_attr, PTHREAD_MUTEX_RECURSIVE);
#endif

#if defined(USE_LUA)
		lua_init_optional_libraries();
#endif
	}


#if !defined(NO_SSL)
	if (features_to_init & MG_FEATURES_SSL) {
		if (!mg_ssl_initialized) {
			if (initialize_ssl(ebuf, sizeof(ebuf))) {
				mg_ssl_initialized = 1;
			} else {
				(void)ebuf;
				DEBUG_TRACE("Initializing SSL failed: %s", ebuf);
				features_inited &= ~(2u);
			}
		} else {
			/* ssl already initialized */
		}
	}
#endif

	/* Start WinSock for Windows */
	if (mg_init_library_called <= 0) {
#if defined(_WIN32) && !defined(__SYMBIAN32__)
		WSADATA data;
		WSAStartup(MAKEWORD(2, 2), &data);
#endif /* _WIN32 && !__SYMBIAN32__ */
		mg_init_library_called = 1;
	} else {
		mg_init_library_called++;
	}

	mg_global_unlock();

	return features_inited;
}
```

**Comment by bel2125** [comment]
1) Essentially you are right - still, this piece of code will never be reached in practice. If `pthread_key_create()` fails, you probably need to restart your entire computer, free some memory, exchange some operating system libraries, ... but I cannot imagine any situation where you could continue in any reasonable way.

2) I know it's default attributes but I did not get a recursion in any of my test systems - basically Windows and Linux. What system are you using? Did you set the `NO_ATOMICS` define?

In principle the `mg_global_lock` can be removed completely from `mg_init_library` as well, since `mg_init_library` by definition must only be called by one thread a time - the caller has to take care of this.

**Comment by extergnoto** [comment]
1) OK
2) I use an embedded system. It is´t neither _WIN32 nor __GNUC__. Therfore the default branch is selected in the atomic functions, using the global lock. This causes a deadlock. 
My workaround is to add an additional branch without any atomicity, which is tolerable, because I have only one CPU core.

**Comment by bel2125** [comment]
On a single core machine with preemtive multi-threading, you might still need some lock - although the multicore atomicity is not required. Even a statement as simple as `x++` is not multithreading safe without a lock. The compiler might create code like 
```
LOAD [x] into register
increment register
STORE register to [x]
```
And if you do this with two threads, x might be incremented either by 2 or only by 1 (if thread two interrupts thread 1 in the middle).

The more safe solution seems to be to remove the mg_global_lock from mg_init_library - the caller has to take care to call this function only once.

**Comment by bel2125** [comment]
I removed the lock from mg_init_library some weeks ago, but it was too busy before Christmas and forwent giving feedback ... and finally forgot.
Did you try the current version? It should not have any deadlock, but I did not test it with a "non Windows, non Linux, non GNU" system.

**Comment by extergnoto** [comment]
It works. Thanks.

Just a remark:
In mg_init_library I find the following line:
  features_inited &= ~(2u);
2u should probably be replaced by the symbolic name.

**Comment by bel2125** [comment]
You are right. I will do this.
