### ISSUE TITLE
Race condition when stopping server with ongoing websocket connection

### ISSUE THREAD

**Issue by extergnoto** [civetweb/civetweb#570]
I am using version 1.10, but master is the same.

The following race condition causes a dead lock:
- When stop is called with a websocket connection running, the master thread raises the signal, but the worker thread misses it, because it is processing the websocket.
- Afterwards, when the worker either recognizes the stop flag or the closed socket, it enters consume_socket() again. There it blocks on the event forever. 
- The master thread waits in join forever.

Is it really necessary to enter consume_socket() again when the stop_flag is already set?
I think the commentary in worker_thread_run() is not up to date any more.

**Comment by bel2125** [comment]
You are referring to this comment?
```
	/* Call consume_socket() even when ctx->stop_flag > 0, to let it
	 * signal sq_empty condvar to wake up the master waiting in
	 * produce_socket() */
```

The `sq_empty` variable is no longer used in the default build. I replaced the queue implementation of the original author some time ago, but left it in the code with some define:

```C
/* Connection to thread dispatching */
#ifdef ALTERNATIVE_QUEUE
	struct socket *client_socks;
	void **client_wait_events;
#else
	struct socket queue[MGSQLEN]; /* Accepted sockets */
	volatile int sq_head;         /* Head of the socket queue */
	volatile int sq_tail;         /* Tail of the socket queue */
	pthread_cond_t sq_full;       /* Signaled when socket is produced */
	pthread_cond_t sq_empty;      /* Signaled when socket is consumed */
#endif
```
`ALTERNATIVE_QUEUE` (my implementation) is the default since some time. 
The original source code comment makes no sense for the new queue.

**Comment by bel2125** [comment]
... again here: Done some related changes some weeks before, but I did not ask for feedback (I really had to much to do before Christmas, and then successfully utilized the holidays to forget everything).

Does it fix this issue for you?

**Comment by extergnoto** [comment]
I implemented the same fix inside consume_socket and it works.
