### ISSUE TITLE
Embended file resources

### ISSUE THREAD

**Issue by BigJoe01** [civetweb/civetweb#571]
Hi,
I need a little help, have any support for serve files from memory?

Regards

**Comment by jbmonroe** [comment]
Would that be from all routes, or just selected routes?  My default route handler caches the home page until it changes--then re-caches it.  It's pretty easy to do yourself if your handlers derive from CivetHandler--no extra support required from CivetWeb.

**Comment by BigJoe01** [comment]
Thanks

**Comment by jbmonroe** [comment]
I can provide more gruesome details if you need them.
