### ISSUE TITLE
HTTP responses overwriting each other

### ISSUE THREAD

**Issue by jbmonroe** [civetweb/civetweb#572]
I'm not sure if this is a defect, or an issue with the way I've written my application--so here goes nothing.

My application manages a data store and serves a page to multiple users at once.  The page loads two scripts--let's call them $.js and work.js from the local server.  They have to be local because of security requirements at the site.  I've derived some classes via CivetHandler to handle the routes, and one of those handles scripts.  The work.js file requires some "macro replacement" before going out to the caller, and $.js doesn't.  For convenience I'm just letting CivetWeb handle both.

I know that anything derived from CivetHandler has to be thread-safe, and I reviewed my code again this morning to make sure I'm enforcing that, and I believe I am.  Nevertheless, sometimes I see the browser issuing overlapping requests for both $.js and work.js, and my log says they're both being handled--but $.js goes back to the caller as an empty stream, and work.js goes back as both scripts, separated by a redundant HTTP/1.1 header between the two scripts.

The browser is not impressed.  (Neither is QA.) 

So, on the topic of reentrancy and thread-safety, should I be ensuring that--even though there are two instances of the script handler class, each presumably with a separate mg_connection, handling the requests--only one instance of a script handler is allowed to call mg_write at a time?  I might even have to elevate it to the "parent" class that derives from CivetHandler, as the issue might occur during overlapping calls from separate users.   The docs for mg_write() don't say that it should be tied to an exclusion mechanism, but mg_lock_connection() and mg_lock_context() exist--and the docs don't appear to suggest that they should always be bracketing calls to mg_write().  I don't know what I'm seeing here, so I'd appreciate any guidance that anyone has on how to handle this.

**Comment by bel2125** [comment]
You can call `mg_write` from two threads, as long as you have two different `mg_connection` handles.
If you want to write to the same `mg_connection` from two different threads, you have to call `mg_lock_connection` first. You do not need `mg_lock_context`, except when you modify the server, e.g. by installing additional handlers - but never for `mg_write`.

**Comment by jbmonroe** [comment]
I don't want to write to the same connection from different threads--and since I can't compare the connections in separate threads (at least not without some overhead) I don't know how I'd tell the difference.

I think the problem I'm having is caused by there only ever being one instance of a ThisHandler or ThatHandler, rather than having a new instance spun up when the capturing thread dispatches the handleGet(), or what-have-you.  I determined this by noticing that the code, if it was first invoked by Chrome, would then say that all other callers were also using Chrome.  It looks like what I need to do is write generic top-level handlers that create and invoke route-specific implementation handlers internally. Without some template or RTTI magic, I don't think you can create a new instance of ThisHandler or ThatHandler for a new connection...am I right?

Right now simply locking the handleGet or handlePost methods works.  There's not going to be enough traffic or transactions to warrant any other approach than serialization by exclusion, and I have to do that already for reads and updates to the data store.    The whole project exists because someone insisted that no one could possibly ever figure out how to edit a configuration file with NotePad.

**Comment by bel2125** [comment]
You probably derived your "ThisHandler" and "ThatHandler" from
```C++
/**
 * Basic interface for a URI request handler.  Handlers implementations
 * must be reentrant.
 */
class CIVETWEB_API CivetHandler {
...
virtual bool handleGet(CivetServer *server, struct mg_connection *conn);
...
virtual bool handlePost(CivetServer *server, struct mg_connection *conn);
...
}
```
You distinguish different connections by different `conn` parameters. You cannot use any member variable in your derived class to store data, since then your handler implementation will no longer be reentrant and share these member variables between different connections. In C, you would use the `conn_data` member with `mg_get_user_connection_data` ... I think this function is not yet available in C++ ... the C++ interface is not as complete as the C interface.
I personally only use the C interface - I just inherited the existing C++ interface with the project - so probably someone else can give better hints on how to use the C++ interface most effectively.

**Comment by bel2125** [comment]
You cannot use variables like
```C++
class ThisHandler : CivetHandler {
private:
   int something;
   string morethings;
...
   bool handleGet(CivetServer *server, struct mg_connection *conn);
}
```

but you can use local variables

```C++
bool ThisHandler::handleGet(CivetServer *server, struct mg_connection *conn) 
{
   int something;
   string morethings;
   ...
}
```

Then you don't need a lock ... of course you can use one, if parallel access of multiple clients to the same HTTP resource (the same handler) is not required.

**Comment by bel2125** [comment]
Anything else I can do here to help?

**Comment by jbmonroe** [comment]
Nope--not on this one, at least.  The SSL thing is still kicking our behinds, but I have someone else working on that on an Azure server.  I rewrote my handlers to call instances of other classes NOT derived from CivetHandler, and it works a treat.

Thanks for confirming that I was Doing It Wrong (c) (tm) (patent pending).  \<grin\>
