### ISSUE TITLE
Any tips for getting server-sent events to work?

### ISSUE THREAD

**Issue by colmartofus** [civetweb/civetweb#574]
I use to use server-sent events in my application: https://hpbn.co/server-sent-events-sse/

I've been able to implement this with libsoup but I want to use Civet. My relevant soup code:

```
connection->finished = false;
connection->nextIdentifier = 0;
connection->msg = msg;
connection->server = server;
g_signal_connect(msg, "finished", G_CALLBACK(on_finished), connection.get());
self->connectionsMutex.lock();
self->connections.push_back(connection);
self->connectionsMutex.unlock();
```

For Civet:

- Is `SO_KEEPALIVE` automatically active if `Connection: Keep-Alive` is in the header text?
- Do I have to keep the connection alive myself or will this happen automatically?
- How to have an onFinished callback?

My current code:

```
bool DetectionMetadataHandler::handleGet(CivetServer *server, struct mg_connection *conn) {
  mg_printf(conn,
            "HTTP/1.1 200 OK\r\n"
            "Cache-Control: no-cache\r\n"
            "Content-Type: text/event-stream\r\n"
            "Transfer-Encoding: chunked\r\n"
            "Connection: Keep-Alive\r\n\r\n");
  return true;
}
```
Any tips?

**Comment by bel2125** [comment]
I did never use SSE myself, usually I use websockets.

Keep alive needs to be enabled in the CivetWeb configuration, by setting `enable_keep_alive yes` (see [manual](https://github.com/civetweb/civetweb/blob/master/docs/UserManual.md#enable_keep_alive-no)).

**Comment by colmartofus** [comment]
That manual was enough to help me get it working. Much thanks.
