### ISSUE TITLE
Option to set the server charset

### ISSUE THREAD

**Issue by PhilLab** [civetweb/civetweb#580]
As my backend is not fully utf-8 capable, I want to configure civetweb such that all clients connecting to it know to communicate e.g. in ISO-8859-1 (ANSI)

**Comment by bel2125** [comment]
So, you want CivetWeb to send content type headers like this?

Content-Type: text/html; charset=ISO-8859-1

(from the registered charset table https://www.iana.org/assignments/character-sets/character-sets.xhtml)

Or, you want the server to reject all requests not using this charset?

**Comment by bel2125** [comment]
I just checked the RFC again: All HTTP header data sent by any client to the server is supposed to be ASCII: https://tools.ietf.org/html/rfc7230#section-3.2.4 (even ISO-8859-1 is only historical and new fields should be all ASCII).

Maybe this is interesting as well:
https://stackoverflow.com/questions/4400678/what-character-encoding-should-i-use-for-a-http-header

But, from my experience it is by no means important if the backend supports UTF-8. Even embedded backends (with operating systems much smaller than Linux or Windows) that do not even know what character encoding is can handle UTF-8, if you consider a few small things.

But before I go into details, please explain the problem in more detail.

**Comment by PhilLab** [comment]
The specific problem I encounter happens when my backend reacts to file uploads with files having non-ASCII characters in the filename, e.g. Umlauts üöä. If I then pass these parameters to a file copy/creation routine (e.g. the one from boost::filesystem), it fails because it cannot resolve the filename correctly.

If I explicitly convert the string to 1252 using the function below before copying, it works and I see the correct filename on my disc. I was now wondering if there is a way besides converting each and every string I handle in the backend.

```
string utf8ToString(const string& utf8String, const locale targetLocale /*= locale(".1252")*/)
{
    try {
        // UTF-8 to wstring. throws std::range_error if not successful
        wstring_convert<codecvt_utf8<wchar_t>> wconv;
        wstring wstr = wconv.from_bytes(utf8String.c_str());
        // wstring to string
        if (wstr.empty()) {
            return std::string();
        }
        else {
            vector<char> buf(wstr.size());
            use_facet<ctype<wchar_t>>(targetLocale).narrow(wstr.data(), wstr.data() + wstr.size(), '?', buf.data());
            return std::string(buf.data(), buf.size());
        }
    }
    catch (range_error&) {
        //  text doesn't seem to be an UTF-8 string. Assuming Win-1252 instead");
        return utf8String;
    }
}
```

**Comment by bel2125** [comment]
Welcome to the wonderful world of string encoding ;-)

Windows systems use either a specific code page, such as [Windows-1252](https://en.wikipedia.org/wiki/Windows-1252) (fine for English, German and most Western-European languages and, as to my knowledge, the earliest code-page for Windows), but there are also other code pages.
Alternatively Windows can use UTF-16, but the basic Windows system APIs cannot use UTF-8

In contrast Linux always uses UTF-8 but cannot use UTF-16 or anything equivalent to Windows code pages. The GNU Linux compiler can also use UTF-32 (although the Linux system API cannot).
In contrast, Visual Studio C++ cannot use UTF-32 but only UTF-16.

Other programming languages than C/C++ may use other encodings.

When communicating between systems, you must always define the encoding, otherwise Umlauts will break. You can define whatever encoding you prefer, as long as both sides agree. 

> I was now wondering if there is a way besides converting each and every string I handle in the backend.

From my point of view, it's the only reasonable way, at least if the backend should be operating system independent. It's what `mg_open` in CivetWeb does when calling `path_to_unicode`.

**Comment by PhilLab** [comment]
okay, thanks for the insights. So is there a possibility to configure civetweb's default code page? I see several hard-coded strings "charset=utf-8" but no configurable code point. If there is none, it is probably the best to fix my middleware connecting with the webserver and leaving civetweb at UTF-8

**Comment by bel2125** [comment]
> okay, thanks for the insights. 

:smirk:


> So is there a possibility to configure civetweb's default code page? I see several hard-coded strings "charset=utf-8" but no configurable code point. If there is none, it is probably the best to fix my middleware connecting with the webserver and leaving civetweb at UTF-8.
> Also it seems that ajax will always use UTF-8

Currently there is none, and even if I add something simple like 

```C
#ifndef CHARSET
#define CHARSET "utf-8"
#endif

...

mg_printf(conn, "Content-Type: text/plain; charset=%s\r\n", CHARSET);

...

```
I am not sure if it will fulfil your requirements. CivetWeb uses UTF-8, so it can directly use Linux system API functions. For Windows, there are conversion functions in civetweb.c. If I got it right, your system is neither Linux nor Windows. What character encoding is your system using?

**Comment by PhilLab** [comment]
It is windows and the problems arise after some post-processing of filenames, other parameters, etc.. so although mg_open is UTF-8 capable, the problem lies in my middleware. I was just hoping to find an easy workaround using what the HTTP protocol offers. But as this is not possible or even sensible, I will close this issue.
