### ISSUE TITLE
WSS Client example?

### ISSUE THREAD

**Issue by CrackerHax** [civetweb/civetweb#593]
Looks like a lot of the old examples don't work anymore and a lot of ssl code has changed. Any chance to get an example for TLS websocket clients? Shouldn't mg_connect_websocket_client with 'use_ssl' "just work"?

**Comment by bel2125** [comment]
By "old examples" you mean the ones in the obsolete folder https://github.com/civetweb/civetweb/tree/master/examples/_obsolete ?

There is a WSS client in the unit test - it "just works" by setting `use_ssl` to 1:
https://github.com/civetweb/civetweb/blob/a8b11a99eb84046ed225224c254c0ceb090ab8ff/unittest/public_server.c#L1965

**Comment by CrackerHax** [comment]
When trying to connect to echo.websocket.org I get Error: SSL is not initialized.

**Comment by CrackerHax** [comment]
```
struct tclient_data {
  void *data;
  size_t len;
  int closed;
};
struct tclient_data client1_data = {NULL, 0, 0};
struct mg_connection *newconn1 = NULL;
static int
websocket_client_data_handler(struct mg_connection *conn,
                              int flags,
                              char *data,
                              size_t data_len,
                              void *user_data)
{
  struct mg_context *ctx = mg_get_context(conn);
  struct tclient_data *pclient_data =
    (struct tclient_data *)mg_get_user_data(ctx);

  printf("Client received data from server: ");
  fwrite(data, 1, data_len, stdout);
  printf("\n");

  pclient_data->data = malloc(data_len);
  assert(pclient_data->data != NULL);
  memcpy(pclient_data->data, data, data_len);
  pclient_data->len = data_len;

  return 1;
}

static void
websocket_client_close_handler(const struct mg_connection *conn,
                               void *user_data)
{
  struct mg_context *ctx = mg_get_context(conn);
  struct tclient_data *pclient_data =
    (struct tclient_data *)mg_get_user_data(ctx);

  printf("Client: Close handler\n");
  pclient_data->closed++;
}
void startWebsocket()
{
  char ebuf[100] = {0};                                                                                                                       
  std::string path = "/";
  newconn1 = mg_connect_websocket_client("echo.websocket.org",
                                         443,
                                         true,
                                         ebuf,
                                         sizeof(ebuf),
                                         path.c_str(),
                                         NULL,
                                         websocket_client_data_handler,
                                         websocket_client_close_handler,
                                         &client1_data);

  if (newconn1 == NULL) {
    printf("Error: %s", ebuf);
    //    return 1;                                                                                                                                                     
  }

```

**Comment by bel2125** [comment]
Did you call "mg_init_library(MG_FEATURES_SSL)"?

**Comment by CrackerHax** [comment]
Yes, and I get 
`Error: SSL_CTX_new`

**Comment by bel2125** [comment]
> Yes, and I get
> Error: SSL_CTX_new

Could you please provide some more details? Where do you get this - in a log, as a return code, ... from what function? And the full error message ... there is no error message in the code that's only "Error: SSL_CTX_new".

**Comment by CrackerHax** [comment]
Yes I got the error from 
`if (newconn1 == NULL) {
    printf("Error: %s", ebuf);
    //    return 1;                                                                                                                                                     
  }`
As I posted earlier...
But yes, not very informative is it? I assume the error is from ssl.

**Comment by bel2125** [comment]
In the current head version, I can't locate any place in civetweb.c setting only this function name to an ebuf. What version are you using? Are you using the `NO_SSL_DL`? 

Probably it's best to use a debugger to locate where this error is coming from.

**Comment by bel2125** [comment]
The following example works for me:
```C
#include <time.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include "civetweb.h"

struct tclient_data {
	void *data;
	size_t len;
	int closed;
};

struct tclient_data client1_data = {NULL, 0, 0};
struct mg_connection *newconn1 = NULL;

static int
websocket_client_data_handler(struct mg_connection *conn,
                              int flags,
                              char *data,
                              size_t data_len,
                              void *user_data)
{
	struct mg_context *ctx = mg_get_context(conn);
	struct tclient_data *pclient_data =
	    (struct tclient_data *)mg_get_user_data(ctx);

	printf("Client received data from server: ");
	fwrite(data, 1, data_len, stdout);
	printf("\n");

	pclient_data->data = malloc(data_len);
	/* assert(pclient_data->data != NULL); ... just sigfault */
	memcpy(pclient_data->data, data, data_len);
	pclient_data->len = data_len;

	return 1;
}

static void
websocket_client_close_handler(const struct mg_connection *conn,
                               void *user_data)
{
	struct mg_context *ctx = mg_get_context(conn);
	struct tclient_data *pclient_data =
	    (struct tclient_data *)mg_get_user_data(ctx);

	printf("Client: Close handler\n");
	pclient_data->closed++;
}

void
startWebsocket()
{
	char ebuf[100] = {0};
	const char *path = "/";
	newconn1 = mg_connect_websocket_client("echo.websocket.org",
	                                       443,
	                                       1,
	                                       ebuf,
	                                       sizeof(ebuf),
	                                       path,
	                                       NULL,
	                                       websocket_client_data_handler,
	                                       websocket_client_close_handler,
	                                       &client1_data);

	if (newconn1 == NULL) {
		printf("Error: %s\n", ebuf);
	} else {
		const char *text = "Can you hear me, Major Tom?";
		printf("OK ... sending text\n");

		mg_websocket_client_write(newconn1,
		                          MG_WEBSOCKET_OPCODE_TEXT,
		                          text,
		                          strlen(text));
		sleep(1);
	}
}

void
main(void)
{
	mg_init_library(MG_FEATURES_SSL);
	startWebsocket();
}
```
Build and run:
```
$ cc y.c src/civetweb.c -DUSE_WEBSOCKET -Iinclude -lpthread -ldl
$ ./a.out OK ... sending text
Client received data from server: Can you hear me, Major Tom?
```

**Comment by CrackerHax** [comment]
That worked for me too, thanks!
Now we have a nice little example to add to the project!

**Comment by CrackerHax** [comment]
Oh I think I see the problem. I was able to connect, but when I tried a second time it wouldn't connect. I wonder if this has something to do with openssl being busy or not shutting down correctly?

**Comment by bel2125** [comment]
> Now we have a nice little example to add to the project!

I just used your original source code (call it x.c) and modified it as little as possible to make it complete and C, not C++ (call it y.c). But there are a couple of issues with this example:

1) There is a `malloc(data_len);` but no free
2) `mg_get_user_data(ctx);` is per callback, not per connected client connection, and refers to global data.
3) It works just for one response package and it does not filter packages without payload data (e.g., PING/PONG).
4) It never closes the connection, and does not wait for the server to close the connection. It does not free the resources allocated for the connection.

> I wonder if this has something to do with openssl being busy or not shutting down correctly?

Seems unlikely. I cannot reproduce this by calling the executable multiple times, and I cannot reproduce it by calling `startWebsocket();` in a loop in main. I did not try it with multiple threads in the same process, since the callback implementation is not thread-safe (see 2). If this is still important, and you could provide full details how to reproduce this error, I might be able to tell more.

For the example: I agree, it is probably a good idea to add a new set of client examples.

**Comment by bel2125** [comment]
A new example is available here:
https://github.com/civetweb/civetweb/tree/master/examples/ws_client
