### ISSUE TITLE
Is there a way to dynamically generate some data while using document root?

### ISSUE THREAD

**Issue by tamertemizer** [civetweb/civetweb#595]
We have a web application that receives information from the database and prints it to the web page. Most of the pages are static but each page has data that needs to be dynamically generated with the information from the database. Do I need to create handlers for each page or is there a way to use document root for the static parts of the pages and use handlers only for the dynamic parts? 

I am trying to avoid embedding all of the static html code to the civetweb.

**Comment by bel2125** [comment]
There are many ways to do that. You can add handler only for the pages that have dynamic data, if you have some pattern to distinguish static from dynamic pages. This could be a a file extension, a path prefix or something else from the file name (the URI). You could also have a dynamic handler for everything and call "mg_send_file" or "mg_send_mime_file(2)" if your handler code finds this is a static file.
You could build a directory tree with some Lua handlers, or you could completely avoid Lua and do everything in C.
The [embedded_c](https://github.com/civetweb/civetweb/blob/master/examples/embedded_c/embedded_c.c) example also uses a mixture of static files in the document root and various handlers (but no Lua).

**Comment by tamertemizer** [comment]
But as I understand it, if I have a single HTML file that has 95% static content and 5% dynamic content, I need to create a handler that embeds 100% of the code in the html file. I can't say civetweb to import the static content from document root and create a handler that just fills some placeholders with a handler (I am talking about a single HTML file). Is that correct?

**Comment by bel2125** [comment]
Ok, I thought you have 95% of files that are 100% static and 5% that are (almost) 100% dynamic.

But you rather need something like [page.lp](https://github.com/civetweb/civetweb/blob/master/test/page.lp) or [page3.lp](https://github.com/civetweb/civetweb/blob/master/test/page3.lp): 
```html
<html> 
  some html 
  <? script ?> 
  again html 
</html>
```
Right?

**Comment by bel2125** [comment]
The examples above are "Lua server pages" - the script in between `<?` and `?>` can be full [Lua](http://www.lua.org/) syntax - see [documentation](https://github.com/civetweb/civetweb/blob/master/docs/UserManual.md#lua-scripts-and-lua-server-pages).

Is this what you need?
Then I could give you some more links on how to connect this to a database or a C application.
What operating system are you using?

**Comment by tamertemizer** [comment]
Thanks! Yes, this is what I need. I am running civetweb on Debian 32 bit.

**Comment by bel2125** [comment]
Ok. So, to get a first test system, you can build civetweb with
```
make WITH_LUA=1
```
or, to get even more features
```
make WITH_ALL=1
```
this will get you an executable. Run it with
```
./civetweb -document_root test
```
Then you can open http://localhost:8080 and test the page*.lp in action.


For the next step, there are several questions you need to consider:
What database do you need to connect to? Are you free to choose the database technology or do you need to connect to an existing one?
Is there an existing Lua interface for this database, and you could just use the executable from above and do everything in a script?
Otherwise you need to create an interface, in C/C++. 
It is possible to create this interface as a library and use the existing executable.
It is also possible to add civetweb.c (web functionality) to an existing C/C++ application.

If you need to create a C/C++ interface, you could either create a standard Lua library.
But there is also a "convenience interface" for C/C++ applications (available in mainline in a week).

**Comment by tamertemizer** [comment]
I am connecting to a SQLite database, which is convenient considering Civetweb and Lua both support it.

I created a simple Lua server page which retrieves data from a SQLite3 database and plugs it into some predetermined position in a HTML file. It worked nicely initially but stopped working after restarting civetweb service. Which is kind of weird considering no code is changed and browser's cache was cleared before both trials. 

By the way stopped working means it encapsulated all of the HTML code in a <pre> tag. So it just prints all the code in plaintext instead of executing the code. I triple checked I built civetweb with Lua support (using make WITH_LUA=1) yet the problem continues.

The problem exists even if I copy a valid HTML page to a Lua server page. So the problem is not with the syntax. If the file extension is *.lp it can't execute the code.

Do you have any idea why this might happen?

**Comment by bel2125** [comment]
Disabled Lua support in the build would be my first suggestion as well - but you said you triple checked this.
You could "quadruple" the test by trying if *.lua scripts are executed.
Then it could be a misconfiguration of `lua_server_page_pattern`. 

Does it occur with the test pages in the civetweb/test directory as well?

**Comment by tamertemizer** [comment]
It magically sorted itself out after restarting few things. It is stable now. Thank you very much for your assistance.
