### ISSUE TITLE
using "localhost:8080" as listening_ports

### ISSUE THREAD

**Issue by albertino80** [civetweb/civetweb#600]
I'm embedding civetweb on win32 project.

I need to bind `localhost` address on port `8080`, this is usefull because on windows using `localhost` instead of `127.0.0.1` does not require to open local firewal port (that is a strange request for a end user).

```
const char *options[] = {
        "listening_ports", "localhost:8080",
...
}
```
The problem is with the function 
```
static int
is_ssl_port_used(const char *ports)
```
that check for a 's' or 'r' character on port string, and string `localhost ` contains letter 's'

So i suggest to consider this implementation:
```
/* Is there any SSL port in use? */
static int
is_ssl_port_used(const char *ports)
{
	if (ports) {
            int portslen = (int)strlen(ports);
            char prevIsNumber = 0;
            for(int i=0; i<portslen; i++) {
                if(prevIsNumber && (ports[i] == 's' || ports[i] == 'r'))
                    return 1;
                if(ports[i] >= '0' && ports[i] <= '9')
                    prevIsNumber = 1;
                else
                    prevIsNumber = 0;
            }
        }
	return 0;
}
```

**Comment by bel2125** [comment]
You are definitely right, the "s" in localhost and other host names might cause this kind of confusion and initialize SSL although it's not required. Did you test that code so I can directly merge it?

**Comment by bel2125** [comment]
It might still be confused by a hostname like "my24something", but it's definitely an improvement.
Merged.

**Comment by albertino80** [comment]
Thanks
