### ISSUE TITLE
Sqlite3 works with Civetweb 1.8 but not Civetweb 1.10

### ISSUE THREAD

**Issue by tamertemizer** [civetweb/civetweb#601]
Hi, we have a sqlite3 application which worked perfectly with civetweb 1.8. After we upgraded civetweb to 1.10, I can't connect to the database and it won't execute any Lua commands after that line. I connect to database with `db=sqlite3.open(mg.document_root .. '/test.db')` which worked perfectly fine in the older version. The source files, the database and civetweb.conf is exactly the same between versions.

I built the new version with `make clean`  `make build WITH_LUA=1` and `make install`. Is there any change in 1.10 that might break the application?

**Comment by bel2125** [comment]
> Is there any change in 1.10 that might break the application?

I'm not aware of any such incompatibility, and I also tested it with every release using the test scripts in the test folder. You are using Linux?

Maybe there is a newer version of sqlite im more recent versions of CivetWeb, but I'm not aware of an incompatibility "you can't open old databases with new sqlite3 versions". Did you use an old data base or create a new one anyway? 
No, ... my test data base shows entries from 2015 to 2018, so it's definitely possible to use the old data base as well.

Did you get any error message?

**Comment by bel2125** [comment]
In case of an error, sqlite3.open returns nil, an error code and an error message.
Could you try `db, errcode, errmsg = sqlite3.open(mg.document_root .. '/test.db')` and print `errcode` and `errmsg` if open fails?

**Comment by tamertemizer** [comment]
I tried to reinstall civetweb-1.10 from scratch to be certain. Sqlite3 still doesn't work. I tried loading page.lua under test folder. Sqlite3 object is null. That is the problem. So there is no sqlite3.open at all and I can't print an error code. Do I need to do any additional things to install civetweb's Sqlite3 module?

**Comment by bel2125** [comment]
try the following sequence:

1) copy the entire repository to /somewhere/civetweb
2) go into that directory
3) `make clean`
4) `make WITH_LUA=1`
5) `./civetweb -I`
==> please post the result of this
6) `ls -l req*`
==> check if requests.db exists,
==> if yes: do you have write access
==> if yes: is it a valid database file 
==> in case of doubt, delete requests.db, the server will create a new one
6) `./civetweb -document_root test &`
7) http://localhost:8080/page.lua (please take the new page.lua from the repository)

The new page will print some error code:
http://lua.sqlite.org/index.cgi/doc/tip/doc/lsqlite3.wiki#numerical_error_and_result_codes

I could only reproduce an error, if cleared the read permission for the request.db file

**Comment by tamertemizer** [comment]
CivetWeb V1.10 (CivetWeb V1.10)
{
"version" : "1.10",
"os" : "Linux #1 SMP Debian 4.9.65-3+deb9u1 (2017-12-23) (4.9.0-4-686) - i686",
"features" : 3751,
"feature_list" : "Server: Files HTTPS CGI Lua Cache",
"lua_version" : "502 (Lua 5.2.4)",
"build" : "Mar 29 2018",
"compiler" : "gcc: 6.3.0",
"data_model" : "int:2/4/4/8, float:4/8/12, char:1/4, ptr:4, size:4, time:4"
}



This is Lua script example 1, served by the CivetWeb web server, version 1.10.

The following features are available:

    Lua 5.2 server pages
    lua file system

Today is Thursday

URI is /page.lua

/home/alphan/Desktop/civetweb-1.10/test/page.lua:43: attempt to index global 'sqlite3' (a nil value)
stack traceback:
	[string "mg.write(debug.traceback(), '\n')"]:1: in main chunk
	[C]: in function '__index'
	/home/alphan/Desktop/civetweb-1.10/test/page.lua:43: in main chunk

**Comment by tamertemizer** [comment]
This is the output of civetweb -I and page.lua. I gave the database read/write permissions but I don't think it is relevant. There is no function named sqlite3.open as sqlite3 object does not exist. So it won't print an error code.

**Comment by tamertemizer** [comment]
Hi I just tried to write a C application using civetweb.h and I can use Sqlite3 in there. So the problem is with civetweb's own process (using document root).

**Comment by bel2125** [comment]
I'm not really sure what the problem is - but you can try two alternative approaches:

- copy the lsqlite3.c from the current repository to the 1.10, replacing the existing one

alternatively:

- use the Lua system library by building with `make WITH_ALL=1 WITH_LUA_SHARED=1`.
You have to have lua5.2 installed (`sudo apt-get install lua5.2`), then luarocks (`sudo apt-get install luarocks`) and lsqlite3 (`luarocks install lsqlite3`). And add a `require "lsqlite3"` to page.lua.

Please tell me if this works in your system.
Meanwhile I try to find out more details.

**Comment by tamertemizer** [comment]
The problem is with lsqlite3.c, it started working when I overwrote the file in the 1.10 release with the file in the current repository. Thank you very much.

**Comment by bel2125** [comment]
For the current version, the required modification were done in December with this commit:
https://github.com/civetweb/civetweb/commit/62362643edf6405fe6f96a91af85d0bd0e506868#diff-cdf0b9fabe1b59e2b24b6b4f1146f77e

Issue solved in the upcoming V1.11 release
As a workaround to solve this issue in V1.10, please use the lsqlite3.c file from V1.8

**Comment by bel2125** [comment]
Solved in 2018
