### ISSUE TITLE
Accessing CivetHandler's private member from mg_form_data_handler using C++

### ISSUE THREAD

**Issue by mattdibi** [civetweb/civetweb#602]
Hi,
I encountered a problem using the C++ interface and I'm looking for some inputs on how to solve it.
I have the following code structure:

``` c++
    int post_field_found(const char *key,
            const char *filename,
            char *path,
            size_t pathlen,
            void *user_data) {

        if (filename && *filename)
            return MG_FORM_FIELD_STORAGE_SKIP;

        return MG_FORM_FIELD_STORAGE_GET;
    }

    int post_field_get(const char *key,
            const char *value,
            size_t valuelen,
            void *user_data) {

        if (key[0]) {
            std::string par_name {key};
            std::string par_value {value};

            std::cout << par_name << ": " << par_value.substr(0, valuelen) <<  " " << a_string << std::endl;
        }

        return 0;
    }

class aHandler : public CivetHandler {
  public:
    bool handlePost(CivetServer *server, struct mg_connection *conn) {
        try {
            int ret;
            struct mg_form_data_handler post_fdh = {post_field_found, post_field_get, 0, 0};

            ret = mg_handle_form_request(conn, &post_fdh);

            if(ret <= 0) throw std::runtime_error("POST error: no field found");

            mg_printf(conn, "HTTP/1.1 204 No Content\r\nConnection: close\r\n\r\n");
        } catch (std::runtime_error e) {
            mg_printf(conn, "HTTP/1.1 400 Bad Request\r\nContent-Type: "
                    "text/plain; charset=utf-8\r\nConnection: close\r\n\r\n");
            mg_printf(conn, "%s", e.what()); // Send error message
        }

        return true;
    }
 private:
    std::string a_string;
};
```

I need to access the private members of the Handler class from the callback functions of the `mg_form_data_handler`.

I thought of setting the callback function as `friend` of the handler class but I need to pass the handler object to access its members.

Setting the callback functions as `static` I can compile but cannot access members of the class that are not `static`.

Setting the callback function as private methods of the handler class I get the following:
```
aHandler.h:124:91: error: cannot convert ‘aHandler::post_field_found’ from type ‘int (aHandler::)(const char*, const char*, char*, size_t, void*) {aka int (aHandler::)(const char*, const char*, char*, long unsigned int, void*)}’ to type ‘int (*)(const char*, const char*, char*, size_t, void*) {aka int (*)(const char*, const char*, char*, long unsigned int, void*)}’
             struct mg_form_data_handler post_fdh = {post_field_found, post_field_get, 0, 0};
```
Is there a "right" way to do this? Am I missing something?

EDIT: The main problem seems to be due to the fact that I need to declare the callback functions as members of the CivetHandler's class to access its private members, but this is not compatible to the declaration in the `mg_form_data_handler` that accepts pointer to functions that are not members of a class.

**Comment by bel2125** [comment]
Usually I use the C interface. Without doing a test for C++, I would recommend:

make the `post_field_*` callbacks `static` members of `class aHandler`, pass `(void*)this` as the last component of `struct mg_form_data_handler` - inside the callbacks cast `user_data` back to `class aHandler*` and access the members from there

or

don't use class members of `class aHandler` but use a separate `struct mydata` (which could be a private member of the class), and pass the pointer to this struct to `struct mg_form_data_handler`.  
inside the callback cast `user_data` back to `struct mydata *` and access it there

**Comment by mattdibi** [comment]
Thanks for the insight, I'll give it a go after the weekend.

**Comment by mattdibi** [comment]
I tried both solutions and they work flawlessly.
I misunderstood what was the purpose of the `user_data` field of the `mg_form_data_handler` struct. Now everything is clear.
Thanks for your help!
