### ISSUE TITLE
Civetweb hangs up during stoppage

### ISSUE THREAD

**Issue by dFionov** [civetweb/civetweb#603]
I'm using prometheus_cpp library which uses civetweb, and during stoppage of my app it hangs up inside this loop:
```cpp
/* Wait until everything has stopped. */
while (ctx->stop_flag != 2) {
	(void)mg_sleep(10);
}
```
lines 17891 - 17894 inside civetweb.c

Will it be better to change code for something like:
```cpp
/* Wait until everything has stopped. */
for (i = 0; i < ctx->cfg_worker_threads; i++) {
	if (ctx->worker_threadids[i] != 0) {
		mg_join_thread(ctx->worker_threadids[i]);
	}
}
```
?

**Comment by bel2125** [comment]
Could you post the system and version information. You could get it by using "civetweb -I" from the command line (if you have the standalone executable), by calling [`mg_get_system_info`](https://github.com/civetweb/civetweb/blob/5851132e6478a8ee64902ef5a046f7bc89e727a0/include/civetweb.h#L1412), or you can collect the information manually.

**Comment by bel2125** [comment]
The code you recommend already exists inside the master thread:

```C
	/* Join all worker threads to avoid leaking threads. */
	workerthreadcount = ctx->cfg_worker_threads;
	for (i = 0; i < workerthreadcount; i++) {
		if (ctx->worker_threadids[i] != 0) {
			mg_join_thread(ctx->worker_threadids[i]);
		}
	}
...
	/* Signal mg_stop() that we're done.
	 * WARNING: This must be the very last thing this
	 * thread does, as ctx becomes invalid after this line. */
	ctx->stop_flag = 2;
```

Did you test your recommendation above? Does it change the behaviour?

**Comment by dFionov** [comment]
It reproduces under latest Windows Server with application builded using VS2013 compiler.
Basically project uses civetweb from prometheus_cpp library: [fbdee7440b](https://github.com/jupp0r/prometheus-cpp/tree/master/3rdparty).
Using my version no hanging takes place.
I didn't clearly understand what stop_flag means and why removing loop i mentioned with just `mg_join_thread(mt)` not enough.

**Comment by bel2125** [comment]
fbdee7440be24f904208c15a1fc9e2582b866049 is from 25 Sep 2016, somewhere between release 1.8 and release 1.9 (see [Releases](https://github.com/civetweb/civetweb/releases)).
In the release notes, you can find several changes that have influence on shutdown behavior, at least: "Use non-blocking sockets", "Rewrite connection close handling", "Partially rewrite timeout handling"
For intermediate versions, I don't know if all implementations have been finished and tested.

Please update to a released version (preferably 1.10, but at least 1.9.1) - or better to the current head version.

**Comment by dFionov** [comment]
Sory for delay.
What happens:
When SIGINT sended to Windows service starts KernelBase!CtrlRoutine(or kernel32!CtrlRoutine for x86) and it kills all threads, then unloads static objects. In destructor CivetServer calls mg_stop, which sets ctx->stop_flag to 1 and waits for stop_flag == 2, which never happens. It reproduces on head version too.
Code I propose didn't hangups since it immediately ends waiting for threads, since their gone already.

**Comment by bel2125** [comment]
So, you are using CivetServer as a static C++ object in a DLL?

As to my knowledge, static constructors and destructors of C++ objects in Win32 DLLs are called under the windows "loader lock" - just like [DllMain](https://msdn.microsoft.com/en-us/library/ms682583%28v=vs.85%29.aspx). According to the Microsoft documentation: *Because DLL notifications are serialized, entry-point functions should not attempt to communicate with other threads or processes. Deadlocks may occur as a result.* In fact you can do some operations with other threads, but you cannot join CivetWeb worker threads under the loader lock. 

Maybe there is some useful information in #264 (although this was more than two years ago, the restrictions from Windows are still the same).
