### ISSUE TITLE
mg_handle_form_request  can call strchr with uninitialized data

### ISSUE THREAD

**Issue by PandaChauve** [civetweb/civetweb#605]
Hi,
there may be an issue with mg_handle_form_request (line 381 src/handle_form.inl),
strchr can be called with buf pointing to an uninitialized part of the original buffer.

The issue was found using valgrind (memcheck) on a custom integration of civet and can be reproduced easily.

### Context :
mg_handle_form_request is the first method used in a request_handler (using the cpp api but I don't think it has any impact). 
The issue was found using the last release but I reproduced it using the last version of handle_form.inl (i didn't change anything else)

The data is form-url-encoded and the issue may be reproduced with content as simple as 1=1.

### Behaviour:
The loop in the "form url encoded" part of the function is called. (lines 350 to 515)
We need to follow the content of "buf" and "buf_fill".
 
At the start buff isn't initialized, it will be filled by "mg_read" (ln 361)
"buf_fill" will contain the size of the useful data in buff (ln 374)

If we're parsing the last parameter (or only one), we won't find & in "buff "thus "end_of_key_value_pair_found" is 0 (block ln 420 - 427)

ln461 buff is translated over itself (removing the buffer's useful part.) using memmove
It's ok, "buf_fill" is set to 0 (ln 464) => no useful data left in "buf"

Since there's nothing to read any more, nothing happens until ln  509
"used" should be 0 but isn't (next is computed before the memmove) and "buf_fill" is negative.

From there we have bad stuff, "buf_fill" is cast to size_t (unsigned) => buf_fill > sizeof(buf) -1 (ln 358)

The next call to "strchr" is done with random data found in memory (ln381).
If the user is lucky, "buf" contains '0' and not '=' and we break line 384.
if the user isn't I'm not sure but it's bad.

### How to fix
I still don't have a perfect understanding of this function (it's a bit long for a newcomer) but recomputing next after memmove may be enough ?
```
				if (!end_of_key_value_pair_found) {	
						used = next - buf;	
						memmove(buf,	
							buf + (size_t)used,
							sizeof(buf) - (size_t)used);
					buf_fill -= (int)used;
					next = buf;
					if ((size_t)buf_fill < (sizeof(buf) - 1)) {
```
(added next = buf)

Have a nice day !

**Comment by bel2125** [comment]
Thanks for your detailed report. From time to time I'm using different static code analysis tools ([Coverity scan is online](https://scan.coverity.com/projects/5784)), but I did not get this warning there. I will have a more detailed look on this issue during the next days.

**Comment by PandaChauve** [comment]
Thanks, if you need anything else, feel free to ask ;)

**Comment by bel2125** [comment]
I added `next = buf;` according to your suggestion - still I was not able to force a problem in my different url-encoded form POST tests.
Could you repeat your valgrind test?

**Comment by PandaChauve** [comment]
It's working.

**Comment by PandaChauve** [comment]
Two words : good work ! :+1: 

As a independent note, you should be able to run ctest under valgrind if you want to (should, I never tested it myself)
https://github.com/ainfosec/ci_helloworld#valgrind
