### ISSUE TITLE
Ability to filter specific types of connections and prevent logging to access log

### ISSUE THREAD

**Issue by toMeloos** [civetweb/civetweb#608]
**Use case**

Civetweb will output a lot of logging when conducting frequent monitoring checks on it or running it behind a loadbalancer like HAproxy, since each monitoring systems and loadbalancer will establish a healthcheck connection every second or so, especially when using highly preferable HTTP checks. Each healthcheck is a connection, resulting in an access log entry. This results in an overload of logging.

**Solution**

Create filtering or routing support that result in valid connections, but make sure these don't get logged. The easiest way seems to be to do User-Agent filtering. So once you set the monitoring/loadbalancer to identify itself as such with a User Agent header, civetweb could decide what to do with it. For example:

- Apache allows filtering by setting `SetEnvIf User-Agent ^nagios$ do-not-log-this-request` and `CustomLog ... env=!do-not-log-this-request`
- uWSGI allows routing by setting `route-user-agent = ^nagios$ donotlog:`

Hoping this is something you guys find an interesting feature request. I believe with access filtering and user-agent detection a lot of components are already present. This might even create other opportunities?

**Comment by bel2125** [comment]
Adding this kind of filter would be possible - but the User-Agent can be modified by the user (https://www.howtogeek.com/113439/how-to-change-your-browsers-user-agent-without-installing-any-extensions/).

Do you think one would need other filter criteria as well: client IP, URL, ...?

**Comment by serverbiz** [comment]
I guess any kind of header-based filtering would be useful. Just figured the User-Agent header is enough for this log output filtering use case and would be a nice minimally viable product, but if you can add various options then I assume there might be people that can find a use for it.

Can I recommend having a look at the [uWSGI internal routing](http://uwsgi-docs.readthedocs.io/en/latest/InternalRouting.html) support? It might give provide some inspiration :-)

**Comment by bel2125** [comment]
I am reviewing some of the old, forgotten issues we never closed to see what is still relevant and which ones have already been solved but never closed.

You can use the Lua Background Script (see UserManual.md) for this - Lua will allow you to specify almost arbitrary filtering rules. Here is an example: https://github.com/civetweb/civetweb/blob/master/test/lua_backbround_script_logging.lua
