### ISSUE TITLE
path_to_unicode + strchr(path, '~')

### ISSUE THREAD

**Issue by pavel-pimenov** [civetweb/civetweb#613]
https://github.com/civetweb/civetweb/blob/master/src/civetweb.c#L5127-L5129

if (strchr(path, '~')) {
		wbuf[0] = L'\0';
}
Error ?

**Comment by bel2125** [comment]
For WIN-CE, in case there is a ~ character in the file name (usual for Windows short names used for 8.3 filename compatibility), do not serve the file. This is indeed intentional - but a comment would be a good idea ;-)

**Comment by pavel-pimenov** [comment]
Only WIN-CE! ok.
