### ISSUE TITLE
#define NO_FILES + fopen(/.htpasswd)

### ISSUE THREAD

**Issue by pavel-pimenov** [civetweb/civetweb#614]
*** 1524500231.600745941        47282 3072609088 process_new_connection:17293: http: 1.1, error: none
*** 1524500231.600805444        59503 3072609088 handle_request:13476: URL: /fly-test-port
***** 1524500231.600942331       136887 3072609088 open_auth_file:8012: fopen(/.htpasswd): No such file or directory

Fix

![default](https://user-images.githubusercontent.com/920705/39140135-5c29e30c-472c-11e8-83b9-e8a69bdf0051.png)

**Comment by bel2125** [comment]
The intention of "NO_FILES" was to have no document root. 
In line 8393 in the same function, there is another `mg_fopen` call, so setting a define for the corresponding `mg_close` call will cause file handle leaks.

We could remove the entire `check_authorization` call:
```C
		/* 6.3. This is either a OPTIONS, GET, HEAD or POST request,
		 * or it is a PUT or DELETE request to a resource that does not
		 * correspond to a file. Check authorization. */
		if (!check_authorization(conn, path)) {
			send_authorization_request(conn, NULL);
			return;
		}
```

Currently you can also register an auth callback, then you won't have the `open_auth_file:8012: fopen(/.htpasswd): No such file or directory`.
