### ISSUE TITLE
Porting civetweb to ESP8266 MCU with custom cgi interpreter

### ISSUE THREAD

**Issue by sanyaade-iot** [civetweb/civetweb#617]
Hi Everybody,

I am trying to compile civetweb for ESP8266 microcontroller and to be able to call a CGI executable without the use of shebang inside top most of my scripts. Is there a civetweb example code to achieve this? If so in which file do I place the code? Many thanks!

I went through the document and follow all the #555 discussion but I am still lost.
For example in Mongoose if I declare a --> **static struct mg_serve_http_ opts s_http_server_opts;** on top of my own C implementation file below the line **#include mongoose.h**. Then I can use the code below to add directive for my custom CGI executable:

`// Set up HTTP server parameters
mg_set_protocol_http_websocket(nc);
**s_http_server_opts.document_root = "web_root";** // Set up web root directory
if (mg_stat(s_http_server_opts.document_root, &st) != 0) {
fprintf(stderr, "%s", "Cannot find web_root directory, exiting\n");
exit(1);
}

**s_http_server_opts.cgi_interpreter = "fs/ph7_cgi";**	//set up cgi-interpreter directory and executable
**s_http_server_opts.cgi_file_pattern = ".php$";****
**s_http_server_opts.index_files = "index.php, index.html, index.htm, index.shtml, index.cgi";**
if (mg_stat(s_http_server_opts.cgi_interpreter, &cgi_st) != 0) {
fprintf(stderr, "%s", "Cannot find cgi_interpreter directory, exiting\n");
exit(1);
}
The bold lines in above code setup my cgi_interpreter executable and directory path; the file pattern and index files.
I could also do: --> **s_http_server_opts.cgi_interpreter = "./ph7_cgi";** //set up cgi-interpreter directory.

As I porting to a ROM / Flash memory based device, everything run inside the hardware, no shell or console,and no commandline arguments to be run or passed to the device. The whole program is flashed into ESP8266Ex (a 4MB flash and 640k ram capacity micro-controller device).

How can I achieve the above equivalent with civetweb? Many thanks

Hear from you soon!

God blesses!!!

Best regards,
Sanyaade

**Comment by bel2125** [comment]
I don't know about recent changes in Mongoose - in fact I did not look at Mongoose since several years, since CivetWeb is forked.

Did you try to set the `cgi_interpreter` option for `mg_start` (see [UserManual.md](https://github.com/civetweb/civetweb/blob/master/docs/UserManual.md#cgi_interpreter))?

Options are passed to `mg_start` as a string array, as shown in this example: https://github.com/civetweb/civetweb/blob/65bd4ce50c23af1c8d6ebf10a17a275fa3a857c0/examples/rest/rest.c#L116

**Comment by sanyaade-iot** [comment]
@bel2125 : 
Many thanks for getting back to me. Much appreciated.
I did add the following to the main.c file:
     `  **options[0] = NULL;
	set_option(options, "document_root", ".");
	set_option(options, "cgi_interpreter", "./ph7_cgi");**
'
So far civetweb works and the custom ph7_cgi was able to compile .php file and return output to the browser correctly on my Ubuntu 16.04 Linux box. 

My next step is to get civetweb compile for Esp8266 environment then port the embedded_c sample with the custom ph7_cgi.

I am also looking at the **set_option(char **options, const char *name, const char *value)** as used in main.c to see how to add the file pattern e.g. **"**.php | **.cgi " ;**  to it.

Many thanks!

Hear from you soon!

God blesses!!!

Best regards,
Sanyaade

**Comment by bel2125** [comment]
Just let me hear if you need something else. If not, then let's close this issue after a few weeks.
