### ISSUE TITLE
civetweb 1.10: redirection for ipv6 addreses

### ISSUE THREAD

**Issue by dargo600** [civetweb/civetweb#619]
When entering an ipv6 address instead of a hostname civetweb doesn't redirect properly

The problem appears to be the Location gets mangled as it doesn't look at [] and only ':'
So something like:

lynx -mime_header http://[2001:192:168:222:218:48ff:fe16:a2d5]/mibs/file.txt
HTTP/1.1 302 Found
Location: https://[2001:443/mibs/file.txt

will occur.  You can fix this on 1.10 by checking for ], however using a similar patch doesn't work too well on latest civetweb for some reason as I tend to get:
Location: Location: https://[2001:443/mibs/file.txt
which is obviously wrong.

**Comment by bel2125** [comment]
Thanks for your bug report.
I was able to reproduce and fix the issue.
