### ISSUE TITLE
problem in persian character

### ISSUE THREAD

**Issue by mrd3691** [civetweb/civetweb#621]
When we send character as unicode to civetweb , the received message in civetweb side is incorrect.
I think reason is transfer and asci .
has anyone same problem with other language?and can anyone help to me?

**Comment by bel2125** [comment]
What encoding are you using?
What operating systems are used for server and client?
Are you sending the persian character as part of the URI, as some header or body data?
What CivetWeb version are you using?

**Comment by mrd3691** [comment]
utf-16le
windows10
yes
1.9

**Comment by bel2125** [comment]
Could you post the unicode code point of some example character?


>> Are you sending the persian character as part of the URI, as some header or body data?
> yes

Maybe, let's spit this in multiple questions:
Are you sending the persian character as part of the URI? (yes/no)
Are you sending the persian character as part of some HTTP header? (yes/no)
Are you sending the persian character as part of the HTTP body data? (yes/no)


You send from a web browser to civetweb as a server? (yes / no ...)

Do you have an example request, so I can reproduce the issue?

**Comment by bel2125** [comment]
Unfortunately I can't help without more information.

I assume, you are not using HTTP header or URI but the HTTP body, i.e., the transferred HTML page.
You cannot use UTF-16 for URI and HTTP headers.

For HTML character encoding, please read the following documents:

https://www.w3schools.com/tags/att_meta_charset.asp
https://www.w3schools.com/html/html_charset.asp

https://www.w3.org/International/articles/http-charset/index

**Comment by bel2125** [comment]
CivetWeb has some test cases with non-latin characters (not only A-Z and their [accent characters](https://www.fonts.com/content/learning/fontology/level-3/signs-and-symbols/accents)) :
https://github.com/civetweb/civetweb/tree/master/test/nonlatin
Both, the file names (and, thus, the URIs) and the file content are tested to support non-latin characters. The content has also some arabic text (translated by Google): 
https://github.com/civetweb/civetweb/blob/ee7c3fbdc5c015bc842341443c2da9e920243f1b/test/nonlatin/%E8%BF%99%E6%98%AF%E4%B8%80%E4%B8%AA%E7%A4%BA%E4%BE%8B%E6%96%87%E6%9C%AC.html#L30
The file name is tested with Chinese (the language with the most characters) and [Fula/Adlam](https://en.wikipedia.org/wiki/Fula_language#Adlam_script) (a language encoded only in characters outside the [BMP](https://en.wikipedia.org/wiki/Plane_(Unicode)#Basic_Multilingual_Plane)) - the two most complicated cases.

With these tests, I'm quite sure there is no problem in CivetWeb.
