### ISSUE TITLE
error build: ubuntu 18.04 + opensll 1.1.0

### ISSUE THREAD

**Issue by pavel-pimenov** [civetweb/civetweb#623]
vpn@vpn:~/src/civetweb/examples/embedded_cpp$

vpn@vpn:~/src/civetweb/examples/embedded_c$ make
make -C ../.. WITH_IPV6=1 WITH_WEBSOCKET=1 COPT='-DNO_SSL_DL=1' clean lib
make[1]: Entering directory '/home/vpn/src/civetweb'
rm -rf out
rm -rf libcivetweb.a
rm -rf libcivetweb.so
rm -rf libcivetweb.so.1
rm -rf libcivetweb.so.1.11.0
rm -rf civetweb
rm -f civetweb_test
cc -c -Wall -Wextra -Wshadow -Wformat-security -Winit-self -Wmissing-prototypes -DLINUX -Iinclude -DNO_SSL_DL=1 -DUSE_STACK_SIZE=102400 -O2 -DNDEBUG -DUSE_IPV6 -DUSE_WEBSOCKET -fPIC src/civetweb.c -o out/src/civetweb.o
src/civetweb.c:1712:10: fatal error: openssl/ssl.h: No such file or directory
 #include <openssl/ssl.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
Makefile:370: recipe for target 'out/src/civetweb.o' failed
make[1]: *** [out/src/civetweb.o] Error 1
make[1]: Leaving directory '/home/vpn/src/civetweb'
Makefile:30: recipe for target 'libcivetweb.a' failed
make: *** [libcivetweb.a] Error 2

vpn@vpn:~/src/civetweb/examples/embedded_c$ sudo apt install libssl-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  libssl-doc
The following NEW packages will be installed:
  libssl-dev libssl-doc
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 2,629 kB of archives.
After this operation, 11.5 MB of additional disk space will be used.
Do you want to continue? [Y/n]
Get:1 http://mirror.yandex.ru/ubuntu bionic/main amd64 libssl-dev amd64 1.1.0g-2ubuntu4 [1,372 kB]
Get:2 http://mirror.yandex.ru/ubuntu bionic/main amd64 libssl-doc all 1.1.0g-2ubuntu4 [1,256 kB]
Fetched 2,629 kB in 1s (4,583 kB/s)
Selecting previously unselected package libssl-dev:amd64.
(Reading database ... 110113 files and directories currently installed.)
Preparing to unpack .../libssl-dev_1.1.0g-2ubuntu4_amd64.deb ...
Unpacking libssl-dev:amd64 (1.1.0g-2ubuntu4) ...
Selecting previously unselected package libssl-doc.
Preparing to unpack .../libssl-doc_1.1.0g-2ubuntu4_all.deb ...
Unpacking libssl-doc (1.1.0g-2ubuntu4) ...
Setting up libssl-dev:amd64 (1.1.0g-2ubuntu4) ...
Setting up libssl-doc (1.1.0g-2ubuntu4) ...
vpn@vpn:~/src/civetweb/examples/embedded_c$ make
make -C ../.. WITH_IPV6=1 WITH_WEBSOCKET=1 COPT='-DNO_SSL_DL=1' clean lib
make[1]: Entering directory '/home/vpn/src/civetweb'
rm -rf out
rm -rf libcivetweb.a
rm -rf libcivetweb.so
rm -rf libcivetweb.so.1
rm -rf libcivetweb.so.1.11.0
rm -rf civetweb
rm -f civetweb_test
cc -c -Wall -Wextra -Wshadow -Wformat-security -Winit-self -Wmissing-prototypes -DLINUX -Iinclude -DNO_SSL_DL=1 -DUSE_STACK_SIZE=102400 -O2 -DNDEBUG -DUSE_IPV6 -DUSE_WEBSOCKET -fPIC src/civetweb.c -o out/src/civetweb.o
src/civetweb.c: In function ‘sslize’:
src/civetweb.c:14842:3: warning: ‘ERR_remove_state’ is deprecated [-Wdeprecated-declarations]
   ERR_remove_state(0);
   ^~~~~~~~~~~~~~~~
In file included from /usr/include/openssl/ct.h:13:0,
                 from /usr/include/openssl/ssl.h:61,
                 from src/civetweb.c:1712:
/usr/include/openssl/err.h:248:1: note: declared here
 DEPRECATEDIN_1_0_0(void ERR_remove_state(unsigned long pid))
 ^
src/civetweb.c:14891:3: warning: ‘ERR_remove_state’ is deprecated [-Wdeprecated-declarations]
   ERR_remove_state(0);
   ^~~~~~~~~~~~~~~~
In file included from /usr/include/openssl/ct.h:13:0,
                 from /usr/include/openssl/ssl.h:61,
                 from src/civetweb.c:1712:
/usr/include/openssl/err.h:248:1: note: declared here
 DEPRECATEDIN_1_0_0(void ERR_remove_state(unsigned long pid))
 ^
src/civetweb.c: In function ‘uninitialize_ssl’:
src/civetweb.c:15752:3: warning: ‘ERR_remove_state’ is deprecated [-Wdeprecated-declarations]
   ERR_remove_state(0);
   ^~~~~~~~~~~~~~~~
In file included from /usr/include/openssl/ct.h:13:0,
                 from /usr/include/openssl/ssl.h:61,
                 from src/civetweb.c:1712:
/usr/include/openssl/err.h:248:1: note: declared here
 DEPRECATEDIN_1_0_0(void ERR_remove_state(unsigned long pid))
 ^
src/civetweb.c: In function ‘close_connection’:
src/civetweb.c:16063:3: warning: ‘ERR_remove_state’ is deprecated [-Wdeprecated-declarations]
   ERR_remove_state(0);
   ^~~~~~~~~~~~~~~~
In file included from /usr/include/openssl/ct.h:13:0,
                 from /usr/include/openssl/ssl.h:61,
                 from src/civetweb.c:1712:
/usr/include/openssl/err.h:248:1: note: declared here
 DEPRECATEDIN_1_0_0(void ERR_remove_state(unsigned long pid))
 ^
ar cq libcivetweb.a out/src/civetweb.o
make[1]: Leaving directory '/home/vpn/src/civetweb'
cp ../../libcivetweb.a .
cc -o embedded_c -I../../include  -DUSE_WEBSOCKET -DUSE_IPV6  embedded_c.c libcivetweb.a -lpthread -ldl -lcrypto -lssl -DUSE_SSL_DH=1
embedded_c.c: In function ‘get_dh2236’:
embedded_c.c:838:4: error: dereferencing pointer to incomplete type ‘DH {aka struct dh_st}’
  dh->p = BN_bin2bn(dh2236_p, sizeof(dh2236_p), NULL);
    ^~
Makefile:27: recipe for target 'embedded_c' failed
make: *** [embedded_c] Error 1

**Comment by bel2125** [comment]
You have to set the `OPENSSL_API_1_1` define to use OpenSLL 1.1.x

**Comment by pavel-pimenov** [comment]
diff --git a/examples/embedded_c/Makefile b/examples/embedded_c/Makefile
index 93d6379d..a9f2310a 100644
--- a/examples/embedded_c/Makefile
+++ b/examples/embedded_c/Makefile
@@ -12,7 +12,7 @@ SRC = embedded_c.c
 TOP = ../..
 CIVETWEB_LIB = libcivetweb.a

-CFLAGS = -I$(TOP)/include $(COPT) -DUSE_WEBSOCKET -DUSE_IPV6
+CFLAGS = -I$(TOP)/include $(COPT) -DUSE_WEBSOCKET -DUSE_IPV6 -DOPENSSL_API_1_1
 LIBS = -lpthread

vpn@vpn:~/src/civetweb/examples/embedded_c$ make
cc -o embedded_c -I../../include  -DUSE_WEBSOCKET -DUSE_IPV6 -DOPENSSL_API_1_1  embedded_c.c libcivetweb.a -lpthread -ldl -lcrypto -lssl -DUSE_SSL_DH=1
embedded_c.c: In function ‘get_dh2236’:
embedded_c.c:838:4: error: dereferencing pointer to incomplete type ‘DH {aka struct dh_st}’
  dh->p = BN_bin2bn(dh2236_p, sizeof(dh2236_p), NULL);
    ^~
Makefile:27: recipe for target 'embedded_c' failed
make: *** [embedded_c] Error 1

**Comment by pavel-pimenov** [comment]
#if OPENSSL_VERSION_NUMBER < 0x10100000L
...
https://github.com/neutrinolabs/xrdp/pull/1063/files

**Comment by bel2125** [comment]
Regarding https://github.com/civetweb/civetweb/issues/623#issuecomment-394069369: Did you rebuild both, libcivetweb and embedded_c with the -DOPENSSL_API_1_1 flag?
Regarding https://github.com/civetweb/civetweb/issues/623#issuecomment-394069688: I will have a look.

**Comment by bel2125** [comment]
Is there anything left to do here, or did we just forgot to close this issue?
