### ISSUE TITLE
Civetweb returns bad response for Lua Server Pages(.lp)

### ISSUE THREAD

**Issue by tamertemizer** [civetweb/civetweb#636]
We are running Nunit based test automation suite on our web application. They work perfectly fine for .html files served by civetweb but they give Protocol Violation for lp files. 

Also curl returns "weird server reply" when used on lp files.

Do you know what may be the cause of this?

**Comment by bel2125** [comment]
You opened your issue 9 hours ago and closed it 9 hours ago?
Was this intended, or did you indeed solve the issue right away?

As a general hint for *.lp files: make sure you built with Lua support (`make WITH_LUA=1`) and test with some *.lp files in the test/ folder.

**Comment by tamertemizer** [comment]
Yes, sorry about it. I missed civetweb doesn't send HTTP headers for lua and lp files. That was the issue. It was solved after I manually entered the headers.

**Comment by bel2125** [comment]
The current version does not require you to do this:
Example: see https://github.com/civetweb/civetweb/blob/master/test/page4kepler.lp

It's a recent extension in [V1.11](https://github.com/civetweb/civetweb/blob/master/RELEASE_NOTES.md): "Allow Kepler Syntax for Lua Server pages"

I still need to write a more detailed documentation for the release.
