### ISSUE TITLE
80->443 Redirects - error out with header Location field issue - using latest git-head of today

### ISSUE THREAD

**Issue by dlissimore** [civetweb/civetweb#639]
Just did a fresh git clone this morning - to look at some ipv6 handling - using the civetweb binary itself. 
Tried the web redirect  IPv4 and IPv6 ... and Nada ... was not functioning. 

Looked at wireshark and saw that the Location field in the header parse from wiresharks HTTP parser had the "Location:" duplicated into where you'd normally find the URL only. 

In the code-base:  if you remove the "Location:" from line 13056 ... and rebuild - it works. 
Before: 
civetweb.c:13056:                   "Location: https://%s:%d%s%s%s",
After: 
civetweb.c:13056:                   "https://%s:%d%s%s%s",

Tested using IPv4 and IPv6 redirects. 

Build-Box -  KDE Neon - up-to-date; 
Built with:   WITH_IPV6=1 WITH_SERVER_STATS=1 WITH_ZLIB=1 make; 

Tested using Firefox web-browser -- latest release as of today.

**Comment by bel2125** [comment]
You are right, thanks.

**Comment by dlissimore** [comment]
Works -- thanks for the commit.
