### ISSUE TITLE
using #pragma diagnostic inside functions with older GCC versions

### ISSUE THREAD

**Issue by bberry6** [civetweb/civetweb#640]
In the [master branch](https://github.com/civetweb/civetweb/commit/7259a80f1d1620f351dd93fb6f4acff48c9373db), when compiling with GCC version 4.4.3 the following errors are returned

```
/home/berry/powerpc-gcc-4.4.3/powerpc-linux-uclibc-gcc -c -Wall -Wextra -Wshadow -Wformat-security -Winit-self -Wmissing-prototypes -DLINUX -Iinclude  -DUSE_STACK_SIZE=102400 -O2 -DNDEBUG src/civetweb.c -o out/src/civetweb.o
src/civetweb.c: In function 'mg_cry_internal_impl':
src/civetweb.c:3614: error: #pragma GCC diagnostic not allowed inside functions
src/civetweb.c:3615: error: #pragma GCC diagnostic not allowed inside functions
src/civetweb.c:3621: error: #pragma GCC diagnostic not allowed inside functions
src/civetweb.c: At top level:
src/civetweb.c:6842: warning: expected [error|warning|ignored] after '#pragma GCC diagnostic'
src/civetweb.c:6940: warning: expected [error|warning|ignored] after '#pragma GCC diagnostic'
src/civetweb.c: In function 'ssl_servername_callback':
src/civetweb.c:15580: error: #pragma GCC diagnostic not allowed inside functions
src/civetweb.c:15581: error: #pragma GCC diagnostic not allowed inside functions
src/civetweb.c:15588: error: #pragma GCC diagnostic not allowed inside functions
src/civetweb.c: In function 'init_ssl_ctx_impl':
src/civetweb.c:15691: error: #pragma GCC diagnostic not allowed inside functions
src/civetweb.c:15692: error: #pragma GCC diagnostic not allowed inside functions
src/civetweb.c:15714: error: #pragma GCC diagnostic not allowed inside functions
src/civetweb.c: In function 'close_socket_gracefully':
src/civetweb.c:16144: error: #pragma GCC diagnostic not allowed inside functions
src/civetweb.c:16145: error: #pragma GCC diagnostic not allowed inside functions
src/civetweb.c:16154: error: #pragma GCC diagnostic not allowed inside functions
src/civetweb.c: In function 'mg_connect_client_impl':
src/civetweb.c:16387: error: #pragma GCC diagnostic not allowed inside functions
src/civetweb.c:16388: error: #pragma GCC diagnostic not allowed inside functions
src/civetweb.c:16395: error: #pragma GCC diagnostic not allowed inside functions
src/civetweb.c: In function 'mg_get_system_info_impl':
src/civetweb.c:19014: error: #pragma GCC diagnostic not allowed inside functions
src/civetweb.c:19016: error: #pragma GCC diagnostic not allowed inside functions
src/civetweb.c:19027: error: #pragma GCC diagnostic not allowed inside functions
make: *** [out/src/civetweb.o] Error 1
```

If I comment the pragma lines, it compiles without errors.  It seems that in 4.6.0, in addition to adding push and pop, they also allow usage of `#pragma GCC diagnostic` inside of functions.

The first solution that comes to mind is to wrapper them with GCC version checks.  It appears that this has been done for some of the `#pragma GCC diagnostic` but not all of the ones inside of functions. Side note: The [latest release version](https://github.com/civetweb/civetweb/blob/v1.10/src/civetweb.c#L947) does a check against GCC version 4.5 when `#pragma GCC diagnostic push` wasn't implemented until version 4.6 

I personally wouldn't suggest moving them outside the functions and suppressing the warnings with `#pragma GCC diagnostic ignored` because, as GCC documentation states, "these pragmas override any command line options".  Instead, by leaving them inside the functions wrappered by a version check, users can use command line options to suppress them, but that's subjective.

I believe there are more instances than what is shown in the compile results if I were to build with more features.

**Comment by bel2125** [comment]
GCC warning pragmas ... not really a glorious history.

I added a version check, but this needs some more tests.

**Comment by bberry6** [comment]
Not sure if it helps, but it all works great on my system now (cross compiling using GCC 4.4.3).  Cheers mate :D

**Comment by bel2125** [comment]
Thanks. I just forgot to close this issue.
