### ISSUE TITLE
Error running on ubuntu 18.04

### ISSUE THREAD

**Issue by mpromonet** [civetweb/civetweb#641]
Hi,

I am trying to run your server on ubuntu 18.04 with SSL support.
It build without problem, but it fails to start complaining : 

```
./civetweb -ssl_certificate ../ssl.pem -listening_ports 8000s
truncating vsnprintf buffer: [,]
load_dll: libcrypto.so: cannot find CRYPTO_num_locks, CRYPTO_set_locking_callback, CRYPTO_set_id_callback, ERR_free_strings,...
Failed to start CivetWeb V1.10:
load_dll: libcrypto.so: cannot find CRYPTO_num_locks, CRYPTO_set_locking_callback, CRYPTO_set_id_callback, ERR_free_strings,...
```
This seems link to ssl/libcrypto version. It seems to have 2 releases installed.
```
/usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0
/usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
/usr/lib/x86_64-linux-gnu/libssl.so.1.0.0
/usr/lib/x86_64-linux-gnu/libssl.so.1.1
```
I try to force the selection using  SSL_LIB=libssl.so.1.0  CRYPTO_LIB=libcrypto.so.1.0.0 and so on, but none is working.

Did you reproduce this problem ?

Best Regards,
Michel.

**Comment by bel2125** [comment]
That's an OpenSSL 1.1.x vs. OpenSSL 1.0.x issue.
What CivetWeb version did you use?
Did you try to set the `OPENSSL_API_1_1` define while building?
Did you build the server with the "make" file in the repository?
You could also build with the `NO_SSL_DL` flag.

I still have an Ubuntu 16 test machine, so I cannot do a quick test now - I need some time to get a create a test environment.

**Comment by mpromonet** [comment]
Hi bel2125,

Thanks for your answer, with `NO_SSL_DL` flags, I was able to run your server.

Michel.

**Comment by bel2125** [comment]
Thanks for the information.

I will try to add a more helpful error message since this is a rather common problem.

**Comment by seltzy** [comment]
I am running into these problems on 18.04 as well. I stepped through `load_dll` in gdb and it is indeed failing to find the crypto symbols at runtime. After some time trying to understand the nature of the problem, I now understand why a define was added for `OPENSSL_API_1_1` as a result of #370. This isn't an ideal solution for me though.

Here are my findings. Hopefully they will help others.

Symlinks for reference:
```
$ ll /usr/lib/x86_64-linux-gnu/libcrypto*
-rw-r--r-- 1 root root 4833260 Jun 20 07:29 /usr/lib/x86_64-linux-gnu/libcrypto.a
lrwxrwxrwx 1 root root      16 Jun 20 07:29 /usr/lib/x86_64-linux-gnu/libcrypto.so -> libcrypto.so.1.1
-rw-r--r-- 1 root root 2357760 Jun 20 08:00 /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0
-rw-r--r-- 1 root root 2575848 Jun 20 07:29 /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1

$ ll /usr/lib/x86_64-linux-gnu/libssl*
-rw-r--r-- 1 root root 328128 Feb  5  2018 /usr/lib/x86_64-linux-gnu/libssl3.so
-rw-r--r-- 1 root root 740092 Jun 20 07:29 /usr/lib/x86_64-linux-gnu/libssl.a
lrwxrwxrwx 1 root root     13 Jun 20 07:29 /usr/lib/x86_64-linux-gnu/libssl.so -> libssl.so.1.1
-rw-r--r-- 1 root root 426232 Jun 20 08:00 /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0
-rw-r--r-- 1 root root 433760 Jun 20 07:29 /usr/lib/x86_64-linux-gnu/libssl.so.1.1
```

Inspecting symbols with `objdump -T /usr/lib/x86_64-linux-gnu/libcrypto.so | grep num_locks` showed no such symbols. I checked `libssl.so` in the same way for good measure. Upon inspecting `/usr/include/openssl/crypto.h`, I discovered the cause.
```c
/*
 * The old locking functions have been removed completely without compatibility
 * macros. This is because the old functions either could not properly report
 * errors, or the returned error values were not clearly documented.
 * Replacing the locking functions with with no-ops would cause race condition
 * issues in the affected applications. It is far better for them to fail at
 * compile time.
 * On the other hand, the locking callbacks are no longer used.  Consequently,
 * the callback management functions can be safely replaced with no-op macros.
 */
#  define CRYPTO_num_locks()            (1)
#  define CRYPTO_set_locking_callback(func)
#  define CRYPTO_get_locking_callback()         (NULL)
#  define CRYPTO_set_add_lock_callback(func)
#  define CRYPTO_get_add_lock_callback()        (NULL)
```

The offending changes:
https://github.com/openssl/openssl/commit/2e52e7df518d80188c865ea3f7bb3526d14b0c08#diff-a88baedd3b3f460db4620f1794f6ef48L354
https://github.com/openssl/openssl/commit/2e52e7df518d80188c865ea3f7bb3526d14b0c08#diff-bda76b1bf5e1fc02e0d09dbc6a251c38L227
So it has been present for a while, but I'm not sure exactly when this version made its way into distributions.

The define that was added in #370 seems like a bit of a hack. It looks like it eliminates the possibility of supporting different versions of OpenSSL at the same time. I work on an application that ships without knowing which versions the users have, so runtime loading is important.

One solution is to have application users manually prioritize the old OpenSSL libraries, assuming they're also installed, which appears to be the case on Ubuntu 18.04 and 16.04.

Example:
```
mkdir ~/oldssl
ln -s /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0 ~/oldssl/libssl.so
ln -s /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0 ~/oldssl/libcrypto.so
LD_LIBRARY_PATH=$HOME/oldssl:$LD_LIBRARY_PATH ./civetweb <args>
```
What's the suggested course of action for those who still wish to use SSL support via `dlopen` but don't know which version of OpenSSL will be available on target systems?

**Comment by mpromonet** [comment]
That's nice.
