### ISSUE TITLE
Controlling max. size of uploaded files (mg_form_data_handler interface)

### ISSUE THREAD

**Issue by nfrmtkr** [civetweb/civetweb#646]
I have to implement a file quota check for uploads in civetweb. I use the mg_from_data_handler interface. It works fine, but the nature of ContentType=multipart/form-data and standard upload semantics don't deliver the filesize upfront in order to check if the upload is allowed.
Anyhow, using Content-Length or any other header or form field may not a reliable information. Thus, there is a need to check file upload size on the fly wile uploading an break if max. allowed file size is reached. The max. file size must be configurable on each call of mg_form_data_interface and not a civetweb option. The interface must inform the caller about file size limit reached, other error reporting would be fine as well, currently code calls mg_cry.

I had a look at handle_from.inl. There is a mention of FORM_FIELD_STORAGE_READ, but marked as "not implemented". Letting developers read field data chunk by chunk may be a good "do it your self " approach. This feature also allows calculating a MD5 checksum on-the-fly (another requirement I get bothered with).

Please help enancing mg_form_data_handller interface in order to support quota checks.

**Comment by bel2125** [comment]
Currently, I would do it like this:

1) In the form for file upload, check the file size before uploading ([size property](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file)). With this browser side check, you know a user selected a too large file without even trying to transfer it. You can do a corresponding error message here.
Of course, somebody could intentionally bypass this check by modifying the upload page or handcrafting a request. But all sincere users trying to upload too large files will stop here.

2) At the server side, you need a final size check - but if this check fails, either someone is trying to bypass the client site check or something else went wrong in the implementation.
I think `MG_FORM_FIELD_STORAGE_GET` will receive the file in chunks - `MG_FORM_FIELD_STORAGE_READ` is indeed not implemented yet.

**Comment by nfrmtkr** [comment]
Re 1: Yes, this we will do. However, backend check is required in order to protect against DOS attacks.

Re 2: Thank you for the hint. I've debugged it an yes, the MG_FORM_FIELD_STORAGE_GET variant reads data in chunks of 979 bytes and calls field_get callback for each chunk. On first call argument key contains the name of the field (e.g. "File"). On subsequent calls the argument key is empty string.
You may add this valuable information to documentation.

The return code of field_get is not being checked in handle_form.inl code. What about defining an abort condition like FORM_FIELD_STORAGE_ABORT? 
With current implementation I store chunk by chunk to file until size limit has reached and subsequent chunks have to be read but I avoid writing it to file. The size exceeded condition is stored somewhere and in field_found callabck I can abort using FORM_FIELD_STORAGE_ABORT or mg_handle_form_request() ends anyhow and I have to check the size exceeded condition, too.

**Comment by bel2125** [comment]
> However, backend check is required in order to protect against DOS attacks.

Definitely. What I meant: The frontend is responsible for showing users a "nice" error message. The hacker attacking the backend does not need/deserve a nice error message - you could just close the socket without an additional message (or do some minimal message, but don't waste your time on this).

> The return code of field_get is not being checked in handle_form.inl code.

Currently, the return value of the get field is not used, but "reserved for future use" (which isn't exactly a good idea):
https://github.com/civetweb/civetweb/blob/3ebb61e3ab9606228fdbfcff02cbdcc70350b1b6/include/civetweb.h#L1185

I think adding this response code handling would solve your particular problem, and will also be a valuable feature in general.

**Comment by nfrmtkr** [comment]
Should be a new set of enums? I had a look at MG_FORM_FIELD_STORAGE_* enums. They don't fit very well. Asuming most developers retun 0 indicating successfull operation + proceed parsing, the enums may like this:

```
enum {
MG_FORM_FIELD_GET_CONTINUE = 0x0,
MG_FORM_FIELD_GET_SKIP = 0x01,
MG_FORM_FIELD_GET_ABORT = 0x10
};
```

* CONTINUE: Proceed reading and calling field_get()
* SKIP: Proceed reading until next field but don't call field_get()
* ABORT: Stop reading and field parsing

The SKIP mode would be of interrest in case of multi file uploads and a fair handling of each file.
With CONTINUE = 0x0 most implementations will not fail after interoducing the new code if my assumption is right.

By the way: Controlling the read buffer would good as well. The 979 byte chunks are very small and lead to many file append operations.

**Comment by bel2125** [comment]
For field_store, the return code definition is missing as well:
https://github.com/civetweb/civetweb/blob/3ebb61e3ab9606228fdbfcff02cbdcc70350b1b6/include/civetweb.h#L1206-L1207

Probably, there is a common return code for _get and _store - need to think about it ...

Unfortunately, return values are not very consistent:
- some developers return 1 for success and 0 for error (effectively boolean)
- some developers return 1 for success and negative numbers for errors
- some 0 for success and 1, 2, 3, ... for errors
- or 1, 2, 3, ... for the amount of successfully processed data (which may be less than "all data")
- ...

Not all APIs within CivetWeb use the same pattern (some legacy functions from different authors, ...) - most new APIs returning int use negative numbers for errors.
However, this is not exactly an "error/success" situations, but rather instructions on how to proceed - call it a "control word", if you like.

> By the way: Controlling the read buffer would good as well. The 979 byte chunks are very small and lead to many file append operations.

I wonder why this is so small ... maybe I did this for a test if spitting in chunks works well, and did not set it back to the typical `MG_BUF_LEN` (8 kB default - can be controlled by redefining this number at compile time).
 
https://github.com/civetweb/civetweb/blob/3ebb61e3ab9606228fdbfcff02cbdcc70350b1b6/src/handle_form.inl#L184

Probably try 
```C
char buf[MG_BUF_LEN];
```

**Comment by nfrmtkr** [comment]
RE buffer size:

Yes using MG_BUF_LEN works fine, I've tested it. Please change source code.

**Comment by nfrmtkr** [comment]
>Unfortunately, return values are not very consistent

Well, that's always the problem with unused and undocumented return codes. We do not know what a developer has used and adding new features based on return code may break existing implementations.
We may make this enhancment optional with #ifdef and drop the old code after a reasonable grace period. This way we're free in design of the return codes. 
Yes, the return code is more a control of callback interaction. 

>Probably, there is a common return code for _get and _store - need to think about it ...

I think _store() needs different return code. With _store() you  indicate that the upload has been successfully completed. Its used for finalization (e.g. calculating checksum, move it to DB etc).
I see CONTINUE and ABORT here but not SKIP.

**Comment by bel2125** [comment]
Some return values are defined now, but there are no automated tests yet.

**Comment by bel2125** [comment]
> If existing handler code returns 0 or 1 than the old behavior will be applied.

exactly.

And if someone returns MG_FORM_FIELD_STORAGE_ABORT instead of MG_FORM_FIELD_HANDLE_ABORT it will also work, since both are 0x10

**Comment by bel2125** [comment]
I think this is solved, and we just forgot to close it.
