### ISSUE TITLE
Connection reset immediately when using absoluteURI

### ISSUE THREAD

**Issue by r0ss3** [civetweb/civetweb#648]
Hi All,

I'm having an issue with ceph radosgw, but I believe it is caused by the embedded civetweb.  My issue started after upgrading to ceph mimic, which I believe ships with civetweb 1.10 where the previous version luminous shipped with 1.8.

My problem is that all requests from a certain application (docker registry) are closed immediately.  These requests are not logged in any way (or I've not been able to see them in any debug log).  It happens both with and without ssl.  By using strace on the radosgw I can see the socket being opened from the client, so the request is handled by civetweb afaik, but it is immediatly dropped on the floor.

With tcpdump using http I was able to see a clean SYN, SYN/ACK, ACK followed by this GET request:

```
Hypertext Transfer Protocol
    GET http://vip.lb.com/tda-registry/docker/registry/v2/repositories/pnu/kubectl-download/_manifests/tags/v1.11.2/current/link HTTP/1.1\r\n
    Host: vip.lb.com\r\n
    User-Agent: aws-sdk-go/1.2.4 (go1.7.6; linux; amd64)\r\n
    Authorization: AWS4-HMAC-SHA256 Credential=7Z2GY04RZZAGF0B39URY/20180824/default/s3/aws4_request, SignedHeaders=host;range;x-amz-content-sha256;x-amz-date, Signature=4e96773845e41c7d34cbf71f03845bdd7d91682cde04097d9e148344ca282964\r\n
    Range: bytes=0-\r\n
    X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\r\n
    X-Amz-Date: 20180824T122611Z\r\n
    \r\n
    [Full request URI: http://vip.lb.com/tda-registry/docker/registry/v2/repositories/pnu/kubectl-download/_manifests/tags/v1.11.2/current/link]
    [HTTP request 1/1]
```

Followed by a ACK, FIN/ACK.  So the connection is just closed.  How can I debug this issue any further?

**Comment by bel2125** [comment]
You could set the `DEBUG` define for civetweb.c.
CivetWeb will log a lot of operations (`DEBUG_TRACE`) - probably something can be found in the logs.

Otherwise: what CivetWeb options are you using?

**Comment by r0ss3** [comment]
civetweb is now running with 

```
port=10.11.12.13:443s num_threads=30 ssl_certificate=/etc/ceph/rgw_cert.pem
```

The ceph way to enable debug for civetweb  (debug civetweb = 20) does not seem to increase the verbosity.  So as far as I can see I can only pass commandline options to civetweb, but it seems there is no commandline option to enable debugging in UserManual.md?

**Comment by r0ss3** [comment]
I noticed one thing about that get request which seems odd to me.  The application does a GET with "Range: bytes=0-\r\n".  So i did some further testing with curl.

```
curl -H 'range: bytes=0-' returns HTTP/1.1 206 Partial Content, Content-Length: 71, Content-Range: bytes 0-70/71
```
This returns the entire object, as expected by the client application.  However:

```
curl -H 'range: bytes=0-\r\n' returns HTTP/1.1 206 Partial Content, Content-Length: 1, Content-Range: bytes 0-0/71
```

I don't think this is expected that only 1 byte is returned and not the entire object.  This might explain the "unexpected EOF" I see in the client application (which expects to get an entire sha256 sum).

Not sure if this is my issue, as my previous tcpdump show no response at all, but it seems that this strange range header is not entirely handled as expected?

**Comment by bel2125** [comment]
> So as far as I can see I can only pass commandline options to civetweb, but it seems there is no commandline option to enable debugging in UserManual.md?

No, these additional debug traces are printed only when enabled at compile time. The server becomes very noisy and there is considerable performance loss when traces are enabled.

> The application does a GET with "Range: bytes=0-\r\n" ...

Every HTTP header line ends with \r\n, and the entire HTTP header ends with an empty line with \r\n.
So, if `curl -H ` itself adds another \r\n for every header, the second version will yield in an invalid request, or at least with the HTTP header ending after this line. If `curl -H` does not add a \r\n, the line following this header will be invalid in the first version - I can't imagine curl works this way, but I have to check the documentation.

**Comment by bel2125** [comment]
Got it in the documentation: https://curl.haxx.se/docs/manpage.html#-H

***curl will make sure that each header you add/replace is sent with the proper end-of-line marker, you should thus not add that as a part of the header content: do not add newlines or carriage returns, they will only mess things up for you.***

**Comment by bel2125** [comment]
In other words: `curl -H 'range: bytes=0-\r\n'` is an invalid request.

Now, this probably does not help you with the original issue ...

- are you able to build the civetweb source yourself with the DEBUG define set?
- otherwise, could you print the log of a web debugging tool such as "fiddler"?
- if you don't have fiddler, wireshark logs will also help (I think both, fiddler and wireshark are free)

**Comment by r0ss3** [comment]
Many thanks for your answers bel2125.  You are absolutely correct that my curl tests made no sense. 

I am not able to compile and test myself, so DEBUG will not be possible.  I have an issue open on the ceph tracker but it is going to take a while.  I do have the wireshark, that's where I got the full request incl headers from.  It shows that civetweb never responds but just closes the connection.  

I did some further trial and error testing by manually sending the GET request with netcat, and it seems it has something to do with the absolute path.  Every request I send that starts with http://vip.lb.com/ is closed without reply.  This might explain why other client applications work just fine.  Most of them use relative paths I guess.  And I was able to do absolute path requests using curl as well, so it has to be a combination of absolute path and something else.

**Comment by r0ss3** [comment]
I believe the problem is when using absoluteURI and auth_domain_check is not "yes". 

https://github.com/civetweb/civetweb/blob/0f1b43536d97d9311c73b658b86a9d44be9e5e82/src/civetweb.c#L15174-L15180

I'm no C expert at all, but mg_strcasecmp will return something else than 0 when auth_domain_check is not yes.  So auth_domain_check_enabled will not be true, as expected.  So the check on line 15177 returns 0 and the connection gets closed, right?

**Comment by r0ss3** [comment]
It seems someone already has a PR to fix this on the ceph fork:

https://github.com/ceph/civetweb/pull/27

**Comment by bel2125** [comment]
Do you have to use absolute URIs? Does it work with relative URIs?

**Comment by r0ss3** [comment]
yes it does work with relative URIs.  It works with most client applications, except one which uses aws-sdk-go which does absoluteURI requests.

So, since it is apparently fixed in master I will close this issue, and try to get this fix merged in ceph asap.

Many thanks bel2125 for your excellent support!
