### ISSUE TITLE
Failed to handle Content-Type: application/x-www-form-urlencoded; charset=UTF-8

### ISSUE THREAD

**Issue by jienew** [civetweb/civetweb#651]
https://github.com/civetweb/civetweb/blob/19b85cf807fb1acd6ba113c980509cd00953162b/src/handle_form.inl#L360-L361

Should be?
mg_strncasecmp(content_type, "APPLICATION/X-WWW-FORM-URLENCODED", 33)
mg_strncasecmp(content_type, "APPLICATION/WWW-FORM-URLENCODED", 31)

**Comment by bel2125** [comment]
parameters like "charset=something" are not scheduled for this content type, according to the IANA media type registration:

https://www.iana.org/assignments/media-types/application/x-www-form-urlencoded

```
Optional parameters : 
No parameters
```

(For reference: a list of registered media types is [here](https://www.iana.org/assignments/media-types/media-types.xhtml) and some other media types do have parameters).

So, I think "Content-Type: application/x-www-form-urlencoded; charset=UTF-8" is invalid.
Where did you get this request from?

Your code change does not cause any harm, so we can still merge it - still all optional parameters will be ignored.

**Comment by jienew** [comment]
The request is sent by jQuery ajax() function with POST method, on Firefox.

**Comment by bel2125** [comment]
Modified according to your suggestion above.
Could you repeat your test, just to be sure (doing a test with a browser form does not seem to create a parameter for forms).

**Comment by bel2125** [comment]
Done in 2018
