### ISSUE TITLE
mg_write crashing ceph RGW 13.2

### ISSUE THREAD

**Issue by kevinmccarthy** [civetweb/civetweb#653]
Full issue here: https://tracker.ceph.com/issues/24364

Cross-posting this since it appears the actual code that is breaking is in civetweb, and perhaps someone here has advice?

Appears to be related to content size. Call works fine for small responses but crashes on large ones.

ceph version 13.2.1 (5533ecdc0fda920179d7ad84e0aa65a127b20d77) mimic (stable)
 1: (()+0x281670) [0x55fd3e88f670]
 2: (()+0xf6d0) [0x7f577208c6d0]
 3: (gsignal()+0x37) [0x7f57664f0277]
 4: (abort()+0x148) [0x7f57664f1968]
 5: (()+0x78d37) [0x7f5766532d37]
 6: (__fortify_fail()+0x37) [0x7f57665d26e7]
 7: (()+0x116862) [0x7f57665d0862]
 8: (()+0x118647) [0x7f57665d2647]
 9: (()+0x2655da) [0x55fd3e8735da]
 10: (mg_write()+0xc1) [0x55fd3e87a521]
 11: (RGWCivetWeb::write_data(char const*, unsigned long)+0x40) [0x55fd3e885ae0]
 12: (rgw::io::BufferingFilter&lt;rgw::io::ChunkingFilter&lt;rgw::io::ConLenControllingFilter&lt;RGWCivetWeb*&gt; > >::send_body(char const*, unsigned long)+0xf8) [0x55fd3e812f78]
 13: (rgw::io::AccountingFilter&lt;rgw::io::RestfulClient*&gt;::send_body(char const*, unsigned long)+0x15) [0x55fd3e80fe05]
 14: (dump_body(req_state*, char const*, unsigned long)+0x43) [0x55fd3ea22bd3]
 15: (RGWGetObj_ObjStore_S3::send_response_data(ceph::buffer::list&, long, long)+0x280) [0x55fd3ea7a2a0]
 16: (RGWGetObj::get_data_cb(ceph::buffer::list&, long, long)+0x67) [0x55fd3e94ffb7]
 17: (RGWRados::get_obj_iterate_cb(RGWObjectCtx*, RGWObjState*, RGWBucketInfo const&, rgw_obj const&, rgw_raw_obj const&, long, long, long, bool, void*)+0xea) [0x55fd3e9d4d9a]
 18: (()+0x3c7596) [0x55fd3e9d5596]
 19: (RGWRados::iterate_obj(RGWObjectCtx&, RGWBucketInfo const&, rgw_obj const&, long, long, unsigned long, int ()(RGWBucketInfo const&, rgw_obj const&, rgw_raw_obj const&, long, long, long, bool, RGWObjState, void*), void*)+0x3f9) [0x55fd3e9d7f69]
 20: (RGWRados::Object::Read::iterate(long, long, RGWGetDataCB*)+0x2a1) [0x55fd3e9d83c1]
 21: (RGWGetObj::execute()+0xc5c) [0x55fd3e976ebc]
 22: (rgw_process_authenticated(RGWHandler_REST*, RGWOp*&, RGWRequest*, req_state*, bool)+0x1cd) [0x55fd3e9903ad]
 23: (process_request(RGWRados*, RGWREST*, RGWRequest*, std::string const&, rgw::auth::StrategyRegistry const&, RGWRestfulIO*, OpsLogSocket*, int*)+0xe4c) [0x55fd3e9912fc]
 24: (RGWCivetWebFrontend::process(mg_connection*)+0x37c) [0x55fd3e810f9c]
 25: (()+0x27249e) [0x55fd3e88049e]
 26: (()+0x274188) [0x55fd3e882188]
 27: (()+0x274628) [0x55fd3e882628]
 28: (()+0x7e25) [0x7f5772084e25]
 29: (clone()+0x6d) [0x7f57665b8bad]
 NOTE: a copy of the executable, or `objdump -rdS &lt;executable&gt;` is needed to interpret this.

**Comment by bel2125** [comment]
Is there a chance to get symbols in the backtrace for civetweb beyond `mg_write`?
In particular, what function is 0x55fd3e8735da (probably within civetweb) and what is 0x7f57665d2647 (not within civetweb - maybe some system call)?
What version of civetweb is used here? 
What architecture (linux x64 ...)?

From the callstack, it could be an invalid argument passed to `mg_write` as well ... some invalid pointer to a buffer, an invalid mg_connection that's already closed or a broken pointer, ...

If you have a core dump and the source, you can probably get the full callstack with all function names, all arguments and all local variables.

**Comment by kevinmccarthy** [comment]
Thank you for the reply. It looks like this issue has been addressed but did not make it into the version packaged with Ceph:

https://github.com/ceph/civetweb/pull/29
