### ISSUE TITLE
Add support for clientside OpenSSL TLS SNI extension

### ISSUE THREAD

**Issue by Mellnik** [civetweb/civetweb#655]
Please add **clientside** servername verification for OpenSSL.
This is as easy as calling `SSL_set_tlsext_host_name` after ssl context creation.

**Comment by bel2125** [comment]
Seems reasonable - I'm going to add this in a couple of days.

However, if you already had a look, it is also welcome if you prepare a pull request (so I only have to push "merge" and add you to the contributors list :-) )

**Comment by Mellnik** [comment]
#658
