### ISSUE TITLE
errors when execute "make all" in examples/emnedded_c

### ISSUE THREAD

**Issue by willl0320** [civetweb/civetweb#657]
There are errors when execute "make all" in examples/emnedded_c .  
I deleted -DUSE_SSL_DH=1 in line 27 of Makefile and make in Linux.
Anyone could offer any advices?

cc -c -Wall -Wextra -Wshadow -Wformat-security -Winit-self -Wmissing-prototypes -DLINUX -Iinclude -DNO_SSL=1 -DUSE_STACK_SIZE=102400 -O2 -DNDEBUG -DUSE_IPV6 -DUSE_WEBSOCKET -fPIC src/civetweb.c -o out/src/civetweb.o
ar cq libcivetweb.a out/src/civetweb.o
make[1]: Leaving directory `/mnt/hgfs/18.8_nextGen/civetweb-master'
cp ../../libcivetweb.a .
cc -o embedded_c -I../../include  -DUSE_WEBSOCKET -DUSE_IPV6  embedded_c.c libcivetweb.a -lpthread -ldl -lcrypto -lssl
libcivetweb.a(civetweb.o): In function `mg_get_current_time_ns':
civetweb.c:(.text+0x165a): undefined reference to `clock_gettime'
libcivetweb.a(civetweb.o): In function `read_message':
civetweb.c:(.text+0xbacd): undefined reference to `clock_gettime'
civetweb.c:(.text+0xbbd7): undefined reference to `clock_gettime'
libcivetweb.a(civetweb.o): In function `get_message':
civetweb.c:(.text+0xbd2b): undefined reference to `clock_gettime'
collect2: ld returned 1 exit status
make: *** [embedded_c] Error 1

**Comment by bel2125** [comment]
Then you probably need to add "-lrt" (link with "rt" lib). It seems some distributions need this, others don't. Or maybe you built the lib with different options than the example?
Just try to add -lrt right next to -ldl.

Could you also post what linux distibution you are using ("uname -a" and "cat /etc/issue")?

**Comment by willl0320** [comment]
Thanks a lot, it works with adding -lrt
