### ISSUE TITLE
Error while loading libcrypto.so

### ISSUE THREAD

**Issue by taralshah1234** [civetweb/civetweb#666]
Hi Team, Thanks for the awesome civetweb server. 
I was using this for my pc application. Now i need to run same application in my embedded linux device. 
So for starting I tried to use example "rest" included with civetweb. I was able to cross compile rest application and generate binary file "rest_server" for my linux device. These are the changes made in rest example makefile

```all: $(PROG)

$(PROG): $(CIVETWEB_LIB) $(SRC)
$(CC) -o $@ $(CFLAGS) $(LDFLAGS) $(SRC) $(CIVETWEB_LIB) $(LIBS) $(SSL_LIB) $(CRYPTO_LIB)

$(CIVETWEB_LIB):
$(MAKE) -C $(TOP) WITH_IPV6=1 WITH_WEBSOCKET=1 WITH_DEBUG=1 clean lib
cp $(TOP)/$(CIVETWEB_LIB) . 
```

I removed -DUSE_SSL_DH=1
I also removed COPT=-DNO_SSL_DL as this was not allowing me to compile civetweb lib.
I changed -lssl and -lcrypto to my SSL_LIB and CRYPTO_LIB where, the .so files for my device were stored in my device's toolchain on my workstation.
I was able to compile properly. It generated libcivetweb.a and rest_server binary.
But when I run that on my board, it throws an error loading libcrypto.so
I verified that the path it is looking for the libcrypto.so file, it is already there. With some more prints I came to know that It was printing as:
```
Missing function: ENGINE_cleanup
Missing function: CONF_modules_unload
Missing function: CRYPTO_free
*** 3897.126582923            0 4146032640 initialize_ssl:15420: initialize_ssl: error loading library libcrypto.so
*** 3897.126997846       414923 4146032640 mg_init_library:19825: Initializing SSL failed: initialize_ssl: error loading library libcrypto.so
*** 3897.127710308       712462 4146032640 mg_start:18484: [listening_ports] -> [8089r,8843s]
*** 3897.127749923        39615 4146032640 mg_start:18484: [request_timeout_ms] -> [10000]
*** 3897.127776770        26847 4146032640 mg_start:18484: [error_log_file] -> [error.log]
*** 3897.127804077        27307 4146032640 mg_start:18484: [ssl_certificate] -> [server.pem]
*** 3897.127821693        17616 4146032640 mg_start:18484: [ssl_protocol_version] -> [3]
*** 3897.127839231        17538 4146032640 mg_start:18484: [ssl_cipher_list] -> [DES-CBC3-SHA:AES128-SHA:AES128-GCM-SHA256]
*** 3897.127865462        26231 4146032640 mg_start:18484: [ssl_verify_peer] -> [yes]
*** 3897.127890923        25461 4146032640 mg_start:18484: [ssl_ca_file] -> [client.pem]
*** 3897.127907462        16539 4146032640 mg_start:18484: [enable_auth_domain_check] -> [no]
******** load_dll. libcrypto.so 
Missing function: ENGINE_cleanup
Missing function: CONF_modules_unload
Missing function: CRYPTO_free
*** 3897.128147693       240231 4146032640 initialize_ssl:15420: initialize_ssl: error loading library libcrypto.so
*** 3897.128188693        41000 4146032640 mg_cry_internal_impl:3647: mg_cry called from init_ssl_ctx:15948: initialize_ssl: error loading library libcrypto.so
```
Can anyone please tell me how should I properly crosscompile and run for a different target device having Linux? I want it with HTTPS support. My device already has openssl support. It has libcrypto.so in its /system/lib path

**Comment by bel2125** [comment]
I guess it's a OpenSSL 1.0 vs. OpenSSL 1.1 API issue.
CivetWeb defaults to the OpenSSL 1.0 API (for compatibility reasons), if you want to use 1.1, you need to set the `OPENSSL_API_1_1` define (compile flag '-DOPENSSL_API_1_1')
