### ISSUE TITLE
error_pages must end with a slash

### ISSUE THREAD

**Issue by tkauppin** [civetweb/civetweb#670]
I took me couple of hours to notice that the error_pages parameter must end with a "/" or "\".
It is very hard to see this kind of errors, so I suggest to make it work also without the extra character.

**Comment by bel2125** [comment]
As a quick "first aid" I added an extra line in the description. 
The current implementation allowed to use a file name prefix, not only a directory - although I have to admit, this was not intended.

**Comment by tkauppin** [comment]
I would be more than enough if this behavior is clearly mentioned in the documentation.

**Comment by bel2125** [comment]
Documentation already updated in 2018, but it was forgotten to close this issue.
