### ISSUE TITLE
Is there a way to set timeout / cancel current `mg_read`?

### ISSUE THREAD

**Issue by duong2179** [civetweb/civetweb#673]
I am using `mg_read` for a http client module. Say, for a slow connection, I would like to cancel / abort current `mg_read` action. How could I do that?

**Comment by bel2125** [comment]
Currently, I don't see a direct interface to abort `mg_read`. You can use a timeout, so `mg_read` will fail a connection that's not receiving something in time. Forcefully closing the connection would also do more than just cancel the `mg_read` operation (the connection is unusable afterwards, while if you just cancel `mg_read` you could still try again later).

From my experience, mechanisms, where one task cancels operations of another one, tend to cause problems. The available functions are significantly different depending on the operating system. I would try to solve it with a short timeout and a loop in the calling task, while the other task does not exactly "cancel" an operation, but sets the exit condition for the loop of the first one - that's also far more portable. The `mg_read` function uses a timeout from `request_timeout_ms` - you can set this easily for servers, but I'm not sure if you **currently** can set this particular parameter for clients as well. I know there is an issue for setting all client configuration options (#479) - I'm just not sure if there is already a workaround/trick to set this particular parameter without having to wait for (#479). I'll post it here if I find one.

**Comment by duong2179** [comment]
Thanks. I used small buffer for each `mg_read` and surrounded the reading action with a `while (!stopped) { ... }`.
