### ISSUE TITLE
Accept Timeout

### ISSUE THREAD

**Issue by mretallack** [civetweb/civetweb#674]
Hi, 

I have noticed an issue when the sslize function calls SSL_accept the timeout is 2 seconds https://github.com/civetweb/civetweb/blob/c47476e289e3bb4543ad9ab2ddf1c286ebbe97ab/src/civetweb.c#L15104 (16+32+64+128+256+512+1024 ms). 

I think this is causes us issues on a simulated slow/bad network where the SSL negotiation takes longer than 2 seconds. 

There are options to change the timeouts (request_timeout_ms, websocket_timeout_ms) but these dont effect the SSL_timeout. 

Is my reading of the situation correct? if so I will propose a patch. 

Thanks

**Comment by bel2125** [comment]
Yes, your reading of this part of the code is correct.
I can't tell if this piece of code really causes your particular issue on your particular simulated slow/bad network connection - but you can easily check if you run into `i > 1024` and if it helps to increase the limit.

A patch is certainly welcome.

**Comment by mretallack** [comment]
Created pull request with change, will close this issue now there is a pull request

https://github.com/civetweb/civetweb/pull/676

**Comment by mretallack** [comment]
Created pull request with change, will close this issue now there is a pull request

https://github.com/civetweb/civetweb/pull/676
