### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by rojdes** [civetweb/civetweb#678]
Due to building "Building on Android" I always receive error 
_make: *** No rule to make target `jni/../../../../src/main.c', needed by `obj/local/arm64-v8a/objs/civetweb/__/__/src/main.o'.  Stop._

Also I try to use cross-compiling approach, but get error like  
_x86_64-linux-android/bin/ld: error: cannot find -lgcc_
Is it possible update mk file?

**Comment by bel2125** [comment]
During the last years, we collected a couple of build scripts here ;-)
so, which one are you using - CMake, an (older) Makefile?

**Comment by rojdes** [comment]
Better using CMake

**Comment by rojdes** [comment]
Civetweb .a library was built using approach with environments in scrypt https://github.com/gcesarmza/curl-android-ios/tree/master/curl-compile-scripts

Unfortunately I couldn't build .so because of error during compilation UnitTest.
