### ISSUE TITLE
Init a server with client-only ssl is not possible anymore

### ISSUE THREAD

**Issue by PhilLab** [civetweb/civetweb#680]
(Possibly) since 9fc4d3e250d529dd
> Add client interface to standalone server and fix ssl init for clients

Starting a server without a SSL listening port but with the ability to initiate an SSL connection as client is not possible anymore. At least the previous way of providing the option ``ssl_certificate`` does not initialize SSL anymore because
```
	if (is_ssl_port_used(ports_option)) {
		/* Initialize with SSL support */
		mg_init_library(MG_FEATURES_TLS);
	} else {
		/* Initialize without SSL support */
		mg_init_library(MG_FEATURES_DEFAULT);
	}
```

I am using the CPP interface which only does ``	context = mg_start(&callbacks, this, options);`` without any previous ``mg_init_library``

**Comment by PhilLab** [comment]
Just adding
```
	/* Initialize with SSL support */
	mg_init_library(MG_FEATURES_TLS);
```
to CivetServer.cpp before the ``mg_start()`` solved the issue, though I am not sure if this is okay for every user of the CPP interface

**Comment by bel2125** [comment]
I think this will cause problems on systems where OpenSSL is not installed (or not found in the system path) when you do not plan to use SSL at all. Furthermore, it will call mg_init_library more than once if you have more than one CivetServer instance - this way constructing a server will no longer be thread safe,

The intended way is indeed to call mg_init_library manually, either with MG_FEATURES_TLS set or not set ... there is no way to know this in advance.

**Comment by PhilLab** [comment]
Okay, I understand, thanks for responding. Isn't calling mg_init_library guarded by ``mg_init_library_called``, though?

What about an option ``init_tls`` or similar, which is parsed by ``mg_start``?

**Comment by PhilLab** [comment]
> Is there a reason to avoid the mg_init_library call?

No, there is no reason. But as you said it cannot simply always initialize TLS
> I think this will cause problems on systems where OpenSSL is not installed (or not found in the system path) 

so we have to make it configurable, even when using the Cpp interface. So what do you think about this: in the ``mg_start`` either we add a new option (pseudocode)
```
        if (is_ssl_port_used(ports_option) || ifNewTlsOptionFoundInOptions(options)) {
		/* Initialize with SSL support */
		mg_init_library(MG_FEATURES_TLS);
	} else {
		/* Initialize without SSL support */
		mg_init_library(MG_FEATURES_DEFAULT);
	}
````
or use the ``#define NO_SSL`` to either never or always init TLS, irregardless of the ssl_port_used (because our server might use SSL only as client)
```
#ifdef NO_SSL
		/* Initialize without SSL support */
		mg_init_library(MG_FEATURES_DEFAULT);
#else
		/* Initialize with SSL support */
		mg_init_library(MG_FEATURES_TLS);
#endif
```

**Comment by bel2125** [comment]
I don't like the idea of adding another option passed to `mg_start` for several reasons. `mg_start` should  take parameters for initializing the server, not the client or the library. For initializing the library, `mg_init_library` is supposed to be called. In the standalone executable, there are already [some options](https://github.com/civetweb/civetweb/blob/8c120199eb69cac99de1035f3487a99728fc0d06/src/main.c#L215) not evaluated by `mg_start` for similar reasons - they just don't fit into a function with the purpose "start an instance of a server". But these parameters are passed to "main" just like all other parameters.
It seems to me, you are missing one layer around mg_start, where you can handle parameters not related to a server instance?
From the parameters passed to "mg_start", it will know it it needs TLS for the server instance started by this very "mg_start" call. But it will not know if TLS is needed for any client, any other server instance or anything else within the same process. From the design, a function calling "mg_start" does not have to know if any other part of the code will require TLS or any other feature. This was the idea why "mg_init_library" has the feature flags as parameter.

If you have an executable only starting one instance of the server, you could do it with code like this:

```C++
CivetServer * start_the_server() {
   std::vector<std::string> options;
   ReadOptionsFromFile(&options);

  if (OptionsContainsTLS(options)) {
    mg_init_library(MG_FEATURES_TLS);
  } else {
    mg_init_library(MG_FEATURES_DEFAULT);
  }

  HandleAllOtherPrivateOptions(options);

  DropAllOptionsNotRelevantForServer(&options);

  CivetServer *server = new CivetServer(options);

  return server;  
}
```

You just have to add the mg_init_library call somewhere.

Or you can probably encapsulate this in a CivetServer derived class.
You can actually call mg_init_library several times, and a later call might add `MG_FEATURE_TLS` even if the first call did not use it - it's just by definition not thread safe, so don't do it in two different threads at the same time.

**Comment by PhilLab** [comment]
Okay, I didn't know that calling ``mg_init_library`` multiple times is going to work. Thank you very much for the extensive feedback 👍 , I will add the tls init to the layer around the ``CivetServer``
