### ISSUE TITLE
endless loop in mg_handle_form_request (V1.11)

### ISSUE THREAD

**Issue by nfrmtkr** [civetweb/civetweb#682]
If a multipart/from-data request starts a field but doesn't send the end boundary, then the  mg_handle_form_request runs in endless loop in the while(!next) loop. The mg_read() call repeatedly returns 0 and search_boundary() returns NULL.

I've tried following code after the call to search_boundary():

`				if(next == 0 && r == 0)
				{
					/* read error */
					if (fstore.access.fp) {
						mg_fclose(&fstore.access);
						remove_bad_file(conn, path);
					}
					mg_free(boundary);
					return -1;
				}
`
This will break the endless loop but ends up with incomplete file. I use MG_FORM_FIELD_STORAGE_GET and write the file chunks by my self. The callbacks should inform about an incomplete upload (missing boundary).

Any idea how to solve this issue?

Another issue in same loop seems to be with MG_FORM_FIELD_HANDLE_ABORT return code of unencoded_field_get(). This leads to visit the "if (field_storage == MG_FORM_FIELD_STORAGE_GET)" after the while loop and this is not the expected behavior, I guess. Most probably a "field_storage = MG_FORM_FIELD_STORAGE_ABORT;" should be set in case unencoded_field_get returns MG_FORM_FIELD_STORAGE_GET?

**Comment by bel2125** [comment]
> If a multipart/from-data request starts a field but doesn't send the end boundary, then the mg_handle_form_request runs in endless loop in the while(!next) loop. The mg_read() call repeatedly returns 0 and search_boundary() returns NULL.

Did you close the connection from the client to the server, or did you keep it open?

I expect mg_read to return a negative value, if the connection is closed.
But if the connection remains open and there is just no data *now* it will return 0 ... but then you should indeed read again, because maybe the boundary will be sent some time later (like expected from the protocol specification).

Or, did I misinterpret this test case?

Or, do you mean, there has to be some timeout, if the connection remains open but no data is received?

**Comment by nfrmtkr** [comment]
I use curl for this use case:

curl  -v -X POST -H "Content-Type: multipart/form-data; boundary=------------------------ed9df0ad17f325eb" --data-binary "@http_body.txt" http://localhost:5555/req/UploadFileRequest 

with following file:
[http_body.txt](https://github.com/civetweb/civetweb/files/2563859/http_body.txt)

It's missing the end-boundary.

**Comment by bel2125** [comment]
I can reproduce this using the "embedded_c" example.

**Comment by nfrmtkr** [comment]
Today I've copier handle_form.inl from master to by 1.11 build and tested your changes.
With my test I still get the endless loop. It is the situation with missing boundary. The body ends with raw data.

In this situation line 135 is:

return fdh->field_get(key_dec, value, value_len, fdh->user_data);

value = some data
value_len = 0

My handler detects this an returns MG_FORM_FIELD_HANDLE_ABORT.
However this causes the while loop break in 893, but field_storage is MG_FORM_FIELD_STORAGE_GET and if in line 948 evaluates to true. 
The followup iteration in the loop will cause a huge value for towrite in line 946 and finaly leads to crash in my code because field_get callback is called wih value_len=18446743199013704624.

I've added a "field_storage = MG_FORM_FIELD_STORAGE_ABORT;" before break in line 893 and this causes to stop processing.

How this situation should be handled in the callback functions? In general it would be good to be informed about that civetweb stops processing in order to clean up resources. At least it should be passed back as negative return code of mg_handle_form_request.

**Comment by bel2125** [comment]
I added another fix.
A test with the existing embedded example works:
```
curl -v -X POST -H "Content-Type: multipart/form-data; boundary=------------------------ed9df0ad17f325eb" --data-binary "@http_body.txt" http://localhost:8884/handle_form.embedded_c.example.callback
```

Could you repeat your tests as well?

**Comment by nfrmtkr** [comment]
I've tested with my use case.

Before break; in line 893 and 965 I've added following code in order to get it to work:

    field_storage = MG_FORM_FIELD_STORAGE_ABORT;

As I mentioned in my last post. The callback field_get() will be called with

valuelen=0
value=next-data-block

This means that unencoded_field_get() is called with towrite=0.

I'll check for value==0 and return MG_FORM_FIELD_HANDLE_ABORT.

**Comment by nfrmtkr** [comment]
Here is my example upload data:

**Comment by bel2125** [comment]
Just tested with your file from the EMail:

```
C:\CPP\CivetWeb>curl -v -X POST -H "Content-Type: multipart/form-data; boundary=------------------------ed9df0ad17f325eb" --data-binary "@without_end_boundary.raw" http://localhost:8884/handle_form.embedded_c.example.callback
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying ::1...
* TCP_NODELAY set
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8884 (#0)
> POST /handle_form.embedded_c.example.callback HTTP/1.1
> Host: localhost:8884
> User-Agent: curl/7.55.1
> Accept: */*
> Content-Type: multipart/form-data; boundary=------------------------ed9df0ad17f325eb
> Content-Length: 2446
> Expect: 100-continue
>
< HTTP/1.1 200 OK
< Content-Type: text/plain
< Connection: close
<
Form data:* Done waiting for 100-continue
* We are completely uploaded and fine


Path:
Path = /zoo

Name:
Name = newbutterfly.jpg

File:

-1 fields found* Closing connection 0

C:\CPP\CivetWeb>
```

```
C:\CPP\CivetWeb>curl -v -X POST -H "Content-Type: multipart/form-data; boundary=------------------------ed9df0ad17f325eb" --data-binary "@with_end_boundary.raw" http://localhost:8884/handle_form.embedded_c.example.callback
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying ::1...
* TCP_NODELAY set
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8884 (#0)
> POST /handle_form.embedded_c.example.callback HTTP/1.1
> Host: localhost:8884
> User-Agent: curl/7.55.1
> Accept: */*
> Content-Type: multipart/form-data; boundary=------------------------ed9df0ad17f325eb
> Content-Length: 2446
> Expect: 100-continue
>
< HTTP/1.1 200 OK
< Content-Type: text/plain
< Connection: close
<
Form data:* Done waiting for 100-continue
* We are completely uploaded and fine


Path:
Path = /zoo

Name:
Name = newbutterfly.jpg

File:
stored as D:\tmp\newbutterfly.jpg (2046 bytes)


3 fields found* Closing connection 0

C:\CPP\CivetWeb>
```

I used http://localhost:8884/handle_form.embedded_c.example.callback from the embedded_c example - the result is as expected, right? You used a `field_get` callback. Could you post a C code snipped, or better, is it possible to add this to the embedded_c example, so I can reproduce your test?

**Comment by nfrmtkr** [comment]
I've tested embedded_c with "master". I've send you a modified version that shows the issue I face.

In field_found I return MG_FORM_FIELD_STORAGE_GET. 
In field_get I check for key && key[0] == '\0' valuelen == 0, exec cleanup code and return MG_FORM_FIELD_HANDLE_ABORT in order to abort field handling. 

In this case the process exits.

You'll see that the function will be called 3 times for the "file" field:

valuelen=2050
valuelen=0
valuelen=some nonsense value

At the point with valuelen=0 it would be valuable to know that civetweb detected an issue and will end the form data handling procedure. I need to close the file and remove it in this case.

From my point of view it would be sufficent to vall field_get with value pointer 0 and valuelen 0. 
The I can check and interpret it as "something went wrong". Civetweb must not call field_get with pointer 0 and valuelen 0 in case nothing went wrong. For the unlikley case that a 0 byte read from socket occurs, this can be checked an the call to field_get can be skipped.

Any suggestions?

**Comment by bel2125** [comment]
> I've send you a modified version that shows the issue I face.

I did not get this version. How did you send it/where did you put it?

**Comment by nfrmtkr** [comment]
I've sent it again to your gmail.com address.

**Comment by bel2125** [comment]
I integrated your file into embedded_c - see 124b236121cfb390d2cf4454f235739c32e40833

```
C:\CPP\CivetWeb>curl -v -X POST -H "Content-Type: multipart/form-data; boundary=------------------------ed9df0ad17f325eb" --data-binary "@with_end_boundary.raw" http://localhost:8884/handle_form.embedded_c.example.callback
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying ::1...
* TCP_NODELAY set
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8884 (#0)
> POST /handle_form.embedded_c.example.callback HTTP/1.1
> Host: localhost:8884
> User-Agent: curl/7.55.1
> Accept: */*
> Content-Type: multipart/form-data; boundary=------------------------ed9df0ad17f325eb
> Content-Length: 2446
> Expect: 100-continue
>
< HTTP/1.1 200 OK
< Content-Type: text/plain
< Connection: close
<
Form data:* Done waiting for 100-continue
* We are completely uploaded and fine


Path:
key = Path
valuelen = 4
value md5 hash = 3ed8d199596a9da68b73d5f3c7443af6


Name:
key = Name
valuelen = 16
value md5 hash = c8c31f81a35430af68be9a2171beccea


File:
key = File
valuelen = 2046
value md5 hash = 6e282acebb8bfcc4ec88800088c00a43

3 fields found* Closing connection 0

C:\CPP\CivetWeb>curl -v -X POST -H "Content-Type: multipart/form-data; boundary=------------------------ed9df0ad17f325eb" --data-binary "@without_end_boundary.raw" http://localhost:8884/handle_form.embedded_c.example.callback
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying ::1...
* TCP_NODELAY set
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8884 (#0)
> POST /handle_form.embedded_c.example.callback HTTP/1.1
> Host: localhost:8884
> User-Agent: curl/7.55.1
> Accept: */*
> Content-Type: multipart/form-data; boundary=------------------------ed9df0ad17f325eb
> Content-Length: 2446
> Expect: 100-continue
>
< HTTP/1.1 200 OK
< Content-Type: text/plain
< Connection: close
<
Form data:* Done waiting for 100-continue
* We are completely uploaded and fine


Path:
key = Path
valuelen = 4
value md5 hash = 3ed8d199596a9da68b73d5f3c7443af6


Name:
key = Name
valuelen = 16
value md5 hash = c8c31f81a35430af68be9a2171beccea


File:
key = File
valuelen = 2050
value md5 hash = a8e89d69e016bb7b09cbd378e3f29850

3 fields found* Closing connection 0

C:\CPP\CivetWeb>
```

Both files have the same size of 2446 bytes - "without" reads 4 bytes more in the last field.
But the image data seems to be completely different in these two files.

With 2a9d318971b11e425037ff594f687e18d45d3188 handle_form returns an error, if the multipart message is not complete.

Could you repeat your test with this version?
