### ISSUE TITLE
Callback handle_error: Wrong return code handling

### ISSUE THREAD

**Issue by nfrmtkr** [civetweb/civetweb#683]
The documentation about http_error states:

>If the application sends their own error page, it must return 1 to signal CivetWeb that no further processing is needed. If the returned value is 0, CivetWeb will send a built-in error page to the client.

In current implementation it's the opposite: The callback must return 0 in order to signal CivetWeb not to send a built-in error page. 

Looking at the code:

`handled_by_callback =
		    (conn->phys_ctx->callbacks.http_error(conn, status, errmsg_buf)
		     == 0);
`
You'll see that "handle_by_callback" will be true if return code is 0, only!

You may change the documentation, but looking at the other callbacks you should change the code in order to have same sematics among all callbacks.

**Comment by bel2125** [comment]
Thanks.
I will check the code, the examples and the documentation.

**Comment by bel2125** [comment]
Already fixed in current documentation
