### ISSUE TITLE
How to know whether request connection is still alive?

### ISSUE THREAD

**Issue by SanderMertens** [civetweb/civetweb#691]
I am trying to do the following: I have an application that is single threaded, and for various reasons I cannot add locking to its data structures. I want to add a web UI to this application to monitor & control aspects of this application through a REST API (not websockets), but these interactions may only happen at application-controlled moments in time, which occur frequently (many times per second). 

Since civetweb is multithreaded, I was thinking about gathering all requests in a list, walking the list when the app is ready & replying to each request with `mg_printf` or equivalent - **outside of the request thread**.

In order to do this though I need to know whether the connection is still alive. Is there a way to achieve this for plain HTTP request connections?

**Comment by bel2125** [comment]
There are several ways to do this. A very simple (brute force) way would be to use one big lock and let all request handlers wait there until your single threaded application is ready, releases the lock, answers the open requests, and takes the lock again. Another way would be to have a copy of the data cached for the read operations ... or maybe it is possible to always read data without lock and just write needs to be protected? Then you could queue write operations, and block the callback until the queue is empty.
An elegant solution could be to use async write operations (http://restcookbook.com/Resources/asynchroneous-operations/).

In either case, you can just mg_write to the client - if the connection is broken/closed, you get an error.

**Comment by SanderMertens** [comment]
Thanks for the quick reply, that is helpful! The brute force lock will be the way to go for me, as unfortunately it is unsafe to read without a lock.

A more elegant way IMO to address this would be to have the server do all of its work in a single thread. Are there any plans to support Mongoose-polling like behavior? I noticed this question has been asked a long time ago (#28), curious if it is still under consideration.

**Comment by bel2125** [comment]
I don't plan to implement #28 - I did not need it for any application. Even if this feature would be available, there are probably a couple of undesirable side effects. When you have just one thread, clients, server and the rest of the application can block one another. From my experience, in particular if you have blocking handler, a multi-threaded server works way better than a single threaded one. In this case (in a real application with handlers reading data from other devices/peripherals), the response time of civetweb (multithreaded) is by factors better than e.g. nodejs (which is single threaded). Of course, this can be different for different use cases - my point is just in all of my use cases and all of my tests, a multithreaded server was better or equivalent than a single threaded one.

**Comment by SanderMertens** [comment]
That makes sense, and I agree that multithreaded servers outperform single threaded ones. What this feature would allow for though is to move the thread dispatching to the application layer, and thus to application threads. 

This can be advantageous if certain application-level resources are a bound to certain threads, as it would reduce the amount of locking required- which is something I'm now essentially doing manually in my application, and something I would've imagined being more relevant for embedded servers.

If it's not going to be implemented that's fine though- the workaround you suggested is adequate. Feel free to close the issue.

**Comment by SanderMertens** [comment]
I ended up doing a combination of the things you suggested. I prepare/update a JSON response periodically at a time when it is safe to do so and just return that JSON string when a client requests it- only access to the JSON string is locked. On the other hand, when issuing commands to the server, they are processed synchronously, for which I do this:

> A very simple (brute force) way would be to use one big lock and let all request handlers wait there until your single threaded application is ready, releases the lock, answers the open requests, and takes the lock again.

I'll close this issue.
