### ISSUE TITLE
V547 Expression 'buf_fill == 0'

### ISSUE THREAD

**Issue by pavel-pimenov** [civetweb/civetweb#692]
V547 Expression 'buf_fill == 0' is always false. handle_form.inl 935

![default](https://user-images.githubusercontent.com/920705/48673705-583de900-eb55-11e8-80ff-c13ffc3cc13e.png)

**Comment by bel2125** [comment]
All data is read, if the buffer fill state is 0, and we did not read any more data.

This line is in this file several times - a low priority "TODO" is to eliminate some of the duplicate code.
At least all the other uses of this line are not always false.

**Comment by bel2125** [comment]
I think this was a result of a PVS Studio scan.

All PVS warnings have already been solved https://github.com/civetweb/civetweb/issues/597#issuecomment-618458863:
![image](https://user-images.githubusercontent.com/5619191/94561673-9f728600-0264-11eb-93fa-925b221cba09.png)
