### ISSUE TITLE
More details in documentation for mg_send_mime_file2

### ISSUE THREAD

**Issue by nfrmtkr** [civetweb/civetweb#693]
You may add following useful details to the doczmentation for mg_send_mime_file2:

The additional_headers string must not end with \r\n. The character sequence \r\n will be added by Civetweb automatically:

additional_headers + \r\n + \r\n\ + body

Avoid setting additional_headers to empty string, because this will add \r\n and will break the HTTP response.

**Comment by bel2125** [comment]
You are right.
But since this is at least the second time (maybe more, I just remember one other case), I think it's better to just drop the \r\n at the end if there is any. It's apparently a common mistake, that can be easily avoided by making the code a bit tolerant here.

**Comment by nfrmtkr** [comment]
Well, making code more tolerant means more processing steps. A clean statement about what to do avoids unecessary checks in Civetweb code. I would keep it as it is and provide more details in documentation.

**Comment by bel2125** [comment]
Seems we forgot to close this issue:
The current implementation does not care if you add `\r\n` or use empty lines.
