### ISSUE TITLE
Cannot support Chinese/Korean/Japanses etc.. at windows

### ISSUE THREAD

**Issue by FEI17N** [civetweb/civetweb#697]
Cannot support Chinese/Korean/Japanses etc.. at windows.

and will crash at the judge if is number function.

**Comment by FEI17N** [comment]
Chinese/Korean/Japanese and even full-width symbol will occupy 2 bytes. So if you get a char at char* buffer in this string， you will get a wrong value and must not be a character.
I tried to used for film sharing in the LAN. and also want to re-develop for a bridge to commit between my local app and the control html.
But, if someone typing some  Chinese/Korean/Japanese it will crash(i cannot control user the content he typed).
< windows 7  x64 (Chinese version)
< vs2015 x86  
the reason is not the system version or language packs.
the reason is only 1 byte cannot be a Chinese character.

**Comment by xtne6f** [comment]
Almost all CKJ / full-width symbols occupy 3 bytes (UTF-8), though Civetweb generally does not need to pay attention to these because of well-designed UTF-8 encoding.
At least, in my Windows 10 x64 (Japanese) environment, Civetweb seems not to crash with these symbols.

**Comment by bel2125** [comment]
Yes, civetweb internally uses [UTF-8](https://en.wikipedia.org/wiki/UTF-8) multibyte encoding FOR FILENAMES .
This is also the native encoding for Linux FILENAMES.
On a Windows System, FILENAMES are converted to [UTF-16](https://en.wikipedia.org/wiki/UTF-16) (or UCS-2 for older Versions) - both are using 16 bits for each character. One 16 bit character is enough to encode the [basic multilingual plane](https://en.wikipedia.org/wiki/Plane_(Unicode)#Basic_Multilingual_Plane) - this plane contains almost all living languages, including CJK characters. I was told, only traditional Chinese ideographics are not included in this plane (I can't verify this myself, my Japanese is limited to reading ~20 symbols). So, this is the 65535 limit I mentioned above. Characters outside the basic multilingual plane will have a code above 65535 and cannot be encoded in one 16 bit block - so [surrogate pairs](https://en.wikipedia.org/wiki/UTF-16#U+010000_to_U+10FFFF) have to be used - but different Windows versions seem to handle surrogate pairs IN FILENAMES differently, partially even allowing invalid encoding.

All stated above refers to FILENAMES on the server side.

If we are talking about FILE CONTENTS, or INPUT FORM FIELDS or ... ? ... it's a different consideration. CivetWeb will also handle this, internally it just works differently.

So, please provide some details what will crash or what will not work. Best would be an example how to reproduce the undesired behavior.

**Comment by bel2125** [comment]
I just did that test with Chrome (Version 70) on Win 10 64-bit (Version 1803) "America+Europe Edition?"
The file can have a Chinese name and Chinese contents, and it works as expected (it definitely does not crash).

I added the file (in the /test/nonlatin directory, it also works directly in the document root as in your test). The content is "This is a sample text" in a couple of languages known by Google Translate - I took all that created "significantly non-latin looking characters" (excluding languages using characters that are only "latin" with additions above like circumflex, diaresis, ... like [â](https://en.wiktionary.org/wiki/%C3%A2), [ñ](https://en.wiktionary.org/wiki/%C3%B1), [ö](https://en.wiktionary.org/wiki/%C3%B6)).

Tested with the current head version of CivetWeb.

**Comment by FEI17N** [comment]
do you use a single exe or run debug with vs studio?
if you run debug with vs studio, it will show this:
![1](https://user-images.githubusercontent.com/5754593/48999176-c9eae800-f190-11e8-8a1e-272a2819efca.png)
![2](https://user-images.githubusercontent.com/5754593/48999177-c9eae800-f190-11e8-928d-f58120745353.png)

**Comment by FEI17N** [comment]
i had fix this problem ,you should change some code like this


static int
path_cannot_disclose_cgi(const char *path)
{
    static const char *allowed_last_characters = "_-";
    int last = path[strlen(path) - 1];
    int bLast = (last >= -1 && last <= 255 ? isalnum(last) : 0);
    int bStrchr = strchr(allowed_last_characters, last);
    int bStrchrRes = bStrchr != NULL;
    return bLast || bStrchrRes;
}

**Comment by xtne6f** [comment]
Not only the `isalnum`, but some other `is*` also seem to be used with uncasted char arguments.
There will be no problem in release build, but it would be better to correct.
Another simple (and standard-compliant) way is just to cast to unsigned char :
`int last = (unsigned char)path[strlen(path) - 1];`
