### ISSUE TITLE
does civetweb support http pipelining?

### ISSUE THREAD

**Issue by wanderer1234** [civetweb/civetweb#707]
Hello all,

i was wondering if civetweb supports http pipelining? I have made a client that sends pipelined http request to my civetweb server, but I only see the first request being served and the rest are not. In wireshark I see the client request as a single packet with multiple http parts (for each request) in a single packet (so for example 2 GET requests, or 1 GET 1 PUT) but the response packet has only the response for the first request in the chain. 

is this functionality supported? If not, can it be hacked for a quick fix?

Thank you and best regards

**Comment by xtne6f** [comment]
Currently (maybe from v0.7), it seems to be unsupported, because (I suspect) 9d58de6615c12b84a111d8206fff93a85910f48c (#49) resets cache of the following requests.

**Comment by bel2125** [comment]
I actually thought it would be supported by the server, but browsers stopped to support it (see https://en.wikipedia.org/wiki/HTTP_pipelining: "As of 2018, HTTP pipelining is not enabled by default in modern browsers"), so I did not test it for quite a while. You definitely have to set the `keep_alive` configuration value to `yes`, and the total length of pipelined requests is limited. 

For everything else, I need to redo some tests - maybe it got accidentally unsupported ...

**Comment by xtne6f** [comment]
I have opened #717 about this issue.
We can easily test HTTP pipelining by using netcat.
`echo -en "GET /test1.txt HTTP/1.1\r\nHost: localhost:8080\r\n\r\nGET /test2.txt HTTP/1.1\r\nHost: localhost:8080\r\n\r\n" | nc localhost 8080`

**Comment by bel2125** [comment]
This issue has already been fixed quite some time ago.
The test `echo -en "GET /hello.txt HTTP/1.1\r\nHost: localhost:8080\r\n\r\nGET /hello.txt HTTP/1.1\r\nHost: loca
lhost:8080\r\n\r\n" | nc localhost 8080` still works, provided `enable_keep_alive` is set to `yes`.
