### ISSUE TITLE
Performance of CivetWeb client

### ISSUE THREAD

**Issue by nemethz5** [civetweb/civetweb#708]
Hi,

I made some measuring of CivetWeb performance.
My reference was the RemoteObject server/client.
I find that the CivetWeb server works fine both on http and https.
But the CivetWeb client is significantly slower than RemoteObject client on htpp and its performance is very poor on https.
I attached my measurements values and the code of my CivetWeb client.
My CivetWeb version is 1.12.

Can you explain this problem or can you suggest me any solution to speed up the client performance?

Thanks
Zoltan Nemeth

[PerformanceTests.txt](https://github.com/civetweb/civetweb/files/2652765/PerformanceTests.txt)
[main.c.zip](https://github.com/civetweb/civetweb/files/2652769/main.c.zip)

**Comment by bel2125** [comment]
CivetWeb is traditionally a server, which later on got an additional client interface. While a lot of work has been done to optimize the server, this has not yet been done for the client.
I also don't know, how ".NET RemObject client" works: Does it recycle connections, so several requests are done with one connection after one HTTPS handshake? If you don't know: Is there either some place I can download this client, or could you provide a wireshark log from 3 consecutive requests?

**Comment by bel2125** [comment]
@xtne6f : I merged the commit to the master branch, thank you.
@nemethz5 : Could you redo the test? The HTTP performance should not change, but you should see a better HTTPS client performance. 
To have a look at the HTTP client, could you provide some information on the ".NET RemObject client"?

**Comment by bel2125** [comment]
I think we solved this topic long ago but forgot to close the issue.
