### ISSUE TITLE
Multiple HTTP headers

### ISSUE THREAD

**Issue by ptaferner** [civetweb/civetweb#710]
Civetweb 1.11 introduced the possibility to use the Kepler Syntax which is very convenient for me migrating a project which used to have Haserl CGI pages.
However, I seem to have a dilemma in my project, as I would like to use mg.include() which is available for Lua Server Pages only - and for Lua Server Pages HTTP headers are automatically included currently if not already defined in the included file. This currently results in additional headers appearing in the body, i.e. I have them as additional text on the final HTML page. My current workaround is rather a hack, and seems kind of weird to me... I start the file to include with a Lua page code tag, i.e. <? ?>, because then it's treated as Lua Page by Civetweb. This, however, has the disadvantage that I can't use Kepler syntax for this file any more.

Am I missing something here or misunderstanding the way Civetweb works? Otherwise it would be beneficial for my situation to be able to control the mg.include() behavior, i.e. controlling via a boolean parameter whether I want to have the automatic HTTP header addition.

**Comment by bel2125** [comment]
After reading this issue several times, I'm still not sure if I fully understood it.
Could you add some minimal example files to reproduce the problem.

In principle:
You should be able to use `mg.include()' from Kepler Syntax Lua Pages as well as from "Traditional Civetweb Syntax" Lua Pages. An additional parameter in `mg.include(file, includetype)` (see example https://github.com/civetweb/civetweb/blob/master/test/page3a.lp#L16) defines if this include uses an absolute or relative path. Headers are only sent for the outer most "Kepler Syntax" Lua file, not for any included file.

**Comment by ptaferner** [comment]
[header-example.zip](https://github.com/civetweb/civetweb/files/2683540/header-example.zip)

Yes, I can provide you with a minimal example. Requesting the included example.html results in an additional HTTP header in the body for me on Civetweb 1.11. Note that I use the lua_server_page_pattern to map .html files to Lua Server Pages (this is for backwards compatibility in my project).

The additional header occurs on the second (and nested) mg.include() call. It seems that Civetweb correctly skips the header for includes on the root file, but does add a header if another include occurs within an include.

However, as explained before, I can circumvent the problem when I add a Lua code statement at the very beginning of the inner most include file, i.e. when i add something like `<? headers = false ?>`. So I do have a workaround to the problem, but the root issue remains.

**Comment by bel2125** [comment]
Now civetweb will only send HTTP headers for "Kepler Syntax" the top level pages - not for the ones included by "mg.include" - no matter what syntax is used.

Please check again with your pages.

**Comment by ptaferner** [comment]
Yes, I can confirm that your patch fixes the issue.
Thanks for the quick reaction.
