### ISSUE TITLE
Distribute CivetWeb Conan package

### ISSUE THREAD

**Issue by uilianries** [civetweb/civetweb#712]
Hi!

It's really nice to see Conan support in your project :1st_place_medal: 

However, the package is not being distributed on [Conan Center](https://bintray.com/conan/conan-center) server. The advantage is building your project using multiple configuration and distributing all binary package.

Including Conan CI support for your project is can be really simple and even I could help you.

Regards!

/cc @steakhal

**Comment by uilianries** [comment]
>  it seems the version is not up to date.

Yes, indeed is outdated, but we can update :)

> Is deployment to conan center automatic - triggered from github pushes/merges or releases?

Yes. Your CI environment is able to build and deploy in Conan center.

I could support with a PR including all changes needed.

**Comment by bel2125** [comment]
>> Is deployment to conan center automatic - triggered from github pushes/merges or releases?
>
> Yes. Your CI environment is able to build and deploy in Conan center.

Is it deployed for every push / pull request (like Travis CI does), or does it only deploy releases?
Is there some automatic versioning of pull requests? How many artifacts does it keep?

> I could support with a PR including all changes needed.

Yes, please.

**Comment by uilianries** [comment]
> Is it deployed for every push / pull request (like Travis CI does), or does it only deploy releases?

It only deploys new releases. When I say deploy, it means upload to Conan Center repository -- You could build a package in your CI, but dont upload it.
Each build could be executed only when a new tag is created, avoiding overloading its CI service.

>  Is there some automatic versioning of pull requests?

We will use branch name as version, so each new release will follow the correct name.

> How many artifacts does it keep?

Usually, a C++ project could provide ~200 artifacts, where each one is different from others (arch, os, release/debug, compiler, ...). But dont worry about, Conan Center is totally free and has storage enough for all releases, including future ones.

Okay, I'm going to work in a new PR with all necessary changes. Also, I'll invite some Conan experts to review the new PR.

**Comment by bel2125** [comment]
Unfortunately the CONAN builds in Travis CI do not work, and I don't know how to fix it. 
According to the new credit based system on Travis CI these failed builds are extremely expensive, so we might need to remove them from the .travis.yml file again. 
See #991.
