### ISSUE TITLE
PUT can hang due to wrong error handling in forward_body_data

### ISSUE THREAD

**Issue by ken-walters** [civetweb/civetweb#713]
We were seeing PUT for large files hang and never return with an https connection.

I added some extra logging and found in forward_body_data if pull_inner returns -1 for timeout then forward_body_data will never return.  The bug is that if -1 is returned the code decrements conn->consumed_content by 1 and then the while loop never finishes.  

The code should only increment conn->consumed_content if pull_inner returns a positive value

I will submit a PR for the fix I am using

**Comment by bel2125** [comment]
So, it's already fixed in the master branch with https://github.com/civetweb/civetweb/commit/8c736c0a99b79f6da2d52891b1abcddf4fdbf47d, and we can close this issue, right?
Thanks for your contribution.

**Comment by ken-walters** [comment]
Yes we can close it now.  Thanks
