### ISSUE TITLE
Number of mg.includes() limited instead of depth

### ISSUE THREAD

**Issue by ptaferner** [civetweb/civetweb#714]
I have a page where 10 mg.include() calls occur. The last include seems to be skipped with an error message "lsp max include depth of 10 reached while including...".
In mod_lua.inl I could find the constant LSP_MAX_INCLUDE_DEPTH which, as a comment in the source informs, shall limit the depth of includes to avoid things like recursion - makes absolutely sense to me.

However, on the page just mentioned I have 10 include calls on total, but the include depth is never higher than 2, i.e. I have one include where another include occurs, but there isn't any deeper nesting.
In prepare_lua_environment() every include seems to add to lsp_include_history, thus simply counting the amount of include calls, irrelevant from the nesting.

This is a serious problem in my project, as working around this means either patching LSP_MAX_INCLUDE_DEPTH (possible, but maybe not too future proof) or re-factoring many of my pages. Unfortunately, I couldn't consider this current limitation of Civetweb in my work, as it isn't documented anywhere other than in the source code.

**Comment by bel2125** [comment]
LSP_MAX_INCLUDE_DEPTH is supposed to limit the nesting depth, not the total number of calls.

I guess you just found an implementation issue (either no one tested 10 mg.include calls in one script, or I broke it with some modification). The fix could be as simple as inserting the line "include_history->depth--;" at the end of "handle_lsp_request" (or before "cleanup_handle_lsp_request:"). I will test this when I'm back.

**Comment by bel2125** [comment]
This has been fixed quite some time ago.
We just forgot to close this issue.
