### ISSUE TITLE
Memory (and handles) leak when mg_printf/SSL_write function is called

### ISSUE THREAD

**Issue by nemethz5** [civetweb/civetweb#719]
Hi,

I find memory leak in a simple https client application.
The number of handles is growing up when the mg_printf() calls the SSL_write().

My app like this:
	
	...
	// Set connection options
	struct mg_client_options Options;
	memset(&Options, 0, sizeof(Options));
	Options.host = Server;
	Options.port = ServerPort;

	// Reset error message store
	char ClientError[256];
	memset(ClientError, 0, sizeof(ClientError));

	// Connect the server
	struct mg_connection *Connection = mg_connect_client_secure(&Options, ClientError, sizeof(ClientError));
	if(!Connection)
		{
		...
		return -1;
		}

	// Send request to the server
	mg_printf(Connection, "%s", Request);

	// Get server response
	int RetVal = 0;
	int ClientResult = mg_get_response(Connection, ClientError, sizeof(ClientError), 10000);
	if(ClientResult < 0)
		{
		…
		RetVal = -1;
		}
	else
		{
		const struct mg_response_info *ClientResponseInfo = mg_get_response_info(Connection);
		…
		}

    // Close server connection
    mg_close_connection(Connection);
…

Is above code good?
Any suggestion appreciated!

I use CivetWeb 1.12 with MinGW32 on Windows.

Thanks
Zoltan

**Comment by bel2125** [comment]
I do have some test code for a client here in the unit tests:
https://github.com/civetweb/civetweb/blob/e59e14a7955551c4dd2237fcf48a85300ef9d641/unittest/public_server.c#L4629

Where precisely are you loosing handles and how do you detect that? Handles and/or memory? What handles? How many: one per mg_printf call?

**Comment by nemethz5** [comment]
I think I found the problem. There is a mutex created on connection but not destroyed on disconnection. Its handler and memory not freed, so all new connections grow the used system resources.

Here is my quick fix, but I'm not sure this is the good solution.

void
mg_close_connection(struct mg_connection *conn)
{
	…
	close_connection(conn);

#if !defined(NO_SSL)
	if (conn->client_ssl_ctx != NULL) {
		SSL_CTX_free((SSL_CTX *)conn->client_ssl_ctx);
	}
#endif

	if(conn->mutex)
		pthread_mutex_destroy(&conn->mutex);

#if defined(USE_WEBSOCKET)
	if (client_ctx != NULL) {
	...
}

Can you check this?

**Comment by bel2125** [comment]
Looks correct.
Will you provide a pull request for this?

**Comment by nemethz5** [comment]
I simple downloaded the source, I have not own branch yet so I cannot provide a pull request.

**Comment by xtne6f** [comment]
I want @bel2125 to create a commit for this issue. (I'm an outsider about this, I can't do it.)
There seems to be no further discussion.

**Comment by bel2125** [comment]
Seems this issue was forgotten for a while.
I committed the fix from nemethz5
