### ISSUE TITLE
examples\embedded_c.c invalid field_storage detection in field_found()

### ISSUE THREAD

**Issue by nemethz5** [civetweb/civetweb#725]
The field_found() returns MSG_FORM_FIELD_GET when there is a filename, so the file is not saved in mg_handle_form_request().

I think, the line 263 of embedded_c.c file has to be changed to:
return MG_FORM_FIELD_STORAGE_**STORE**;

Please fix the embedded_c.c file!

**Comment by bel2125** [comment]
Fix made some time ago in a different branch --> finally merged.
