### ISSUE TITLE
Multipart answers and HTTP Keep-Alive

### ISSUE THREAD

**Issue by jodogne** [civetweb/civetweb#727]
Hello, I am currently working on sending multipart answers over HTTP persistent connections (`enable_keep_alive` option is set to `yes` in CivetWeb). More precisely, I wish to send a sequence of medical images in the body of a single HTTP answer.

As I am dealing with medical images, the final answer can gather hundreds of medical images, whose total size can easily grow up to several GBs. As a consequence, in order to reduce RAM consumption, I would like to prevent having to gather all of those images into a single memory buffer that would be sent at once using `mg_write()`. Consequently, I would like to send the multipart header, then to send each individual image using one separate call to `mg_write()`. 

Unfortunately, even though the HTTP transfer works correctly, it turns out that its performance is very bad if `enable_keep_alive` is `yes`. It is probably ten times slower than if `enable_keep_alive` is `no` (note that `tcp_nodelay` is set to `true`, so Nagle's algorithm is not the culprit here). My question is therefore twofold:

1. Is my use of a sequence of calls to `mg_write()` over a HTTP persistent connection incorrect wrt. HTTP standard, or is there some caveat inside CivetWeb?

2. Would it make sense to include a flag within the `struct mg_connection` that would lead function `should_keep_alive()` to return `0` in order to disable keep-alive on a per-request basis (instead of on a global basis as currently implemented)? This would allow to manually switch off HTTP persistent connections for multipart answers.

TIA for your insights!
Sébastien-

**Comment by bel2125** [comment]
Answering your questions directly:

1. You definitely can use a sequence of mg_write calls, but for a good performance you should use a reasonable size for the buffer, 1 kB or more. I don't think you should disable Nagle for this use case. 
As I understood you need throughput, not ping-pong response time.
The performance should be good if you do it this way. Within the "test" folder, there is the "100 images" test demonstrating something that sound similar (although all images are quite small in this test).

2. There is the "must_close" flag in "mg_connection". For Lua scripts, there is actually a function "keep_alive" to set this flag to tell CivetWeb keep_alive or close the connection in the Lua callback. It's not exported to the C interface, but we can do this.

Some additional thoughts:

-) If you don't know in advance how many bytes you are going to send, "chunked encoding" might useful.
-) HTTPS might be faster than HTTP in your case (see https://www.httpvshttps.com/) 
-) Browsers tend to load image files with more than one connection, so make sure not to limit num_threads too much.


I know a couple of similar applications (the images are not *medical*), and performance depends on several factors. The size of the images and the speed and reliability of the connection also plays a major role on what you need to do to optimize performance.

**Comment by jodogne** [comment]
Many thanks for your extremely complete answer! In my setup, I only see a marginal improvement if using buffers of 1KB and/or if using chunk transfer encoding. I have therefore decided to follow your second point, i.e. publishing a function in the C interface that sets `must_close` to `1`. This perfectly fits my throughput requirements. As a consequence, I close this issue.
