### ISSUE TITLE
V1004 The 'buffer' pointer was used unsafely

### ISSUE THREAD

**Issue by pavel-pimenov** [civetweb/civetweb#728]
V1004 The 'buffer' pointer was used unsafely after it was verified against nullptr. Check lines: 18962, 18967. civetweb.c 18967

![default](https://user-images.githubusercontent.com/920705/51696478-a7e9d680-2016-11e9-9fa8-aaaf563f83fa.png)

**Comment by xtne6f** [comment]
I want you to confirm whether the following expression can suppress V1004 or not:
```C
if ((buffer == NULL) || (buflen < 1)) {
	buflen = 0;
	end = buffer;
} else {
	*buffer = 0;
	end = buffer + buflen;
}
if (buflen > (int)(sizeof(eoobj) - 1)) {
```

**Comment by pavel-pimenov** [comment]
v1004 - fixed
![default](https://user-images.githubusercontent.com/920705/52356313-0797a700-2a45-11e9-80b4-02743a810904.png)

**Comment by xtne6f** [comment]
Thank you for the reply.
I can't judge whether the `(NULL + 0)` expression is legal or illegal in C-specification, but anyway I think such an expression is not clear. I have fixed it.
