### ISSUE TITLE
Make LTO optional for civetweb-cpp

### ISSUE THREAD

**Issue by chrisejones** [civetweb/civetweb#733]
Hi LTO is currently enabled for civetweb-cpp (but not civetweb). Please could you make LTO optional? We're currently needing to patch the CMakeLists.txt file as we are not using LTO.

Happy to make a PR to do this if you agree.

**Comment by bel2125** [comment]
LTO? https://en.wikipedia.org/wiki/Linear_Tape-Open
... oh, ... the link-time optimizer compiler options:

https://github.com/civetweb/civetweb/blob/38fe585a5c4f6584c59e31eb9c8ac78efbd09fc0/CMakeLists.txt#L391
https://github.com/civetweb/civetweb/blob/38fe585a5c4f6584c59e31eb9c8ac78efbd09fc0/CMakeLists.txt#L318

Yes, please provide a PR
