### ISSUE TITLE
Patch request support

### ISSUE THREAD

**Issue by bmoskalev** [civetweb/civetweb#736]
Does Civetweb support PATCH requests? Just when I try to make PATCH request I get next message

Error 405: Method Not Allowed
PATCH method not allowed

**Comment by bel2125** [comment]
Sorry for the late answer (was abroad last week).

Yes, it does support the "PATCH" method, but only for CGI scripts, Lua scripts and C/C++ callbacks:
https://github.com/civetweb/civetweb/blob/6fec72314a1b40e71da487dcc66d64657da99bcd/src/civetweb.c#L10218-L10231

You cannot send a "PATCH" request to an arbitrary file or an unknown URL.

**Comment by bel2125** [comment]
Question answered in March ... closing this issue.
If there is anything left to do, please reopen or create a new issue.
