### ISSUE TITLE
Then, of course you get an "incomplete type".

### ISSUE THREAD

**Issue by ptaferner** [civetweb/civetweb#737]
Then, of course you get an "incomplete type".

In line 1010:

``` C
#if defined(NO_SSL_DL)
#include <openssl/ssl.h>   --- this is not used
...
#else
/* SSL loaded dynamically from DLL.
 * I put the prototypes here to be independent from OpenSSL source
 * installation. */
typedef struct ssl_st SSL;  --- this is an incomplete type
```

There is no definition of struct ssl_st in civetweb.c, so you cannot access the members.

You will have to deal with your build environment to get NO_SSL_DL working.
OR you move the callback to a different file and include ssl.h there
OR you copy the definition of the SSL structure from this header (for a test - but you must take care of the license)

_Originally posted by @bel2125 in https://github.com/civetweb/civetweb/issues/347#issuecomment-244188669_

**Comment by ptaferner** [comment]
I have recently performed a scan of my Civetweb application via sslyze which reports client-side renegotiation as an issue.
Searching among the current issues in Civetweb brought me to an old issue from 2016 (#347). Most of the security problems mentioned there have been fixed by now, except for the renegotiation thing. In the later part of the issue discussion a possible workaround is mentioned using the SSL_set_info_callback. However, if I try this, I also end up with the problem of dereferencing the s3 pointer of the SSL struct.
My application needs the NO_SSL_DL compile flag set, and copying the whole SSL definition from ssl.h seems not a good solution to me, nor creating a new file and including the header.

Before I investigate my options further, I wanted to know if disabling renegotiation via the config, as proposed in #347 is still on your to-do list.

**Comment by bel2125** [comment]
Sorry for the late reply ... was abroad last week.

Yes, it should be possible to eliminate renegotiation.
As to my knowledge, SSL renegotioations has been completely removed from TLS 1.3 (see [Features Removed from TLS 1.3](https://www.cloudflare.com/learning-resources/tls-1-3/)). So my idea was to solve this by setting the required protocol version to > 1.2 - but I did not really investigate it up to now.

> My application needs the NO_SSL_DL compile flag set, and copying the whole SSL definition from ssl.h seems not a good solution to me, nor creating a new file and including the header.

... don't get it ...
If you set the `NO_SSL_DL` flag, then you get the `#include "ssl.h"` and do not require to define any struct there. You are missing the struct definitions, if you *do not* set the `NO_SSL_DL` flag.

**Comment by bel2125** [comment]
I just found, now there is a "no renegotiation" option: See [ssl.h](https://github.com/openssl/openssl/blob/38023b87f037f4b832c236dfce2a76272be08763/include/openssl/ssl.h#L397) and [description](https://github.com/openssl/openssl/blob/088dfa133561d7613b9391a56ddbce58f32c934a/doc/man3/SSL_CTX_set_options.pod).

Seems this already does the job, without the need to add some private struct definitions.

**Comment by ptaferner** [comment]
> I just found, now there is a "no renegotiation" option: See [ssl.h](https://github.com/openssl/openssl/blob/38023b87f037f4b832c236dfce2a76272be08763/include/openssl/ssl.h#L397) and [description](https://github.com/openssl/openssl/blob/088dfa133561d7613b9391a56ddbce58f32c934a/doc/man3/SSL_CTX_set_options.pod).
> 
> Seems this already does the job, without the need to add some private struct definitions.

This seems to be a good way for me to go; just need to check on the OpenSSL version I can use in my project. Thanks for the hint!

**Comment by ptaferner** [comment]
`
   #define SSL_CB_HANDSHAKE_START (0x10)
+ #define SSL_CB_HANDSHAKE_DONE (0x20)
   @@ -15707,6 +15708,7 @@ init_ssl_ctx_impl(struct mg_context *phys_ctx,
        SSL_CTX_set_options(dom_ctx->ssl_ctx,
                           SSL_OP_NO_SESSION_RESUMPTION_ON_RENEGOTIATION);
        SSL_CTX_set_options(dom_ctx->ssl_ctx, SSL_OP_NO_COMPRESSION);
+      SSL_CTX_set_options(dom_ctx->ssl_ctx, SSL_OP_NO_RENEGOTIATION);
#if !defined(NO_SSL_DL)
       SSL_CTX_set_ecdh_auto(dom_ctx->ssl_ctx, 1);
#endif /* NO_SSL_DL */
`
I now ended up with a patch like this above which completely disables client-side renegotiation. Btw, is there a specific reason why you want to keep the support of client-side renegotiation? It seems very rarely to be the case that the server needs to accept that.
But anyway, this patch does the job for me.

**Comment by bel2125** [comment]
No, I don't want to keep any renegotiation. It's just an old OpenSSL default and up to some days ago it seems it can only be disabled by accessing some members of a struct defined in ssl.h in some callback - and this does not work out with dynamically loading OpenSSL.

> +      SSL_CTX_set_options(dom_ctx->ssl_ctx, SSL_OP_NO_RENEGOTIATION);

That's exactly what I did in the patch 2 days ago:

https://github.com/civetweb/civetweb/commit/5df77ec2f51fe135f979d9dc7a66606ca17c5474#diff-942b175a4f5673b8f0ce6c0ab2fc2932R15854

... surrounded by an `#ifdef SSL_OP_NO_RENEGOTIATION`, since some older versions of ssl.h seem to not have this definition.

**Comment by bel2125** [comment]
SSL renegotiation deactivated (for recent OpenSSL versions)
