### ISSUE TITLE
Ordering between mg_lock_connection() and mg_lock_context()

### ISSUE THREAD

**Issue by xtne6f** [civetweb/civetweb#753]
CivetWeb exports these locking functions, but the allowed locking order is not clear. If someone calls `mg_lock_context()` after `mg_lock_connection()` and another does the opposite, it causes deadlock, so I want you to define the order.
In my opinion, it would be better to define `mg_lock_connection()` as the first order. If you consider the compatibility with the code: https://github.com/civetweb/civetweb/blob/9f07491d42be7f096cfb447edd007897f561bf40/src/CivetServer.cpp#L474-L476 , then define `mg_lock_context()` as the first order.

**Comment by bel2125** [comment]
I agree. Will you prepare a PR?

**Comment by xtne6f** [comment]
I will, because this issue is deeply related to my work-in-progress commit 744e8f8ed4f7c8d3ab1ec1ce107beb767a8b9dff.

**Comment by vaind** [comment]
FYI this is reported by Clang TSAN as well as a potential deadlock
```
WARNING: ThreadSanitizer: lock-order-inversion (potential deadlock) (pid=698)
  Cycle in lock order graph: M143 (0x7b6c00000410) => M145 (0x7b9400001370) => M143

  Mutex M145 acquired here while holding mutex M143 in thread T8:
    #0 pthread_mutex_lock <null> (http-server-test+0x112611)
    #1 mg_lock_connection civetweb/src/civetweb.cpp:12000:9 (http-server-test+0xcb572c)
    #2 CivetServer::getParam(mg_connection*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, unsigned long) civetweb/src/CivetServer.cpp:476:2 (http-server-test+0xcebdd7)

  Mutex M143 acquired here while holding mutex M145 in thread T8:
    #0 pthread_mutex_lock <null> (http-server-test+0x112611)
    #1 mg_lock_context civetweb/src/civetweb.cpp:12016:9 (http-server-test+0xcb57cc)
    #2 CivetServer::closeHandler(mg_connection const*) civetweb/src/CivetServer.cpp:345:2 (http-server-test+0xceaa9e)
    #3 close_connection(mg_connection*) civetweb/src/civetweb.cpp:16260:4 (http-server-test+0xcbb4e5)
    #4 process_new_connection(mg_connection*) civetweb/src/civetweb.cpp:17607:2 (http-server-test+0xcdd20b)
    #5 worker_thread_run(worker_thread_args*) civetweb/src/civetweb.cpp:17871:4 (http-server-test+0xcdb68c)
    #6 worker_thread(void*) civetweb/src/civetweb.cpp:17921:2 (http-server-test+0xcc1485)
````

**Comment by bel2125** [comment]
@xtne6f: The [wip-ssl-error-queue branch](https://github.com/civetweb/civetweb/commits/wip-ssl-error-queue) with the work-in-progress commit referenced above is currently not merged with master.
What is the current state of this?

**Comment by xtne6f** [comment]
Very sorry for my long silence. I've concentrated on my embedding project for a while...
I'm testing the [wip-ssl-error-queue]( https://github.com/civetweb/civetweb/commits/wip-ssl-error-queue ) (rebased) and some other requests now, while reading related issues (#834 and so on). Please wait an extra few days.

**Comment by xtne6f** [comment]
PR:#871 would have solved this.
