### ISSUE TITLE
read_message() blocks for 2 * request_timeout_ms when response is not coming

### ISSUE THREAD

**Issue by chrust** [civetweb/civetweb#754]
The input condition: a client connected to a civetweb server and not sending data (e.g. $nc civet-ip 80). In such situation the read_message() function requires [2 * request_timeout_ms], so 60s by default, to return timeout. It it because the "last_action_time" variable is not updated before mg_difftimespec(), thus pull_inner() is called twice!
I would suggest:
`
n = pull_inner(
   fp, conn, buf + *nread, bufsiz - *nread, request_timeout);
+clock_gettime(CLOCK_MONOTONIC, &last_action_time);
`

**Comment by bel2125** [comment]
Fixed in April 2019
