### ISSUE TITLE
documentation about config parameter max_request_size is missing

### ISSUE THREAD

**Issue by nfrmtkr** [civetweb/civetweb#758]
I don't find any documentation about the configuration paramater max_request_size. It was absent from mongoose at the point civetweb was spawned and has been reintroduced to civetweb some years ago. 

The documentation should include information about how max_request_size is checked and what happens if this limit is reached. 
Currently I don't see impact if I use mg_read(). The max_request_size seems not beeing checked during calls of mg_read. 
Does max_request_size check for HTTP body size only or for the complete request incl. the headers?

**Comment by bel2125** [comment]
I'm not aware of the history of max\_request\_size

max\_request\_size does not affect the HTTP body length, but only the header size. The server has to read the entire header from a client or from a CGI script, before it is able to process it. If the header is longer than max\_request\_size, the request is considered invalid (or malicious). Probably max\_header\_size would be a better name.

**Comment by nfrmtkr** [comment]
max_header_size would be a better name, but it will cause an incompatibility.
Adding your statement from above to the "manual" documentation would be enough.

**Comment by bel2125** [comment]
Done
