### ISSUE TITLE
Ceph/rgw How to konw about the civetweb log format for any log level?

### ISSUE THREAD

**Issue by Tanyy** [civetweb/civetweb#763]
just like the title.
I am using ELK to analysis my rgw logs , but I am no sure about the log output field mean.

and anywhere can check about that ?

**Comment by bel2125** [comment]
I don't know if ceph/rgw modifies anything in "standard" civetweb logging - there are callbacks to overwrite standard logging.

In civetweb, there are actually two different log files: the "error_log_file" and the "access_log_file" (that's the names of the civetweb configuration - see [UserManual](https://github.com/civetweb/civetweb/blob/master/docs/UserManual.md)). In addition there are also debug logs, but I guess they are only relevant for civetweb developers and turned off in ceph/rgw.

Error log is
`[`timestamp`] [error] [client `address`] `requestMethod` `requestURI`: `plain text error details

Access log is
sourceAddress` - `userNameOr-` [`dateAndTime`] "`requestMethod` `requestURIinclQueryString` `httpversion`" `statusCode` `bytesSent` `refererHeaderIfKnown` `userAgentIfKnown

But this is no interface that's guaranteed to be compatible for all future versions.

**Comment by Tanyy** [comment]
yep, the rgw access log output info  look like Ceph/rgw add some fieled, but i cannot find any things about that~

**Comment by bel2125** [comment]
As to my knowledge, ceph uses an older version of civetweb - but the relevant part of the code seems to be the same:
https://github.com/ceph/civetweb/blob/d7bcae46177670a266f9c2bae3bd4d13be9c24d4/src/civetweb.c#L6098

If they use some specific logging callback, then I don't know what was added and where to find it, sorry.

**Comment by Tanyy** [comment]
I am mistake ,  I was used the ceph client.rgw log before.
now I am get civetweb access log 

[client.rgw.gateway-node1]
rgw_frontends = civetweb request_timeout_ms=30000 error_log_file=/var/log/radosgw/civetweb.error.log access_log_file=/var/log/radosgw/civetweb.access.log

thanks for answer my question
