### ISSUE TITLE
Access violation in init_ssl_ctx_impl() with SSL_ALREADY_INITIALIZED defined

### ISSUE THREAD

**Issue by kimaluco17** [civetweb/civetweb#771]
Greetings,

I'm trying to embed v1.11 using the C++ wrapper into an application that already initializes SSL outside of Civetweb. When the application attempts to initialize Civetweb, an access violation exception is thrown in this section(line 15686 of v1.11):

`if ((dom_ctx->ssl_ctx = SSL_CTX_new(SSLv23_server_method())) == NULL) {`
`		mg_cry_internal(fc(phys_ctx),`
`		                "SSL_CTX_new (server) error: %s",`
`		                ssl_error());`
`		return 0;`
`}`

I found that this is due to the ssl_sw array not being initialized, which is supposed to be done in initialize_ssl(). The SSL_LIB dlls never get loaded since the function returns before getting there because of this condition(line 15395 of v1.11):

`if (mg_atomic_inc(&cryptolib_users) > 1) {`
`		return 1;`
`}`

I currently have v1.8 working in the application with no issues so far. I've compared those two versions and found in v1.8, the loading of SSL_LIB is done after the call to initialize_ssl() in set_ssl_option(), but this has since changed drastically.

I'm not too familiar with the internals of Civetweb since I haven't been working with it for long, so I'm wondering if I'm missing a step or if this is a bug. It seems like the dll for SSL_LIB should always be loaded before calling any of those SSL macros, but I'm not sure if that's done in another way with the SSL_ALREADY_INITIALIZED pre-processor flag.

Any suggestions on what I may be missing?

**Comment by bel2125** [comment]
The `ssl_sw` array is only used, if `NO_SSL_DL` is not set.
If `NO_SSL_DL` is set, civetweb assumes OpenSSL is directly loaded in the process at start time. Only if it is not set, civetweb loads the DLLs/SharedObjects at runtime using LoadLibrary/dlopen and initializes the `ssl_sw` array, which is basically a list of function pointers from GetProcAddress/dlsym. Are you using Windows, Linux or something else?
Can you use `NO_SSL_DL`?

**Comment by kimaluco17** [comment]
Our libssl is dynamically linked and used by other projects in the solution, so we cannot statically link it to civetweb, we want to load the libssl DLLs. In v1.8, both ssleay32.dll and libeay32.dll are loaded with no issue but in v1.11, ssleay32.dll does not get loaded but libeay32.dll does. The application also initializes SSL outside of Civetweb as other components that are part of that application use it. It also has to be supported on Windows, Ubuntu and CentOS.

**Comment by bel2125** [comment]
`NO_SSL_DL` does not mean, OpenSSL is statically linked - it's still dynamically linked, but not dynamically loaded. The difference is between loading at start time, and loading on demand during run time.
So `NO_SSL_DL` might still work. Did you use it for v1.8?
What precisely are the settings/defines that used to work in v1.8, that do no longer work for v1.11?

**Comment by kimaluco17** [comment]
Thanks for the clarification, I assumed the DL meant dynamically link. We are currently using v1.8 with defines for SSL_ALREADY_INITIALIZED, NO_CGI, and NO_FILES. When using v1.11, it does not work for us with SSL_ALREADY_INITIALIZED. We do not currently use the NO_SSL_DL flag and it has no impact on getting it to work in v1.11.

As far as I know, our SSL libraries are initialized by other components within the same process. We have a singleton object that handles initializing OpenSSL with a call to SSL_library_init(). All components that use our SSL library has a reference to that singleton object and I've verified that SSL_library_init() only gets called once on process start up and before Civetweb gets initialized.

**Comment by bel2125** [comment]
Yes, DL meant dynamic linking.

From V1.8 to V1.11, there are several changes in way CivetWeb uses OpenSSL, including changes in the initialization - see https://github.com/civetweb/civetweb/blob/master/RELEASE_NOTES.md

Now, there is a mandatory `mg_init_library` call, and there is a new callback to provide an external SSL context: https://github.com/civetweb/civetweb/blob/f6d7b04288c6ad11d0c1b187ee1324dfcdf1621d/include/civetweb.h#L269

**Comment by kimaluco17** [comment]
I did notice that new callback function, the issue I had with that is we do not currently create an ssl_ctx to provide to CivetWeb. The comment above that function prototype states that a return value of 0 should result in CivetWeb creating the context, but when I tried implementing it and returning a value of 0 in that callback, it ended up with the same result - init_ssl_ctx_impl() gets called and ends up calling SSLv23_server_method(), which gives the access violation error. Do we have to create the ssl_ctx ourselves and provide it or should returning a value of 0 work?

https://github.com/civetweb/civetweb/blob/f6d7b04288c6ad11d0c1b187ee1324dfcdf1621d/include/civetweb.h#L257-L265

**Comment by bel2125** [comment]
I think I do not fully understand the way you are using SSL in you project - maybe you are using it in a different way than all use cases we had up to now. Maybe I just don't understand the error description.
Then I would need a full call stack including parameter values up to that address, including the load address of all modules (DLLs for Windows, or SOs if you build for Ubuntu). 

SSLv23_server_method() is a pointer, when you compile without NO_SSL_DL (and can be NULL), or it is a function address within the SSL library if you compile with NO_SSL_DL (and will never be NULL). What is the value of SSLv23_server_method() in your case?

If you build without NO_SSL_DL, and ssleay32.dll does not get loaded, what is the error code?
(In general, building without NO_SSL_DL and using preloaded SSL libraries does not work so well, although it can work in some special cases).

Where are your libraries located? 

Did you use prebuilt SSL libraries with an installer (like [those](https://slproweb.com/products/Win32OpenSSL.html))? Did you install to the system directory?
Did you use a 32 or 64 bit version? Is there also an ssleay64.dll?

Alternatively, would it be possible to provide a minimal example code to reproduce this problem?

**Comment by kimaluco17** [comment]
We have upgraded to OpenSSL v1.1.1d, the issue is not apparent when using Civetweb v1.11 with that OpenSSL version.

I am closing this since the issue is not apparent with the new version of OpenSSL.
