### ISSUE TITLE
API for close (drop) client connection at server side?

### ISSUE THREAD

**Issue by tzjb** [civetweb/civetweb#774]
Hi, is there an API for the server to close a connection (drop/close a client connection)? Thanks!

**Comment by bel2125** [comment]
Sorry for the late reply ... been on holidays.

You can use `mg_close_connection` also to drop a client connection in a server callback.
But usually you want to reply something ... permission denied ... not found ... forbidden ... whatever (https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#4xx_Client_errors) - that can be done using `mg_send_http_error`.

**Comment by bel2125** [comment]
Question answered ... closing this issue.
If there is anything else to do, please reopen or create a new issue.
