### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [civetweb/civetweb#783]
I would like to point out that an identifier like “[`_CIVETWEB_SERVER_H_`](https://github.com/civetweb/civetweb/blob/79fcb558551e9f4378d18ae224bac61f0d64d523/include/CivetServer.h#L7 "Update candidate")” [does not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by bel2125** [comment]
Interestingly, this `_FILENAME_H_` seems to be common practice, I think it was even auto generated (Visual Studio?). Changing this is easy ... done.

**Comment by elfring** [comment]
Thanks for [your improvement of an affected include guard](https://github.com/civetweb/civetweb/commit/f407edfb2d1e2f37b051fa5c5f8b565f745d2648 "Renaming of an include guard").
