### ISSUE TITLE
Crash caused by global_lock_mutex violation when USE_SERVER_STATS defined

### ISSUE THREAD

**Issue by nemethz5** [civetweb/civetweb#784]
Mg_start() calls mg_calloc() before calling mg_init_library().
The global_lock_mutex is initialized by mg_init_library() calling the pthread_mutex_init(&global_lock_mutex, NULL), so mg_calloc() uses the global_lock_mutex before it is initialized.
This means that the application crashes in mg_start() if USE_SERVER_STATS is defined.

It seems this bug is in the current master branch also.
Has anyone encountered this error?

_I'm working a performance critical application and I want to build in a feature for online monitoring of server resources. I think I could to use CivetWeb's environmental information for this, so I should define USE_SERVER_STATS.
My main question is that, can be used this statistics feature in the release application or it is usable for debug only (is performance decreased by using statistics)?_

**Comment by bel2125** [comment]
I wrote a detailed explanation, and the browser crashed when I pressed "Comment" ... so here a short version:

Please call `mg_init_library` before calling `mg_start`. The implicit call to `mg_init_library` in `mg_start` is legacy, has some restrictions, and will be removed (replaced by an error message) in a future version.

Server stats use some performance, but not too much - I do use it in practice (not only for debugging). For an extremely "performance-critical" application, you need to test it.

**Comment by nemethz5** [comment]
It works if I call mg_init_library before calling mg_start.
Thanks!
