### ISSUE TITLE
Civetweb binary releases in GitHub?

### ISSUE THREAD

**Issue by quantuumsnot** [civetweb/civetweb#789]
Hi, I'm still using civetweb after the first public forks of Mongoose and lurking around today found that it's not possible to automate updating of the webserver because there's no GitHub 'releases' page for it? For example [Caddy](https://github.com/caddyserver/caddy/releases/latest) has it which allows to be used as an app and updated in [scoop](https://github.com/lukesampson/scoop) or similar command-line installers for Windows. So, will you add releases page for this?

**Comment by bel2125** [comment]
> So, will you add releases page for this?

There are GitHub releases: https://github.com/civetweb/civetweb/releases

So, you are missing binaries there? The binaries are stored on SourceForge: https://sourceforge.net/projects/civetweb/

As far as i remember, it was not possible to store binaries on GitHub, when the SourceForge page was created. Of course, I cold add some binaries here as well (the same binaries as in SourceForge). 

> it's not possible to automate updating of the webserver because there's no GitHub 'releases' page

However, I don't understand why it is not possible to automate updating with binaries from Sourceforge? Just to be clear: Your requirement is to have a script that can run on Windows only, check for updates on some server and download it (after confirmation)?

> updated in scoop 

I don't know scoop ... from a brief look, it seems to work only for Windows and require some privileges from the user account. CivetWeb can be used without any installer, just by copying the binary. If you are using it on windows, 

We could have a "check for updates" integrated in the pre-built "CivetWeb.exe" for Windows as well (with some option to enable/disable).

**Comment by quantuumsnot** [comment]
Yes, prebuilt binaries in .zip files in the releases. Building and installing it from source code can also be fully automated but adding civetweb as a part of frameworks like chocolatey and scoop will be very usefull for some of us that constantly like to harass their win installations to catch up with linux distros

I'm just moving my Windows 7 and 8 installations to have at least 85% automatic updates of the user apps, including civetweb

**Comment by bel2125** [comment]
I did not know chocolatey either.

So, the only thing you need is the same prebuilt binaries, that are available on SourceForge in GitHub releases? Do they need some special naming conventions? What about the content of the ZIP archives?

**Comment by quantuumsnot** [comment]
This is the app manifest documentation, it's straight forward to copy/paste the main parts. Personally I'm using [vegeta](https://github.com/tsenart/vegeta) as main load testing tool against webservers, with help from `ash` managed to create a [manifest](https://github.com/quantuumsnot/qtools/blob/master/vegeta.json) for it. You can use it as main guide when building the manifest for civetweb

**Comment by gjasny** [comment]
I also added civetweb to vcpkg: https://github.com/microsoft/vcpkg/tree/master/ports/civetweb

**Comment by bel2125** [comment]
V1.12, released 25 days ago, has some binaries attached: https://github.com/civetweb/civetweb/releases/tag/v1.12

Is this what you were asking for, or is there still something missing?

**Comment by bel2125** [comment]
V1.13 and V1.14 also have binary files attached - and vcpkg support.
Closing this issue.
