### ISSUE TITLE
Memory leak when using keep-alive

### ISSUE THREAD

**Issue by parnham** [civetweb/civetweb#790]
Platform: linux
Version: 1.11
Usage: embedded

When using keep-alive the `get_request(...)` function overwrites the host name in the connection having already been allocated on a previous request.

```
conn->host = alloc_get_host(conn);
```

Since the host should not be changing between requests then the above call can probably be skipped if it's non-null.

**Comment by parnham** [comment]
Ignore this - I hadn't noticed that v1.11 was from September last year and not this year. The issue has already been fixed in master.

**Comment by kimaluco17** [comment]
My team also ran into this issue when many requests are being sent out to Civetweb at once.

In case anyone wants to know the fix, the commit is here: https://github.com/civetweb/civetweb/commit/96e3e8c50acb4b8e0c946d02b5f880a3e62986e1
