### ISSUE TITLE
civetweb leaving open sockets in CLOSE_WAIT state

### ISSUE THREAD

**Issue by BillHayden** [civetweb/civetweb#792]
OS: CentOS 7

We are using civetweb as a websocket server, with an Angular/HTML5 client.  We have put in the options for keep_alive:
        "enable_keep_alive", "yes", "keep_alive_timeout_ms", "500"
I've defined DEBUG in the civetweb.c file so we can see some logging, and observed that a few requests (the number varies) from the client use the same socket, but then a new socket will be used for requests, and the old ones go into a CLOSE_WAIT state and are never closed.  These open sockets add up, and eventually the application becomes unresponsive.

**Comment by bel2125** [comment]
I guess I will either need the debug traces, or try to reproduce the problem. I don't have a CentOS running, probably Debian will do. What version of CivetWeb did you use?

**Comment by BillHayden** [comment]
I meant to update this.  We seem to have a pre-release version of 1.11.0.   By setting the keep_alive_timeout_ms option to 30 minutes instead of the default 500ms, this issue mostly went away.  There were still a dozen or so CLOSE_WAIT state sockets each time our app started up on a browser, but one of the check in fixes for leaking sockets in 1.11.0 fixed that.
