### ISSUE TITLE
Add additional options for Cache-Control header of static resources

### ISSUE THREAD

**Issue by samal84** [civetweb/civetweb#801]
This is regarding the send_static_cache_header function in civetweb.c:
https://github.com/civetweb/civetweb/blob/a87eeecdda8017c74495d6139682e069421f7592/src/civetweb.c#L4353

This only gives us the option to set `max-age` on the `Cache-Control` header for static resources:
`return mg_printf(conn, "Cache-Control: max-age=%u\r\n", (unsigned)max_age);`

There are several different options that can be added to this same header at the same time. Here are the two most authorative sources on the subject I could find:
* https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/http-caching
* https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control

For my particular use case I just want to use the set `Cache-Control` for static resources to `no-cache`, but people might have the need for any of the possible combinations of options for this header.

**Comment by bel2125** [comment]
If you set max_age to zero, you will get a "no-cache" header (see docs: https://github.com/civetweb/civetweb/blob/master/docs/UserManual.md#static_file_max_age-3600) 

https://github.com/civetweb/civetweb/blob/a87eeecdda8017c74495d6139682e069421f7592/src/civetweb.c#L4344-L4348

.. with a lot different (maybe partially legacy) headers to tell clients/caches not to cache

Then there is the "additional_header" configuration (https://github.com/civetweb/civetweb/blob/master/docs/UserManual.md#additional_header) to add one or more additional headers 

You think we need more?

**Comment by samal84** [comment]
Those headers complete disable caching. That's not what I was looking for. For our use case we still need the performance improvement of caching, but need to be able to invalidate the client cache when there are new files on the server.

"Cache-Control: no-cache" only forces the client to check in with the server before using its cache. Without this the client will keep using old files even if the server has new files. But it will still save us from having to re-download all files always on every page load.

For different use cases you might want to configure your Cache-Control header otherwise. See the flow chart in the article I linked to, it summarizes it perfectly: https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/images/http-cache-decision-tree.png

What I would love is for a civetweb setting that takes a string and uses that string as the default Cache-Control header for static resources. Simple and will be flexible for everyone's use case.

**Comment by samal84** [comment]
Also, the old "disable all caching completely" Cache-Control header is configured in an invalid way, as it included both no-cache and no-store, and these mean different things. no-cache means don't use your cache before you check in with the server to see if it is still the newest, and no-store means what you would assume no-cache means from just the name. It disabled caching completely. I assume that this hasn't caused issues as no-store probably takes precedence any hows.

**Comment by bel2125** [comment]
The "no-cache" and "no-store" header combination came from some articles on *what needs to be done that existing caches really, really do not store anything (including existing cache implementations that may have different interpretations of what a "standard" defines)*.
So, maybe the "no-cache" + "no-store" combination should not be required in theory, these articles stated its required in practice - I don't have the link available right now, but I can remember this exact combination we have here was the minimum to make every existing cache implementation understand "not to cache".

Anyway, you now do have a pull request that solves this issue?

**Comment by samal84** [comment]
Yeah. Thanks for merging :)
