### ISSUE TITLE
asynchronous requests

### ISSUE THREAD

**Issue by hansipie** [civetweb/civetweb#805]
Hello 

I was wondering if there was a good way to implement asynchronous requests in the server ?
This what i've done in pseudo code :
```
int reqAsyncHandler(struct mg_connection *conn, void *cbdata)
{
   extract arguments from the request;	
   send a reply; /* mg_printf( ... )*/
   make some operations with the extracted arguments; /* can be long */
   return with code 200;
}
```

 is it ok ? (Don't care about concurrency issues and the followup of the operations)

Thanks for your answer 👍

**Comment by DL6ER** [comment]
Do I understand you right, ou want to return the 200 early and still continue processing? In this case, I'd recommend to spawn a thread in place of
```
make some operations with the extracted arguments;
```
which you hand over the arguments and let it process it for you. This will be completely independent of the main flow of the HTTP server.

**Comment by bel2125** [comment]
I'm not exactly sure if I understood what you want to do. Do you want to send a "HTTP OK" first, maybe with some data (maybe without), then calculate something, then send more data, then calculate again ... send again ... until you eventually got everything - but want to keep this connection open?

In that case, don't use an extra thread, but just send a HTTP response header with a "Transfer-Encoding: chunked" header. See https://en.wikipedia.org/wiki/Chunked_transfer_encoding.
Then send some data with `mg_send_chunk` whenever you have some data ready.

This depends on how long your calculation is going to last, and what kind of client you have.
If you do not send data for a while, browsers may consider the server/connection as broken, and close the connection. For operations that really take long (minutes, hours, ...) you need to return some preliminary response ("request understood ... processing started ... come back later")  and allow to close the connection (if you are very courteous, reply with a temporary url allowing the client to query the status of the operation - but don't create/delete temporary urls by registering/unregistering handlers). The data processing may indeed be done in a different thread - but NEVER use the mg_connection object in the second thread - it get's invalid after the handler function returned. 

Before I write more, please let me know if I understood the requirement correctly.

**Comment by hansipie** [comment]
Ok, i understand.
So i'll create a thread for my operations as i don't need to keep the connection oppened and i don't need to send anymore data after my first replay.  
Thanks for your answers and advises.

**Comment by bel2125** [comment]
One more advise: Maybe you limit the number of threads you create, or send the request to a message queue to some predefined worker pool. Make sure you do not run into "denial of service" problems by creating too many threads that may eventually block the entire system.
