### ISSUE TITLE
Simple TCP server with websocket-like interface?

### ISSUE THREAD

**Issue by pfeatherstone** [civetweb/civetweb#807]
Question:

Can civetweb be used to instantiate a simple TCP server with callbacks similar to websocket callbacks (mg_websocket_connect_handler, mg_websocket_ready_handler,mg_websocket_data_handler,mg_websocket_close_handler but replace websocket for TCP)?

**Comment by bel2125** [comment]
Civetweb instantiates a HTTP server ... HTTP is a higher level protocol, using TCP underneath.
Websocket initially uses a HTTP connection to send an "Upgrade" request to switch from HTTP to websocket.
I'm not sure what you are asking for: Should there be some HTTP "Upgrade" request to switch from the higher level HTTP to the lower level TCP protocol, until the connection is closed? Or, do you want to skip the HTTP upgrade entirely and just build a TCP server? Or do you mean some specific TCP based protocol, some RFC? Or something else?
You cannot switch to TCP out of the box using some configuration, but it's possible with a minimal modification of the source ... depends on what you need exactly.

**Comment by pfeatherstone** [comment]
I’m just building a tcp server with a nice api, I.e using callbacks such as on_connected, on_recv, on_close etc. like the websocket callbacks in your library. Since http is built on tcp you already have a tcp server in civetweb. So I was wondering if you could expose a nice api for raw tcp server since the implementation is already there for http stuff.

**Comment by pfeatherstone** [comment]
Don’t worry. I spent the afternoon doing this just using the c socket api. Laborious but done.
