### ISSUE TITLE
Middleware for authentication

### ISSUE THREAD

**Issue by folibis** [civetweb/civetweb#810]
Is there some way to implement some kind of middleware or whatever for authentication? I want to check if user authenticated and if no sent him to /auth, otherwise use one of routes as is.

**Comment by bel2125** [comment]
If you build the server on your own, you could use auth callbacks for certain URLs (see `mg_set_auth_handler`), or one global callback to check everything (`begin_request`).
If you use the prebuild server, you could use Lua scripting: Just put one /index.lua into your docroot and check there.
Depends on what you want to do exactly.

**Comment by bel2125** [comment]
I think this question has been answered quite some time ago.
Closing this issue.
