### ISSUE TITLE
Disable tray menu

### ISSUE THREAD

**Issue by aolko** [civetweb/civetweb#813]
Is it possible to disable tray menu via a config or by adding such flag to the config?

**Comment by bel2125** [comment]
Currently not, but that would be a simple and reasonable extension.
I can do that in the next days.

**Comment by bel2125** [comment]
The feature is available in the release 1.12 from last month (https://github.com/civetweb/civetweb/releases/tag/v1.12). 

If you do start the executable `civetweb.exe -hide_tray yes` it starts without tray icon.
