### ISSUE TITLE
V781 The value of the 'd' index is checked after it was used

### ISSUE THREAD

**Issue by pavel-pimenov** [civetweb/civetweb#817]
V781 The value of the 'd' index is checked after it was used. Perhaps there is a mistake in program logic. handle_form.inl 686

https://github.com/civetweb/civetweb/blob/5475c99e941c7661f33b4bfc4722780f9072487e/src/handle_form.inl#L686

**Comment by bel2125** [comment]
What do you think would be the error in this algorithm?

https://github.com/civetweb/civetweb/blob/5475c99e941c7661f33b4bfc4722780f9072487e/src/handle_form.inl#L685-L688

I read it as "Find the first character from the begin of `buf` that is not `-`, but do not read for longer than `buf_fill`"

https://github.com/civetweb/civetweb/blob/5475c99e941c7661f33b4bfc4722780f9072487e/src/handle_form.inl#L689-L693

If there are character that is not '-' at the begin of buffer, remove them from the buffer.
