### ISSUE TITLE
error: filename in tree entry contains backslash: ''

### ISSUE THREAD

**Issue by pavel-pimenov** [civetweb/civetweb#818]
C:\git-ppa>git clone https://github.com/pavel-pimenov/prometheus-cpp.git
Cloning into 'prometheus-cpp'...
remote: Enumerating objects: 53, done.
remote: Counting objects: 100% (53/53), done.
remote: Compressing objects: 100% (24/24), done.
remote: Total 3050 (delta 43), reused 35 (delta 29), pack-reused 2997
Receiving objects: 100% (3050/3050), 655.07 KiB | 831.00 KiB/s, done.
Resolving deltas: 100% (1883/1883), done.

C:\git-ppa\prometheus-cpp>git submodule update --init --recursive
Submodule 'civetweb' (https://github.com/civetweb/civetweb.git) registered for path '3rdparty/civetweb'
Submodule 'googletest' (https://github.com/google/googletest.git) registered for path '3rdparty/googletest'
Cloning into 'C:/git-ppa/prometheus-cpp/3rdparty/civetweb'...
error: filename in tree entry contains backslash: '\'
error: filename in tree entry contains backslash: '\'
error: filename in tree entry contains backslash: '\'
error: filename in tree entry contains backslash: '\'
error: filename in tree entry contains backslash: '\'
error: filename in tree entry contains backslash: '\'
error: filename in tree entry contains backslash: '\'
error: filename in tree entry contains backslash: '\'
error: filename in tree entry contains backslash: '\'
error: filename in tree entry contains backslash: '\'
error: filename in tree entry contains backslash: '\'
error: filename in tree entry contains backslash: '\'
error: filename in tree entry contains backslash: '\'
error: filename in tree entry contains backslash: '\'
error: filename in tree entry contains backslash: '\'
error: filename in tree entry contains backslash: '\'
error: filename in tree entry contains backslash: '\'
error: filename in tree entry contains backslash: '\'
Cloning into 'C:/git-ppa/prometheus-cpp/3rdparty/googletest'...
Submodule path '3rdparty/civetweb': checked out 'ce8f6d38a60eb16c996afee1e5340f76ef4d0923'
Submodule path '3rdparty/googletest': checked out '703bd9caab50b139428cea1aaff9974ebee5742e'

**Comment by bel2125** [comment]
I guess this is a duplicate to https://github.com/civetweb/civetweb/issues/812

It is a bug in the new Git for Windows version 2.24: https://github.com/git-for-windows/git/issues/2435
and there is no reasonable solution or even workaround in CivetWeb, since it would require a history rewrite back to 2012.
