### ISSUE TITLE
Want to know how to implement language translation on this framework,Dynamic language

### ISSUE THREAD

**Issue by francisxie** [civetweb/civetweb#826]
Want to know how to implement language translation on this framework,Dynamic language

**Comment by bel2125** [comment]
Could you explain in some detail what you mean with "language transition" / "dynamic language"?
Are we talking about the language of the web content (such as: "if a web request is made from China, send a Chinese HTML page"). Or something completely different?

**Comment by francisxie** [comment]
Maybe I didn't describe it clearly, but how do you implement the template function.

You can replace the specified HTML tag with the corresponding variable

**Comment by bel2125** [comment]
I'm still not sure what precisely you mean by "template function":

There is a HTML standard tag `<template>`: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/template
This is done purely on the client side (in the browser), you don't need anything special in the server. Just put the HTML and javascript files there.

To replace tags in a HTML document is also possible in the client using JavaScript. I can check if I have an example somewhere, if this is what you try to do. Again, this is done only in the browser and you don't need to do something in the server - just put the html and js files there.

There is one way to replace tags in the server. For this, name the document `*.lp` (other file extensions are possible with some configuration), and use tags like this:
`<p><?= greeting ?></p>`
Here "greetings" is a variable that needs to be set before:
`<? greeting = "Hello" ?>` or you can use some conditions:
```Lua
<?
hour = tonumber(os.date("%H"))
if hour < 10 then greetings = "Good morning"
elseif hour > 18 then greetings = "Good evening"
else greetings = "Hello"
end
?>
```
Is this what you are looking for?

**Comment by francisxie** [comment]
The second one is what I want,But I don't know how.

**Comment by bel2125** [comment]
> The second one is what I want,But I don't know how.

1st) HTML tag <template>
2nd) replace tags in the client with javascript
3rd) replace tags in the server

How to replace some tags using javascript:

```javascript
<html>
<body>
<div class="dyn">
<p>{{sometext}}</p>
</div>
<script>

var data = {};
data.sometext = "new text goes here"

var regex = new RegExp('\{\{([^\}]*)\}\}', 'g');

var dynElms = document.getElementsByClassName("dyn");
var orig = [];
for (var i = 0; i < dynElms.length; i++) {
	orig[i] = dynElms[i].innerHTML;
}

for (var i = 0; i < dynElms.length; i++) {
	dynElms[i].innerHTML = orig[i].replace(regex, function(match, p1, offset, string) {return data[p1];});
}

</script>
</body>
</html>
```

**Comment by bel2125** [comment]
In case you want to replace tags in the server: See scripting documentation
https://github.com/civetweb/civetweb/blob/master/docs/UserManual.md#scripting
and *.lp files here https://github.com/civetweb/civetweb/tree/master/test

**Comment by francisxie** [comment]
thank you!
