### ISSUE TITLE
conn->host is leaked in get_request

### ISSUE THREAD

**Issue by jenik1** [civetweb/civetweb#827]
If connection handles more than 1 request, the 
conn->host is overwritten without releasing previous value.
 
Simple fix resolves the problem:
	//Fix memory leak:
	if (conn->host) 
	{
		mg_free((void *)conn->host);
		conn->host = NULL;
	}
	/* Is there a "host" ? */
	conn->host = alloc_get_host(conn);

**Comment by bel2125** [comment]
To help me identify this quickly: Are you referring to the current head version or the current release version + What line number?

**Comment by jenik1** [comment]
Sorry - I have missed that on master this bug was already fixed.
https://github.com/civetweb/civetweb/blob/master/src/civetweb.c#L17358
