### ISSUE TITLE
Does civetweb client support initiation of SNI when establishing a https connection?

### ISSUE THREAD

**Issue by duong2179** [civetweb/civetweb#833]
Our `mg_connect_client` output `SSL connection error` when connecting to our own `https`-enabled server to download a file (e.g. `https://my.own.server/some-data/video.mp4`):

```
[debug] Connecting to https://my.own.server/some-data/video.mp4
*** 1580548732.527937905 908730144948 140302910715648 mg_cry_internal_impl:3655: mg_cry called from sslize:15129: sslize error: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
[error] Failed to connect: SSL connection error
[error] Failed to download https://my.own.server/some-data/video.mp4
```

I then tested with `openssl s_client -connect my.own.server:443` and got similar error message:

```
$ openssl s_client -connect my.own.server:443
CONNECTED(00000006)
140735494824904:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:...
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 7 bytes and written 318 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
```

I suspected that the server didn't support `SNI (TLS Server Name Indication)` as using `-severname` option did make `openssl s_client` successfully connected to the server:

```
$ openssl s_client -connect my.own.server:443 -servername my.own.server
CONNECTED(00000006)
depth=3 C = US, ...
verify error:num=20:unable to get local issuer certificate
verify return:0
---
Certificate chain
...
---
Server certificate
-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
...
---
No client certificate CA names sent
---
SSL handshake has read 5349 bytes and written 480 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES128-GCM-SHA256
Server public key is 2048 bit
Secure Renegotiation IS supported
...
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES128-GCM-SHA256
    ...
    Verify return code: 0 (ok)
---
```

One possible solution is to enable `SNI` on the server but I wonder if there is a way to make `mg_connect_client` behave similarly to `-servername` option of `openssl s_client`?

**Comment by bel2125** [comment]
The server supports SNI, if you host multiple domains. 
Here is an example how to configure it: https://github.com/civetweb/civetweb/tree/master/examples/multidomain

I never checked it for the client ... probably it is not available now, but would be easy to add.

Do you need it for the server or the client or both?

**Comment by duong2179** [comment]
For now I just need it for client as the server is NOT made of civetweb. Thanks!

**Comment by duong2179** [comment]
I just found that `mg_connect_client_secure` does allow us to initiate SNI (by setting `host_name` in `mg_client_options `). Verified it worked. Thanks!
