### ISSUE TITLE
Question about discard_unread_request_data

### ISSUE THREAD

**Issue by helloray** [civetweb/civetweb#840]
I saw this function was added in #362 to fix a keepalive related issue. Suppose I want to check the content_length in my handler, if the content_length is too large, I don't want to handle this connection any more. I return an error and hope the connection is closed immediately. However, discard_unread_request_data will continue to read all of the request, this will waste a lot of time on an already dropped connection. My question is: is it necessary to do  discard_unread_request_data in this case?  If not, any suggestion to bypass it.

**Comment by helloray** [comment]
I suggest make below check before discard_unread_request_data. 
		if (!conn->must_close)
				discard_unread_request_data(conn);

**Comment by bel2125** [comment]
After checking the history - yes, I think this can be done without breaking the fix in the original PR.
Would you provide a pull request?

**Comment by helloray** [comment]
Please check PR #842. Thanks

**Comment by bel2125** [comment]
Thanks. Merged
