### ISSUE TITLE
run_as_user config problem

### ISSUE THREAD

**Issue by veselinovicst** [civetweb/civetweb#851]
When I start civetweb server as non root user using this configuration parameter I have problems accessing sqlite database. I am using lsqlite3 library in lua scripts that are used as REST API. Tried multiple stuff nothing helps, any suggestions ?

**Comment by bel2125** [comment]
Did you check the ownership and access rights of the sqlite database file?

**Comment by veselinovicst** [comment]
Yes, I even tried putting chmod 777 and changing a couple of different locations, it didn't help.

**Comment by bel2125** [comment]
Is the owner of the sqlite database file the same as the "run_as_user" user?

**Comment by bel2125** [comment]
Your problem case is like this: 
You start civetweb "non-root" user (let's call it "user1"), and start with "run_as_user" as another user (let's call it "httpuser").
right?

**Comment by veselinovicst** [comment]
Hmm, run_as_user is "user1" but I am logged as root user ie. I am starting civetweb as root user. Is it necesarry to start is as "user1"?

**Comment by veselinovicst** [comment]
Hmm, run_as_user is "user1" but I am logged as root user ie. I am starting civetweb as root user. Is it necesarry to start is as "user1"?

**Comment by veselinovicst** [comment]
Hmm, run_as_user is "user1" but I am logged as root user ie. I am starting civetweb as root user. Is it necesarry to start is as "user1"?

**Comment by bel2125** [comment]
> ... I am starting civetweb as root user. ...

No, you can of course start as root user and then run_as_user using a different user - that's actually the standard case. But in the original message above:

> When I start civetweb server as non root user ...

So, do you have an issue when you start as root or start not as root?
The "run_as_user" is different than root, right?
Who is the owner of the database file?

In order to give any qualified suggestion, I need to understand the exact situation.

**Comment by veselinovicst** [comment]
Okay, sorry for misunderstanding. 
I am starting the civetweb as root user. In the configuration run_as_user is different user (not root one) eg. "user1". I've tried putting root user as well as the "user1" user as the owner of the database file, and it didn't work in both cases.

**Comment by bel2125** [comment]
Just tested this with Ubuntu 18.04 LTS as root with `./civetweb -run_as_user user -document_root test", with the db owner "user", and it did work like expected with "http://localhost:8080/page.lp".

What system are you using? Can you reproduce this problem with the "page.lp" file in the test folder?

**Comment by veselinovicst** [comment]
Okay, I am using Debian system with some additional services running on it. I will try testing it as you suggested and will get back to you.

**Comment by veselinovicst** [comment]
Hey, sorry for not getting back to this lately. The issue was with the user rights of the folder where the db file was stored. Thank you for helping.
