### ISSUE TITLE
Windows exe-file version

### ISSUE THREAD

**Issue by christopheg** [civetweb/civetweb#852]
Hi,

Would it be possible to include the version number of the build in every produced exe-file?
We have an ansible role that installs civethweb on a Windows-server. Altough, there is currently no way to tell what the installed version on the server is, making an upgrade quite difficult.

I want to use this Ansible module:

> https://docs.ansible.com/ansible/latest/modules/win_file_version_module.html

I'm not familiar with your Windows build process, but there is a tool available that can include the version number after comilation:

> https://github.com/electron/rcedit

Thanks,

**Comment by bel2125** [comment]
I don't know how Ansible works ... probably it reads the version field from an embedded resource file?

CivetWeb knows it's version information in a dialog - but you probably need this accessible with the `win_file_version` function from your link: 

![image](https://user-images.githubusercontent.com/5619191/77192685-38b62800-6add-11ea-8837-cf694515d7c7.png)

I have an idea how this might work ... but better I post some executable here first, so you can test if this is what you need.

**Comment by christopheg** [comment]
If you send me some files, I will be happy to test them!

**Comment by bel2125** [comment]
The first method I tried did not work - you won't find the version number in the exe file properties.
The second method broke the automatic build process.

The third method - using rcedit - seems to work:
```
rcedit-x64.exe VisualStudio\Release\Win32\civetweb_lua.exe --set-product-version 1.13
rcedit-x64.exe VisualStudio\Release\Win32\civetweb_lua.exe --set-file-version 1.13
```

**Comment by christopheg** [comment]
> rcedit-x64.exe VisualStudio\Release\Win32\civetweb_lua.exe --set-file-version 1.13

This ons did the job!
It would be great if you could include it in the build proces.

**Comment by bel2125** [comment]
Post-Build step has been added
