### ISSUE TITLE
Is WSS with client certificate authentication supported in this library?

### ISSUE THREAD

**Issue by gou4shi1** [civetweb/civetweb#853]
It seems that `mg_connect_websocket_client()` does not support client certificate.
How to support it?

**Comment by gou4shi1** [comment]
ping

**Comment by bel2125** [comment]
You are right, the current API does not have an option for client certificates for websockets.
For HTTP requests, there is `mg_connect_client_secure`, but there is no equivalent function for websockets. A workaround using this function is possible, but I think we need to add a similar `mg_connect_websocket_client` API. Currently, the client interface is not complete, and some parts need redesign (#479).

**Comment by bel2125** [comment]
A new API function is available for this:

https://github.com/civetweb/civetweb/blob/ace251b5c171aba9aa2f3f2c264294f3ca770087/include/civetweb.h#L1461-L1469

**Comment by bel2125** [comment]
Did you check out the new API?
Is there anything else we can do here, or can we close this issue?

**Comment by gou4shi1** [comment]
Sorry for the late reply, but I can't see where you use client_options.client_cert.
