### ISSUE TITLE
API to parse query strings

### ISSUE THREAD

**Issue by gaborcsardi** [civetweb/civetweb#856]
Would it make sense to have a function for this?

**Comment by bel2125** [comment]
What about `mg_get_var` / `mg_get_var2`?
https://github.com/civetweb/civetweb/blob/ace251b5c171aba9aa2f3f2c264294f3ca770087/include/civetweb.h#L1110

Probably the [API documentation](https://github.com/civetweb/civetweb/blob/master/docs/api/mg_get_var2.md) should explicitly mention "query string" (not just "the URI in a GET call").

**Comment by gaborcsardi** [comment]
Yes, I think I actually saw that. But when writing a generic server for HTTP testing, I want to parse the whole query string, without knowing the variables included in it.

**Comment by bel2125** [comment]
A query string is more or less built like
`variableName1=variableValue1&variableName2=variableValue2&variableName3=variableValue3` - names and values are not necessarily unique.

What ANSI C API would you suggest for this?

In C you could use strchr/memchr followed by mg_url_decode. There is no "return a list" in C. Of course you could combine it with a C++ library defining "list". But if you are using additional C++ libraries, you might just as well pass the query string to a pattern matching library of your choice. The civetweb.c file does not force you to use any C++ library. 

How would an API look like, if you do not return any lists?
We could do something like 
```C
int /* success/failure ... index in string? */ mg_get_key(
    /* IN  */ const char * query_string, 
    /* IN  */ int key_index,
    /* OUT */ char * key_name,
    /* IN  */ size_t key_name_length,
    /* OUT OPTIONAL */ char * value,
    /* IN  OPTIONAL */ size_t value_length
);
```
And then you need to call this in a loop, until there are no more variables. But every call needs to parse the entire string. Would this be helpful?

**Comment by gaborcsardi** [comment]
I think it would be actually simpler to parse it in one shot. You could have a `struct query_params` type which has a buffer, the number of parameters, and list of pointers to the names and values. Something like this:

```c
struct query_params {
  char *buffer;
  size_t num_params;
  char** names;
  char** values;
};
```

Or instead of the last two you could also have a `struct query_param` that is similar to what you have for headers.

So here civetweb would allocate the data for you, and it probably makes sense to have another function to deallocate the data.

But if you think it would be better if they user allocated a buffer first, that's also fine. Then civetweb could have a function to query the size of the buffer, and the user would call that first.

**Comment by bel2125** [comment]
A `struct query_param` seems to be closer to other APIs - for example the headers.

I would prefer not to allocate memory in civetweb, and provide a "free" function. I think it is better if the user provides the buffer. However, here you have multiple dynamic dimensions - the number of list elements and the string length of each element.
However, you know the total length is the length of the query string. So you probably don't need to copy everything, but to have one query string as in-out parameter. The function would replace the & and = characters by terminating zeros and return pointers or indices where to find the key- and value names.

**Comment by gaborcsardi** [comment]
Yeah, that works as well, except that you cannot really transform the query string, because then the API is not idempotent, and also, some elements might be URL encoded, although I guess URL encoding only makes them longer.

It seems to me then that it better to let the user allocate a single buffer, and the decoded strings can be just packed in there. You could have another function that queries the size of the buffer, so the user would do it like this:

```c
struct query_params qp;
qp.buffer_size = mg_query_params_buffer_size(query_string);
qp.buffer = malloc(gs_size);
if (!qp.buffer) handle_out_of_memory();
ret = mg_query_params(query_string, &qp);
```

and then it is up to the user to `free()` the buffer.

**Comment by bel2125** [comment]
> except that you cannot really transform the query string, because then the API is not idempotent

You would work on a copy of the query string, of course, since the `query_string` member in the API is `const` anyway. 
I would tend to work with just one function, that either fills the output data, or calculates the required space (if the input buffer is NULL). 

I will post an interface proposal in the evening (in some hours).

**Comment by gaborcsardi** [comment]
Yeah, you can also combine the two functions, like many Windows API functions do, that's a good idea.

**Comment by bel2125** [comment]
Minimal version without any memory dynamic in civetweb (only one strdup in the user code).

```C
int mg_split_form_encoded(
  char * buf, // Input-output-buffer. Format may be an x-www-form-urlencoded http body or query string.
  struct mg_header form_fields[MG_MAX_FORM_FIELDS];
);

// Typical use:
{
  char * myBuf = strdup(request_info->query_string);
  struct mg_header myFields[MG_MAX_FORM_FIELDS];
  int numFields = mg_split_form_encoded(myBuf, myFields);
  for (int i=0; i<numFields; i++) {
    printf("%i\t%s\t%s\n", i, numFields[i].name, numFields[i].value);
  }
  free(myBuf);
}
```

Alternative with two variable size buffers ... but it cannot return if "buf_len" or "form_fields_len" needs to be larger.
```C
int mg_split_form_encoded(
  const char * in, // string to split. Might be an x-www-form-urlencoded http body or query string. 
  char * buf, // output buffer. In case in==NULL, this is used as in-out-buffer
  size_t buf_len, // input buffer size available, including terminating zero
  struct mg_header *form_fields;
  size_t form_fields_len;
);

// Typical use:
{
  char myBuf[1024]; 
  struct mg_header myFields[128];
  int numFields = mg_split_form_encoded(request_info->query_string, myBuf, 1024, myFields, 128);
  for (int i=0; i<numFields; i++) {
    printf("%i\t%s\t%s\n", i, numFields[i].name, numFields[i].value);
  }
}
```

`buf_len` needs to be `strlen(in)` (or a little less) and `form_fields_len` needs to be the number of `&` characters + 1.

**Comment by gaborcsardi** [comment]
I like the first one, but isn't a compile time constant like `MG_MAX_FORM_FIELDS` somewhat limiting?

**Comment by bel2125** [comment]
For HTTP headers, there is a similar limit:
`#define MG_MAX_HEADERS (64)`
64 is significantly oversized in practice - still it consumes 512 Bytes (32 bit) or 1024 Bytes (64 bit pointers) only. A variable size API would be far more complicated to use ... for saving some 100 Bytes.

If there is a reasonably oversized limit for `MG_MAX_FORM_FIELDS` as well, I think one could argue the same way as for headers. Special applications that - for whatever reason - need much more fields can still increase this constant at compile time. Only if there is no reasonably low limit, the size must be allocated dynamically - with a more complicated API.

What would you think would be a reasonable maximum for the number of field values submitted in a query string of body of a HTTP POST form message?

**Comment by gaborcsardi** [comment]
Oh, I don't want to save 100 bytes, I was more concerned about hitting the limit. But you are right, something like 64 is plenty.

**Comment by xtne6f** [comment]
Is `url_decode_in_place()` needed?
I think `mg_url_decode()` is already "in-place" capable. If not so, the following is not allowed:
```
	/* 1.3. decode url (if config says so) */
	if (should_decode_url(conn)) {
		mg_url_decode(
		    ri->local_uri, uri_len, (char *)ri->local_uri, uri_len + 1, 0);
	}
```

**Comment by bel2125** [comment]
Probably `url_decode_in_place()` can be reduced to

```C
static void
url_decode_in_place(char *buf)
{
    size_t len = strlen(buf);
    (void)mg_url_decode(buf, len, buf,  len+1, 1);
}
```

**Comment by xtne6f** [comment]
Although some `size_t`->`int` casts are needed, I also think so.

**Comment by bel2125** [comment]
Already available in the new API (since April).
