### ISSUE TITLE
Parse multipart data?

### ISSUE THREAD

**Issue by gaborcsardi** [civetweb/civetweb#858]
In the spirit of #856, would it make sense to have a parser for multipart data?

**Comment by bel2125** [comment]
[mg_handle_form_request](https://github.com/civetweb/civetweb/blob/master/docs/api/mg_handle_form_request.md)

Example:
https://github.com/civetweb/civetweb/blob/ace251b5c171aba9aa2f3f2c264294f3ca770087/examples/embedded_c/embedded_c.c#L357

**Comment by gaborcsardi** [comment]
Oh, thanks! I should search more carefully. 

Do you think it would make sense to add a function to parse multipart data that I have read out from the connection already, from just a buffer? I would want to have the request body both as a raw buffer, as is, and then also parse it.

AFAICT now I need to choose between the raw and the parsed data.

**Comment by bel2125** [comment]
Currently you need to choose: You can read the entire request "raw" using mg_read ***or*** you can use mg_handle_form_request to process a multipart message (or also url-encoded messages) on the fly. Multipart messages may become huge - several gigabytes, if you choose to upload a file big enough. The body might be larger than your available RAM. E.g. it is possible to upload a 10 GB file on a 32 bit machine with 2 GB RAM ... there is no way to store the entire request in memory first.
With the "mg_handle_form_request" API, you can choose to store it directly to disk, with just a few kB RAM consumption, independent from the file size.

There is an implementation that first reads the entire request, and then splits it. You will find it in the  handle_form.lua file in the test folder. The implementation is in Lua, not in C. I think somewhere in the commit history some years ago, there was another implementation in C ...? 
However, they have the disadvantage of first reading "everything", and that might be a lot.

**Comment by gaborcsardi** [comment]
I understand that reading out the whole request is bad for a generic web server. For my use it makes sense, however it makes sense because I know that the body is not very big, as I am also controlling the client side.

But I get it that this is not something that is useful for a lot of people, so feel free to close this. Thanks!

**Comment by bel2125** [comment]
Probably you can save some work by starting from the already existing Lua implementation.

**Comment by gaborcsardi** [comment]
Oh, I already found an implementation in R, which is the embedding language, so all is fine. :)

Feel free to close this.
