### ISSUE TITLE
query string is always null

### ISSUE THREAD

**Issue by theprogrammermachine** [civetweb/civetweb#859]
i do :

const char* query = mg_get_request_info(conn)->query_string;

and query is always null.

**Comment by bel2125** [comment]
What URL?
What CivetWeb version?
Where do you call this function?

**Comment by theprogrammermachine** [comment]
http://localhost:8884/query?hello=world
Version 1.12
I call the code mentioned above inside a request handler .

**Comment by bel2125** [comment]
It actually did work in the unit test for Windows and Linux (Ubuntu) - with a code like this:

```C
const struct mg_request_info *ri;
ri = mg_get_request_info(conn);
strcmp(ri->query_string, expected)
```

What operating system?
Are the other fields of `struct mg_request_info` correct?

**Comment by theprogrammermachine** [comment]
yes other fields are correct except request_uri which does not contain query string too.
i'm running the program in ubuntu 18.04.

**Comment by bel2125** [comment]
Here is some example code of a handler that does work with a query string:

https://github.com/civetweb/civetweb/blob/085e10c309fe63b8e3f61efd3d58e7cc9e8f3051/examples/embedded_c/embedded_c.c#L141

I tested it with Ubuntu 18.04 running in WSL (Windows Subsystem for Linux).

Using Firefox wiht `http://localhost:8888/A/B?qs=test` returns

```
This is the AB handler.

    request_method = GET
    request_uri = /A/B
    local_uri = /A/B
    http_version = 1.1
    query_string = qs=test
    remote_user = (null)
    remote_addr = ::1
    remote_port = 49787
    is_ssl = 0
    num_headers = 8
        Host = localhost:8888
        User-Agent = Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0
        Accept = text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
        Accept-Language = en-US,en;q=0.5
        Accept-Encoding = gzip, deflate
        Connection = keep-alive
        Upgrade-Insecure-Requests = 1
        Cache-Control = max-age=0
```

**Comment by theprogrammermachine** [comment]
there's something wrong with mg_get_request_info.
i tested :

const struct mg_request_info *ri;
ri = mg_get_request_info(conn);

and checked "ri" fields and some of them were wrong . for example : http version was null and uri was "1.1" and header count was wrong and etc .

**Comment by bel2125** [comment]
Are you sure the version of the civetweb.h file matches the version of the civetweb.c (or the compiled libcivetweb)?

**Comment by theprogrammermachine** [comment]
sorry . it was my mistake . i used libhttp header file with civetweb binaries mistakenly .
