### ISSUE TITLE
Pattern for shutting down threads

### ISSUE THREAD

**Issue by gaborcsardi** [civetweb/civetweb#862]
I have a use case where the `begin_request` callback does some potentially long processing before sending out the response. This is problematic when the application decides to shut down the web server, because `mg_stop()` will wait for all threads to exit and I don't want to wait that long... 

It seems to me that one reasonable thing I can do is to make `begin_request` cooperative, and exit when some global stop flag is set. (Or something similar with cancellation points would be better, actually). Ideally I would use the already existing `stop_flag` for this, but that is not part of the API. 

I can create my own stop flag as well, but then I have a race condition between my trying to ask the threads to quit using my own stop flag, and then calling `mg_stop()`, because civetweb might create more worker threads before its `stop_flag` is in effect. (Should not be very bad in practice, I can probably live with this.)

Is there a pattern I am missing?

**Comment by bel2125** [comment]
Shutting down a running web server is not an easy task. Whatever shutdown strategy you choose, there seems to be always one particular problematic use case. Should you wait until all connections are closed, should you close the connections gracefully of forcefully, ...

I tend to not use `begin_request` when using a handler callback is possible as well. However, this will not affect the shutdown problematic. If there is a lengthy operation, I tend to just start it asynchronously in another thread or process, and immediately return some intermediate result, like "processing started". Then the client should ask again to see a percentage of completion, and finally a result. An elegant way would be to create a temporary URL for the running operation and return a a "see other" when starting it. The client only sees "short" operations - no long polls.
Or I use websockets to send some intermediate progress.

But this all depends on your use case. It depends on how your "potentially long processing" is done. Is it in itself blocking (e.g., waiting for another server), is it just using CPU (scientific computation) or creating a lengthy report from a database (local or remote), or re-encoding a file it received from the client, or ...? Does it make sense to show a progress bar? Could you maybe send first results using chunked transfer? Is the client actually a browser or another application - an if it is a browser, is the request URL something you load directly, as a reference or using JavaScript?

I don't know if it makes sense to discuss this in detail. If the question is just "could we export the stop flag using some API": Yes we could. The result would be just the same as if you have your own stop flag duplicated your self defined `user_data` struct, and set this flag when you call `mg_stop` - exporting it from the civetweb API might be more elegant, but the result for your callback would be the same.

**Comment by gaborcsardi** [comment]
Thanks for the thoughts. As I am developing a general tool, there is no single use case, so there are no easy answers here, I am afraid. Choosing the API is not up to me.

> The result would be just the same as if you have your own stop flag duplicated your self defined user_data struct, and set this flag when you call mg_stop - exporting it from the civetweb API might be more elegant, but the result for your callback would be the same.

Well, except that at least no race condition, i.e. civetweb would not start processing another request after I set the stop flag. But yeah, that's not a huge difference in practice.
