### ISSUE TITLE
WebSocketHandler HandleData bits parameter nibbles flipped

### ISSUE THREAD

**Issue by kevinlrak** [civetweb/civetweb#864]
https://github.com/civetweb/civetweb/blob/87563818d8e632c11c09be223a4d3867774a0ff2/include/CivetServer.h#L190

The [RFC](https://tools.ietf.org/html/rfc6455#section-5.2) shows the opcode in bits 4-7 of the first byte of the frame. The `bits` parameter received from `CivetWebSocketHandler`'s `handleData` method has the opcode in bits 0-3.

**Comment by bel2125** [comment]
I think you are counting bits in reverse order.
Bit 0 = 0x80 in the first byte = FIN flag
Bit 1 = 0x40 in the first byte = RESERVED, must be 0
Bit 2 = 0x20 in the first byte = RESERVED, must be 0
Bit 3 = 0x10 in the first byte = RESERVED, must be 0
Bit 4 = 0x08 in the first byte = Part of the opcode (x8)
Bit 5 = 0x04 in the first byte = Part of the opcode (x4)
Bit 6 = 0x02 in the first byte = Part of the opcode (x2)
Bit 7 = 0x01 in the first byte = Part of the opcode (x1)

e.g. 0x09 = Bit 4 + Bit 7 = Websocket PING

**Comment by kevinlrak** [comment]
You are correct! Digging a little deeper I see that ["the bit labeled 0 is the most significant bit"](https://tools.ietf.org/html/rfc1700#page-3) which seems a bit counter-intuitive.

I can confirm that for closing a connection I see `bits` value of `0x88` and when receiving text data from a connection I see `bits` value of `0x81`. Given the above, that seems correct.

I'm closing this issue as my own misunderstanding. Thanks for your reply!
