### ISSUE TITLE
Configuring created threads

### ISSUE THREAD

**Issue by epkugelmass** [civetweb/civetweb#866]
I'm running CivetWeb as an embedded server. I'd like a little more control over how threads are configured (specifically around core affinity) than I think can be supported using the existing API (obviously, I'm happy to be mistaken!).

I think this can be done in one of at least three ways:
1. Create a new callback with a signature similar to `mg_start_thread_with_id` to allow a client of CivetWeb to take responsibility for all aspects of thread creation. This seems fairly invasive to me.
2. Clarify that the `init_thread` callback is always by the newly created thread, so `pthread_self()` can be called and any affinity can be set in the callback.
3. Provide a new callback `init_thread_with_id` that passes the `pthread_t` of the newly created thread.

If it doesn't hamper future implementation too much, I think option 2 is decent.

Option 2 would have also resolved https://github.com/civetweb/civetweb/issues/534

**Comment by bel2125** [comment]
Yes, `init_thread` is always called on a newly created thread. It can be used to initialize the thread local storage, change the thread priority or thread affinity, if required.

**Comment by bel2125** [comment]
Documentation has been updated (in April).
