### ISSUE TITLE
CORS options C++ embedded

### ISSUE THREAD

**Issue by uro1012** [civetweb/civetweb#867]
Hi everyone,

I have two BeagleBones which have their own Civet server. I want to retrieve some data in JSON format from the second one to the main. Unfortunately, I get some error due to the CORS when trying to retrieve data with the _$.getJSON_ method (my web knowledge is limited). I tried several tricks found online, but none seems to work for me.

When setting up my server, I have the following code:
```
std::vector<std::string> options = {
      "listening_ports", toString(port),  // Port to listen to
      "document_root", documentRoot,      // Public html documents root path
      "num_threads", "10",                // Maximum number of threads (and max number of simulatneous requests)
      "enable_directory_listing", "yes",  // Show directory listing if no index file present
      "static_file_max_age", "0"          // Disable static page caching
    };

  server = new CivetServer(options);
```

To retrieve my data, I use this:
```
$.getJSON('http://192.168.2.5:8081/dataSPMC', function(data) { })
   .success(function(data) {
     refreshSPMC(data);
   })
   .error(function() {
     console.log("error refreshing data SPMC");
   });
```

I tried to add some CORS parameters (headers, methods and origin), but nothing changed. How should I set up my servers in a way that they can exchange data between them? My primary server has an IP address _192.168.2.2_ and the second one _192.168.2.5_

**Comment by xtne6f** [comment]
Let's open DevTools (developer tools) on your browser, then execute the `getJSON()`. If its response header from your second server does not contain `Access-Control-Allow-Origin: *` or `Access-Control-Allow-Origin: http://192.168.2.2:{listening_ports of primary server}`, the `getJSON()` request will not succeed.

**Comment by grunk** [comment]
Here an example of response which will allow CORS : 

```
mg_printf(conn, "HTTP/1.1 %d %s\r\nAccess-Control-Allow-Origin: *\r\nContent-Type: %s\r\n\r\n", status, statusDescription.c_str(), content_type.c_str());
mg_printf(conn, "%s", content.c_str());
mg_printf(conn, "\r\n");
```

As specified by @xtne6f  the key here , is the value of Access-Control-Allow-Origin header

**Comment by uro1012** [comment]
I changed the parameters of both servers (shared file) to the following:

```
std::vector<std::string> options = {
      "access_control_allow_origin", "*", // Allow access from any other server
      "listening_ports", toString(port),  // Port to listen to
      "document_root", documentRoot,      // Public html documents root path
      "num_threads", "10",                // Maximum number of threads (and max number of simulatneous requests)
      "enable_directory_listing", "yes",  // Show directory listing if no index file present
      "static_file_max_age", "0"          // Disable static page caching
    };
```

When I use `$.getJSON('http://192.168.2.5:8081/dataSPMC')` via the debug console (Firefox), I get the error that the header _Access-Control-Allow-Origin_ is missing. But when I resend it from the connection overview, it can retrieve the data in JSON without the error message. Any idea what is happening and how to solve it?

**Comment by bel2125** [comment]
There are three configuration parameters for CORS: [see access_control_allow_* in the UserManual](https://github.com/civetweb/civetweb/blob/master/docs/UserManual.md#access_control_allow_headers)

All are set to allow CORS by default. Preflights are handled automatically, and all static files should have the proper CORS headers. However, if you have your own script or callback, you have to add the `Access-Control-Allow-Origin: *` in the response of your script/callback yourself.

**Comment by uro1012** [comment]
So if I understand this correctly, the default settings of the server already allow to send data to other IP adresses. It is just my JavaScript request which must have the header `Access-Control-Allow-Origin: *`, which the `$.getJSON()` method does not have. Is this correct?

I will try this again later this week, when I got time for it.

**Comment by xtne6f** [comment]
There is nothing else to do on client (JavaScript) side.
If the "dataSPMC" on your server is script or callback (isn't it?), you have to add the header on your server's script or callback as @bel2125 specified.

Then if you reload the page, once you had better to clear the browser cache. Since modern browser's cache is so sticky, an old response might remain as it is.

**Comment by bel2125** [comment]
Access control is a little more complex. I can't tell precisely what went wrong in your case, without knowing exactly what resources are stored on domain "A" or "B", what resource refers to what other resource and what methods are used.

Can you find your situation in this documentation:
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Comment by uro1012** [comment]
Hi everyone,

Thanks to your help, I could finally solve my problem. It was the response of the server which did not include the CORS header at all (did not code this part myself). I was looking in the wrong parts of the project this whole time, due to my limited knowledge in computer network.
