### ISSUE TITLE
mg_printf is unable to handle HTTP content with C format characters

### ISSUE THREAD

**Issue by Ymitrofanov** [civetweb/civetweb#874]
Hello!
I'm using C API of civetweb (version civetweb-1.10) on Linux with gcc version 4.8.5.  I found the issue when mg_printf is unable to handle http content with C format characters %7C.
I try to pass the string with a response to HTTP client, which contains JSON with text (100 200%s 300_new_%7C:POS%7CPOS2), but mg_printf doesn't handle it propperly and returns -1. If I try (100 200 300_new), all works well, client receives a response successfully.
I investigated calls using gdb and breakpoints from mg_printf to alloc_vprintf2 and found out that alloc_vprintf2 calls vsnprintf_impl and passes to it my string as a format string, but my string contains %7C and print fails because of it. I've tried it without %7C - alloc_vprintf2 works well in this case. According to XSI-extension in Single Unix standard, %C is equivalent to wint_t.
I cannot change my string, removing or escaping format characters from it, because this is a part of needed information for client.
So, how should I use civetweb API to handle it, or is there a fix or workaround?
Thank you!

**Comment by bel2125** [comment]
Could you post one line of C code, that causes this problem? 

Probably you just need to pass it as content instead of as format specifier.

**Comment by Ymitrofanov** [comment]
Yes, I found bug in my code, this is exactly as you wrote.
bug: if (mg_printf(foundProfile->m_conn, mg_prnt_str.c_str()) < 0)
fix: if (mg_printf(foundProfile->m_conn, "%s", mg_prnt_str.c_str()) < 0)
Thank you!
