### ISSUE TITLE
Ability to return arbitrary response code while writing response body

### ISSUE THREAD

**Issue by nanonyme** [civetweb/civetweb#878]
mg_send_http_ok allows writing a response using mg_write or mg_send_chunk. However, it always uses response code 200. It would be nice to be able to also return other response codes not limited to successful ones. (eg dynamic error pages) This seems currently not supported by the API.

**Comment by bel2125** [comment]
The `mg_send_http_ok` indeed always returns "200 OK" - "ok" is defined as 200.
Depending on the status code, there may be other functions like `mg_send_http_redirect` (for Status 30x). Or `mg_send_http_error` (meant for 4xx and 5xx, but the function will accept any 3-digit number).

Depending on your exact needs, one of these functions might work or not.


I think there is a new API currently in a development branch, that would allow what you asked for:

https://github.com/civetweb/civetweb/blob/9aa8192ebae642102782b4153bb362371037a3b2/src/response.inl#L31-L42

**Comment by bel2125** [comment]
The `mg_response_header_start` is already released since quite some time.
We just forgot to close this issue.
