### ISSUE TITLE
Feature request: Add callbacks before server starts

### ISSUE THREAD

**Issue by pfeatherstone** [civetweb/civetweb#879]
Currently, the handlers have to be added after the web server starts. This means requests or websockets can momentarily be ignored at start up. It would be great if mg_start could be separated into: mg_create and mg_start

**Comment by bel2125** [comment]
I understand the problem, but I would prefer if we can find a solution that is not an incompatible change to the current interface.
Would it be possible to add your handler in the `init_context` callback:

https://github.com/civetweb/civetweb/blob/d4509f557690678ac09e326aba0555aab9924a57/include/civetweb.h#L371-L375

You already have the `struct mg_context *` required for `mg_set_request_handler`. The server is already initialized, except for the master thread (required for accepting connections) and the worker threads (responsible for handling request). From a first check, `mg_set_request_handler` can be called here, although it needs a `const` cast.

**Comment by bel2125** [comment]
Did you check if this callback fulfills your requirements?
Can we close this issue?

**Comment by pfeatherstone** [comment]
Yes thank you
