### ISSUE TITLE
question: ssl without filesystem

### ISSUE THREAD

**Issue by xhpohanka** [civetweb/civetweb#880]
Hello,

I'm checking if I can use SSL in civetweb together with `NO_FILESYSTEM`. By brief look at code I think that there is no support for getting cerificates from memory buffers, am I right?

I would like to use civetweb with wolfSSL on Zephyr.

best regards
Jan

**Comment by bel2125** [comment]
It is possible to provide a SSL context externally instead of letting CivetWeb initialize it. Then it is up to your code to provide the certificate.
I don't know your exact configuration, but you might have a look on `SSL_ALREADY_INITIALIZED` and the callback `init_ssl` passed to mg_start.
``` 
	/* If callback returns 0, civetweb sets up the SSL certificate.
	 * If it returns 1, civetweb assumes the calback already did this.
	 * If it returns -1, initializing ssl fails. */
```

**Comment by xhpohanka** [comment]
I will check it. That might be the way, thanks.
