### ISSUE TITLE
CivetServer::GetPostData will clear mg_connection buf data?

### ISSUE THREAD

**Issue by shizheng163** [civetweb/civetweb#881]
hi, i use follow interface to get http request body info, and first get is success, but later tried is failed, did it right?
```
std::string CivetServer::getPostData(struct mg_connection *conn) 
```
and i want to get mg_connection->buf at outside of the civetweb, but i don't get it. it is internal struct.
how can i get it and print the http request content?
i use civetweb version is 1.12.

**Comment by bel2125** [comment]
Did you have a look at the example: https://github.com/civetweb/civetweb/blob/master/examples/embedded_cpp/embedded_cpp.cpp#L161
Essentially it uses the C API funciton `mg_read` to get the body data, and you can only read this data once. `getPostData` essentially does the same - it reads the data once and returns it: https://github.com/civetweb/civetweb/blob/master/src/CivetServer.cpp#L555
Once it's read, it's gone.

The C++ wrapper class only exposes a small subset of all features of the full C interface (civetweb.h), and new features are not added automatically to the C++ wrapper. If you need something special, you are often better served with the C API.

**Comment by shizheng163** [comment]
ok, I already readed above code, thank your reply.
I suggest you can provide a new interface to get request info as string. 
I want to only print the request info string sometimes. but after print, it's buf will clear. it is not convenience.

**Comment by xtne6f** [comment]
For example, if the request body is huge, does the new interface hold the huge buffer until connection closed? I can't find its necessity.

**Comment by shizheng163** [comment]
ok, thank your reply. i knowned.

**Comment by bel2125** [comment]
You could easily create a function on your own by overloading / creating a derived class. This can have a member "string postData". You need to take care when to free this on your own - you probably know this in the context of your application. A library cannot know it and must make some assumptions that might be wrong.
Anyway, the C++ wrapper only works well for the case of "small" POST requests (small = they fit in memory). If your POST body holds a big file (~10 GB video upload), it won't work out - while it will work with the more general case or using "mg_read".

**Comment by shizheng163** [comment]
ok, thank you very mush
