### ISSUE TITLE
Keep alive bug (?)

### ISSUE THREAD

**Issue by DavidPDev** [civetweb/civetweb#889]
After many days of testing I have detected that the keep-alive internal flag stops working after some time (depends on the number of working threads)
I will try to explain the problem:

On `process_new_connection` function:

```
/* NOTE(lsm): order is important here. should_keep_alive() call
		 * is using parsed request, which will be invalid after
		 * memmove's below.
		 * Therefore, memorize should_keep_alive() result now for later
		 * use in loop exit condition. */
		/* Enable it only if this request is completely discardable. */
		keep_alive = STOP_FLAG_IS_ZERO(&conn->phys_ctx->stop_flag)
		             && should_keep_alive(conn) && (conn->content_len >= 0)
		             && (conn->request_len > 0)
		             && ((conn->is_chunked == 4)
		                 || (!conn->is_chunked
		                     && ((conn->consumed_content == conn->content_len)
		                         || ((conn->request_len + conn->content_len)
		                             <= conn->data_len))))
		             && (conn->protocol_type == PROTOCOL_TYPE_HTTP1); // *** conn->protocol_type==-1 ***

		if (keep_alive) {
			/* Discard all buffered data for this request */
```

The `conn->protocol_type` variable "sometimes" is set to -1, so the keep_alive is disabled from now on.

Why is `conn->protocol_type` set to -1?. This line does it:

```
		if (ebuf[0] != '\0') {
			conn->protocol_type = -1;
```

This is because sometimes the ebuf is containing the "No data received" (get_message function). I'm not sure why is this behavior but after debbuging it happens.

Workaround:
I think the `conn->protocol_type` variable should be initialized somewhere.
I have added the following line and now it is working as expected but I'm not sure if I am missing something, as I don't understand all the CivetWeb logic.

On `init_connection` function:

```
	/* Important: on new connection, reset the receiving buffer. Credit
	 * goes to crule42. */
	conn->data_len = 0;
	conn->handled_requests = 0;
	mg_set_user_connection_data(conn, NULL);

	conn->protocol_type = 0; // *** INITIALIZE protocol_type  ***

#if defined(USE_SERVER_STATS)
	conn->conn_state = 2; /* init */
#endif
```
After adding this initialization line all seems to be working for me, but I'm not sure if this is the way to fix it.

It's very easy to reproduce this "bug", just with a minimal http server example using a few number of threads (example: "num_threads", "3"), and in the response showing the current thread (in Windows GetCurrentThreadId()), the working thread with the same response should be always using the same threadId.

I can prepare a test project if needed.

**Comment by bel2125** [comment]
Since the "protocol_type" is rather new, there might indeed be an undiscovered problem there.
I will have a look.

**Comment by bel2125** [comment]
This issue has been solved in the code a long time ago. For whatever reason we never closed it,
