### ISSUE TITLE
Can' set request_timeout_ms for websocket client.

### ISSUE THREAD

**Issue by gou4shi1** [civetweb/civetweb#891]
Will `pull_inner` and `push_inner` block forever?

**Comment by gou4shi1** [comment]
Correct me if I'm wrong, without request_timeout, if mg_websocket_write return error, mg_websocket_close_handler should also be called because `recv` should also return error?

**Comment by bel2125** [comment]
CivetWeb uses nonblocking sockets, and a timeout in pull_inner and push_inner.
Unfortunately the client interface cannot handle all options like the server interface - this is a well known issue: #479
There is an experimental interface `mg_connect_client2` that should accept the same configuration options as the server, including timeouts, but this is not yet completed. So it will use default timeouts.

Regarding your second question: I don't know the use case / context now. Do you mean, if you are using a websocket client, and call mg_websocket_write with the conn handle? But mg_websocket_write will call push_inner, reading functions will call pull_inner.

**Comment by gou4shi1** [comment]
> CivetWeb uses nonblocking sockets, and a timeout in pull_inner and push_inner.

There is a while loop in `pull_inner`/`push_inner`, if timeout is the default value (-1), it seems to loop forever?

**Comment by bel2125** [comment]
I am still not sure what particular usecase you mean. Could you maybe post a call stack?
The REQUEST_TIMEOUT configuration defaults to 30000 ms.
Passing -1 to `mg_poll` will cause a problem - it will either return success or an error, probably due to a timeout in the TCP socket layer (that could be some hours).

**Comment by gou4shi1** [comment]
```
static int
push_all(struct mg_context *ctx,
         FILE *fp,
         SOCKET sock,
         SSL *ssl,
         const char *buf,
         int len)
{
	double timeout = -1.0;
	int n, nwritten = 0;

	if (ctx == NULL) {
		return -1;
	}

	if (ctx->dd.config[REQUEST_TIMEOUT]) {
		timeout = atoi(ctx->dd.config[REQUEST_TIMEOUT]) / 1000.0;
	}
```
For websocket client, I think ctx->dd.config are `0`?

**Comment by bel2125** [comment]
There is `mg_connect_websocket_client` -> `mg_connect_websocket_client_impl` -> `mg_connect_client_impl`, and with an additional `struct mg_client_options` also `mg_connect_websocket_client_secure` -> `mg_connect_websocket_client_impl` -> `mg_connect_client_impl`. None of them allows you to set a timeout. This is a known restriction of the API: #479
The unfinished new interface `mg_connect_client2` will allow you to set all options - but it is not finished yet (for several reasons).

> For websocket client, I think ctx->dd.config are null, then timeout is -1.0?

I think you are right. Then the timeout is defined by the operating system: After quite a while without any network traffic (could be hours), a timeout will cause a socket function to return an error, and the civetweb client loop stops.
As a quick fix, we should probably use a lower default timeout.
On the long term, I think only a new API (#479) will help.
