### ISSUE TITLE
Would be nice to declare as many CGI interpreters we need

### ISSUE THREAD

**Issue by eanon** [civetweb/civetweb#892]
Hello, As a lot of us, sometimes I have to stick with Windows while my staging and prod environments are still with Linux... So, recently I searched a quick and easy way (no need for performance) to easily handle any kind of CGI behind Nginx in Windows.  For PHP, there's php-cgi.exe out of the box, but for the other languages, it's another story. After some fails with different FastCGI wrappers/listener (crash and bugs) and knowing I absolutely need a light solution (eg. no Apache), I finally chose CivetWeb because of its nice cgi_interpreter option in its configuration. so, this is the positive point :)

The negative one is that I would prefer to avoid changing every shebang lines here and there when I'm in Windows and I have to support multiple types of CGI; at least Perl and C ones. So, as a quick and dirty hack, I simply wrote this Windows shell script today (to indicate as cgi_interpreter of course):

```batch
@echo off
:: CGI-Switch for CivetWeb - Eric Lequien Esposti / 2020-07-09
:: USE: set as cgi_interpreter in CivetWeb conf to drive any call to right interpreter.
:: LOG: logfile will be created in CivetWeb dir (or beside batch when invoked outside CivetWeb)
:: LIMIT: handles Perl and compiled (eg. C, C++) CGI only; expandable later if needed.
:: TIP: no need to take care of missing CGI target since CivetWeb does this checking upstream.
:: WARNING: due to its lack of robustness and slowness, it's not designed to be used in prod!
setLocal enabledelayedexpansion
set log=%~n0.log
set perl=c:\perl\perl\bin\perl.exe

cd "%~dp0"
if "%~x1" == ".pl" (
  echo %date% %time% - Perl CGI: %1 >> %log%
  %perl% %1
) else if "%~x1" == ".cgi" (
  set c=0
  for /f "delims=|" %%i in (%1) do (
    set /a c=!c!+1
    if !c! leq 1 set "shebang=%%i"
  )
  echo.!shebang! | findstr /c:"perl">nul
  if !errorlevel!==0 (
    echo %date% %time% - Perl CGI: %1 >> %log%
    %perl% %1
  ) else (
    echo %date% %time% - Bin CGI: %1 >> %log%
    %1
  )
) else (
  echo %date% %time% - Bin CGI: %1 >> %log%
  %1
)
```

So, IMHO, maybe it would be nice to be able to indicate a list of extension-interpreter associations from within CivetWeb conf itself, or, even, beyond, CivetWeb could be able to determine the right type when the extension is ambiguous (e.g. .cgi that I considered language agnostic here)... Well, low priority I think, but an idea in the pipe...

However, nice Civet! 

--
Windows 7 x86_64 + Nginx 1.18.0 x86 + CivetWeb 1.12 x86

**Comment by bel2125** [comment]
Would it be helpful to not have the `cgi_*` block of settings not just once, but multiple times:

![image](https://user-images.githubusercontent.com/5619191/87158021-622ed580-c2bf-11ea-8893-b65f7c9ec265.png)

To have a `cgi2_interpreter`, `cgi3_interpreter` and `cgi4_interpreter`, with corresponding environment, pattern, timeout and args?

**Comment by eanon** [comment]
Yes, it would! Or in the spirit of what done for add_domain, it could be multiple add_interpreter, each relying to an extra conf (eg. perl.conf, python.conf) that would provide detail as cgi_interpreter and cgi_extension (or cgi_type).

**Comment by bel2125** [comment]
An implementation allowing up to 4 cgi interpreters is available in the current master.
Tests and documentation still missing.

**Comment by bel2125** [comment]
The V1.14 release has this feature, and the missing documentation has been added.
