### ISSUE TITLE
issues on zephyr

### ISSUE THREAD

**Issue by xhpohanka** [civetweb/civetweb#895]
Hello, I have some issues with civetweb on zephyr which I summarized here...
https://github.com/zephyrproject-rtos/zephyr/issues/27020

**Comment by bel2125** [comment]
I try to provide some details how civetweb works regarding buffers and threads - but I am not a Zephyr expert.
In fact I basically merged some changes from Zephyr developers after a brief review, checking it will not harm any existing features on currently supported platforms - but without checking if it works on Zephyr.
Probably some changes of some parameters after this initial merge are required.

**Comment by xhpohanka** [comment]
I have closed the referenced issue. There is curently come work on zephyr regarding the civetweb samples, so we will see :)
