### ISSUE TITLE
state variable in t_ws_client structure in embedded_c.c example

### ISSUE THREAD

**Issue by sdcsystems** [civetweb/civetweb#896]
In the t_ws_client structure (embedded_c.c example) there is an integer variable called `state`.  
```
struct t_ws_client {
	struct mg_connection *conn;
	int state;
} static ws_clients[MAX_WS_CLIENTS];
```
At various points in the Websocket handler functions it gets set so numeric values.  What do the various values signify?

-Andy.

**Comment by bel2125** [comment]
`WebSocketConnectHandler` sets state to 1 ("connected")
the connect handler can accept or reject a connection, but it cannot send or receive any data at this state

`WebSocketReadyHandler` sets state to 2 ("ready")
reading and writing is possible now

`WebSocketCloseHandler` sets state to 0
the websocket is about to be closed, reading and writing is no longer possible
this callback can be used to cleanup allocated resources

`InformWebsockets` is called cyclic every second, and sends some data (a counter value) to all websockets in state 2

**Comment by bel2125** [comment]
The same description as above has been added as comment to embedded_c.c
