### ISSUE TITLE
build civetweb with musl failed with cmake

### ISSUE THREAD

**Issue by laoshaw** [civetweb/civetweb#900]
trying to build civetweb with musl/cmake and it failed(CC=musl-gcc cmake .. && make), note if I do 'CC=musl-gcc make' directly it builds fine.

```
In file included from /usr/include/ctype.h:25,
                 from /home/userx/civetweb-1.12/src/main.c:75:
/usr/include/features.h:461:12: fatal error: sys/cdefs.h: No such file or directory
  461 | #  include <sys/cdefs.h>
      |            ^~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/CMakeFiles/civetweb-c-executable.dir/build.make:63: src/CMakeFiles/civetweb-c-executable.dir/main.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:916: src/CMakeFiles/civetweb-c-executable.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
```

mucl claims it's not good to use cdefs.h in the code directly: https://wiki.musl-libc.org/faq.html  (search cdefs.h in that page)

this is from /usr/include/features.h on ubuntu 20.04:

```
* This is here only because every header file already includes this one.  */
#ifndef __ASSEMBLER__
# ifndef _SYS_CDEFS_H
#  include <sys/cdefs.h>
# endif
```

**Comment by bel2125** [comment]
I cannot see any direct include of `<sys/cdefs.h>` in civetweb.c or main.c
Even a full text search for `cdefs` in all files (`*.*`) returns just one comment line in sqlite3 (containing `** new function.  But the FuncDefs for built-in functions are read-only.`)

Using `CC=musl-gcc && make` (from the civetweb repository root directory, after `make clean`) works for me.
Probably there is a bug in `cmake`? Does is support musl-gcc?

**Comment by laoshaw** [comment]
it's about cmake, Makefile works fine.

I think it's from main.c --> ctype.h --> features.h --> cdefs.h

**Comment by bel2125** [comment]
But ctype.h is part of the standard C library, so it's definitely perfectly allowed to include it.

Could it be some inconsistency in your cmake build system?
I tested the following
```sh
cd output
rm -rf *
export CC=musl-gcc
cmake ..
make
```
--> this works for me

```
cmake --version
```
--> `cmake version 3.10.2`

**Comment by laoshaw** [comment]
I'm on ubuntu 20.04 and it has cmake 3.16.3.

I can build with gcc-10 just fine(though with quite a lot warnings).

with musl-gcc it now reports stdio.h errors(after I added gcc-multilib):

/usr/include/stdio.h:52:9: error: unknown type name ‘__gnuc_va_list’

so cmake is somehow using gcc's include path instead of musl-gcc's own include header files.

Again, use Makefile directly it works fine here.

**Comment by bel2125** [comment]
I'm still using Ubuntu 18.04 LTS - right now I don't have a 20.04 at hand to test it there.

```
$ musl-gcc --version
cc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ gcc --version
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ clang --version
clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```


```
$ export CC=musl-gcc
$ cmake  .. -DCIVETWEB_ENABLE_SSL=NO
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/musl-gcc
-- Check for working C compiler: /usr/bin/musl-gcc -- works
-- Detecting C compiler ABI info
...
```

In contrast to
```
$ export CC=clang
$ cmake  .. -DCIVETWEB_ENABLE_SSL=NO
-- The C compiler identification is Clang 6.0.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/clang
-- Check for working C compiler: /usr/bin/clang -- works
-- Detecting C compiler ABI info
...
```

I did a build without any C++ parts, only C. If you are using C++, you probably need to set a C++ compiler by `export CXX=musl-???` as well (don't know the name of this compiler).

But I have to admit, I'm absolutely not an expert on cmake. It works on my PC, but I think I cannot provide any useful hint for remote diagnosis. Maybe "check if there is something suspicious in the cmake output"?

**Comment by laoshaw** [comment]
I was using gcc-10 on ubuntu 20.04 which is not the default, which gave me some troubles here and there, I changed it back to the default gcc-9, now cmake works with civetweb, I would call this a gcc-10 related issue instead of civetweb's, thus close it. Thanks for the help!
