### ISSUE TITLE
Civetweb Fails to Compile (using WITH_LUA_VERSION=504)

### ISSUE THREAD

**Issue by JoshuaPK** [civetweb/civetweb#905]
I am attempting to build the current master branch on CentOS 8 using the following command line:

make build WITH_LUA_VERSION=504 WITH_WEBSOCKET=1 WITH_SERVER_STATS=1 PREFIX=/home/josh

When I do, the link step fails with this error:

out/src/civetweb.o: In function `lsp_mg_gc':
civetweb.c:(.text+0x30f7): undefined reference to `lua_tounsigned'
out/src/civetweb.o: In function `prepare_lua_environment':
civetweb.c:(.text+0x9298): undefined reference to `lua_pushunsigned'
collect2: error: ld returned 1 exit status
make: *** [Makefile:393: civetweb] Error 1

**Comment by bel2125** [comment]
Thank you ... it seems this combination of flags needs the #define `LUA_COMPAT_APIINTCASTS` from Lua5.4 (https://www.lua.org/source/5.4/lua.h.html).

A quick fix is to add `#define LUA_COMPAT_APIINTCASTS` at the top of civetweb_lua.h - I will have a closer look how to do this best with all combinations.

**Comment by bel2125** [comment]
Fixed for Lua 5.4
