### ISSUE TITLE
What is the plan of next release?

### ISSUE THREAD

**Issue by gou4shi1** [civetweb/civetweb#906]
Hello, @bel2125 , when will you release the next version?

**Comment by bel2125** [comment]
The plan is Mid/End of this month (September 2020).

Every release requires a couple of manual steps, like checking all open issues, checking if all new features are finished to a degree they are safe to use (or under an #experimental define), performing some manual tests on different platforms, checking static source code analysis ...
Depending on how much time this takes, and if some issue arises during these checks, it may be some days earlier or later.
