### ISSUE TITLE
init_lua callback

### ISSUE THREAD

**Issue by nemethz5** [civetweb/civetweb#907]
First of all, i'm not familiar well with Lua, I started to use it just now, but I think the calling of init_lua() is in wrong place, because the reg_... functions cannot be used in the callback.
I think the callback function would be more usable if it is called after the prepare_lua_request_info and before the lua_setglobal calls.

What do you think, is this an acceptable suggestion?

The code is in mod_lua.inl file.

	/* Export connection specific info */
	if (conn != NULL) {
		prepare_lua_request_info(conn, L);
	}

CALL THE callbacks.init_lua() HERE!

	/* Store as global table "mg" */
	lua_setglobal(L, "mg");

	/* Register "shared" table */
	lua_shared_register(L);

	/* Register default mg.onerror function */
	IGNORE_UNUSED_RESULT(
	    luaL_dostring(L,
	                  "mg.onerror = function(e) mg.write('\\nLua error:\\n', "
	                  "debug.traceback(e, 1)) end"));

	/* Check if a preload file is available */
	if ((conn != NULL) && (conn->dom_ctx != NULL)) {
		preload_file_name = conn->dom_ctx->config[LUA_PRELOAD_FILE];
	}

	/* Preload file into new Lua environment */
	if (preload_file_name) {
		IGNORE_UNUSED_RESULT(luaL_dofile(L, preload_file_name));
	}

IT IS CALLED HERE NOW.

	/* Call user init function */
	if (ctx != NULL) {
		if (ctx->callbacks.init_lua != NULL) {
			ctx->callbacks.init_lua(conn, L, lua_context_flags);
		}
	}

**Comment by bel2125** [comment]
> I think the callback function would be more usable if it is called after the prepare_lua_request_info and before the lua_setglobal calls.

Could you explain a little why you think it is more usable there? What do you want to do in this callback?

> What do you think, is this an acceptable suggestion?

I am open for every improvement, but I want to understand the problem first.
Maybe you are using the init_lua callback for something it was not intended to be used.
Maybe I can suggest to use a different callback, or it might indeed be better to move the call - but you need to tell me your requirements, or your reasons why you think this callback needs to be moved.

**Comment by nemethz5** [comment]
Hi, I try to add some constant version numbers of my app and my modules in the init_lua, but it is not possible there.
Well, I think I have to create and use my own namespace, instead using of mg. 
Lua seems as very usable for me in my server app, so I tried to found usable examples about using of Lua, but I didn't found yet...

**Comment by bel2125** [comment]
> I try to add some constant version numbers of my app and my modules in the init_lua, but it is not possible there.

Adding elements to the Lua state/Lua environment (like your own libraries, tables, strings, ...) is definitely possible there. The callback is called as the final step of creating the Lua environment, thus everything is possible there. You could even remove "mg", if you registered appropriate replacement functions.

> Well, I think I have to create and use my own namespace, instead using of `mg`.

Definitely doable at the current place of this callback, but not doable if you move the callback to the place you suggested.
Now the callback is called after `mg` has been registered, so you can easily "unregister" it there.
If you move the callback, `mg` is registered afterwards, so you can not do anything.

> Lua seems as very usable for me in my server app, so I tried to find usable examples about using of Lua, but I didn't find yet...  

There are a lot of Lua examples in the /test/ folder.

Or do you need an example how to register a C library callable from Lua?
How to do this depends a little on your platform. You can build them into your application using the "init_lua" callback, and follow the same registering process like already done for other libraries/tables such as "mg", "shared" or "lsqlite" - this will work mostly independent from the platform, but you cannot benefit if the Lua-C-library already exists on the platform.
If you do have a Debian / Ubuntu / ... Linux platform (some major distribution), then you can build the server with "WITH_LUA_SHARED", to access libraries you installed just with "apt-get install" (or whatever package manager), and use these libraries with `require` from your Lua script. (Hint: Add a lua background script where you `require` all C libraries, to prevent the system from loading/unloading the shared objects between requests). Also Windows will allow you to use "Standard Lua C libraries", so you can profit from Lua community development efforts there as well.
But before I go into more details: Is this what you are looking for?

**Comment by nemethz5** [comment]
Thanks for very usefull details!
It's clear, I have no more questions.
