### ISSUE TITLE
Civetweb unstable when running multiple executables on the same machine

### ISSUE THREAD

**Issue by CrackerHax** [civetweb/civetweb#913]
I am unable to keep multiple civetweb executables running on the same machine.

My dedicated server has several IP addresses assigned to it so I am trying to run multiple civetweb executables. If I run one executable it is nice and stable but when I try to run a second one (bound to a different ip address using full ip as SSH_PORT option) both end up crashing eventually.

Sorry I cannot provide more information than that. Going to try to run separate instances within the same executable and see if that works.

**Comment by bel2125** [comment]
You have multiple executables and bind each executable to a different IP address of a different network interface card?
They are "crashing" means, the processes are terminated by the operating system? Linux? Windows?
By "running unstable" you mean, they are both started ... run for a while ... end eventually crash?

**Comment by CrackerHax** [comment]
I have put both servers into a single executable and they seem to be stable now.

Linux, and not sure why or how they would crash because it took over a day in most cases.

**Comment by bel2125** [comment]
Is it possible that it did not really "crash", but the process was stopped by some other program or the "out of memory killer"?
Did it create a core dump?

**Comment by CrackerHax** [comment]
No, no dump or anything. I doubt it would use 64 gigs of memory (especially when its really the only non-OS process running).

**Comment by bel2125** [comment]
If it is an issue in the civetweb code, it should be fixed there. Probably it is not an issue in the code, but something that needs to be considered in the configuration files. I can try to reproduce this by starting two standalone servers on the same Ubuntu machine, and binding them to different interfaces. I know running two executable on Ubuntu/Debian works if they are not bound to different interfaces, but just use different ports.

**Comment by CrackerHax** [comment]
This was an issue with my code. invalid JSON was crashing them.
