### ISSUE TITLE
Null Pointer dereference on method log_message(const struct mg_connection *conn, const char *message)

### ISSUE THREAD

**Issue by ycaibb** [civetweb/civetweb#930]
Dear Developers:

Our static analysis tool reports a NULL pointer dereference bug on [main.c#L974](https://github.com/civetweb/civetweb/blob/68c0a7c37246c7edbb2d148ca834c82d572b2be0/src/main.c#L974.) and the null pointer is set on [civetweb.c](https://github.com/civetweb/civetweb/blob/68c0a7c37246c7edbb2d148ca834c82d572b2be0/src/civetweb.c#L3756). It may a false positive, thank you for your confirmation.

```
static int
log_message(const struct mg_connection *conn, const char *message)
{
	const struct mg_context *ctx = mg_get_context(conn);
	struct tuser_data *ud = (struct tuser_data *)mg_get_user_data(ctx);

	fprintf(stderr, "%s\n", message);

	if (ud->first_message == NULL) {
		ud->first_message = sdup(message);
	}

	return 0;
}
```

```
void *
mg_get_user_data(const struct mg_context *ctx)
{
	return (ctx == NULL) ? NULL : ctx->user_data;
}
```

**Comment by bel2125** [comment]
Your tool complains on the usage of `ud->`, not `message`, right?
The value of `ud` should always be `&g_user_data` (address of a static/global variable), so it is never NULL:
https://github.com/civetweb/civetweb/blob/68c0a7c37246c7edbb2d148ca834c82d572b2be0/src/main.c#L1424

If in the combination civetweb.c+main.c this value is anything else than `&g_user_data`, it would be some error somewhere else in the code - is this what your tool claims? I guess the tool did only look at `mg_get_user_data` - the general case is you only use civetweb.c and write your own main.c, then you cannot assume mg_get_user_data returns non-null.

**Comment by ycaibb** [comment]
Yes. Because the `mg_get_user_data` may return null, so `ud` could be null. It is possible to happen?

**Comment by bel2125** [comment]
Short answer: No, this will not happen if you use unmodified main.c and civetweb.c

Long answer:
`mg_get_user_data` will only return `NULL`, if the user data supplied in `mg_start` is `NULL`.
civetweb.c does not know (or need to know) anything about the user data - it does not know about it's type (thus `void *`), size or meaning, but it just forwards this `void *` to all callbacks.
main.c supplies `&g_user_data` to `mg_start`, a static variable of type `struct tuser_data`. 
Thus, it is safe for every callback called by this instance of civetweb, to assume user data is a non null pointer to a `struct tuser_data`, and the cast from `NULL` to this type is always valid.

**Comment by ycaibb** [comment]
OK. Thank you for your help!!
