### ISSUE TITLE
Debug-Assert when unregistering auth_handler

### ISSUE THREAD

**Issue by GeneratedNickname** [civetweb/civetweb#941]
Civet exits the program with a debug assert when removing an auth handler. The assert happens in `mg_set_handler_type` when the auth_handler is checked via `DEBUG_ASSERT(auth_handler != NULL);`. Maybe it should check for `DEBUG_ASSERT(!is_delete_request && auth_handler != NULL);`

Minimal example:

``` c++
#include "CivetServer.h"

class MyAuthHandler
	: public CivetAuthHandler
{
public:
	bool authorize(CivetServer *server, struct mg_connection *conn) override { return true; }
};

int main(int argc, char *argv[])
{
	{
		CivetServer cs(nullptr);
		cs.addAuthHandler("/metrics", new MyAuthHandler());
		cs.removeAuthHandler("/metrics");
	}
	// More code here.
}
```

For context - my use case comes from using [prometheus-cpp](https://github.com/jupp0r/prometheus-cpp), where destroying the exposer deregisters all handlers. This affect e.g. unit tests where an exposer is involved.

**Comment by bel2125** [comment]
You are right. The `if (!is_delete_request && (auth_handler == NULL))` already has this condition, DEBUG assert is missing it.

**Comment by romainnicod** [comment]
The assert still exits the program. When `auth_handler == NULL`  the value of `!is_delete_request` does not matter.
Shouldn't the assert be changed to the following?
```diff
- DEBUG_ASSERT(!is_delete_request && (auth_handler != NULL));
+ DEBUG_ASSERT(is_delete_request || (auth_handler != NULL));
```

**Comment by bel2125** [comment]
Looking at the code again, you are certainly right.

**Comment by romainnicod** [comment]
Thanks, it is working properly now.
