### ISSUE TITLE
ld: error: LLVM gold plugin: linking module flags 'SmallDataLimit': IDs have conflicting values in 'src/libcivetweb.a.llvm.1432.civetweb.c' (on 64bit RISC-V)

### ISSUE THREAD

**Issue by advancedwebdeveloper** [civetweb/civetweb#951]
Hello.
I was trying to build your project, as a dependency of https://github.com/apache/nifi-minifi-cpp .
I am experimenting under emulated RISC-V env. https://en.opensuse.org/openSUSE:RISC-V

So after entering the shell (hence machinectl is involved, in the manual above) I am firing Ninja:

> oceanfish81@riscv:/home/oceanfish81/nifi-minifi-cpp/build> ninja civetweb-external-prefix/src/civetweb-external-stamp/civetweb-external-build
> [1/1] Performing build step for 'civetweb-external'
> FAILED: civetweb-external-prefix/src/civetweb-external-stamp/civetweb-external-build thirdparty/civetweb-install/lib/libcivetweb.a thirdparty/civetweb-install/lib/libcivetweb-cpp.a 
> cd /home/oceanfish81/nifi-minifi-cpp/build/civetweb-external-prefix/src/civetweb-external-build && /usr/bin/cmake --build . && /usr/bin/cmake -E touch /home/oceanfish81/nifi-minifi-cpp/build/civetweb-external-prefix/src/civetweb-external-stamp/civetweb-external-build
> [0/1] Re-running CMake...
> CMake Deprecation Warning at CMakeLists.txt:2 (cmake_minimum_required):
>   Compatibility with CMake < 2.8.12 will be removed from a future version of
>   CMake.
> 
>   Update the VERSION argument <min> value or use a ...<max> suffix to tell
>   CMake that the project does not need compatibility with older versions.
> 
> 
> -- Target architecture - riscv64
> -- Thread Stack Size - 102400
> -- Serve no static files - OFF
> -- Disable CGI support - OFF
> -- Disable caching support - OFF
> -- C++ wrappers - ON
> -- IP Version 6 - OFF
> -- Websockets support - OFF
> -- Server statistics support - OFF
> -- Memory Debugging - OFF
> -- ASAN in debug mode - OFF
> -- Force x32 / x64 architecture - OFF
> -- Lua CGI support - OFF
> -- Executable installation - ON
> -- Build if there are warnings - ON
> -- Duktape CGI support - OFF
> -- SSL support - ON
> -- Compile for OpenSSL 1.1 API - OFF
> -- Dynamically load SSL libraries - OFF
> -- Configuring C Compiler
> -- Configuring C++ Compiler
> -- Could NOT find WinSock (missing: WINSOCK_LIBRARIES WINSOCK_INCLUDE_DIRS) 
> -- Could NOT find Threads (missing: Threads_FOUND) 
> -- OpenSSL include directory: /home/oceanfish81/nifi-minifi-cpp/build/thirdparty/libressl-install/include
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/oceanfish81/nifi-minifi-cpp/build/civetweb-external-prefix/src/civetweb-external-build
> [1/5] Building CXX object src/CMakeFiles/civetweb-cpp.dir/CivetServer.cpp.o
> [2/5] Linking CXX static library src/libcivetweb-cpp.a
> [3/5] Building C object src/CMakeFiles/c-library.dir/civetweb.c.o
> [4/5] Linking C static library src/libcivetweb.a
> [5/5] Linking C executable src/civetweb
> FAILED: src/civetweb 
> : && /usr/bin/clang -std=c11 -pedantic-errors -fvisibility=hidden -O3 -DNDEBUG -fstack-protector-strong -flto -rdynamic src/CMakeFiles/c-executable.dir/main.c.o -o src/civetweb  src/libcivetweb.a  /usr/lib64/librt.so  /home/oceanfish81/nifi-minifi-cpp/build/thirdparty/libressl-install/lib/libtls.a  /home/oceanfish81/nifi-minifi-cpp/build/thirdparty/libressl-install/lib/libssl.a  /home/oceanfish81/nifi-minifi-cpp/build/thirdparty/libressl-install/lib/libcrypto.a && :
> /usr/bin/ld: error: LLVM gold plugin: linking module flags 'SmallDataLimit': IDs have conflicting values in 'src/libcivetweb.a.llvm.1432.civetweb.c' and 'ld-temp.o'
> clang-11.0: error: linker command failed with exit code 1 (use -v to see invocation)
> ninja: build stopped: subcommand failed.
> ninja: build stopped: subcommand failed.
> 

MiNiFi's C++ port was pre-configured in such a way:

> $ cmake  -DENABLE_PCAP=OFF -DENABLE_GPS=ON -DENABLE_AWS=ON -DENABLE_LIBRDKAFKA=ON -DENABLE_MQTT=ON -DENABLE_PYTHON=ON -DENABLE_COAP=ON -DENABLE_OPENCV=OFF -DENABLE_SFTP=ON -DENABLE_SQLITE=ON -DENABLE_OPENWSMAN=ON -DENABLE_OPC=ON -DSKIP_TESTS=true  -DUSE_SHARED_LIBS=ON  -DPORTABLE=ON  -DBUILD_ROCKSDB=ON  -DBUILD_IDENTIFIER= -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -G Ninja ..

I had env. var. set via 

> $ export LD=lld 
so it was picked up by CMake.

I checked

> $ zypper search gold
>   | llvm-gold          | Gold linker plugin for LLVM          | package
>   | llvm10-gold      | Gold linker plugin for LLVM          | package
> i | llvm11-gold      | Gold linker plugin for LLVM          | package
>   | llvm9-gold        | Gold linker plugin for LLVM          | package

so that's LLVM's plugin.
As @ianlancetaylor explained - "gold" itself is not ported to RISC-V, yet.
This package is not available - so no such executable is available.

But there are three other available linkers:

> $ ld --version && ld.lld --version && ld.bfd --version
> GNU ld (GNU Binutils; openSUSE Tumbleweed) 2.35.1.20201112-1
> LLD 11.0.0 (compatible with GNU linkers)
> GNU ld (GNU Binutils; openSUSE Tumbleweed) 2.35.1.20201112-1

I could try with each of one, sequentially re-configuring and re-building civetweb.

**Comment by advancedwebdeveloper** [comment]
Also hence that MiNiFi's CMakeLists.txt contains a modified flag

> -march=rv64gc

. The value "native" would neither have sense ( under qemu/nspawn) nor working.
Cross-compiling (from/under emulated RISC-V arch or on X86, ARM bare metal hosts) for ASIC or FPGA boards, for real RISC-V hardware, would have practical sense.
Until the hardware would become massively available.

**Comment by advancedwebdeveloper** [comment]
Hm, I caught a similar bug with ld:

> /usr/bin/ld: error: LLVM gold plugin: linking module flags 'SmallDataLimit': IDs have conflicting values in 'src/libcivetweb.a.llvm.1432.civetweb.c' and 'ld-temp.o'
. So now I am sure that I really misunderstand the cause of this.

**Comment by advancedwebdeveloper** [comment]
I shall try to remove LLVM's plugin and try again.
Or that's gold's plugin, for LLVM?

**Comment by bel2125** [comment]
Sorry, I have no idea what "SmallDataLimit" is, I have never seen "IDs have conflicting values", I don't know "ninja" and have only briefly heard of "nifi-minifi-cpp".
I have heard about "RISC-V", but I have no idea about the current state of implementation, availability of hardware, support of tools (compilers, ...).

Is it possible to compile civetweb just by using "make" (the standard Makefile in the civetweb root directory) or by using "mkdir output", "cd output", "cmake ..", "make all" (standard cmake in civetweb - just civetweb without nifi-minifi-cpp)?

**Comment by advancedwebdeveloper** [comment]
@bel2125 , I could try that.
Yes, using GNU Make instead of Ninja is one of the options.
Hence that your project (as also as many others, which are dependencies of MiNiFi) where successfully compiled via GCC, linked via lld and "make" was used all over the place.

CC @tspannhw , in case if there are specific 64bit RISC-V SoC boards (to test on).
@arpadboda , I will open a related issue (unless someone from your team would do that ahead of me) once I would reach the point when civetweb could compiled with both GCC and Clang.

Didn't build any tests for featured https://github.com/apache/nifi-minifi-cpp/blob/main/PROCESSORS.md#listenhttp processors (which requires civetweb) yet - it would involve running OpenJ9 VM and it is super slow virtual. env. (64bit RISC-V under x86_64 host). So leaving that for the culmination.

**Comment by advancedwebdeveloper** [comment]
@bel2125 , I followed your advice:

> $ cmake ..
> CMake Deprecation Warning at CMakeLists.txt:2 (cmake_minimum_required):
>   Compatibility with CMake < 2.8.12 will be removed from a future version of
>   CMake.
> 
>   Update the VERSION argument <min> value or use a ...<max> suffix to tell
>   CMake that the project does not need compatibility with older versions.
> 
> 
> -- The C compiler identification is GNU 10.2.1
> -- The CXX compiler identification is GNU 10.2.1
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Check for working C compiler: /usr/bin/cc - skipped
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Check for working CXX compiler: /usr/bin/c++ - skipped
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Target architecture - riscv64
> -- Enabling tests in the build - ON
> -- Thread Stack Size - 102400
> -- Enabling server executable - ON
> -- Serve no static files - OFF
> -- Disable CGI support - OFF
> -- Disable caching support - OFF
> -- C++ wrappers - OFF
> -- IP Version 6 - OFF
> -- Websockets support - OFF
> -- Server statistics support - OFF
> -- Memory Debugging - OFF
> -- ASAN in debug mode - ON
> -- Force x32 / x64 architecture - OFF
> -- Lua CGI support - OFF
> -- Executable installation - ON
> -- Build if there are warnings - ON
> -- Duktape CGI support - OFF
> -- SSL support - ON
> -- Compile for OpenSSL 1.0 API - OFF
> -- Compile for OpenSSL 1.1 API - ON
> -- Dynamically load SSL libraries - ON
> -- SSL Library Name - libssl.so
> -- SSL Cryptography Library Name - libcrypto.so
> -- Configuring C Compiler
> -- Performing Test NO_DIAGNOSTICS_PRODUCED
> -- Performing Test NO_DIAGNOSTICS_PRODUCED - Failed
> -- Performing Test -Wno-reserved-id-macros
> -- Performing Test -Wno-reserved-id-macros - Failed
> -- Could NOT find WinSock (missing: WINSOCK_LIBRARIES WINSOCK_INCLUDE_DIRS) 
> -- Looking for pthread.h
> -- Looking for pthread.h - found
> -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
> -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
> -- Looking for pthread_create in pthreads
> -- Looking for pthread_create in pthreads - not found
> -- Looking for pthread_create in pthread
> -- Looking for pthread_create in pthread - found
> -- Found Threads: TRUE  
> -- Found LibRt: /usr/lib64/librt.so  
> -- Found LibDl: /usr/lib64/libdl.so  
> -- Check Unit Testing Framework Version - 0.11.0
> -- Found LibM: /usr/lib64/libm.so  
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/oceanfish81/civetweb/release
> 
> oceanfish81@riscv:/home/oceanfish81/civetweb/release> make -j8
> Scanning dependencies of target shared-c-unit-tests
> Scanning dependencies of target civetweb-c-library
> [  3%] Building C object unittest/CMakeFiles/shared-c-unit-tests.dir/shared.c.o
> [  7%] Building C object src/CMakeFiles/civetweb-c-library.dir/civetweb.c.o
> [ 11%] Linking C static library libshared-c-unit-tests.a
> [ 11%] Built target shared-c-unit-tests
> [ 15%] Linking C static library libcivetweb.a
> [ 15%] Built target civetweb-c-library
> Scanning dependencies of target civetweb-c-executable
> Scanning dependencies of target check-unit-test-framework
> [ 19%] Creating directories for 'check-unit-test-framework'
> [ 23%] Building C object src/CMakeFiles/civetweb-c-executable.dir/main.c.o
> [ 26%] Linking C executable civetweb
> [ 30%] Performing download step (download, verify and extract) for 'check-unit-test-framework'
> [ 30%] Built target civetweb-c-executable
> -- check-unit-test-framework download command succeeded.  See also /home/oceanfish81/civetweb/release/third_party/src/check-unit-test-framework-stamp/check-unit-test-framework-download-*.log
> [ 34%] No update step for 'check-unit-test-framework'
> [ 38%] Performing patch step for 'check-unit-test-framework'
> patching file /home/oceanfish81/civetweb/release/third_party/src/check-unit-test-framework/src/check_run.c
> [ 42%] Performing configure step for 'check-unit-test-framework'
> -- check-unit-test-framework configure command succeeded.  See also /home/oceanfish81/civetweb/release/third_party/src/check-unit-test-framework-stamp/check-unit-test-framework-configure-*.log
> [ 46%] Performing build step for 'check-unit-test-framework'
> -- check-unit-test-framework build command succeeded.  See also /home/oceanfish81/civetweb/release/third_party/src/check-unit-test-framework-stamp/check-unit-test-framework-build-*.log
> [ 50%] Performing install step for 'check-unit-test-framework'
> -- check-unit-test-framework install command succeeded.  See also /home/oceanfish81/civetweb/release/third_party/src/check-unit-test-framework-stamp/check-unit-test-framework-install-*.log
> [ 53%] Completed 'check-unit-test-framework'
> [ 53%] Built target check-unit-test-framework
> Scanning dependencies of target public-server-c-unit-tests
> Scanning dependencies of target public-func-c-unit-tests
> Scanning dependencies of target timer-c-unit-tests
> Scanning dependencies of target private-c-unit-tests
> Scanning dependencies of target exe-c-unit-tests
> [ 57%] Building C object unittest/CMakeFiles/public-server-c-unit-tests.dir/public_server.c.o
> [ 61%] Building C object unittest/CMakeFiles/public-func-c-unit-tests.dir/public_func.c.o
> [ 69%] Building C object unittest/CMakeFiles/exe-c-unit-tests.dir/private_exe.c.o
> [ 69%] Building C object unittest/CMakeFiles/timer-c-unit-tests.dir/timertest.c.o
> [ 73%] Building C object unittest/CMakeFiles/private-c-unit-tests.dir/private.c.o
> /home/oceanfish81/civetweb/unittest/public_server.c: In function ‘wait_not_null’:
> /home/oceanfish81/civetweb/unittest/public_server.c:141:32: warning: unknown option after ‘#pragma GCC diagnostic’ kind; did you mean ‘-Wunreachable-code’? [-Wpragmas]
>   141 | #pragma GCC diagnostic ignored "-Wunreachable-code-return"
>       |                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~
> [ 76%] Linking C static library libexe-c-unit-tests.a
> [ 80%] Linking C static library libpublic-func-c-unit-tests.a
> [ 80%] Built target exe-c-unit-tests
> [ 80%] Built target public-func-c-unit-tests
> [ 84%] Linking C static library libpublic-server-c-unit-tests.a
> [ 84%] Built target public-server-c-unit-tests
> [ 88%] Linking C static library libtimer-c-unit-tests.a
> [ 88%] Built target timer-c-unit-tests
> [ 92%] Linking C static library libprivate-c-unit-tests.a
> [ 92%] Built target private-c-unit-tests
> Scanning dependencies of target main-c-unit-test
> [ 96%] Building C object unittest/CMakeFiles/main-c-unit-test.dir/main.c.o
> [100%] Linking C executable main-c-unit-test
> [100%] Built target main-c-unit-test
> oceanfish81@riscv:/home/oceanfish81/civetweb/release> make test
> Running tests...
> Test project /home/oceanfish81/civetweb/release
>       Start  1: test-private-http-message
>  1/50 Test  #1: test-private-http-message .......................   Passed    0.30 sec
>       Start  2: test-private-http-keep-alive
>  2/50 Test  #2: test-private-http-keep-alive ....................   Passed    0.34 sec
>       Start  3: test-private-url-parsing-1
>  3/50 Test  #3: test-private-url-parsing-1 ......................   Passed    0.28 sec
>       Start  4: test-private-url-parsing-2
>  4/50 Test  #4: test-private-url-parsing-2 ......................   Passed    0.34 sec
>       Start  5: test-private-url-parsing-3
>  5/50 Test  #5: test-private-url-parsing-3 ......................   Passed    0.25 sec
>       Start  6: test-private-internal-parsing-1
>  6/50 Test  #6: test-private-internal-parsing-1 .................   Passed    0.33 sec
>       Start  7: test-private-internal-parsing-2
>  7/50 Test  #7: test-private-internal-parsing-2 .................   Passed    0.23 sec
>       Start  8: test-private-internal-parsing-3
>  8/50 Test  #8: test-private-internal-parsing-3 .................   Passed    0.32 sec
>       Start  9: test-private-internal-parsing-4
>  9/50 Test  #9: test-private-internal-parsing-4 .................   Passed    0.21 sec
>       Start 10: test-private-internal-parsing-5
> 10/50 Test #10: test-private-internal-parsing-5 .................   Passed    0.35 sec
>       Start 11: test-private-internal-parsing-6
> 11/50 Test #11: test-private-internal-parsing-6 .................   Passed    0.36 sec
>       Start 12: test-private-internal-parsing-7
> 12/50 Test #12: test-private-internal-parsing-7 .................   Passed    0.26 sec
>       Start 13: test-private-encode-decode
> 13/50 Test #13: test-private-encode-decode ......................   Passed    0.51 sec
>       Start 14: test-private-mask-data
> 14/50 Test #14: test-private-mask-data ..........................   Passed    0.29 sec
>       Start 15: test-private-date-parsing
> 15/50 Test #15: test-private-date-parsing .......................   Passed    0.40 sec
>       Start 16: test-private-sha1
> 16/50 Test #16: test-private-sha1 ...............................   Passed    0.31 sec
>       Start 17: test-private-config-options
> 17/50 Test #17: test-private-config-options .....................   Passed    0.29 sec
>       Start 18: test-publicfunc-version
> 18/50 Test #18: test-publicfunc-version .........................   Passed    0.43 sec
>       Start 19: test-publicfunc-options
> 19/50 Test #19: test-publicfunc-options .........................   Passed    0.30 sec
>       Start 20: test-publicfunc-mime-types
> 20/50 Test #20: test-publicfunc-mime-types ......................   Passed    0.40 sec
>       Start 21: test-publicfunc-strcasecmp
> 21/50 Test #21: test-publicfunc-strcasecmp ......................   Passed    0.25 sec
>       Start 22: test-publicfunc-url-encoding-decoding
> 22/50 Test #22: test-publicfunc-url-encoding-decoding ...........   Passed    0.37 sec
>       Start 23: test-publicfunc-cookies-and-variables
> 23/50 Test #23: test-publicfunc-cookies-and-variables ...........   Passed    0.35 sec
>       Start 24: test-publicfunc-md5
> 24/50 Test #24: test-publicfunc-md5 .............................   Passed    0.30 sec
>       Start 25: test-publicfunc-aux-functions
> 25/50 Test #25: test-publicfunc-aux-functions ...................   Passed    0.27 sec
>       Start 26: test-publicserver-check-test-environment
> 26/50 Test #26: test-publicserver-check-test-environment ........   Passed    0.34 sec
>       Start 27: test-publicserver-init-library
> 27/50 Test #27: test-publicserver-init-library ..................***Failed    0.35 sec
>       Start 28: test-publicserver-start-threads
> 28/50 Test #28: test-publicserver-start-threads .................   Passed    1.42 sec
>       Start 29: test-publicserver-minimal-http-server
> 29/50 Test #29: test-publicserver-minimal-http-server ...........   Passed   27.67 sec
>       Start 30: test-publicserver-minimal-https-server
> 30/50 Test #30: test-publicserver-minimal-https-server ..........***Failed    1.74 sec
>       Start 31: test-publicserver-minimal-http-client
> 31/50 Test #31: test-publicserver-minimal-http-client ...........   Passed    0.68 sec
>       Start 32: test-publicserver-minimal-https-client
> 32/50 Test #32: test-publicserver-minimal-https-client ..........   Passed    0.33 sec
>       Start 33: test-publicserver-start-stop-http-server
> 33/50 Test #33: test-publicserver-start-stop-http-server ........   Passed   31.06 sec
>       Start 34: test-publicserver-start-stop-http-server-ipv6
> 34/50 Test #34: test-publicserver-start-stop-http-server-ipv6 ...   Passed    0.42 sec
>       Start 35: test-publicserver-start-stop-https-server
> 35/50 Test #35: test-publicserver-start-stop-https-server .......***Failed    1.44 sec
>       Start 36: test-publicserver-tls-server-client
> 36/50 Test #36: test-publicserver-tls-server-client .............***Failed    1.52 sec
>       Start 37: test-publicserver-server-requests
> 37/50 Test #37: test-publicserver-server-requests ...............***Failed    1.71 sec
>       Start 38: test-publicserver-store-body
> 38/50 Test #38: test-publicserver-store-body ....................   Passed   27.24 sec
>       Start 39: test-publicserver-handle-form
> 39/50 Test #39: test-publicserver-handle-form ...................   Passed   22.78 sec
>       Start 40: test-publicserver-http-authentication
> 40/50 Test #40: test-publicserver-http-authentication ...........   Passed   18.71 sec
>       Start 41: test-publicserver-http-keep-alive
> 41/50 Test #41: test-publicserver-http-keep-alive ...............   Passed   11.96 sec
>       Start 42: test-publicserver-error-handling
> 42/50 Test #42: test-publicserver-error-handling ................   Passed   20.54 sec
>       Start 43: test-publicserver-error-logging
> 43/50 Test #43: test-publicserver-error-logging .................   Passed   11.85 sec
>       Start 44: test-publicserver-limit-speed
> 44/50 Test #44: test-publicserver-limit-speed ...................   Passed   20.86 sec
>       Start 45: test-publicserver-large-file
> 45/50 Test #45: test-publicserver-large-file ....................***Failed    1.39 sec
>       Start 46: test-publicserver-file-in-memory
> 46/50 Test #46: test-publicserver-file-in-memory ................   Passed    0.34 sec
>       Start 47: test-timer-timer-single-shot
> 47/50 Test #47: test-timer-timer-single-shot ....................   Passed    8.60 sec
>       Start 48: test-timer-timer-periodic
> 48/50 Test #48: test-timer-timer-periodic .......................   Passed   14.41 sec
>       Start 49: test-timer-timer-mixed
> 49/50 Test #49: test-timer-timer-mixed ..........................   Passed    4.59 sec
>       Start 50: test-exe-helper-funcs
> 50/50 Test #50: test-exe-helper-funcs ...........................   Passed    0.36 sec
> 
> 88% tests passed, 6 tests failed out of 50
> 
> Total Test time (real) = 241.26 sec
> 
> The following tests FAILED:
>          27 - test-publicserver-init-library (Failed)
>          30 - test-publicserver-minimal-https-server (Failed)
>          35 - test-publicserver-start-stop-https-server (Failed)
>          36 - test-publicserver-tls-server-client (Failed)
>          37 - test-publicserver-server-requests (Failed)
>          45 - test-publicserver-large-file (Failed)
> Errors while running CTest
> make: *** [Makefile:126: test] Error 8
>

**Comment by advancedwebdeveloper** [comment]
Can't build Lua:

> $ make --trace
> Makefile:881: target 'cmake_check_build_system' does not exist
> /usr/bin/cmake -S/home/oceanfish81/civetweb -B/home/oceanfish81/civetweb/release --check-build-system CMakeFiles/Makefile.cmake 0
> Makefile:181: update target 'all' due to: cmake_check_build_system
> /usr/bin/cmake -E cmake_progress_start /home/oceanfish81/civetweb/release/CMakeFiles /home/oceanfish81/civetweb/release//CMakeFiles/progress.marks
> make -s -f CMakeFiles/Makefile2 all
> CMakeFiles/Makefile2:1141: target 'src/CMakeFiles/luaxml.dir/all' does not exist
> make -s -f src/CMakeFiles/luaxml.dir/build.make src/CMakeFiles/luaxml.dir/depend
> src/CMakeFiles/luaxml.dir/build.make:157: target 'src/CMakeFiles/luaxml.dir/depend' does not exist
> cd /home/oceanfish81/civetweb/release && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/oceanfish81/civetweb /home/oceanfish81/civetweb/src /home/oceanfish81/civetweb/release /home/oceanfish81/civetweb/release/src /home/oceanfish81/civetweb/release/src/CMakeFiles/luaxml.dir/DependInfo.cmake --color=
> make -s -f src/CMakeFiles/luaxml.dir/build.make src/CMakeFiles/luaxml.dir/build
> src/CMakeFiles/luaxml.dir/build.make:97: target 'third_party/src/luaxml-stamp/luaxml-mkdir' does not exist
> /usr/bin/cmake -E cmake_echo_color --switch= --blue --bold --progress-dir=/home/oceanfish81/civetweb/release/CMakeFiles --progress-num=48 "Creating directories for 'luaxml'"
> [  1%] Creating directories for 'luaxml'
> cd /home/oceanfish81/civetweb/release/src && /usr/bin/cmake -E make_directory /home/oceanfish81/civetweb/release/third_party/src/luaxml
> cd /home/oceanfish81/civetweb/release/src && /usr/bin/cmake -E make_directory /home/oceanfish81/civetweb/release/third_party/src/luaxml-build
> cd /home/oceanfish81/civetweb/release/src && /usr/bin/cmake -E make_directory /home/oceanfish81/civetweb/release/third_party
> cd /home/oceanfish81/civetweb/release/src && /usr/bin/cmake -E make_directory /home/oceanfish81/civetweb/release/third_party/tmp
> cd /home/oceanfish81/civetweb/release/src && /usr/bin/cmake -E make_directory /home/oceanfish81/civetweb/release/third_party/src/luaxml-stamp
> cd /home/oceanfish81/civetweb/release/src && /usr/bin/cmake -E make_directory /home/oceanfish81/civetweb/release/third_party/src
> cd /home/oceanfish81/civetweb/release/src && /usr/bin/cmake -E make_directory /home/oceanfish81/civetweb/release/third_party/src/luaxml-stamp
> cd /home/oceanfish81/civetweb/release/src && /usr/bin/cmake -E touch /home/oceanfish81/civetweb/release/third_party/src/luaxml-stamp/luaxml-mkdir
> src/CMakeFiles/luaxml.dir/build.make:109: update target 'third_party/src/luaxml-stamp/luaxml-download' due to: third_party/src/luaxml-stamp/luaxml-mkdir third_party/src/luaxml-stamp/luaxml-urlinfo.txt
> /usr/bin/cmake -E cmake_echo_color --switch= --blue --bold --progress-dir=/home/oceanfish81/civetweb/release/CMakeFiles --progress-num=49 "Performing download step (download, verify and extract) for 'luaxml'"
> [  2%] Performing download step (download, verify and extract) for 'luaxml'
> cd /home/oceanfish81/civetweb/release/third_party/src && /usr/bin/cmake -P /home/oceanfish81/civetweb/release/third_party/src/luaxml-stamp/luaxml-download-.cmake
> -- luaxml download command succeeded.  See also /home/oceanfish81/civetweb/release/third_party/src/luaxml-stamp/luaxml-download-*.log
> cd /home/oceanfish81/civetweb/release/third_party/src && /usr/bin/cmake -E touch /home/oceanfish81/civetweb/release/third_party/src/luaxml-stamp/luaxml-download
> src/CMakeFiles/luaxml.dir/build.make:114: update target 'third_party/src/luaxml-stamp/luaxml-update' due to: third_party/src/luaxml-stamp/luaxml-download
> /usr/bin/cmake -E cmake_echo_color --switch= --blue --bold --progress-dir=/home/oceanfish81/civetweb/release/CMakeFiles --progress-num=50 "No update step for 'luaxml'"
> [  4%] No update step for 'luaxml'
> cd /home/oceanfish81/civetweb/release/src && /usr/bin/cmake -E echo_append
> cd /home/oceanfish81/civetweb/release/src && /usr/bin/cmake -E touch /home/oceanfish81/civetweb/release/third_party/src/luaxml-stamp/luaxml-update
> src/CMakeFiles/luaxml.dir/build.make:119: update target 'third_party/src/luaxml-stamp/luaxml-patch' due to: third_party/src/luaxml-stamp/luaxml-update
> /usr/bin/cmake -E cmake_echo_color --switch= --blue --bold --progress-dir=/home/oceanfish81/civetweb/release/CMakeFiles --progress-num=51 "Performing patch step for 'luaxml'"
> [  5%] Performing patch step for 'luaxml'
> cd /home/oceanfish81/civetweb/release/third_party/src/luaxml && /usr/bin/cmake -E copy /home/oceanfish81/civetweb/src/cmake/luaxml/CMakeLists.txt /home/oceanfish81/civetweb/release/third_party/src/luaxml/CMakeLists.txt
> Error copying file "/home/oceanfish81/civetweb/src/cmake/luaxml/CMakeLists.txt" to "/home/oceanfish81/civetweb/release/third_party/src/luaxml/CMakeLists.txt".
> make[2]: *** [src/CMakeFiles/luaxml.dir/build.make:120: third_party/src/luaxml-stamp/luaxml-patch] Error 1
> make[1]: *** [CMakeFiles/Makefile2:1142: src/CMakeFiles/luaxml.dir/all] Error 2
> make: *** [Makefile:182: all] Error 2
>

**Comment by advancedwebdeveloper** [comment]
My attempt to build civetweb from the top level directory lad to a launchable executable.
It worked locally - and I was able to access 8080 port.

Here is the log, for building lua and sqlite:
https://gist.github.com/advancedwebdeveloper/56dfc55f81435ef595e50d310540fe33#file-civetweb_build_gcc_riscv64-log

**Comment by bel2125** [comment]
`make WITH_LUA=1` works, 
but cmake does not work with Lua. This is a known issue: https://github.com/civetweb/civetweb/issues/543

**Comment by advancedwebdeveloper** [comment]
I didn't new that

**Comment by bel2125** [comment]
Is there anything else I can do to help here, or did it work for you using "make"?
Can we close this issue?

**Comment by advancedwebdeveloper** [comment]
Yes
