### ISSUE TITLE
Unbalanced refcount if auth handler rejects

### ISSUE THREAD

**Issue by gjasny** [civetweb/civetweb#954]
Hi,

if I register an auth handler and authentication fails I cannot unregister the request handler because the refcount is unbalanced.

In `handle_request` refcount is incremented by calling `get_request_handler`. But if the auth handler rejects the request here:
https://github.com/civetweb/civetweb/blob/56ff92f04edd44ca9b7de8ebd563edb6abb380a6/src/civetweb.c#L14628-L14630

then the `handle_request` function is left without decrementing the reference count.

Thanks,
Gregor

**Comment by bel2125** [comment]
I think https://github.com/civetweb/civetweb/commit/935b493e0c60795ef1d8a67a0f5f10c3a47d3db2 should fix all code path where the handler reference is created but not removed anymore. Could you test if it fixes your case?

**Comment by gjasny** [comment]
Hi,

thanks for the fast reply. Applying your change makes my integration tests pass.

-Gregor

**Comment by bel2125** [comment]
fixed
