### ISSUE TITLE
Video files (mp4, webm) don't work.

### ISSUE THREAD

**Issue by krpano** [civetweb/civetweb#955]
For some reason the browsers can't load video files when served from a Civetweb server (version 1.13).
With other servers (Apache, mongoose) it works...

**Comment by krpano** [comment]
Update: with version 1.12 the videos are working!

**Comment by krpano** [comment]
I found the bug and a simple fix:

In the 'civetweb.c' file inside the 'handle_static_file_request' function the 'Content-Range' http response header is first generated here with this code:
```
mg_snprintf(conn,
            NULL, /* range buffer is big enough */
            range,
            sizeof(range),
            "bytes "
            "%" INT64_FMT "-%" INT64_FMT "/%" INT64_FMT "\r\n",    // <=== the "\r\n" here is the bug !!!
            r1,
            r1 + cl - 1,
            filep->stat.size);
```

and then in the 'response.inl' file sent using this code:
```
mg_printf(conn,
          "%s: %s\r\n",       // <=== another '\r\n'
          conn->response_info.http_headers[i].name,
          conn->response_info.http_headers[i].value);
```
There are two '\r\n' and that wrongly ends the http headers. So the remaining http headers are missing and sent as body data and that logically causes the broken behavior on the client-side.

Just removing the the wrong '\r\n' seems to already wholly fix this problem.

**Comment by bel2125** [comment]
Thank you very much. This probably fixes another issue as well.
I think this issue occurred first when adding (experimental) HTTP/2 support and mg_response_header in 1.13.
Is it the same issue you have with Chrome an V1.12?

**Comment by krpano** [comment]
Thanks for adding the fix!

About 1.12 - I've retested now and 1.12 is working now in Chrome and Firefox, might have been a cache issue...
