### ISSUE TITLE
Beginner question: Serving index.html file to client

### ISSUE THREAD

**Issue by RikuOo** [civetweb/civetweb#963]
Hello there!
This might be a basic question (it is), but since I couldn't find any guide or HowTo's besides the examples this is the only place to ask for help.

I wanted to add a web interface to my c++ programm. As framework I used Angular to create the interface.
Now I want to visualize the build files from angular with the help of civetweb.

But I can't wrap my head around how I'm supposed to do it.
I saw that I have to set a document_root as option for the server. Thats where i put all my files like index.html, style.css and more.
I assume I have to use a callback when the client requests a site the server has to responds with the index file(?).
Also I saw that I can set a "index_files" option, but also this doesn't realy helped me.

Maybe someone can show me an example, or point me in the right direction.
I know that this is a beginenr question, but I really don't know who to ask.
Sorry if I clutter your issues section with this.
Thank you all in advance!

**Comment by bel2125** [comment]
> Now I want to visualize the build files from angular with the help of civetweb.

I am not sure what you mean with "visualize the build files". A browser is responsible for the display of your html, css, image, ... files you created. So you just need to put all your files into the document root folder of the web server, and then open the URL of the server with your browser. It does not matter if you created your files using Angular, React, Vue, .... or you wrote them in vanilla JavaScript.
You do not need any C++ callback for this, and you do not need to reconfigure anything (index_files, ...). The default settings will definitely work for an Angular application.
You need callbacks only if your web application needs to get/set some data from your C (C++) code.

**Comment by bel2125** [comment]
For a quick start, follow the following steps (on Windows):

Create some folder "C:\CivetWeb", 
Download the pre-built CivetWeb executable from Sourceforge and put it into this folder.
Create a folder "C:\CivetWeb\docroot".
Put all your files (created by the Angular build) into "C:\CivetWeb\docroot"
Open an Explorer in C:\CivetWeb and double click CivetWeb*.exe (which one depends on your system, but probably the 64 bit exe version).

Your application should already be available at http://localhost:8080/docroot - but the Angular rooting might expect it in http://localhost/ - so change some options. To do so, look for the CivetWeb systray icon. Click it and choose "Edit settings". 
Set "listening_ports" to 80 and set "document_root" to C:\CivetWeb\docroot. Click "save settings" and close the dialog.
Your (Angular) web application should now run on http://localhost/

**Comment by bel2125** [comment]
If you have a Linux system, the steps are similar with some system related differences:

Download the zip file with CivetWeb source (e.g, civetweb-1.13.zip).
Make sure you have the packages "unzip" and "build-essential" installed (Debian: `sudo apt-get install build-essential zip unzip`).
Unpack CivetWeb into some directory (e.g. /opt/civetweb-1.13/) by using `sudo unzip civetweb-1.13.zip -d /opt/`).
Change into this directory (`cd /opt/civetweb-1.13`) and build the server (`make` for default options, `make WITH_ALL=1` for all features). Allow the server to bind to the default web ports `sudo setcap CAP_NET_BIND_SERVICE=+eip civetweb` (this is due to an extremely outdated idea in Linux, that not allowing anyone other than root to host a webserver is a proper way to ensure network security).

Copy your angular application into some directory, e.g., /home/username/webapp
Start civetweb using `/opt/civetweb/civetweb -listening_ports 80 -document_root /home/username/webapp`

**Comment by RikuOo** [comment]
Hey there!
Thanks for the fast reply.
I will test it tomorrow since I dont't have device here where I want to deploy the server.

Since you told me that callbacks are not really needed I assume i messed up setting the doc root in the c++ programm to the right path.
Again thank you for your fast reply even tho this low level question. I will reply as soon as I tested something.

**Comment by RikuOo** [comment]
Hello again!
With your help I managed to make it work.
Main error in my case a combination of setting the wrong path and having the files not in the right folder.
My program at end looked like this:

int main(void)
{
    struct mg_context *ctx;
    struct mg_callbacks callbacks;
    const char *options[] = {
       "listening_ports", "8080",
       "document_root","/opt/application/control/ccontrol/webgui",
       "index_files","index.html",
       NULL};
    memset(&callbacks, 0, sizeof(callbacks));
    ctx = mg_start(&callbacks, NULL, options);
    getchar();
    mg_stop(ctx);
    return 0;
}

While the "webgui" folder looked like this:
-webgui
     -static
          -(((ANGULAR FILES LIKE *.ico , *.js , *js.map and so on)))
     -index.html

Next up is the implementation of a rest api, so my C++ can communicate with my web gui. But for that I'll study the example.

Thanks again for your help!

**Comment by bel2125** [comment]
A minimal example would be here:
https://github.com/civetweb/civetweb/blob/master/docs/Embedding.md#a-minimal-example
An additional `mg_init_library` is recommended.
If your server is not running interactively, probably the `getchar()` should be replaced by some `while (!exitFlag) sleep(1);`, and some handler (signal handler, web url handler, ...) setting this exit flag (or something else in your system infrastructure).

A more complete example: https://github.com/civetweb/civetweb/blob/master/examples/embedded_c/embedded_c.c
