### ISSUE TITLE
Using server-sent events in CivetWeb

### ISSUE THREAD

**Issue by chs-1980** [civetweb/civetweb#967]
Hi,

For the last couple of days i've tried to get server-sent events to work with CivetWeb, but i don't seem to be able to get it to work. As my first suspicion was that the version of CivetWeb is still buggy in this perspective i upgraded to version 1.13 so i guess it should work...

This is the server-side code i am using currently:

```c        
       data = "data: this is a test stream";
        ::mg_printf(conn,
                    "HTTP/1.1 200 OK\r\n"
                    "Cache-Control: no-cache\r\n"
                    "Content-Type: text/event-stream\r\n"
                    "Transfer-Encoding: chunked\r\n"
                    "Access-Control-Allow-Origin: *\r\n"
                    "Content-Length: 27\r\n"
                    "Connection: keep-alive\r\n\r\n");
        int blub = ::mg_send_chunk(conn, data.toLocal8Bit(), data.size());
```
On the client side this is the EventSource-related code i implemented:

```javascript
const evtSource = new EventSource("http://localhost:8080/io/Neue%20Komponente/KinAxis");
evtSource.onopen = (evt) => {
  console.log(`socket opened: ${JSON.stringify(evt)}`);
}
evtSource.onmessage = (evt) => {
  console.log(`message received: ${JSON.stringify(evt)}`);
}

evtSource.onerror = (evt) => {
  console.log(`error occured: ${JSON.stringify(evt)}`);
}
```

So after starting my application and reloading the page hosting the above JavaScript-snippet i see the following in the console:

```
socket opened: {"isTrusted":true}
error occured: {"isTrusted":true}
socket opened: {"isTrusted":true}
```
It looks like something is happening but i never receive a message from the server, although i definitely pass-through the code mentioned above...

The options i use when starting the server are:

`enable_keep_alive yes keep_alive_timeout_ms 500`

I obviously am missing something but i am at a loss at the moment and can't spot my mistake... Can somebody shed some light on this?

Thanks,

Christoph

**Comment by bel2125** [comment]
You should not combine "Content-Length: 27\r\n" and "Transfer-Encoding: chunked\r\n".
Either you know the content length ... then you don't need chunked encoding.
Or you don't know the content length ... then you need to send a final chunk of size zero.

I did not test your example, so maybe there are other issues. Personally I prefer to use WebSockets to SSE:
https://www.telerik.com/blogs/websockets-vs-server-sent-events

From the server point of view, SSE is just a regular request, with a long connection timeout - so it's available since the first version. Probably you need to set request_timeout to some big value.

**Comment by chs-1980** [comment]
Hi bel2125,

Thanks for your answer but i just found my problem. In order to get the onmessage-event to fire i need to send a message of type 'message' first...

So sending this:

```c
        QString evtType = "event: message\n";
        ::mg_write(conn, evtType.toLocal8Bit(), evtType.size());
        ::mg_write(conn, data.toLocal8Bit(), data.size());
        ::mg_printf(conn, "\n\n");
```

from the server resulted in the correct behaviour...

Thanks again for the input!

Christoph
