### ISSUE TITLE
cannot create socket (entry 1) on win10_x64

### ISSUE THREAD

**Issue by andumin** [civetweb/civetweb#977]
Hi,

I have not found a solution for this problem. CivetWeb v1.13 fails to start with that error, please see attached screenshots.

![Selection_999(086)](https://user-images.githubusercontent.com/80351034/110511293-229ddf00-8115-11eb-9cb5-cbe60db626f1.png)

I'm very appreciate for your help!

**Comment by bel2125** [comment]
Entry 1 is the first (and only) entry in your "listening_ports" list: 8080

Maybe this port is already in use on your machine, maybe your firewall is blocking the civetweb executable from opening this port.

**Comment by andumin** [comment]
Hi bel2125,

It doesn't depend of port number, I've tried different port numbers an always got same error. About firewall I think it's not the case because other tools open ports without any problems.

**Comment by andumin** [comment]
Hi bel2125, 

You are right, the problem was in win10 restrictions, I've moved .exe file to C:\ disk and it solved the problem.

Thank you very much for your help!
