### ISSUE TITLE
IPv6 and SSL: sslize error

### ISSUE THREAD

**Issue by jgeiss66** [civetweb/civetweb#979]
I built civetweb as follows:

```
cd output

cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=OFF \
-DBUILD_SHARED_LIBS=ON -DCIVETWEB_BUILD_TESTING=OFF \
-DCIVETWEB_ENABLE_LUA=OFF -DCIVETWEB_ENABLE_DUKTAPE=OFF \
-DCIVETWEB_ENABLE_CXX=no -DCIVETWEB_ENABLE_SERVER_EXECUTABLE=yes \
-DCIVETWEB_ENABLE_SSL=yes -DCIVETWEB_SSL_OPENSSL_API_1_1=ON \
-DCIVETWEB_ENABLE_IPV6=ON ..

ninja

```
And launched it using

`src/civetweb -listening_ports '[::]:30080,[::]:30443s' -ssl_certificate ../../resources/cert/server.pem -document_root <path to my doc>`

Connecting with a web-browser running at localhost worked for
- http://localhost:30080/
- https://localhost:30443/
- http://[::1]:30080/

but not for
- http://[::1]:30443/

This caused the error "sslize error":
```
*** 1615974164.395371790   1184677976 139889733989952 accept_new_connection:18515: Accepted socket 5
*** 1615974164.395415853        44063 139889733989952 produce_socket:18266: queued socket 5
*** 1615974164.395435505        19652 139889721800256 consume_socket:18223: grabbed socket 5, going busy
*** 1615974164.395446256        10751 139889721800256 worker_thread_run:18385: Start processing connection from ::1
*** 1615974164.395563693       117437 139889721800256 mg_cry_internal_impl:3793: mg_cry called from sslize:15508: sslize error: error:1408F09C:SSL routines:ssl3_get_record:http request
sslize error: error:1408F09C:SSL routines:ssl3_get_record:http request
*** 1615974164.395646290        82597 139889721800256 worker_thread_run:18433: Connection closed

```
Is there something, I do wrong or is there an issue with civetweb?

**Comment by bel2125** [comment]
1408F09C seems to be an error code from OpenSSL, from SSLv3 - this may depend on your OpenSSL version.

Could you try to set the [ssl_protocol_version](https://github.com/civetweb/civetweb/blob/master/docs/UserManual.md#ssl_protocol_version-0) maybe to 3 or 4 (not 0 or 1)?

**Comment by jgeiss66** [comment]
I solved it. My IPv6 Environment was not configured properly. How it works.

Sorry for the inconvenience.
