### ISSUE TITLE
resolve missing 

### ISSUE THREAD

**Issue by David-laverty2** [civetweb/civetweb#983]
How to get HTTPS connection to run on Civetweb. I have follwed the instructions from the Github main page and have created my .pem file as described.

When I run Civetweb and set listening port to 443s and SSL_certificate to my .pem file location I get the following error

Failed to start CivetWeb V1.12: initialize_ssl error: error loading library libeay64.dll

I have installed OpenSSL and have got this .dll file (libeay64) in my System32 directory so I cant figure out why this error is occuring. I have seen in troubleshooting that this means my OpenSSL is not properly installed but it is showing up in my installed programs within Control panel so I thought that it was.

I am trying to run a secure web site over Amazon EC2 instance running windows server 2012 R2

Any help will be much appreciated

**Comment by bel2125** [comment]
This could be an OpenSSL1.1 vs OpenSSL1.0 issue. Although the difference 1.0 -> 1.1 seems minor, in fact this is a major version change with significant API incompatibilities. Did you build the executable on your own or did you download one from SourceForge? What OpenSSL libs did you use / where did you download them from?
Probably there is a version mismatch. If you use OpenSSL 1.1, the following DLLs are used (64 bit in Windows 10):

![image](https://user-images.githubusercontent.com/5619191/112103598-48fa5a80-8baa-11eb-99c2-a2a706aad7df.png)

The "libeay64.dll" (without _1_1) sounds like you use a version compiled against the OpenSSL1.0 API and libraries.
If you do not have any reason for remaining at V1.0, you should use a version compiled against V1.1 (some features are not available in V1.1 and some systems are stuck with V1.0 for other reasons, so there may be reasons to keep 1.0). 

Is there any reason why you use CivetWeb 1.12 instead of 1.13? Version 1.14 is going to be released soon (Beginning of April).

**Comment by David-laverty2** [comment]
I downloaded OpenSSL from the 1st link on https://wiki.openssl.org/index.php/Binaries which was https://slproweb.com/products/Win32OpenSSL.html. Version name is Win64 OpenSSL v1.1.1j - non light version.(2nd in the list)

I got CivetWeb from https://sourceforge.net/projects/civetweb/. 

From what you are saying regarding my version of CivetWeb looking for an older version of OpenSSL (without_1_1), is it possible my version of OpenSSL is 1.1? and in fact it is CivetWeb which needs updating to allow use with the newer OpenSSL 1.1.1 binaries?

I just check my SYSTEM32 folder and have got the following .dll files in it 

![image](https://user-images.githubusercontent.com/81199048/112119237-186bee00-8bb5-11eb-8524-2e3430bdb306.png)


Thank you for your reply, I will install CivetWeb v1.13 now and see if this makes a difference to my issue, will report back shortly

**Comment by David-laverty2** [comment]
I got CivetWeb to work again using Version 1.13, thanks very much for that. 
I now have another issue when I try to connect to my website my browser is timing out before securing a connection.
Would you have any idea why this would be happening? Is there another setting I am missing from CivetWeb? I have my .pem file loaded correctly in the correct format, I am really at a loss.

Sorry for all the questions.

**Comment by bel2125** [comment]
CivetWeb always supported OpenSSL V1.0 and supports OpenSSL V1.1 starting from CivetWeb 1.10.
The default changed from "use OpenSSL 1.0" to "use OpenSSL 1.1" only with CivetWeb 1.13
see the [release notes](https://github.com/civetweb/civetweb/blob/master/RELEASE_NOTES.md).

If you compile the executable on your own, you can still use OpenSSL 1.0 in CivetWeb 1.13 or use OpenSSL 1.1 in CivetWeb 1.10. As already mentioned, unfortunately OpenSSL 1.0 to 1.1 is a major change in the API with lots of incompatibilities (more than 0.9 to 1.0), so this has to be decided at compile time. This version labeling decision of OpenSSL sometimes leads to confusion (e.g, recently in https://github.com/civetweb/civetweb/issues/938).


> ... but the certificate created is still showing up as not secure. Any ideas? Is it because its self signed?

You did not tell me where it did show up as "not secure". A browser will consider a self signed certificate as not secure, unless you add this certificate to the browsers trust store. If you tell the browser your certificate is secure, you will get a green "secure" banner in your browser,, a lock symbol or whatever this particular browser uses to indicate "secure".
It depends on what you want to do ... if you want to host a web shop on the internet, you will have to buy an official certificate from a CA - and regularly renew it (those poor CAs need to live from something). If you have can administrate the clients as well, you can create a root certificate yourself (self signed), derive a server certificate from that, and tell your clients (browsers) to trust your root certificate. Or you could try "lets encrypt" to create a certificate with some level of trust ... lower than the certificated bought from a CA but higher than self signed.

Some time ago I got a list of security tests you could use for your certificate and server configuration: 
https://github.com/civetweb/civetweb/tree/master/examples/https
I don't know if all these links still work or if there are newer, better tests - they used to work when this list has been created - now I can't tell. Anyway: I never give an official recommendation for anything like this and don't take any responsibility for any external link - the links may be useful for you or not.

**Comment by David-laverty2** [comment]
thank you for your helpful and detailed responses to my queries. It was in my browser that the not secured red banner showed up, but thanks to your insights I can now try a few more ways to try and rectify my issues. 

Feel free to close this question / issue, I do apologise for opening it as such but was unaware of anywhere else to get help with my beginners knowledge on the troubles I was facing.

**Comment by bel2125** [comment]
You are welcome to ask questions here.
Some years ago there questions were on a mailing list, but all activities are now concatenated in GitHub and I think that's more convenient for everybody.
