### ISSUE TITLE
Non-Embed Restful

### ISSUE THREAD

**Issue by newcivetweb** [civetweb/civetweb#987]
Hello, 
   We have an embedded systems use case, where the application that can handle the REstFul calls are tightly integrated into the embedded application that is/should run with root privileges. On the front end is the CivetWeb that servers up the webcontent but also act as the RestFul API handler.
Until now we have the CivetWeb integrated into the application, which made the CivetWeb server(Frontend+interface to REST)was also running as root. 
We now have a security requirement that the webserver should be running at less privileged mode. run_as_user does not help us in this can as it will bring down the elevated privilege of the application too. 
Is there a solution or mechanism that we could use from CivetWeb that break this dependency in a way that all RestCall are directed to a different port with in the system ? Even if this mean integrating part of CivetWeb into the embedded application. 

The only way we see this going forward is running two instances of civetweb one to serve the UI contents and any request to the RestFul API is then re-requested to the backend instance. It does not look like a good idea. Any thoughts are welcome. Appreciate a quick response.

**Comment by bel2125** [comment]
> Any thoughts are welcome.

Multiple ideas ... but I need some more information:

1) "embedded system": Does it have a full operating system, e.g. Linux?

2) "integrated into the application": So it needs access to data in your C/C++ application. Mainly read-write access or mainly calling functions? Synchronous or asynchronous functions?

3) "a security requirement that the webserver should be running at less privileged mode" ... from the wording this does not sound like an "real" requirement, but like a means to an end - probably the "base requirement" is something like Availability, Confidentiality or Data Integrity of the entire embedded system. I don't want to say "it's a good idea to run the webserver as root" (and I don't say it's not) - I just want to give you the advice to look into more detail at the background of this requirement.
But I can definitely give you some hints on how you could split webserver and application based on 1) and 2)

**Comment by bel2125** [comment]
If you have a Linux operation system (or a system with similar features), you could run the server as a non privileged process - except for the privilege to bind port 80 and 443: (`setcap 'cap_net_bind_service=+ep' /path/to/civetweb`).
Your "root process" (the embedded process that has to run with root privileges) can communicate with the civetweb process in multiple ways, two of them are shared memories and domain sockets (... assuming Linux).
A C or C++ process can store data in a shared memory - with a skillfully designed C++ class (base class), variables stored in a shared memory can work just like "ordinary" variables in RAM. Depending on your needs you could also use two shared memories and set the the access rights for one shared memory to "read only" for civetweb and the other one as "read only" for your root process.
Domain sockets are an efficient way to communicate between two processes running on a Linux host - available only for localhost but more efficient than a localhost TCP connection. They have a name and you can use access rights (just like for shared memories). The current HEAD version of civetweb also allows to listen to domain sockets. So you could still have a civetweb instance in your root process, but bound to a domain socket - and another instance running on TCP 80 serving the static content (html, js, css, images, ...) and acting as a proxy for all data in the root process.

For everything more detailed, I need a lot more information.

**Comment by newcivetweb** [comment]
Hello, 
   Thanks for all that inputs.. looks like a good way forward especially on the domain socket side. 
To answer some more of your questions. 
1) "embedded system": Does it have a full operating system, e.g. Linux?
  Yes, it's  a build root base linux kernel + busy box. 
  
 2)  "integrated into the application": So it needs access to data in your C/C++ application. Mainly read-write access or mainly calling functions? Synchronous or asynchronous functions?
  That is right, we, register quite a few handlers (almost close to a 100)  using CivetServer::addHandler(const std::string &uri, CivetHandler *handler). This until now is synchronous. 
3) "a security requirement that the webserver should be running at less privileged mode"
  Like you have rightly said, this is a debatable topic, but the places that the system would function will need good security. So we do not want to take a chance here. 

Of the two solution that you provided, the second one using Domain sockets looks more lucrative. We are using CIVETWEB_VERSION "1.14" . Does this version also support Domain sockets. We will dig around anyway. 
Do you have any examples on using the domain sockets in this case ?

**Comment by bel2125** [comment]
> We are using CIVETWEB_VERSION "1.14" . Does this version also support Domain sockets

Version 1.14 is the current HEAD version - not released today, but (probably) next week.
To enable domain socket support, you need to build the code with the `USE_X_DOM_SOCKET` preprocessor define.
Then you can specify a domain socket name in the `listening_ports` ... see [UserManual](https://github.com/civetweb/civetweb/blob/master/docs/UserManual.md#listening_ports-8080).

The domain socket client is not implemented yet, only the server side. The client side will be added soon, but probably after the V1.14 release. In fact adding the client to C is trivial. There will be a Lua interface as well.
There is another "pattern" that you might take into consideration:

You do have one "FRONTEND" server instance that will handle all access to the "outside world" (TCP network). This server will handle all HTTP or HTTPS requests. Is it possible to use certificates for your embedded device? If yes, you might want to use server AND client certificates for the best possible security. This frontend server will handle all requests for static files and also authentication and authorization. It might be handy to use the "standard" CivetWeb standalone executable with Lua support enabled. A little bit of Lua code could handle all the auth stuff before contacting the "backend" server - and it could do some formatting or even collect information from different "backend" components. Of course this can be done in C too, it is not required to do this in Lua, it might just be handy.
The "BACKEND" server is your root application ... you could also have more than one backend. You do not contact a backend application directly from the network (TCP), but only through a frontend server. If the frontend has already handled all the auth, you don't need to implement this in the backend process again. The backend could CivetWeb with `USE_X_DOM_SOCKET` activated and no TCP listening ports (you could use TCP bound to 127.0.0.1 as well, but domain sockets are more efficient on Linux). You will not need to change the code for your ~100 handlers, only the configuration.
If all your handler function have a common prefix in the URL (e.g. "/api/", "/v1.1/", "/data/" .. whatever), you only need one handler for that URL prefix in the frontend. It will forward the requests to the backend, maybe after some auth checks, sanity checks, ... probably limiting the number of simultaneous clients, requests per second, ... whatever ... to provide some additional protection for the backend process. If someone manages to crash the frontend server, the backend will remain unaffected - you can add a script to check `pidof` the fronend process, and restart the frontend after some seconds when it is no longer running.

**Comment by newcivetweb** [comment]
Thanks for all the inputs .. we will do some feasibility checks along your lines of suggestion and circle back to you, if we have any issues . 
Thanks again.
