### ISSUE TITLE
How to get an error message string for mg_start() ?

### ISSUE THREAD

**Issue by bscbrn** [civetweb/civetweb#988]
Hi, I am trying to get an error message when executing mg_start().
I would like to have information of what option is wrong or similar.
Is there any way to get this from civetweb or any example code?

Thank you for any help.

**Comment by bel2125** [comment]
There is `mg_start2` (still requires the `MG_EXPERIMENTAL_INTERFACES` define) - it will return an error message.

An alternative is to provide a `log_message` callback like this:
https://github.com/civetweb/civetweb/blob/06821ee78b5a3b51754871da7040990107194b6a/src/main.c#L1464-L1466

**Comment by bscbrn** [comment]
Thank you.
This really helps.

**Comment by bel2125** [comment]
For completeness: 
`mg_start2()` is no longer marked with the EXPERIMENTAL define. A full example using this function would be here.

https://github.com/civetweb/civetweb/blob/41181944d63d20336a568b3baef9baa501c637fb/examples/ws_server/ws_server.c#L144-L170
