### ISSUE TITLE
Conan build fails

### ISSUE THREAD

**Issue by bel2125** [civetweb/civetweb#991]
It seems the Conan (package manager) build always fails:
https://travis-ci.org/github/civetweb/civetweb/builds/766110175
It is only triggered for releases, not for regular commits/pushes/merges.

Since I have no idea how Conan actually works, help fixing this issue would be appreciated.

**Comment by bel2125** [comment]
Release V1.15:
The conan build on Travis CI is triggered again and fails:
https://app.travis-ci.com/github/civetweb/civetweb/builds/236737011
I still have no idea how to fix it.

However, in the meantime travis-ci.org does no longer exist and CivetWeb had to move to travis-ci.com. The new service works well, but it calculates "credits" for every started minutes on a build VM:  https://docs.travis-ci.com/user/billing-overview/#usage---credits
10 credits per started minute for Linux and FreeBSD, 20 for Windows and 50 for Mac OS.
A free account has a total balance of 10000. Since CivetWeb is an open source project, I got some additional credits for free and might get some more if they are used up ... still we should not spent these credits carelessly.

The successful build of the V1.15 release costs 820 credits:
![image](https://user-images.githubusercontent.com/5619191/131729533-2950c92d-073c-4ad6-af33-b323e248de48.png)

The not working CONAN build costs 4830 credit:
![image](https://user-images.githubusercontent.com/5619191/131729679-de78e14f-fca6-4deb-bd72-71a6cb14dc6f.png)

The unsuccessful CONAN build cost almost half of the credits a free account has to spend. Mostly because all Mac OS builds are hanging somehow and finally timed out.

I cannot experiment here and try to figure out what is going wrong with a try and error approach.

Unless somebody knows how to fix these issues, the only chance I see is to remove the CONAN builds from the Travis CI file again. 

Do they need to be part of the CI build at all, or could they also be built locally and uploaded?

**Comment by uilianries** [comment]
Let's remove Conan. The new Conan Center should take CivetWeb package there directly, so you don't need to break your project. I'll open a PR removing all stuff related to Conan.

**Comment by bel2125** [comment]
> The new Conan Center should take CivetWeb package there directly ...

Yes, I think this is a good idea.
Download (pull) the CivetWeb releases from GitHub instead of trying to get CivetWeb/Travis to push them to the Conan Center.

Thank you.
