### ISSUE TITLE
CivetServer.cpp handlers - issues after 1024 HTTP 1.1 Connections - sockets not released ? (bug on ARM and not on X86...)

### ISSUE THREAD

**Issue by f4gkr** [civetweb/civetweb#994]
I am using the latest release, on ARM platform [NVIDIA ARM with Ubuntu 18.04 LTS]. Apparently the "consumed sockets" are not released properly. After 1024 calls, the socket pool exhauts and the application hangs.
[could not reproduce the same issue on Ubuntu 18.04 on X86_64]
The requests are performed by a Javascript call in the browser via JQuery, here every 300 millisecs (same with slower)

The handler does nothing special, just mg_print() a json document...

Normal trace : before hanging :

*** 1618835192.455860467 548103249152 accept_new_connection:19018: **Accepted socket 251**
*** 1618835192.456571012 548103249152 produce_socket:18727: **queued socket 251**
*** 1618835192.456941917 548111641856 consume_socket:18683: **grabbed socket 251, going busy**
*** 1618835192.457220439 548111641856 worker_thread_run:18841: Incomming connection from 192.168.10.235
*** 1618835192.457490705 548111641856 process_new_connection:18418: Start processing connection from 192.168.10.235
*** 1618835192.457654830 548111641856 process_new_connection:18424: calling get_request (1 times for this connection)
*** 1618835192.458342752 548111641856 switch_domain_context:13424: HTTP Host: 192.168.10.177
*** 1618835192.458564251 548111641856 process_new_connection:18514: http: 1.1, error: none
handle_request in
*** 1618835192.458896565 548111641856 handle_request:13999: URL: /position
*** 1618835192.459722724 548111641856 open_auth_file:8310: fopen(/.htpasswd): No such file or directory
handle_request precall
**/// MY HANDLER IS RUNNING HERE**
handle_request postcall
*** 1618835192.466509113 548111641856 handle_request_stat_log:6529: handle_request done
*** 1618835192.466585335 548111641856 process_new_connection:18586: Done processing connection from 192.168.10.235 (0.000000 sec)
*** 1618835192.466828818 548111641856 worker_thread_run:18930: Connection closed
*** 1618835192.466894513 548111641856 consume_socket:18669: going idle

*** 1618835192.956865669 548103249152 accept_new_connection:19018: **Accepted socket 251**
*** 1618835192.957404218 548103249152 produce_socket:18727: **queued socket 251**
*** 1618835192.957733043 548111641856 consume_socket:18683: **grabbed socket 251, going busy**
*** 1618835192.958057420 548111641856 worker_thread_run:18841: Incomming connection from 192.168.10.235
*** 1618835192.958225641 548111641856 process_new_connection:18418: Start processing connection from 192.168.10.235
*** 1618835192.958430949 548111641856 process_new_connection:18424: calling get_request (1 times for this connection)
*** 1618835192.959180629 548111641856 switch_domain_context:13424: HTTP Host: 192.168.10.177
*** 1618835192.959456496 548111641856 process_new_connection:18514: http: 1.1, error: none
handle_request in
*** 1618835192.959788265 548111641856 handle_request:13999: URL: /position
*** 1618835192.961367657 548111641856 open_auth_file:8310: fopen(/.htpasswd): No such file or directory
handle_request precall
**/// MY HANDLER IS RUNNING HERE**
handle_request postcall
*** 1618835192.967504363 548111641856 handle_request_stat_log:6529: handle_request done
*** 1618835192.967569386 548111641856 process_new_connection:18586: Done processing connection from 192.168.10.235 (0.000000 sec)
*** 1618835192.967827684 548111641856 worker_thread_run:18930: Connection closed
*** 1618835192.967884067 548111641856 consume_socket:18669: going idle
*** 1618835193.456634959 548103249152 accept_new_connection:19018: **Accepted socket 253**
*** 1618835193.457183172 548103249152 produce_socket:18727: **queued socket 253**
*** 1618835193.457575516 548111641856 consume_socket:18683: grabbed socket 253, going busy
*** 1618835193.457863734 548111641856 worker_thread_run:18841: Incomming connection from 192.168.10.235
*** 1618835193.458114321 548111641856 process_new_connection:18418: Start processing connection from 192.168.10.235
*** 1618835193.458261358 548111641856 process_new_connection:18424: calling get_request (1 times for this connection)
*** 1618835193.458968415 548111641856 switch_domain_context:13424: HTTP Host: 192.168.10.177
*** 1618835193.459175483 548111641856 process_new_connection:18514: http: 1.1, error: none
handle_request in
*** 1618835193.459528724 548111641856 handle_request:13999: URL: /position
*** 1618835193.460446337 548111641856 open_auth_file:8310: fopen(/.htpasswd): No such file or directory
handle_request precall

Last call before hang : 
*** 1618835578.174877914 548111641856 handle_request_stat_log:6529: handle_request done
*** 1618835578.174928953 548111641856 process_new_connection:18586: Done processing connection from 192.168.10.235 (0.000000 sec)
*** 1618835578.175086230 548111641856 worker_thread_run:18930: Connection closed
*** 1618835578.175130485 548111641856 consume_socket:18669: going idle
*** 1618835578.663620573 548103249152 accept_new_connection:19018: **Accepted socket 1023**
*** 1618835578.664597609 548103249152 produce_socket:18727: **queued socket 1023**
*** 1618835578.665001312 548111641856 consume_socket:18683: grabbed socket 1023, going busy
*** 1618835578.665330745 548111641856 worker_thread_run:18841: Incomming connection from 192.168.10.235
*** 1618835578.665381912 548111641856 process_new_connection:18418: Start processing connection from 192.168.10.235
*** 1618835578.665413080 548111641856 process_new_connection:18424: calling get_request (1 times for this connection)
*** 1618835578.665921901 548111641856 switch_domain_context:13424: HTTP Host: 192.168.10.177
*** 1618835578.666068362 548111641856 process_new_connection:18514: http: 1.1, error: none
handle_request in
*** 1618835578.666264518 548111641856 handle_request:13999: URL: /position
*** 1618835578.666766875 548111641856 open_auth_file:8310: fopen(/.htpasswd): No such file or directory
handle_request precall
///
handle_request postcall
*** 1618835578.673364721 548111641856 handle_request_stat_log:6529: handle_request done
*** 1618835578.673407824 548111641856 process_new_connection:18586: Done processing connection from 192.168.10.235 (0.000000 sec)
*** 1618835578.673535534 548111641856 worker_thread_run:18930: Connection closed
*** 1618835578.673570413 548111641856 consume_socket:18669: going idle

**Comment by f4gkr** [comment]
Not sure it is useful, but : 

- On the ARM :
> gcc --version
> gcc (Ubuntu/Linaro 6.5.0-2ubuntu1~18.04) 6.5.0 20181026

- on the PC :

> gcc --version
> gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

**Comment by f4gkr** [comment]
Still trying to fix this here. I've added some trace in civetweb.c to track the issue.
It hangs in consume_socket() : 

/* If the queue is empty, wait. We're idle at this point. */
        while ((ctx->sq_head == ctx->sq_tail)
               && (STOP_FLAG_IS_ZERO(&ctx->stop_flag))) { 
                **pthread_cond_wait(&ctx->sq_full, &ctx->thread_mutex);**
        }

**Comment by bel2125** [comment]
I will try to reproduce this on an ARM system, although I probably don't have the same ARM as you do.
Is it a 32 bit or 64 bit ARM?

How did you set the file descriptor limit for this process on your ARM device?
Could you check the socket states (https://computingforgeeks.com/how-to-check-tcp-connections-states-in-linux-with-netstat/).
Probably all sockets hang out in some "closing state"?

**Comment by bel2125** [comment]
Using main.c and the default configuration, I cannot reproduce this on an ARM Linux system: Everything works fine there.
I need some more information to reproduce and investigate this.

**Comment by f4gkr** [comment]
Sorry for the late feedback, wanted to clean review the code in case there was an issue I did not figure out. 

- The app (called vmservice in the logs below) is using **embedded** civet (C++) on a ARM 64 Bits platform, NVIDIA Jetson TX2 with Ubuntu 18.04
- The same code has been tested on x86_64 PC with Apache "ab" tool and handles thousands of requests with no problem
- The limits are standard, max opened files is 1024. Tried to increase but that does not change the problem, it locks just after a longer period if the limit is increased.
ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 15026
max locked memory       (kbytes, -l) 65536
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 15026
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

- About socket status : 
 Command "netstat -apn | grep CLOSE_WAIT | awk '{ print $7 }' | sort | uniq -c | sort -nr" gives NO OUTPUT => no socket in "close wait"
BUT :
When it hangs, "netstat -apn" shows a long list of "TIME_WAIT" : 
tcp        0      0 10.8.0.198:8080         10.8.0.6:45240          TIME_WAIT   -                   
tcp        0      0 10.8.0.198:8080         10.8.0.6:45256          TIME_WAIT   -                   
tcp        0      0 10.8.0.198:8080         10.8.0.6:45258          TIME_WAIT   -                   
tcp        0      0 10.8.0.198:8080         10.8.0.6:45376          TIME_WAIT   -                   
tcp        0      0 10.8.0.198:8080         10.8.0.6:45342          TIME_WAIT   -                   
tcp        0      0 10.8.0.198:8080         10.8.0.6:45332          TIME_WAIT   -                   
tcp        0      0 10.8.0.198:8080         10.8.0.6:45252          TIME_WAIT   -                   
tcp        0      0 10.8.0.198:8080         10.8.0.6:45230          TIME_WAIT   -                   
tcp        0      0 10.8.0.198:8080         10.8.0.6:45238          TIME_WAIT   -                   
tcp        0      0 10.8.0.198:8080         10.8.0.6:45356          TIME_WAIT   -                   
tcp        0      0 10.8.0.198:8080         10.8.0.6:45242          TIME_WAIT   -                   
tcp        0      0 10.8.0.198:8080         10.8.0.6:45284          TIME_WAIT   -                   
tcp        0      0 10.8.0.198:8080         10.8.0.6:45362          TIME_WAIT   - 

After a short while, the TIME_WAIT list reduces and then when trying to refresh the browser (no reply) :  
netstat -apn | grep CLOSE_WAIT | awk '{ print $7 }' | sort | uniq -c | sort -nr
      5 -
      1 7042/./vmservice (my app)

netstat -nat | awk '{print $6}' | sort | uniq -c | sort -r
      8 ESTABLISHED
      6 LISTEN
      6 CLOSE_WAIT
      1 established)
      1 Foreign

**Comment by f4gkr** [comment]
Before the lock here is how it goes : 
root@TX2:~# netstat -nat | awk '{print $6}' | sort | uniq -c | sort -r
      8 ESTABLISHED
      6 LISTEN
      6 CLOSE_WAIT
      1 established)
      1 Foreign
root@TX2:~# netstat -nat | awk '{print $6}' | sort | uniq -c | sort -r
      5 LISTEN
      2 ESTABLISHED
      1 established)
      1 Foreign
root@TX2:~# netstat -nat | awk '{print $6}' | sort | uniq -c | sort -r
     18 TIME_WAIT
      6 LISTEN
      2 ESTABLISHED
      1 established)
      1 Foreign
root@TX2:~# netstat -nat | awk '{print $6}' | sort | uniq -c | sort -r
     26 TIME_WAIT
      6 LISTEN
      2 ESTABLISHED
      1 established)
      1 Foreign
root@TX2:~# netstat -nat | awk '{print $6}' | sort | uniq -c | sort -r
     28 TIME_WAIT
      6 LISTEN
      2 ESTABLISHED
      1 established)
      1 Foreign
root@TX2:~# netstat -nat | awk '{print $6}' | sort | uniq -c | sort -r
     30 TIME_WAIT
      6 LISTEN
      2 FIN_WAIT1
      2 ESTABLISHED
      1 established)
      1 Foreign
root@TX2:~# netstat -nat | awk '{print $6}' | sort | uniq -c | sort -r
     38 TIME_WAIT
      6 LISTEN
      2 ESTABLISHED
      1 established)
      1 Foreign
root@TX2:~# netstat -nat | awk '{print $6}' | sort | uniq -c | sort -r
     40 TIME_WAIT
      6 LISTEN
      2 ESTABLISHED
      1 established)
      1 Foreign
root@TX2:~# netstat -nat | awk '{print $6}' | sort | uniq -c | sort -r
     44 TIME_WAIT
      6 LISTEN
      2 ESTABLISHED
      1 established)
      1 Foreign
root@TX2:~#

**Comment by f4gkr** [comment]
number of TIME_WAIT socket remains between 120 and 125

**Comment by f4gkr** [comment]
Another info : 
when blocked : 
lsof | awk '{print $1}' | sort | uniq -c | sort -r -n | head
  12276 civetweb-
   7812 (my app)
   1116 (my app)
    281 sshd
    219 nvargus-d
    146 systemd
    112 bash
    105 bioset
    100 sudo
     70 nvphsd

netstat -apn 
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      4109/systemd-resolv 
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      4172/sshd           
tcp        0      0 0.0.0.0:1883            0.0.0.0:*               LISTEN      3844/mosquitto      
tcp        6      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      4912/./vmservice    
tcp      426      0 10.8.0.198:8080         10.8.0.6:56146          ESTABLISHED -                   
tcp      360      0 192.168.10.195:8080     192.168.10.146:42740    CLOSE_WAIT  -                   
tcp      426      0 10.8.0.198:8080         10.8.0.6:56136          ESTABLISHED -                   
tcp      426      0 10.8.0.198:8080         10.8.0.6:56122          ESTABLISHED -                   
tcp      426      0 10.8.0.198:8080         10.8.0.6:56124          ESTABLISHED -                   
tcp        0      0 192.168.10.195:22       192.168.10.4:54566      ESTABLISHED 4319/sshd: nvidia [ 
tcp        0    196 10.8.0.198:22           10.8.0.6:51938          ESTABLISHED 4603/sshd: nvidia [ 
tcp      426      0 10.8.0.198:8080         10.8.0.6:56134          ESTABLISHED -                   
tcp        0      0 10.8.0.198:8080         10.8.0.6:56112          ESTABLISHED 4912/./vmservice    
tcp6       0      0 :::22                   :::*                    LISTEN      4172/sshd           
tcp6       0      0 :::1883                 :::*                    LISTEN      3844/mosquitto      
udp        0      0 127.0.0.53:53           0.0.0.0:*                           4109/systemd-resolv 
udp        0      0 0.0.0.0:68              0.0.0.0:*                           4142/dhclient       
udp        0      0 0.0.0.0:68              0.0.0.0:*                           4113/dhclient       
udp        0      0 0.0.0.0:47245           0.0.0.0:*                           4164/openvpn

**Comment by f4gkr** [comment]
Replaced my handler code by something basic : 

bool JSTaskHandler::handleGet(CivetServer *server, mg_connection *conn) {
        mg_printf(conn,
                  "HTTP/1.1 200 OK\r\nContent-Type: text/html\r\nConnection: "
                  "close\r\n\r\n");
        mg_printf(conn, "<html><body>");
        mg_printf(conn, "<h2>This is the A handler.</h2>");
        mg_printf(conn, "</body></html>\n");
    return(true);
}

Then run this with Apache ab : 
ab -c 100 -n 10000 http://10.8.0.198:8080/operation
This is ApacheBench, Version 2.3 <$Revision: 1807734 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 10.8.0.198 (be patient)
Completed 1000 requests
Completed 2000 requests
Completed 3000 requests
Completed 4000 requests
Completed 5000 requests
Completed 6000 requests
Completed 7000 requests
Completed 8000 requests
Completed 9000 requests
Completed 10000 requests
Finished 10000 requests


All requests passed.............

Means there is a bug in my code !

**Comment by bel2125** [comment]
Thank you for this information.

One recommendation: 

```C
mg_printf(conn,
"HTTP/1.1 200 OK\r\nContent-Type: text/html\r\nConnection: "
"close\r\n\r\n");
```

For new code I would use

```C
mg_response_header_start(conn, 200);
mg_response_header_add(conn, "Content-Length", len, -1);
mg_response_header_add(conn, "Content-Type", "text/html; charset=utf-8", -1);
mg_response_header_send(conn);
```

a) This pattern allows you to use HTTP/1.x and HTTP/2 as well, while `mg_printf(conn,
"HTTP/1.1 200 OK ...` works only for HTTP/1.x
b) The "Connection: close" (or "Connection: keep-alive") header is sent automatically - and a "Date" header as well.

This "Connection" header is related to the FIN_WAIT state.
Details: http://www.tcpipguide.com/free/t_TCPOperationalOverviewandtheTCPFiniteStateMachineF-2.htm
Sending a "Connection: close" header will tell the browser to close the connection, so the client will go into the TIME_WAIT state, not the server.

**Comment by f4gkr** [comment]
Thanks
I really cannot figure out why the code is not working on the TX2 ARM... It
always hangs after exactly 1024 requests, while this never happens on x86 !

the C++ handler is pretty simple :
accumulates the output in one std::string and once finished it does just :

bool JSTaskHandler::handleGet(CivetServer *server, mg_connection *conn) {

    char tmp[1024] ;

    std::string body_section ;

    std::string content_type ;


    /*** lines of code adding content to body_section and setting
content_type **/

    ...

    /** end **/

    int contentLength = body_section.length() ;

    if( content_type.length() == 0 ) {

        content_type = "text/html" ;

    }

    sprintf(tmp, "%d", contentLength );

    mg_response_header_start(conn, 200);

    mg_response_header_add(conn, "Content-Length", tmp, -1);

    mg_response_header_add(conn, "Content-Type", content_type.c_str(), -1);

    mg_response_header_send(conn);

    mg_write( conn, body_section.c_str(), body_section.length() );

    return(true);

}

**Comment by f4gkr** [comment]
Another info :
tried on another NVIDIA ARM platform (Jetson Nano 4GB). Same issue, but...
the issue came this time when requesting (after 1024 successful calls) a
simple PNG image
[image: image.png]


Le jeu. 29 avr. 2021 à 10:02, Sylvain AZARIAN ***@***.***> a
écrit :

> Thanks
> I really cannot figure out why the code is not working on the TX2 ARM...
> It always hangs after exactly 1024 requests, while this never happens on
> x86 !
>
> the C++ handler is pretty simple :
> accumulates the output in one std::string and once finished it does just :
>
> bool JSTaskHandler::handleGet(CivetServer *server, mg_connection *conn) {
>
>     char tmp[1024] ;
>
>     std::string body_section ;
>
>     std::string content_type ;
>
>
>     /*** lines of code adding content to body_section and setting content_type **/
>
>     ...
>
>     /** end **/
>
>     int contentLength = body_section.length() ;
>
>     if( content_type.length() == 0 ) {
>
>         content_type = "text/html" ;
>
>     }
>
>     sprintf(tmp, "%d", contentLength );
>
>     mg_response_header_start(conn, 200);
>
>     mg_response_header_add(conn, "Content-Length", tmp, -1);
>
>     mg_response_header_add(conn, "Content-Type", content_type.c_str(), -1);
>
>     mg_response_header_send(conn);
>
>     mg_write( conn, body_section.c_str(), body_section.length() );
>
>     return(true);
>
> }
>
>
>
>

**Comment by f4gkr** [comment]
Follow up :
once the process has hung, I issue the following command :
*prlimit --pid [the task pid] --rss --nofiles=4096:65536 *
and it comes back to life and continues working.

Le jeu. 29 avr. 2021 à 15:51, Sylvain AZARIAN ***@***.***> a
écrit :

**Comment by bel2125** [comment]
Your handler looks correct.
Did you set "enable_keep_alive" to "no"?
For another test, you could add another mg_disable_connection_keep_alive() call before the mg_response_header_ calls.
If you rise the soft limit to 4096 as in your prlimit above, does it work "forever" then, or does it only take a little more time until you hit that limit?

**Comment by bel2125** [comment]
Another tuning parameter could be linger_timeout_ms --> see User Manual.

**Comment by grunk** [comment]
@f4gkr I have exactly the same problem as you on the same plateform.
Did you manage to find a solution ? Maybe by following some of @bel2125 advices ?

**Comment by f4gkr** [comment]
The issue was coming from files not properly closed, not from the CivetWeb implementation. One of the handlers was opening a file descriptor and not properly closing it at end. When all descriptors are consumed, no way to open a socket as it is processed as a file by linux...
This was detected checking the number of opened files and then checking the sys call from my app
