### ISSUE TITLE
mbedtls: Potential issue in mbed_sslctx_init

### ISSUE THREAD

**Issue by mglettig** [civetweb/civetweb#999]
I noticed that in mbed_sslctx_init both of the following functions

- mbedtls_pk_parse_keyfile
- mbedtls_x509_crt_parse_file

are called with the variable **crt as parameter**. Shouldn't mbedtls_pk_parse_keyfile be called with a path to the **private keyfile** rather than the certificate? See here: https://github.com/civetweb/civetweb/blob/d674d31e52bee3c07ab8a7c1b4f8cf42fbf1ecb3/src/mod_mbedtls.inl#L93

**Comment by bel2125** [comment]
We are using the same configuration ([server_cert](https://github.com/civetweb/civetweb/blob/master/docs/UserManual.md#ssl_certificate)) for mbedTLS as we use for [OpenSSL](https://github.com/civetweb/civetweb/blob/master/docs/OpenSSL.md). An (OpenSSL) file must contain both, like this [example file](https://github.com/civetweb/civetweb/blob/master/resources/cert/server_bkup.pem). 

Maybe mbedTLS would allow separate files, but we inherited the configuration structure from the OpenSSL server configuration here.

**Comment by mglettig** [comment]
Hi @bel2125 

Thanks for the clarification. Yes mbedtls would allow to separate it but if it works with the combined server_cert than this is not an issue.
